### ISSUE TITLE
Superfluous dirty worktree warnings when status.branch=true in Git config

### ISSUE THREAD

**Issue by dieggsy** [raxod502/straight.el#101]
Title pretty much says it. i'm getting a warning for a lot (all?) of my packages where it asks what to do with the changes, even though the repos show up as clean when I check with git.

**Comment by raxod502** [comment]
The warning message about a dirty worktree should show you a list of the files that are dirty. Is that list empty? Or does it list files that are not actually modified?

**Comment by therockmandolinist** [comment]
It says 
```
Repository [name-of-repository] has a dirty worktree:  

  ## master...origin/master
```
(With the actual repo name of course) and then the list of options. It may or may not be relevant that I use 
```
[status]
    short=true
    branch=true
```
In my global .gitconfig, and what the straight prompt is showing is the output of calling  `git status` on a clean repo.

**Comment by raxod502** [comment]
Oh lol. Well, the temporary workaround is to add `-c status.short=false` to the `git status` command used by `straight.el`. The real solution is to use `git status --porcelain`, which is explicitly what I *should* be using for this (according to the man page).

**Comment by therockmandolinist** [comment]
Oh I see, it's using `git status --short` at the moment. That sounds about right, dunno why I didn't think about that - I've actually run into this issue before with some crude git status parsing scripts I wrote. Thanks!

**Comment by dieggsy** [comment]
Just out of curiosity, are there any nuances/subtleties holding back the switch to `git status --porcelain`? It seems largely the same as `git status --short` to me.

**Comment by raxod502** [comment]
It's just because I've not had the time to seriously investigate it yet. If it looks easy to you, it probably is. I'd gladly merge a fix.

**Comment by dieggsy** [comment]
FWIW, since the call to git status is to be displayed to the user, and if no actual parsing of that output is happening, it may be worth just having `-c status.branch=false` in there and just using `--short`. I haven't noticed differences between `--porcelain` and `--short` but I think the point is that `short` is user-targeted and `porcelain` is for parsing with scripts.

**Comment by raxod502** [comment]
Fixed, please verify. See also #143.

**Comment by dieggsy** [comment]
That should do it, thanks. I'll reference my above comments in the new issue.
