### ISSUE TITLE
Does Emacs 26 no longer write autoloads if none are declared?

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#104]
Let's answer this question so that the comment in `straight--activate-package-autoloads` can be updated.

**Comment by therockmandolinist** [comment]
Great idea on `git-bisect`, by the way. First time I use it, so for some reason I couldn't get `git bisect run my-test.el` to work, but I used the following script to manually test
```emacs-lisp
#!emacs --script

(load-file "/home/diego/.ghq/git.savannah.gnu.org/emacs/lisp/emacs-lisp/autoload.el")

(defvar d/autoload "/home/diego/.emacs.d/straight/build/evil-anzu/evil-anzu-autoloads.el")
(let ((generated-autoload-file d/autoload))
  (update-directory-autoloads "/home/diego/.emacs.d/straight/build/evil-anzu/"))
(if (file-exists-p d/autoload)
    (delete-file d/autoload)
  (error "No autoload"))
```
What it came up with was https://github.com/emacs-mirror/emacs/commit/03d941982fbdf96260fc47d1cafbdda78c1d128e

**Comment by raxod502** [comment]
That's interesting. I guess it might be a bug. Perhaps somebody should ask on emacs-devel?

**Comment by raxod502** [comment]
See https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg00884.html.

**Comment by raxod502** [comment]
Eh, who cares what the intended behavior is. Best to be careful.
