### ISSUE TITLE
Install Magit if missing

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#106]

**Comment by vyp** [comment]
Does straight.el require magit?

**Comment by raxod502** [comment]
Of course, it won't be a formal dependency. But why not just `(straight-use-package 'magit)` if the feature isn't available and the user has selected `Magit and recursive edit`, is my thinking.

**Comment by raxod502** [comment]
Now that people are actually watching this repository, I should really start putting proper descriptions for my issues :o

**Comment by vyp** [comment]
Nah it should still be fine for now, idm. PS - impressed by how well the source is documented!
