### ISSUE TITLE
Keep straight.el from automatically adding files to recentf-list

### ISSUE THREAD

**Issue by PythonNut** [raxod502/straight.el#109]
If you use `recentf`, `recentf-list` can get polluted with files from `straight/build`. Since the user should have no interested editing such files, it would be good to keep these from being added in the first place.

**Comment by raxod502** [comment]
This will probably involve hacking one of the byte-compilation functions to use `insert-file-contents-literally` instead of `insert-file-contents`, or something like that.

**Comment by PythonNut** [comment]
Yeah, that's what I figured.

**Comment by raxod502** [comment]
Should be fixed, please test.
