### ISSUE TITLE
Packages with recipes, but which are not installed, error on straight-pull-all

### ISSUE THREAD

**Issue by PythonNut** [raxod502/straight.el#110]
If a package has a registered recipe, but is not installed, as may happen with `(use-package packagename :defer-install t ...)`, `straight-pull-all` will error when trying to pull the package, saying the repository directory does not exist (it doesn't). In this case, I believe it would be better to silently skip the package entirely.

I'll grab an exact copy of the message whenever I get a chance.

**Comment by PythonNut** [comment]
Currently working on this... again.

**Comment by raxod502** [comment]
It would be best, I think, to use `straight--repository-is-available-p` for this.

**Comment by raxod502** [comment]
Closed by https://github.com/raxod502/straight.el/pull/181.
