### ISSUE TITLE
Pull recipes from el-get

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#115]
I noticed they've got some shiny things that I can totally steal, like instructions on [how to build Org](https://github.com/dimitri/el-get/blob/4a1dde57e8a4d4c22ed279bac8253f5f16da9197/recipes/org-mode.rcp#L7-L14).

**Comment by agsdot** [comment]
:+1

**Comment by agsdot** [comment]
Thumbs-up

**Comment by raxod502** [comment]
Note that this probably doesn't make sense until after #71 and #72, and it also won't be making it into the 1.0 release unless somebody provides a pull request.
