### ISSUE TITLE
Error with find command after recent pull from develop branch

### ISSUE THREAD

**Issue by therockmandolinist** [raxod502/straight.el#120]
Seems like after this commit: https://github.com/raxod502/straight.el/commit/f689b59e93a22e14b6a674aeaaa2a0dfb32a5e03

Here's the error:

```
Debugger entered--Lisp error: (error "Command failed: find . -depth 2 -name .git -prune -o -path ./straight.el/\\* -newermt 2017-07-25T12\\:13\\:42-0400 -print: ")
  signal(error ("Command failed: find . -depth 2 -name .git -prune -o -path ./straight.el/\\* -newermt 2017-07-25T12\\:13\\:42-0400 -print: "))
  error("Command failed: %s: %s" "find . -depth 2 -name .git -prune -o -path ./straight.el/\\* -newermt 2017-07-25T12\\:13\\:42-0400 -print" "")
  straight--cache-package-modifications()
  straight--transaction-exec(bulk-find straight--cache-package-modifications straight--uncache-package-modifications)
  straight--package-might-be-modified-p((:host github :repo "raxod502/straight.el" :files ("straight.el") :branch "develop" :package "straight" :type git :local-repo "straight.el"))
  #f(compiled-function () #<bytecode>)()
  straight--transaction-exec(use-package-straight #f(compiled-function () #<bytecode>))
  straight-use-package((straight :type git :host github :repo "raxod502/straight.el" :files ("straight.el")))
  eval-buffer(#<buffer  *load*-545375> nil "/home/diego/.emacs.d/straight/bootstrap.el" nil t)  ; Reading at buffer position 2771
  load-with-code-conversion("/home/diego/.emacs.d/straight/bootstrap.el" "/home/diego/.emacs.d/straight/bootstrap.el" nil t)
  load("~/.emacs.d/straight/bootstrap.el" nil nomessage)
  (let ((bootstrap-file (concat user-emacs-directory "straight/bootstrap.el")) (bootstrap-version 2)) (if (file-exists-p bootstrap-file) nil (save-current-buffer (set-buffer (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el" 'silent 'inhibit-cookies)) (goto-char (point-max)) (eval-print-last-sexp))) (load bootstrap-file nil 'nomessage))
  eval-buffer(#<buffer  *load*> nil "/home/diego/.emacs.d/init.el" nil t)  ; Reading at buffer position 2647
  load-with-code-conversion("/home/diego/.emacs.d/init.el" "/home/diego/.emacs.d/init.el" t t)
  load("/home/diego/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode>)()
  command-line()
  normal-top-level()
```
Also when I try to evaluate the `find` command on the command line, I get 
```
find: paths must precede expression: 2 
```

**Comment by raxod502** [comment]
Actually, I think that find command never worked (on GNU find; it works with BSD find). It's just that commit https://github.com/raxod502/straight.el/commit/f689b59e93a22e14b6a674aeaaa2a0dfb32a5e03 fixed `straight.el` so that it actually reports an error if find fails unexpectedly.

**Comment by raxod502** [comment]
Fixed in https://github.com/raxod502/straight.el/commit/4c4488cae8347d2500311b522236334f2a359b30, but see #121.

**Comment by raxod502** [comment]
Oh, and just for your edification, the problem was that I was under the impression that `-prune` and `-depth` could be used together. It turns out that they can't be. Apparently BSD find silently ignores one of them in this case, while GNU find reports an error.

I think #78 is an entirely separate issue, though.

**Comment by therockmandolinist** [comment]
@raxod502 it actually seems like `-prune` and `-depth` can be used together in GNU find (er, it ignores `-prune` in this case just like BSD find), I just don't think there's an option for passing in a level to GNU find's `-depth` (e.g. `-depth 2`).

**Comment by raxod502** [comment]
Wait wat

Is the meaning of `-depth` seriously completely different in BSD vs. GNU find? That's horrifying; I didn't even think to check that.

Anyways, `-depth` is useless either way. In GNU find, it's a global option; in BSD find, it can't be used with `-prune`. OTOH there is a `-maxdepth` option which has the same meaning in both, but it's global in both.

So in the end I think there's nothing more than can be done. Does the patched version work for you, though?

**Comment by therockmandolinist** [comment]
Yeah, the patched version works.
