### ISSUE TITLE
timestamp interpretation problem with find 4.4.2

### ISSUE THREAD

**Issue by xsteve** [raxod502/straight.el#127]
The bootstrap code for straight.el fails for me.

The download is o.k.

But the 2nd invocation fails:
```
straight--cache-package-modifications: Command failed: find . -name .git -prune -o -path ./straight.el/\* -newermt 2017-08-10T13\:21\:37\+0200 -print:
/usr/bin/find: I cannot figure out how to interpret ‘2017-08-10T13:21:37+0200’ as a date or time
```

I tried this on Ubuntu 14.04 (GNU findutils) 4.4.2

It works on Ubuntu 16.04:
find (GNU findutils) 4.7.0-git

**Comment by xsteve** [comment]
From a users point of view it is important that the package installer "just works".
I solved my problem by installing a newer find-utils on my machine.

You could make the "%FT%T%z" customizable.
That way it is possible to fix the problem without a need to edit the source code or to install a newer find-utils package.

**Comment by raxod502** [comment]
I agree that the `find` interop should be made more customizable. However, I would also like to set the defaults such that they work on as many machines as possible. This is the only way for the package installer to "just work".

**Comment by xsteve** [comment]
One way would be to run "find --version" and extract the version number. Use (version< ...) to set the time-stamp-format-string. However this will break when a user updates find-utils. No idea what version of find-utils is used on the also mentioned BSD systems...

**Comment by raxod502** [comment]
Nah, checking the version should be fine, as long as it is fast enough to be run on every startup. The real question is how to handle the old version: must the time zone be dropped, or is there an alternative syntax that can be used?

**Comment by raxod502** [comment]
Well, OK, checking the version is more complicated than I thought, because BSD find does not have any `--version` flag.

**Comment by raxod502** [comment]
FYI, I'm holding off on making the time format customizable because my current to-do item is fixing #41, which requires doing some refactoring of this part of the codebase. But I would not object to merging a pull request for that, in the meantime.

**Comment by raxod502** [comment]
This should be fixed by https://github.com/raxod502/straight.el/commit/e7b096d13e261a17c66f69932009b71e2295dc57, please test.
