### ISSUE TITLE
Ivy actions in straight-use-package

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#130]
We could take advantage of Ivy's alternate-action capability if it is installed, in order to allow you to `M-x straight-use-package` but then `M-o r` to get the recipe instead.

**Comment by progfolio** [comment]
Could this be implemented in a separate package?

**Comment by raxod502** [comment]
Quite. Since nobody's requested this, and I long since have stopped using Ivy, I think there's no reason to keep this open.
