### ISSUE TITLE
straight.el should support local repositories anywhere on the filesystem

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#133]
Currently, `:local-repo` is resolved in a rather naive way: namely, it's appended directly to `~/.emacs.d/straight/repos`. It would be better to use `expand-file-name` against a `default-directory` of `~/.emacs.d/straight/repos`, which would allow specifying an absolute path for `:local-repo`. See https://github.com/raxod502/straight.el/issues/128#issuecomment-322375028.

I've put this on the 1.0 milestone because it's trivial. Although in the process, I think we should use a shared method for computing local repository paths, rather than doing it ad-hoc in 20 different places.

**Comment by raxod502** [comment]
@rgrinberg this feature is added in https://github.com/raxod502/straight.el/commit/e1b671b26cb500115820eb7fea8fdc1535f09c27.

**Comment by rgrinberg** [comment]
Yay! Thanks.
