### ISSUE TITLE
Documentation of (package-initialize) in README

### ISSUE THREAD

**Issue by emacs18** [raxod502/straight.el#138]
README.md has this line:

    package.el aggressively inserts a call to package-initialize into
    the init-file if it is not already present, whenever any package
    management operation is performed.

This statement does not seem to be accurate.

I have this comment line in my init file:
```
;; (package-initialize)
```
Emacs looks for such comment line on start-up.   If found, then emacs does not add a line to call this function.

**Comment by vyp** [comment]
While you're correct, this is known, see https://github.com/raxod502/straight.el/issues/73#issuecomment-320571816.

**Comment by vyp** [comment]
In short:

> This is ugly and looks ridiculous. Is requiring a magic comment in the
init-file to prevent unnecessary code from being inserted on Emacs
startup really the best possible user experience?

**Comment by emacs18** [comment]
I don't have any strong feeling one way or the other as to the merits of current emacs behavior.  I have read some of the discussions on emacs-devel.

All I'm pointing out is that README.md seems to make statements which some readers might conclude as being incorrect.

**Comment by vyp** [comment]
I'd argue the statement is accurate in general, just not when this comment exists. And I don't think many people would have such a comment in their init file anyway. But of course, it could be argued that this case makes the statement inaccurate, which is maybe what you're saying, so just semantics/interpretation I think.

**Comment by raxod502** [comment]
In my opinion, the statement is completely accurate. After all, if you have

    ;; (package-initialize)

in your init-file, then you do indeed have a call to `package-initialize` in your init-file. It's commented out, yes, but it's still there.
