### ISSUE TITLE
Configure remote naming

### ISSUE THREAD

**Issue by rgrinberg** [raxod502/straight.el#140]
Some straight recipes require a particular naming convention for the remotes. So it would be good if that was configurable. See original problem here:

https://github.com/raxod502/straight.el/issues/128#issuecomment-324214018

**Comment by raxod502** [comment]
Probably this will look like `:remote` keys at the top level and in the `:upstream` sub-plist. It should be pretty easy to do, just find all the places where `straight-vc-git-primary-remote` and `straight-vc-git-upstream-remote` are used, and have them try those values from the recipe before defaulting back to the variables.

**Comment by progfolio** [comment]
It looks like 6abe699e1ecf9431e65f044f1ce07f0ab0ca2247 took care of this.
Please reopen if I'm mistaken.
