### ISSUE TITLE
find-library takes me to the build directory instead of the repos one

### ISSUE THREAD

**Issue by dieggsy** [raxod502/straight.el#144]
I'm not sure when this started happening, though it's unfortunate since I can't call magit status from the build directory.

**Comment by dieggsy** [comment]
Hmm, I doubt this is a `straight.el` issue, will further investigate.

**Comment by raxod502** [comment]
I think this happened to me once recently, but I wasn't able to reproduce it.

**Comment by dieggsy** [comment]
It appears that the behavior shows up after this commit https://github.com/emacs-mirror/emacs/commit/e8001d4c27e1e33c83b9994aac4d5fc3feada2da in emacs master. (Tried find-library with emacs built before and after that commit).

**Comment by dieggsy** [comment]
More specifically, that commit may have broken vc-follow-symlinks? :confused:

**Comment by raxod502** [comment]
Oh fun. I'll see if I can check it out (although I'm just starting school again so I'll be very very busy shortly).

**Comment by dieggsy** [comment]
I've submitted a [bug report](https://lists.gnu.org/archive/html/bug-gnu-emacs/2017-08/msg01107.html).

**Comment by raxod502** [comment]
Nice.

**Comment by dieggsy** [comment]
This appears resolved.
