### ISSUE TITLE
Building package also loads package

### ISSUE THREAD

**Issue by dieggsy** [raxod502/straight.el#145]
Is this normal/expected? I've got a package (exwm) that is loaded based on an environment variable with `:if`, but whenever I use `M-x straight-rebuild-package RET exwm` the package is loaded as well. The package is also loaded if it is built on init (if it has not been built previously), regardless of the `:if`.

**Comment by raxod502** [comment]
That's probably because byte-compiling the package ends up calling `require` on some or all of its features. You'll most likely observe the same behavior with any other package manager; to avoid it, check out #76.

**Comment by dieggsy** [comment]
Was this closed as a "duplicate" or in favor #76? (that's fine, i'm just checking)

**Comment by raxod502** [comment]
Mostly since currently it seems the way to "solve" this problem would be via #76. If there are alternative proposals, we can put them in their own issues.
