### ISSUE TITLE
Add to Spacemacs

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#146]
This is obviously a rather ambitious project. See https://github.com/syl20bnr/spacemacs/issues/9505 for further discussion on the Spacemacs side.

**Comment by raxod502** [comment]
And naturally the anarchy of GitHub leads us to have most of the discussion at #148.

**Comment by progfolio** [comment]
Looks like this is a non-goal for Spacemacs at this point:

https://github.com/syl20bnr/spacemacs/pull/14240
