### ISSUE TITLE
Bootstrapping from nonstandard directory should be allowed

### ISSUE THREAD

**Issue by sooheon** [raxod502/straight.el#147]
I thought I'd try this out, and made a brand new `~/.emacs.d2/init.el` file with the following contents:

```
;;; init.el --- user-init-file
(setq user-emacs-directory "~/.emacs.d2/")
(let ((bootstrap-file (concat user-emacs-directory "straight/bootstrap.el"))
      (bootstrap-version 2))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
;;; init.el ends here
````

Calling emacs with `-Q -l .emacs.d2/init.el` did not bootstrap correctly, putting the straight files into my regular `.emacs.d`.

**Comment by raxod502** [comment]
This should work now without changes on your end.

However, note that loading `straight.el` after init has finished, as you're doing with `-l .emacs.d2/init.el`, has [important performance implications](https://github.com/raxod502/straight.el/issues/128#issuecomment-325552427) unless you [do it correctly](https://github.com/raxod502/straight.el/issues/128#issuecomment-325552738). I'd welcome suggestions on how to make this information more visible in the documentation or to make the system more foolproof.

**Comment by sooheon** [comment]
Some people do this kind of thing in their init.el:

```
(setq gc-cons-threshold (* 200 1024 1024))

... init stuff ...

(setq gc-cons-threshold (car (get 'gc-cons-threshold 'standard-value)))
```

Would it be possible to have some variable which can be set at the start and end of an init file in this way?

**Comment by raxod502** [comment]
No: if we don't have `unwind-protect`, then cleanup won't happen in case of an error. That would have the concrete impact that `straight.el` would forget about all the packages it built in the failed init, and rebuild them next time. As an aside, I think setting `gc-cons-threshold` like that is a bad idea: if there's an error during init, then the garbage collector is disabled for the whole session. You really want `unwind-protect` for such things.

But you don't have to deal with any of this in the usual case that you are putting your configuration in `init.el` or some other file that is loaded as part of normal startup.

**Comment by sooheon** [comment]
Thanks for the knowledge re: `unwind-protect`. In that case I'm fresh out of ideas and will go back to being a passive consumer for now ;)

**Comment by raxod502** [comment]
Sounds like the issue is resolved then.
