### ISSUE TITLE
Document requirement on Emacs version

### ISSUE THREAD

**Issue by jrosdahl** [raxod502/straight.el#152]
After reading the straight.el documentation several times during spare evening time, it looked perfect! At last, a package manager that will work for me who work in a heterogenous environment with various Emacs versions on different systems! Hooray!

Not so much:

    straight.el requires at least Emacs 25, but you are running Emacs 24.5.1

Darn. I really wanted to use straight.el. :-(

It would have been very helpful and saved me some time if the version requirement had been mentioned early in the README, so that's my suggestion.

I'll maybe return in a few years when I don't have to use Emacs 24. :-)

**Comment by raxod502** [comment]
Fixed. See also #153. Let me know if there are other places in the documentation where I could put this information, to make the requirement more apparent.
