### ISSUE TITLE
Support Emacs 24

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#153]
Quite a few people still use it, so it would probably be a good idea to support it (or at least Emacs 24.5). This would increase the use of `straight.el`, presumably. See also #152.

For Spacemacs we would need to support 24.4, according to https://github.com/syl20bnr/spacemacs/blob/8e1af145480d53e8d32cdff2c83291889903164b/init.el.

**Comment by raxod502** [comment]
Boom. Pinging people who have expressed an interest in this:

* @syl20bnr 
* @jrosdahl 
* @agsdot

Since I use Emacs 25.3, I won't be testing this extensively (beyond making sure that basic operations work now, and Travis CI). Open a new issue if there is a bug that happens on older versions, or if support for Emacs 24.3 is desired.

**Comment by syl20bnr** [comment]
Ironically I plan to move to Emacs 25 as the minimum required version as we need the priority feature of `packages.el` :-)
So at this point it should not be an issue for an eventual integration in Spacemacs.

**Comment by raxod502** [comment]
:P 

It's probably good to have this anyway, since it increases market share.
