### ISSUE TITLE
Freeze on a non-master branch?

### ISSUE THREAD

**Issue by xendk** [raxod502/straight.el#155]
I'm trying out straight and as the second thing to try (after installing a plain package) was to let straight install a package I previously had checked out by hand and loaded by `(use-package drupal-mode :ensure t)` (I contribute once in a while).

I got an error because the master branch is out of date, but checking the develop branch and letting straight rebuild works a charm.

But when I freeze versions, straight insists that the package isn't pushed, even though the local develop branch is up to date with the remote.

Shouldn't it be quiet about that, maybe just warn that some projects is using a non-master branch and carry on?

**Comment by raxod502** [comment]
Does specifying `:branch "develop"` in the recipe fix the problem? i.e.

```
(use-package drupal-mode
  :ensure t
  :recipe (:type git
           :files ("drupal-mode.el" "drush-make-mode.el" "drupal")
           :host github
           :repo "arnested/drupal-mode"
           :branch "develop")))
```

That's the purpose of `:branch`.

**Comment by xendk** [comment]
Silly me, makes sense that it should be part of the recipe. Would be nice if one could override just the branch of the recipe rather than copying the whole recipe supplied from melpa?

**Comment by vyp** [comment]
@xendk https://github.com/raxod502/straight.el/issues/113#issuecomment-317617786 🙂

**Comment by xendk** [comment]
@vyp Aha! Thanks, I'll close this as a duplicate then.

**Comment by raxod502** [comment]
See also https://github.com/raxod502/straight.el/issues/116 in particular. And note that you don't have to literally copy from MELPA; you can use `M-x straight-get-recipe`.
