### ISSUE TITLE
Show entire dependency graph

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#16]
Currently dependencies are not necessarily explained very well, since only the direct cause is reported (e.g. a dependency could cause MELPA to be cloned, and the message displayed is then unhelpful). I would like the whole chain to be shown.

**Comment by raxod502** [comment]
It's coming!

**Comment by raxod502** [comment]
Fixed in 2cd29b85baa1fcadb4bff41831b12f42d5c26d2a and 54669c3c7d6e1b60c3d19981afe2bad4ed342f35.

**Comment by raxod502** [comment]
Merged.

**Comment by shackra** [comment]
Any idea how to interactively show which packages a package depends on?

**Comment by raxod502** [comment]
No such feature currently exists. It would be easy to add -- I suggest opening a new issue to propose the idea. Implementation-wise, it would involve looking at the data in `straight--recipe-cache` to determine the dependencies recursively. This would of course only work for packages that have been made available in the current session, as there's no API for Elisp package metadata. ([Well, you can kind of pretend like there is one, see `upm --lang=elisp (search|info)`, but that's a horrifying hack and not compatible with `straight.el`.](https://github.com/replit/upm))
