### ISSUE TITLE
Cloning repository with nonstandard URL fails

### ISSUE THREAD

**Issue by holocronweaver** [raxod502/straight.el#162]
Current behavior: Recipe for `matlab-mode` involves a repo URL that ends in `matlab-mode/src`, resulting in `straight-vc-git-clone` cloning to a directory called `src` rather than `matlab-mode` as expected. This causes the subsequent directory change to `local-repo` to fail.

Expected behavior: Clone `matlab-mode` to `local-repo` or some other consistent naming scheme, avoiding any idiosyncrasies in the git URL.

Suggested fix: In `straight-vc-git-clone` change 
```
 (straight--get-call
             "git" "clone" "--origin"
             straight-vc-git-primary-remote
             "--no-checkout" url)
```
to
```
  (straight--get-call
             "git" "clone" "--origin"
             straight-vc-git-primary-remote
             "--no-checkout" url local-repo)
```
This solved my problem in the case of `matlab-mode`, though I am still getting a message `Cannot load matlab-mode` despite the fact that it seemingly loads just fine.

**Comment by raxod502** [comment]
Pushed in https://github.com/raxod502/straight.el/commit/e39d4affdc0270ac879bca51bea1a0146b157c41. Thanks.

**Comment by holocronweaver** [comment]
FWIW, this fixed my issue, thanks! =)
