### ISSUE TITLE
Bootstrap code generating file error for unknown reasons

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [raxod502/straight.el#163]
I cloned my .emacs.d config and when I start up emacs I get a `File Not Found` error. 
I'm using Manjaro Linux and emacs 25.3.1.

`File error: Cannot open load file, No such file or directory, ~/.emacs.d/straight/bootstrap.el`

The thing is, I don't think it's a problem with the bootstrap code or my code because (1) I just copied and pasted it and (2) I tried cloning my config and starting emacs on a fedora machine and the bootstrapping worked just fine. 

I tried creating an init.el file with only the bootstrap code and `straight-use-package 'use-package)` but It still didn't work. 

Do you have some troubleshooting suggetions?

**Comment by raxod502** [comment]
- Check if the `~/.emacs.d/straight/bootstrap.el` symlink exists, and if so, what is it pointing to?
- Start with `--debug-init` and produce a backtrace—where is the error happening?

**Comment by raxod502** [comment]
I was unable to reproduce this on a Docker container using either `archlinux/base` or `zalox/manjaro`.

**Comment by Luis-Henriquez-Perez** [comment]
1) the bootstrap symlink exists and points to `repos/straight/bootstrap.el` but `repos/straight/bootstrap.el` doesn't seem to exist
2) the `~/.emacs.d/straight/repos/straight.el` exists
3) I think the error happens when the file is being loaded

I'm pasting the backtrace I got below. And I'm going to try to manually put the file in `repos/straight/bootstrap.el`. It's very strange because this package worked on my computer before. I'm not sure what could be causing this error.

`Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "~/.emacs.d/straight/bootstrap.el")
  load("~/.emacs.d/straight/bootstrap.el" nil nomessage)
  (let ((bootstrap-file (concat user-emacs-directory "straight/bootstrap.el")) (bootstrap-version 2)) (if (file-exists-p bootstrap-file) nil (save-current-buffer (set-buffer (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el" (quote silent) (quote inhibit-cookies))) (goto-char (point-max)) (eval-print-last-sexp))) (load bootstrap-file nil (quote nomessage)))
  eval-buffer(#<buffer  *load*> nil "/home/luishp/.emacs.d/init.el" nil t)  ; Reading at buffer position 1121
  load-with-code-conversion("/home/luishp/.emacs.d/init.el" "/home/luishp/.emacs.d/init.el" t t)
  load("/home/luishp/.emacs.d/init" t t)
  #[0 "\205\266`

**Comment by raxod502** [comment]
Something must be very wrong. The simplest explanation would be that somehow the `delete-file` function follows symlinks on Manjaro Linux.

`~/.emacs.d/straight/repos/straight.el` should be a Git repository. Can you verify whether the working directory is dirty? Presumably `git status` shows that `bootstrap.el` has been deleted.

Presuming that this is the case, does it work after you `git checkout` the missing file(s)? To test further, check to see if the `delete-file` function does indeed follow symlinks (i.e. it deletes the target of a symlink instead of the link itself).

**Comment by Luis-Henriquez-Perez** [comment]
Here I show what I did to troubleshoot.
1) When I executed git status in the straight.el directory it said it was clean. I am concerned though that `git status` is referring to my dotfiles rather than straight.el. 

I will look into delete-file.

➜  ~ cd .emacs.d 
➜  .emacs.d git:(master) ls
config  init.el  README.org  straight
➜  .emacs.d git:(master) cd straight 
➜  straight git:(master) ls
bootstrap.el  repos
➜  straight git:(master) ls -l
total 4
lrwxrwxrwx 1 luishp luishp   30 Oct 14 09:37 bootstrap.el -> repos/straight.el/bootstrap.el
drwxr-xr-x 3 luishp luishp 4096 Oct 14 09:37 repos
➜  straight git:(master) cd repos/straight.el/ 
➜  straight.el git:(master) ls -a
.  ..  config  .git  .gitignore  init.el  README.org
➜  straight.el git:(master) git status

On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean

**Comment by vyp** [comment]
> I am concerned though that `git status` is referring to my dotfiles rather than straight.el.

``` shell
cd ~/.emacs.d/straight/repos/straight.el
git config -l | grep remote.origin.url
```

Another way would be to simply check if a `.git` exists:

``` shell
[[ -e ~/.emacs.d/straight/repos/straight.el/.git ]]; echo $?
```

**Comment by raxod502** [comment]
So, somehow, `~/.emacs.d/straight/repos/straight.el` is a symlink pointing to `~/.emacs.d` on your machine?

Can you confirm that if you move `~/.emacs.d` and clone it again (presumably from https://github.com/Luis-Henriquez-Perez/.emacs.d), you see the same problem?

**Comment by Luis-Henriquez-Perez** [comment]
When doing what `vyp` suggested I get the following results: so I think that `~/.emacs/straight.d/repos/straight.el` is not a symlink pointing to `~/.emacs.d/`

The commands below are the ones I used to conclude this. 

➜  ~ cd .emacs.d/straight/repos/straight.el 
#➜  straight.el git:(master) git config -l | grep remote.origin.url
remote.origin.url=https://github.com/Luis-Henriquez-Perez/.emacs.d.git
remote.origin.url=https://github.com/raxod502/straight.el.git
➜  straight.el git:(master) [[ -e ~/.emacs.d/straight/repos/straight.el/.git ]]; echo $?
0
➜  straight.el git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean

**Comment by raxod502** [comment]
Please try cloning from scratch.

**Comment by Luis-Henriquez-Perez** [comment]
Ok. I removed my `.emacs.d` and cloned it back. Then I started emacs to create the `straight` directory. And I deleted `~/.emacs.d/straight/repos/straight.el` and cloned it. Then I tried starting emacs again and the same error was generated.

I put my steps below:
➜  repos git:(master) rm -rf straight.el 
➜  repos git:(master) git clone https://github.com/raxod502/straight.el.git
Cloning into 'straight.el'...
remote: Counting objects: 847, done.
remote: Compressing objects: 100% (195/195), done.
remote: Total 847 (delta 190), reused 369 (delta 183), pack-reused 469
Receiving objects: 100% (847/847), 144.88 KiB | 460.00 KiB/s, done.
Resolving deltas: 100% (429/429), done.
➜  repos git:(master) cd

**Comment by raxod502** [comment]
Why did you delete `~/.emacs.d/straight/repos/straight.el` and re-clone it?

**Comment by Luis-Henriquez-Perez** [comment]
I had already tried deleting my `.emacs.d` cloning it from scratch. So I assumed that was what you meant to do.

**Comment by raxod502** [comment]
Ah. Sorry. I was referring to my suggestion

> Can you confirm that if you move `~/.emacs.d` and clone it again (presumably from https://github.com/Luis-Henriquez-Perez/.emacs.d), you see the same problem?

Precisely, after you clone your `~/.emacs.d` from scratch, I would like to know

* what does Emacs do the _first time_ you start it (messages, errors, functionality), and
* what, exactly, does the `~/.emacs.d/straight` directory and all subdirectories look like after Emacs has started the first time? (preferably displayed using `tree(1)` or a similar utility that can display a directory hierarchy along with symlink targets)

**Comment by Luis-Henriquez-Perez** [comment]
Wow it seems you were right, my own configuration is being cloned into straight.el for some reason.

1) When first starting emacs, it says this:
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "~/.emacs.d/straight/bootstrap.el")
  load("~/.emacs.d/straight/bootstrap.el" nil nomessage)
  (let ((bootstrap-file (concat user-emacs-directory "straight/bootstrap.el")) (bootstrap-version 2)) (if (file-exists-p bootstrap-file) nil (save-current-buffer (set-buffer (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el" (quote silent) (quote inhibit-cookies))) (goto-char (point-max)) (eval-print-last-sexp))) (load bootstrap-file nil (quote nomessage)))
  eval-buffer(#<buffer  *load*> nil "/home/luishp/.emacs.d/init.el" nil t)  ; Reading at buffer position 845
  load-with-code-conversion("/home/luishp/.emacs.d/init.el" "/home/luishp/.emacs.d/init.el" t t)
  load("/home/luishp/.emacs.d/init" t t)
  #[0 "\205\266

2) And the file directory looks like this:
For conciseness I will exclude what's in my config..
.emacs.d
├── config
│   *files in my config*
├── init.el
├── README.org
└── straight
    ├── bootstrap.el -> repos/straight.el/bootstrap.el
    └── repos
        └── straight.el
            ├── config
            │   ├── autoload-funcs
            │   │   ├── emms
            │   │   │   └── emms.el
            │   │   ├── mu4e.el
            │   │   ├── my-windows
            │   │   │   └── my-windows.el
            │   │   ├── notmuch.el
            │   │   └── w3m.el
            │   ├── emacs-completion.el
            │   ├── emacs-core.el
            │   ├── emacs-defaults.el
            │   ├── emacs-dired.el
            │   ├── emacs-email.el
            │   ├── emacs-eshell.el
            │   ├── emacs-evil.el
            │   ├── emacs-general-bindings.el
            │   ├── emacs-get-packages.el
            │   ├── emacs-gui-display.el
            │   ├── emacs-langs.el
            │   ├── emacs-macros.el
            │   ├── emacs-org.el
            │   ├── emacs-osx.el
            │   ├── emacs-text-display.el
            │   ├── emacs-utilities.el
            │   ├── emacs-version-control.el
            │   └── my-packages
            │       └── evil-easymotion
            │           └── evil-easymotion.el
            ├── init.el
            └── README.org

**Comment by Luis-Henriquez-Perez** [comment]
Ok I realized it was a problem in the contents in my .gitconfig file. Looks like I must have inadvertedly changed it using magit. Thank you for helping me troubleshoot.

**Comment by raxod502** [comment]
What was the problem? I'm quite curious since that is a bizarre symptom.

**Comment by Luis-Henriquez-Perez** [comment]
Well to be honest I'm not very good with git yet. So when using magit I inadvertently set `remote` in my `.gitconfig` file to 
`[remote origin]
    url=https://github.com/Luis-Henriquez-Perez/.emacs.d.git`
I think this made it so that whenever I cloned anything, it would clone my .emacs.d instead. When I removed those two lines from my `.gitconfig` file everything worked fine again.
