### ISSUE TITLE
Win7: Operation not permitted while install

### ISSUE THREAD

**Issue by Ovsyanka** [raxod502/straight.el#164]
I use emacs 25.3_1 on Windows7 x64.
While installation process, the straight.el trying to make symbolic link to bootstrap.el. And if you running the emacs without Administrative privileges it fails with error: "Operation not permitted".

See the `(make-symbolic-link target linkname)))` string in `install.el`.

I think it should asking for priveleges evaluation or at least handle this error and show explanation message instead just bare error. Something like this: "Symbolic link creation failed. Try to run emacs as Administrator or make link manually and then start emacs again. linkname: <linkname>, target: <target>.

**Comment by raxod502** [comment]
I'm not convinced that improving this failure condition will be useful until `straight.el` supports Windows; see #124. Currently, the package management model used assumes that symlinks can be created freely, and this would be nontrivial to change.

**Comment by Ovsyanka** [comment]
I didn't found the #124 issue before. In considiration of it I agree with you. I think that #164 could be a "subtask" of #124 because it talks about one of Windows supporting aspects and could be solved separately of others.

**Comment by raxod502** [comment]
This is addressed by https://github.com/raxod502/straight.el/commit/2d6a7d7b5f9d241d78b1e27cad67c2167e0c7f39.
