### ISSUE TITLE
Interest in straight.el-related community chat?

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#165]
It was suggested in https://github.com/raxod502/straight.el/issues/124#issuecomment-336729003 to create a Discord/Gitter/IRC/etc. forum for discussion related to `straight.el` that does not easily fit into the GitHub Issues format.

Would people be interested in this?

**Comment by dieggsy** [comment]
Could be useful. I happen to like IRC, though I'm not opposed to most other formats either.

**Comment by Ovsyanka** [comment]
Personally, I like IRC. But I don't suggest it because it is not cosy for peoples who not familiar with.
I can point to Discord or Gitter.

**Comment by rgrinberg** [comment]
Gitter is OK with me. So is IRC. Anything that is accessible through riot.im :)

**Comment by raxod502** [comment]
Created at https://gitter.im/raxod502/straight.el and badge added to README in https://github.com/raxod502/straight.el/commit/4df854429a3ed002b40b183bbc0c89406b9fe743.
