### ISSUE TITLE
Warn when loading large number of packages outside transaction

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#167]
This is a common problem, see https://github.com/raxod502/straight.el/issues/128#issuecomment-325552427 and (possibly) https://github.com/raxod502/straight.el/issues/9#issuecomment-337700460.

When people see that `straight.el` takes 1 minute to load, they jump to the issue about it being slow, without realizing that that issue is about load times of 1 second being too slow, and that if it takes 1 minute then your configuration is wrong.

**Comment by vyp** [comment]
Any ideas on what constitutes as large, maybe 3+? Or is that too small?

**Comment by raxod502** [comment]
The issue is that there's really no way to count the number of packages in a single session outside a transaction, by definition—since transactions are the means by which sessions are detected. (If you install ten packages interactively, there's nothing amiss.) What would really be useful is checking if five packages are installed outside a transaction, but each within 5 seconds of the previous.

**Comment by raxod502** [comment]
I found a better solution, namely enable transactions automatically without the need for a `straight-transaction` block or other such user code.
