### ISSUE TITLE
Void variable (ert--running-tests)

### ISSUE THREAD

**Issue by noctuid** [raxod502/straight.el#177]
For example `error: git-commit.el:0:0: error: void-variable: (ert--running-tests)`. This also happens for smex, async-bytecomp.el, common-lisp-snippets.el, etc. Emacs crashes if I try `--debug-init` (and I see `Building helm -> Building async` in the echo area, for example). If I don't make any configuration changes, it fails on the same package every time.

**Comment by noctuid** [comment]
If I run `straight-check-all` after initialization, some packages will build correctly the second time (for others, I get the same error).

**Comment by raxod502** [comment]
I can install all of those packages without difficulty. Can you post a minimal init-file which reproduces the problem?

**Comment by noctuid** [comment]
I guess straight just made this issue more obvious since I was loading a package that requires ert after 5 seconds of idle time. See rolandwalker/hardhat#13.
