### ISSUE TITLE
Better support for Org mode

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#192]
I'd like support for Org to be transparent, i.e. there are recipes for `org` and `org-plus-contrib` as in Org ELPA.

As a first step, I've submitted an inquiry to the Org mailing list on whether there is a way to obtain Org securely, i.e. not via HTTP.

**Comment by raxod502** [comment]
See http://lists.gnu.org/archive/html/emacs-orgmode/2017-12/msg00077.html. No response yet. If that continues, then I'll submit a bug report.

**Comment by raxod502** [comment]
We're using EmacsMirror until the Org people support HTTPS. You can now install `org` and `org-plus-contrib` as if from `org-elpa`.

**Comment by xuchunyang** [comment]
> We're using EmacsMirror until the Org people support HTTPS

It is now supported according to http://lists.gnu.org/archive/html/emacs-orgmode/2017-12/msg00578.html, note that the git clone URL is also changed.

**Comment by raxod502** [comment]
@xuchunyang Fixed, thanks for the heads up.
