### ISSUE TITLE
Asks about local variables in repositories on every startup

### ISSUE THREAD

**Issue by sooheon** [raxod502/straight.el#207]
<img width="740" alt="screen shot 2017-12-29 at 11 20 59 am" src="https://user-images.githubusercontent.com/302945/34427887-5c46b2ae-ec8a-11e7-82ca-7d644f7d4f7e.png">

This leaves dirty worktree, interrupting next pull/merge.

**Comment by raxod502** [comment]
Can you provide a `user-init-file` which causes this behavior? On starting `straight.el` from `emacs -Q` and running `M-x straight-use-package RET cider RET`, I do not see a warning about local variables.

**Comment by sooheon** [comment]
I've narrowed it down to the [persp-mode](https://github.com/Bad-ptr/persp-mode.el) package. Until I have time to dig around more, just leaving it be for now. (May have nothing to do with straight.el)
