### ISSUE TITLE
Don't just fail silently when texinfo compilation fails

### ISSUE THREAD

**Issue by xuchunyang** [raxod502/straight.el#210]
After switching straight.el from package.el, I notice the info manual of use-package is missing, it takes me a while to figure out it is because the command fails

> $ makeinfo use-package.texi
> ...
> makeinfo: Removing output file `/Users/xcy/.emacs.d/straight/repos/use-package/use-package.info' due to errors; use --force to preserve.

(the built-in `/usr/bin/makeinfo` on macOS is too old for this use-package.texi)

I hope straight.el can at least let me know when the command fails, even `message` something like the following helps.

>Command "makeinfo use-package.texi" fails

**Comment by raxod502** [comment]
Good idea. I guess it's better to emit a warning by default, since that will probably cause people to be more motivated to fix packages which are broken. I suppose the same logic probably applies to byte-compilation _errors_ (as opposed to warnings).
