### ISSUE TITLE
Warning on Org installation

### ISSUE THREAD

**Issue by xuchunyang** [raxod502/straight.el#211]
When I use `(straight-use-package 'org)` to install the latest Org, it displays the following in `*Warning*` buffer

> Warning (emacs): Could not define org version correctly.  Check installation! [2 times]

and `M-x org-version` shows

> Org mode version N/A (N/A !!check installation!! @ /Users/xcy/tempt/.emacs.d/straight/build/org/)

**Comment by raxod502** [comment]
This should be fixed by #72. The problem is that Org produces this warning if you byte-compile it without running `make` first. The issue should be fixable via some combination of #72 and #115.

**Comment by raxod502** [comment]
See also https://github.com/raxod502/straight.el/issues/168#issuecomment-338450894, where I mention some hacks I put in my init-file to inhibit the warning until this issue is fixed.

**Comment by xuchunyang** [comment]
Thanks for the info. I'm going to close this issue since it has been tracked by other issue.

For now, I switch back to `make` to install org manually, it looks the most obvious downside is that I should not install any package which declares org as its dependency, I think I can live with that.

**Comment by caadar** [comment]
...I should not install any package which declares org as its dependency...

Not a problem at all.

`````
(straight-override-recipe
   '(org :type git :host github :repo "emacsmirror/org" :no-build t))
(use-package org)
`````

(Correct  host, repo etc if needed.)

**Comment by raxod502** [comment]
Actually, I think you can just do

```
(straight-use-package '(org :local-repo nil))
```

in the latest version of `straight.el`.

**Comment by xuchunyang** [comment]
Thank you both for the tips, they helps.

**Comment by raxod502** [comment]
There's a much better hack now, thanks to https://github.com/raxod502/radian/issues/410.

**Comment by dustinlacewell-wk** [comment]
I'm still getting this error, even with the updated hacks and everything.

**Comment by raxod502** [comment]
It continues to work for me. Can you post your configuration?

**Comment by dustinlacewell-wk** [comment]
I think it had to do something with with something causing org8 to be loaded some how. I had to completely deconstruct my init file and rebuild it from scratch, adding piece by piece back, with all my org stuff right after straight.el boostrapping. I still have no idea what was causing org-8 to be loaded. I was getting that NA version thing.

I'm thinking that to help straight.el in terms of adoption in this time (I do _a lot_ of straight.el evangelism) to add a section on the README, maybe near the bit where you explain how to bootstrap straight.el, what a minimal working Org 9 configuration looks like.

Hey anyway, thanks so much for this package, it is definitely the future for emacs.

**Comment by raxod502** [comment]
@dustinlacewell-wk I've done as you suggest on `develop`; let me know what you think. I'm glad you like `straight.el` :)

**Comment by dustinlacewell-wk** [comment]
lgtm :)
