### ISSUE TITLE
(straight-use-package 'debbugs) changes the git repo

### ISSUE THREAD

**Issue by xuchunyang** [raxod502/straight.el#213]
```
~ $ git -C ~/.emacs.d/straight/repos/debbugs status -s
 M debbugs-ug.info
 M debbugs.info
```

I guess it is because debbugs provides both debbugs.{info,texi}, straight.el creates symbol links for them, then `makeinfo debbugs.texi` creates a new version of debbugs.info thus changes it.

**Comment by raxod502** [comment]
Your diagnosis sounds correct. I already fixed a similar problem with autoload generation in #61.
