### ISSUE TITLE
Resolving :local-repo to an absolute path breaks everything

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#218]
A recent change (6a47addd6a0b8c82b25a89cae6f6131654b388ec) caused `:local-repo` to be resolved to an absolute path on conversion of a recipe to the internal format. This caused many regressions in message formatting and other as-of-yet-undiscovered areas. Unfortunately, half of the code expects a relative path (messages, etc.) and the other half implicitly assumes an absolute path (working directory settings, etc.). Some thought is required as to which half is easier to fix.

**Comment by rgrinberg** [comment]
Does this mean we're not allowed to set `:local-repo` to an absolute path anymore?

**Comment by raxod502** [comment]
No it doesn't. That bug remains fixed.
