### ISSUE TITLE
Recipe inheritance and/or no-autoloads use-package keyword

### ISSUE THREAD

**Issue by dieggsy** [raxod502/straight.el#232]
I was expermienting with setting `:no-autoloads t` on some packages that define _way too many autoloads_, and thought it inconvenient to have to copy the whole package recipe just to specify that I don't want autoloads. It would be nice if there was a way to do something like 
```
:straight (:inherit pkg-name 
           :additional-keywords-or-overrides ...)`
```
If there's a way to do this currently, perhaps I missed it :) 

Another idea I had (though I think the above is a better solution) is to expose something like `:straight-no-autoloads` through the use-package interface.

**Comment by raxod502** [comment]
This duplicates #116.

I am very very much in favor of introducing something like this. In fact I've just promoted that issue to the 1.0 release milestone. I just need someone (or me, once I have more time) to come up with a sufficiently general syntax proposal that would cover all the cases we want this feature to handle.

**Comment by dieggsy** [comment]
Ah, thanks - sorry for the duplicate issue.
