### ISSUE TITLE
Dependency problems due to the way straight handles package loading

### ISSUE THREAD

**Issue by Northcode** [raxod502/straight.el#233]
If you load any package that uses a built in package as a dependency (I had it happen with org).

Example init file where this happens:
```
;;;; bootstrap straight.el
(let ((bootstrap-file (concat user-emacs-directory "straight/repos/straight.el/bootstrap.el"))
      (bootstrap-version 3))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

(use-package outline
  :straight t)

(use-package outshine  ;; outshine depends on both outline and org, but will load the built-in org instead of checking if we have a straight.el version downloaded
  :straight t
  :init
  (require 'outshine)
  (add-hook 'outline-minor-mode-hook 'outshine-hook-function))

(use-package org
  :straight t
  :bind
  (("C-c a" . org-agenda)
   ("C-c c" . org-capture)))
```
It will load org as a dependency of outshine, which loads the built-in version since straight hasn't been told to grab org from its repos yet.
When org is loaded with straight it doesn't completely replace the original built-in version that loaded earlier, in my experience at least (default emacs 25.3.1 on archlinux).
This causes a lot of things to break, an example I found was org-capture.
The only errors from emacs are the rather cryptic:
```
Problems while trying to load feature ‘org-w3m’
Problems while trying to load feature ‘org-bbdb’
Problems while trying to load feature ‘org-bibtex’
Problems while trying to load feature ‘org-docview’
Problems while trying to load feature ‘org-gnus’
Problems while trying to load feature ‘org-info’
Problems while trying to load feature ‘org-irc’
Problems while trying to load feature ‘org-mhe’
Problems while trying to load feature ‘org-rmail’
org-element--set-regexps: Symbol’s function definition is void: org-link-types
```

I don't know if theres an easy way to fix this due to the way straight.el works, for now we just have to be careful to place stuff like this in the correct order.
Or if there happens to be an easy fix to this I didn't know about please tell me, I didn't find any after a few hours of search at least.

A possible fix might be to issue a warning when something tries to load a package where a dependency exists in straight.el's repos | build folders, but has not been loaded, so it would load the built-in instead.
Example:

> Warning: package 'outshine depends on 'org, which it looks like exists in your downloaded packages, but is not loaded yet. Move (straight-use-package 'org) load before 'outshine is loaded in your init file to use the straight version instead of the built-in.

**Comment by raxod502** [comment]
I had a look at the `outshine` package. You claim it depends on `org`, but it actually doesn't declare any such dependency:

```elisp
;;; outshine.el --- outline with outshine outshines outline

;; Maintainer: Adam Porter <adam@alphapapa.net>
;; Version: 2.0
;; URL: http://github.com/alphapapa/outshine
;; Package-Requires: ((outorg "2.0") (cl-lib "0.5"))
```

And for `outorg`:

```elisp
;;; outorg.el --- Org-style comment editing

;; Maintainer: Adam Porter
;; Version: 2.1-pre
;; URL: https://github.com/alphapapa/outorg
;; Package-Requires: ((emacs "24.4"))
```

So it looks like this is a bug in `outorg`. It needs to declare a dependency on `org`.

**Comment by raxod502** [comment]
cc @alphapapa as the apparent maintainer of both packages.

**Comment by Northcode** [comment]
@raxod502 @alphapapa There seems to be a discrepancy between what outshine specifies in its el file and what it actually depends on, according to `epkg-describe-package` it has theese dependencies, which includes org:
```
[-] Dependencies:
 |-[+] cl  builtin  cl
 |-[+] cl-lib  builtin  cl-lib
 |-[+] emacs  builtin  newcomment
 |-[+] imenu  builtin  imenu
 |-[+] navi-mode  github  navi-mode
 |-[+] org  git  org-agenda
 |-[+] outline  builtin  outline
 ‘-[+] outorg  github  outorg
```
For outorg too:
```
 ‘-[-] outorg  github  outorg
    |-[+] ert-buffer-report  github  ert-buffer
    |-[+] org  git  org
    |-[+] org-watchdoc  github  org-watchdoc
    ‘-[+] outline  builtin  outline
```
But on melpa and in the package itself it does not list those.
I don't know where epkg defines its dependencies, but those seem more correct than the ones specified in the .el file.
Since straight.el pulls from melpa first it gets the wrong deps, and its not really its fault. 
So I'll close this issue.

I'll make an issue on outshine and outorg as well, as it appears to be a problem there instead of here.

**Comment by alphapapa** [comment]
Copying my response from the other issue, as I don't think this is a bug in Outorg:

> Hi,
> 
> Well, some of those required files are actually included with Emacs and don't need to be declared as package dependencies. And some of the ones that Outshine requires are loaded by Outorg, which Outshine loads and declares a dependency on.
> 
> Specifically, the only package not included with Emacs that is loaded is navi-mode, and it is optional, so not a dependency. org-watchdoc also appears to be optional, and I can't even find it on my system.
> 
> Admittedly, it is a bit messy, and probably the best thing to do is a general refactoring of all 3 packages. I might do that someday, but no promises, as these are large packages that I didn't write myself.
> 
> However, the packages do install and load correctly when installed from MELPA with package.el. I think the problem you're having may be caused by straight.el being more strict than package.el.
> 
> The problem of using an outdated, built-in Org instead of a later version is a more general problem with Emacs package systems, AFAIK. But it shouldn't affect Outorg or Outshine, as they don't require recent Org versions.

**Comment by Spass1966** [comment]
I am having what I think is a variation of the same issue.

```
(let ((straight-current-profile 'pinned))
  (straight-use-package 'org-plus-contrib)
  (straight-use-package 'org)

(define-key global-map "\C-cc" 'org-capture)
```

Invoking `org-capture` gives: `org-capture-select-template: Symbol’s function definition is void: org-mks`

`(find-library "org-capture")`
then grep for `org-mks` which is defined in `org-macs.el`
I can load the file directly which gives me what I need, namely a functional org-capture but this is a huge hack and obviously something is wrong in how Emacs is loading org.

What's going on here? How do I fix this without a hack?

**Comment by raxod502** [comment]
@Spass1966 I cannot reproduce this with the following init-file:

```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'org-plus-contrib)

(define-key global-map "\C-cc" 'org-capture)
```

I suspect there is some other code in your configuration which causes the problem. If you find it, could you open a new issue for that?

**Comment by Spass1966** [comment]
@raxod502 Problem solved! I was loading org before straight because I use a literate emacs config. I loaded straight before tangling my org file and now org-capture works. Thank you!
