### ISSUE TITLE
straight.el barfs in the presence of duplicate file names

### ISSUE THREAD

**Issue by jhenahan** [raxod502/straight.el#234]
Just ran into this corner case while tracking `org-plus-contrib` on `master`. There's an `ob-lua.el` in both `lisp/` and `contrib/lisp` (different files). `straight--symlink-recursively` does not like this and will prevent loading if it would trigger building `org-plus-contrib`.

**Comment by raxod502** [comment]
I would be inclined to ask why there are two copies of `ob-lua.el`??

But I agree, `straight.el` should at least demote this to a warning so that it doesn't break your init over something that probably wouldn't even affect you.

**Comment by jhenahan** [comment]
It looks like the contrib version is a new implementation being worked on by someone other than the authors of the mainline version.

**Comment by raxod502** [comment]
How is this handled in `org-plus-contrib`, then? Do they just not include the version from `lisp/ob-lua.el`? If so, then I guess we would have to make sure that our recipe for `org-plus-contrib` puts the two directories (`lisp` and `contrib/lisp`) in the correct order, depending on whether we decide the first or last copy of a file linked to the same place should "win", so to speak.

**Comment by jhenahan** [comment]
That's a good question. I'll consult the mailing list.

**Comment by jhenahan** [comment]
Looks like this came up on the mailing list. Should be better, now, in this case. Based on the discussion, this broke all kinds of package managers for `org-plus-contrib`, so if `straight.el` can make this nonfatal then that'd be quite a feather in its figurative cap.

**Comment by raxod502** [comment]
This broke my configuration and I didn't have time to figure out why, so I demoted the error to a warning, which I think is probably the better user experience.
