### ISSUE TITLE
Multiple packages out of 1 repository

### ISSUE THREAD

**Issue by rgrinberg** [raxod502/straight.el#237]
I'm trying to use hyperbole using the following straight recipe:

```
  (straight-use-package
   '(hyperbole
     :files ("*.el" "kotl/*.el" "man/*.info" "man/*.texi")
     :host github :repo "rswgnu/hyperbole"))
```

But I get the following error: eval-buffer: Cannot open load file: No such file or directory, kotl/kotl-autoloads

I'm assuming it's because my use `:files` to load 2 packages out of 1 repository isn't correct. How should this be done properly?

**Comment by raxod502** [comment]
The code for `hyperbole` expects all the `kotl` files to be placed in a `kotl` subdirectory. Just use this instead:

```elisp
(straight-use-package
 '(hyperbole
   :files ("*.el" ("kotl" "kotl/*.el") "man/*.info" "man/*.texi")
   :host github :repo "rswgnu/hyperbole"))
```

**Comment by raxod502** [comment]
On another note, apparently byte-compiling `hyperbole` causes global keybindings to registered in the current session. What the actual ~swearword~?

**Comment by rgrinberg** [comment]
Radon Rosborough <notifications@github.com> writes:

> On another note, apparently byte-compiling `hyperbole` causes global keybindings to registered in the current session. What the actual ~swearword~?

Yeah, that's quite gross. Do you recall which keybinding or function
this was happening to? I'll report it as an issue.

Thanks for the help!

**Comment by raxod502** [comment]
It appears to bind `M-RET` to `hkey-either`, `C-h A` to `hkey-help`, `M-o` to `hkey-operate`, `C-c C-r` to `hui:ebut-rename`, and the list goes on and on... goodness me.

The full list can be found [here](https://git.savannah.gnu.org/cgit/hyperbole.git/tree/hyperbole.el?id=66106d3249a784f7c970423dec7c45ccd8945206#n219), and the problematic part is where everything is initialized when the file is loaded, see [here](https://git.savannah.gnu.org/cgit/hyperbole.git/tree/hyperbole.el?id=66106d3249a784f7c970423dec7c45ccd8945206#n710).

If the recipe is working for you, I'll close this issue. Thanks!
