### ISSUE TITLE
Cannot bootstrap: "let: Cannot open load file: No such file or directory, ~/.emacs.d/straight/repos/straight.el/bootstrap.el

### ISSUE THREAD

**Issue by nrvale0** [raxod502/straight.el#244]
Slightly modified bootstrapping code from the install docs in order to make sure necessary dirs exist:

```elisp
(let ((bootstrap-dir (concat user-emacs-directory "straight/repos/straight.el"))
      (bootstrap-file (concat user-emacs-directory "straight/repos/straight.el/bootstrap.el"))
      (bootstrap-version 3))
  (make-directory bootstrap-dir t)
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
```

results in this error message:

```pre
Bootstrapping straight.el...done
let: Cannot open load file: No such file or directory, ~/.emacs.d/straight/repos/straight.el/bootstrap.el
```

I've verified the directory does exist and that the install.el is **not** in the directory. 

I don't see much opportunity for this to go off the rails given the above code is pretty simple. Not sure where to even start with debugging...

**Comment by xuchunyang** [comment]
Why? Doesn't `install.el` already create that dir for you?

**Comment by raxod502** [comment]
Yes, the way in which you modified the bootstrap code will cause it to fail with the error message you indicated. Why did you make that modification?

**Comment by nrvale0** [comment]
The fist time I ran the code from the docs it failed complaining about the dir not existing.

**Comment by nrvale0** [comment]
I have to wonder if this was timing related as I just moved to a "fast" network and things seem to be working now.

**Comment by raxod502** [comment]
If you have a way to reproduce the error, I'd be happy to investigate. Otherwise, feel free to close. In any case, glad to hear it's working now! :)
