### ISSUE TITLE
Package Installasion Issue (HyperBole)

### ISSUE THREAD

**Issue by PlasmaShift** [raxod502/straight.el#247]
When I try to install [Hyperbole](https://www.gnu.org/software/hyperbole/) It fails to load properly and I get "eval-buffer: Cannot open load file: No such file or directory, kotl/kotl-autoloads".

My guess is hyperbole tries to create a folder/file and can't "I don't know if this is restricted" or hyperbole expects the file to be in /elpa

As a side note making using hyperbole to make buttons in your comments In your Radian Emacs might be nice way to add interactivity for example jumping around with buttons to your documentation

**Comment by xuchunyang** [comment]
I don't know about the package but I think this is related to #226. straight.el doesn't ensure all the emacsmirror recipes are correct. You have to adjust the recipe by yourself.

**Comment by raxod502** [comment]
See #237.
