### ISSUE TITLE
recipe for `lispy` should pull in another clojure file

### ISSUE THREAD

**Issue by blak3mill3r** [raxod502/straight.el#248]
I did read the relevant section of the docs, but I wasn't able to find where the default recipe for `lispy` actually lives (sorry).

With the default recipe, which does pull in the file `lispy-clojure.clj`, I get errors:

```
error in process filter: lispy--clojure-middleware-load: CompilerException java.io.FileNotFoundException: /home/blake/.emacs.d/straight/build/lispy/lispy-clojure-test.clj (No such file or directory), compiling:(/home/blake/.emacs.d/straight/build/lispy/lispy-clojure.clj:588:1) 

error in process filter: CompilerException java.io.FileNotFoundException: /home/blake/.emacs.d/straight/build/lispy/lispy-clojure-test.clj (No such file or directory), compiling:(/home/blake/.emacs.d/straight/build/lispy/lispy-clojure.clj:588:1) 
```

This is because, in spite of the name of the file, it is required functionality and the `lispy-clojure` namespace tries to load it dynamically. Since the straight recipe leaves it out, it isn't available and this breaks `lispy`.

My fix is to use this recipe:

```emacs-lisp
  :straight
  (lispy :type git :files (:defaults "lispy-clojure.clj" "lispy-clojure-test.clj") :host github :repo "abo-abo/lispy"
    )
```

I would be happy to make a PR that fixes the default recipe, if someone can point me to it.

**Comment by dieggsy** [comment]
The recipe for lispy I get with `straight-get-recipe` is:
```
(lispy :type git :files (:defaults "lispy-clojure.clj") :host github :repo "abo-abo/lispy")
```
Which I believe is the same as [melpa's lispy recipe](https://github.com/melpa/melpa/blob/269acf093c3aa508479bf532a4e07c9c6d568c72/recipes/lispy).

**Comment by raxod502** [comment]
> I wasn't able to find where the default recipe for `lispy` actually lives

Check out `straight-recipe-repositories`, and `straight-recipes-REPO-(retrieve|list)`. In this case, the recipe is retrieved from MELPA.

`straight.el` does not maintain any package recipes. That would be way too much work. Instead, I have it steal other people's data! :)

> in spite of the name of the file, it is required functionality

If that's the case, it's a problem on MELPA's end. The MELPA package does not include this file either.

**Comment by raxod502** [comment]
What was the resolution here? I notice that the MELPA recipe has not been changed.

**Comment by blak3mill3r** [comment]
I opened https://github.com/abo-abo/lispy/issues/401 to ask the maintainer. If this makes sense, I'll make a PR on MELPA.

**Comment by blak3mill3r** [comment]
It is broken for me without overriding the recipe, like this

```emacs-lisp
use-package lispy
  :straight
  (lispy :type git
         :files (:defaults "lispy-clojure.clj" "lispy-clojure-test.clj")
         :host github
         :repo "abo-abo/lispy")
  ;; ...
  )
```

**Comment by blak3mill3r** [comment]
The file `lispy-clojure-test.clj` is really not required functionality and `lispy-clojure.clj` shouldn't throw in its absence. That's been fixed in `abo-abo/lispy` `master`.
