### ISSUE TITLE
Storing with local changes to installed package in lockfile

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [raxod502/straight.el#249]
When creating a lockfile how exactly do I deal with having made a change to an installed package? When calling `straight-freeze-versions` I get prompted when package has a dirty worktree to either push, pull it, or edit it. I'm confused, though, because I can't push/pull it because the package repository is not mine. Perhaps the solution to this is creating my own fork of the package?

**Comment by raxod502** [comment]
Yes, if you want to maintain changes, you will have to create a fork. Otherwise, how could the change be propagated to other machines?

**Comment by dieggsy** [comment]
@raxod502 though it sounds extremely hackish, wouldn't it technically be possible to version control (somewhere else, like a dotfiles repo) patches that get applied at some point in the pull/build process?

**Comment by raxod502** [comment]
Technically, that might be possible. Under what circumstances would it be an improvement?

**Comment by dieggsy** [comment]
@raxod502 I'm not sure. It's not a feature I'd need, but perhaps it'd be useful someone who doesn't have or want to have a github/gitlab/etc. account.

**Comment by raxod502** [comment]
I suppose I wouldn't have an objection to this feature being implemented, although you'd have to have a pretty extreme use case for it to be worth your time. ¯\\\_(ツ)\_/¯

**Comment by Luis-Henriquez-Perez** [comment]
I thought this would have to be the case, but I just thought if it was strange that if had 50 one line changes in 50 packages, I'd have to fork those 50 packages. I guess the solution would be to strongly prefer advising over modifying packages themselves.

**Comment by raxod502** [comment]
> 50 one line changes in 50 packages

Under what circumstance would this ever happen? I think this would help me to understand the use case better.

> the solution would be to strongly prefer advising

Of course. Advising is much simpler than any solution that involves actual changes to the package files. See also [el-patch](https://github.com/raxod502/el-patch). (And you can automate these things programmatically, if you really had to make the same change to 50 different packages.)

**Comment by Luis-Henriquez-Perez** [comment]
`Under what circumstance would this ever happen? I think this would help me to understand the use case better.`
I was just making the point that It seemed excessive to fork an entire package for a small change. I wasn't being literal. Right now I've only made changes to a handful of packages. Although I could see it adding up  the in the future. 

`Advising is much simpler than any solution that involves actual changes to the package files. `
I knew about advising but I didn't like that if I had a change I had to make on one line in the body of a function of a package, I'd have to copy the whole function over to my `init.el` file. Upon retrospection, though, this is still much better than forking the package. 

`See also el-patch.`
Interesting that you mention this because as I was looking for an alternative to forking some packages I had made changes to I came across `el-patch` and today added it to my [.emacs.d](https://github.com/Luis-Henriquez-Perez/.emacs.d/commit/9577424e27739b6a59608c3551f0d680cff0dd49). The validation is definitely the killer feature. But I like the fact I can tell what I've changed in an overriden function just by looking at the el-patch (as opposed to an overriding advice, where I can't tell). 

I'm open to close the issue at anytime by the way. You've answered my question very thoroughly.

**Comment by raxod502** [comment]
Great to hear! Yes, I think advice (for making simple changes very quickly) and `el-patch` (for overriding entire functions and variables), together, diminish the need for forking by quite a lot. The main reason I fork packages is because I've submitted a pull request, and it hasn't been merged yet. (Of course, `straight.el` helps a lot with that use case—have you noticed that all of my Emacs packages relate to making it easier to hack on other Emacs packages? 😛)
