### ISSUE TITLE
Simplify function backports

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#258]
Currently, we have 163 lines of function definitions copied from new Emacs versions, split into six different `eval-when-compile` forms so that all the dependencies work correctly during byte-compilation. This is very complex and brittle. Instead, we could use much simpler definitions, given that we know how the functions are used in `straight.el` (no need to account for all the weird edge cases, nor provide exactly the same feature-set). For example, instead of the huge setf definition for `alist-get`, we could just use something like [`radian-alist-set`](https://github.com/raxod502/radian/blob/2f900981077d8c2365a9f0f854c54ec0155e957a/radian-emacs/radian-util.el#L9-L31).

**Comment by dieggsy** [comment]
@raxod502 I could look into this. I think it may be worth just getting rid of some of the backports (for example, `thread-first` is _nice_ but pretty much completely unnecessary, maybe even `if-let*` as well). What do you think?

**Comment by dieggsy** [comment]
I feel more strongly about `thread-first`, which is only used in one place.

**Comment by raxod502** [comment]
See also https://github.com/raxod502/straight.el/commit/98b587979baa5738fd9fd9806650411549eb23b7.
