### ISSUE TITLE
Incompatible recipes warning

### ISSUE THREAD

**Issue by apnewberry** [raxod502/straight.el#263]
I accidentally added an invalid recipe path, and now when I try to add the right one I get

`Warning (straight): Package "ox-ravel" has two incompatible recipes (:local-repo cannot be both "~/.emacs.d/orgmode-accessories/ox-ravel.el" and "~/.emacs.d/orgmode-accessories")`

I'm not sure how to clear the wrong one -- perhaps the warning text could make a suggestion?

**Comment by raxod502** [comment]
Providing a new recipe does override the old one. You should only get a warning the first time.

The warning text should be modified to make this clear. Perhaps something like `Warning (straight): Recipe for "ox-ravel" has been overridden (:local-repo changed from "~/.emacs.d/orgmode-accessories/ox-ravel.el" to "~/.emacs.d/orgmode-accessories")`?

**Comment by apnewberry** [comment]
Sounds good to me.
