### ISSUE TITLE
Can't handle different package with the same repo name ?

### ISSUE THREAD

**Issue by xuchunyang** [raxod502/straight.el#265]
I have `web-server` installed a long time ago, 

- https://github.com/eschulte/emacs-web-server
- `~/.emacs.d/straight/repos/emacs-web-server`

today I install `ein` and use it, I get

    Cannot open load file: No such file or directory, simple-httpd

straight.el thinks `simple-httpd` is installed but it is not. I seems it is because both `web-server` and `simple-httpd` are using the same repo name: `emacs-web-server`

- https://github.com/eschulte/emacs-web-server (web-server)
- https://github.com/skeeto/emacs-web-server (simple-httpd)

**Comment by raxod502** [comment]
Yes, you have to rename one of the local repositories. E.g. use the recipe

```
(simple-httpd :type git :host github :repo "skeeto/emacs-web-server" :local-repo "simple-httpd")
```

There's not really anything that can be done on the `straight.el` side, except to emit a warning when two automatically generated local repository names happen to be the same (since it's probably not intentional).

**Comment by CeleritasCelery** [comment]
want to add that I found two other packages with the same conflict; `dracula-theme` and `challenger-deep-theme`.

**Comment by idcrook** [comment]
I encountered exact same problem as OP today. took me a while to figure out that this was what was going on. finally can use https://github.com/ancane/markdown-preview-mode
(requires web-server)

**Comment by raxod502** [comment]
Migrated to #500.
