### ISSUE TITLE
Emacs 27 will load `package` unless variable set nil in "early init file"

### ISSUE THREAD

**Issue by jhenahan** [raxod502/straight.el#268]
http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=24acb31c04b4048b85311d794e600ecd7ce60d3b

Not critical now, but something to be aware of down the road.

**Comment by jhenahan** [comment]
I did not even connect the names. I'll assume they know about it, then.

**Comment by raxod502** [comment]
Indeed, I was aware. The documentation should be updated to cover these changes. See https://github.com/raxod502/straight.el/issues/269.
