### ISSUE TITLE
How to install org-plus-contrib ?

### ISSUE THREAD

**Issue by Jean-MichelC** [raxod502/straight.el#270]
Hi,

trying to install org-plus-contrib, I have followed the instructions at [https://github.com/raxod502/straight.el#installing-org-with-straightel](url)

of course with 
`(provide 'org-version)

(straight-use-package 'org-plus-contrib) ;; org or org-plus-contrib as desired
`
at the end

I get the following error:

> Warning (straight): Command failed: makeinfo /home/guest-xfce/.emacs.d/straight/repos/org/doc/orgguide.texi -o /home/guest-xfce/.emacs.d/straight/build/org-plus-contrib/orgguide.info (default-directory: "/home/guest-xfce/.emacs.d/straight/repos/org/doc/"):
/home/guest-xfce/.emacs.d/straight/repos/org/doc/orgguide.texi:6: @include : impossible de trouver org-version.inc
/home/guest-xfce/.emacs.d/straight/repos/org/doc/orgguide.texi:68: warning: drapeau indéfini : VERSION

any idea ?

**Comment by Jean-MichelC** [comment]
Strangely enough, when I now end the file with 
`(straight-use-package 'org-plus-contrib) ;; org or org-plus-contrib as desired

;; now initializing trough org-babel
(require 'ob-tangle)
(org-babel-load-file "/home/guest-xfce/.emacs.d/init-by-org-babel/emacs-init-minimal.org")
`
It raises no error ... 
However the functions of org-plus-contrib are not available

And how would I do a 
`(use-package org-plus-contrib
(...)
:config
    (add-hook 'org-mode-hook 'turn-on-my-function-for-hook))
`

Could you provide some indications ? Thanks in advance !

**Comment by raxod502** [comment]
The texinfo message is a warning, not an error. Pull request https://github.com/raxod502/straight.el/pull/219 caused texinfo build errors to be reported as warnings, in the hope that this would encourage them to be fixed. However, this has not happened, and I think rather the user experience has simply been degraded for no clear benefit. I have therefore partially reverted that pull request, and warnings will no longer be printed.

> However the functions of org-plus-contrib are not available

As for your second inquiry, could you provide more details? Installing the latest `org-plus-contrib` using a freshly bootstrapped `straight.el` works just fine for me. I can, for example, load `org-eldoc` with no issue.

> And how would I do a
> ```
> (use-package org-plus-contrib (...) :config (add-hook 'org-mode-hook 'turn-on-my-function-> for-hook))
> ```

Are you looking for this?

```elisp
(use-package org
  :straight org-plus-contrib
  :config ...)
```

**Comment by Jean-MichelC** [comment]
For my first question, ok thks.
Second question : issue has ... disappeared ... Indeed, org-eldoc is available. Probably some inconsistency in my test - sorry for that. 
Last : yes
`(use-package org
  :straight org-plus-contrib
  :config ...)`
is what i'm looking for.
Perfect !

**Comment by raxod502** [comment]
Glad to help. By the way, your code blocks will render more attractively on GitHub if you enclose them in triple-quotes.

    ```elisp
    (use-package org
      :straight org-plus-contrib
      :config ...)
    ```

becomes:

```elisp
(use-package org
  :straight org-plus-contrib
  :config ...)
```

**Comment by Jean-MichelC** [comment]
triple-quotes .... much nicer indeed !

I'm still unsure how this globally works (but trying hard to understand ... ;-)) because:
```elisp
(use-package org
  ;; :straight org-plus-contrib
  :config
  (require 'org-eldoc)
  (require 'org-tempo)
  (org-eldoc-load))
```
seems to lead to the same result as the uncommented version : org-eldoc available ... What do I miss here ?

**Comment by raxod502** [comment]
You can also indent code blocks. Hence,

```
    ```elisp
    (use-package org
      :straight org-plus-contrib
      :config ...)
    ```
```

The code you gave installs `org`, not `org-plus-contrib`. As `org-eldoc` does not exist in `org`, I don't see why it would work. Just to be sure, I tested the following init-file:

```elisp
(with-eval-after-load 'gnutls
  (setq gnutls-verify-error t)
  (setq gnutls-min-prime-bits 3072)
  (add-to-list 'gnutls-trustfiles "/usr/local/etc/libressl/cert.pem"))

(let ((bootstrap-file (concat user-emacs-directory "straight/repos/straight.el/bootstrap.el"))
      (bootstrap-version 3))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(use-package org
  :config
  (require 'org-eldoc)
  (require 'org-tempo)
  (org-eldoc-load))
```

It doesn't work.

**Comment by Jean-MichelC** [comment]
OK. The point is that with `straight.el` I'm rebuilding my configuration from scratch, and at this occasion have messed up a little bit my configuration. 
My configuration is done via a minimal init.el and the rest in a tangled file from org-mode.
But but but ... my init.el was not so minimal anymore, and i had an overlap between the 2 files, so that `org-plus-contrib` was already loaded.
Fixed now, back to the basics : when you base your configuration on a tangled org-mode file, your `init.el` should /really/ be minimal.
Thanks for your clear example that gave me the evidence of what was wrong.
I tested at this occasion your example, and the minimal `init.el` that works for me is:
```
(with-eval-after-load 'gnutls
  (setq gnutls-verify-error t)
  (setq gnutls-min-prime-bits 3072)
  (add-to-list 'gnutls-trustfiles "/usr/local/etc/libressl/cert.pem"))

(let ((bootstrap-file (concat user-emacs-directory "straight/repos/straight.el/bootstrap.el"))
      (bootstrap-version 3))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(use-package org
  :straight org-plus-contrib
  :config
  ;; (require 'org-eldoc)
  (require 'org-tempo)
  (org-eldoc-load))
```
Btw, what is the gain brought by your
```
(with-eval-after-load 'gnutls
  (setq gnutls-verify-error t)
  (setq gnutls-min-prime-bits 3072)
  (add-to-list 'gnutls-trustfiles "/usr/local/etc/libressl/cert.pem"))

```
?

**Comment by raxod502** [comment]
OK, if I understand correctly then everything is working fine for you. Glad to hear. The `gnutls` stuff fixes a bug in Emacs on macOS whereby it doesn't recognize certificates installed via Homebrew, and therefore can't make HTTPS requests to execute the bootstrap.

**Comment by Jean-MichelC** [comment]
Yes everything is fine, thanks for the help given.
For the macOS fix : I am on linux, but for shouldn't you mention the snippet [here](https://github.com/raxod502/straight.el#getting-started) for the macOS users ?

**Comment by raxod502** [comment]
Fixed, see https://github.com/raxod502/straight.el/tree/eb2da3dcd590e258578203a112b894fa98e98944#getting-started.
