### ISSUE TITLE
MELPA recipes whose repos have custom default branches

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#279]
E.g. the recipe for `ensime` is

```
(ensime :fetcher github
	:repo "ensime/ensime-emacs")
```

from this there is no way to tell that the correct branch to check out is `2.0` and not `master`. Thus the user must override the recipe in their init-file, which is undesirable (all MELPA recipes should work out of the box).

I don't know how to fix this without introducing more problems.

See also https://github.com/sjrmanning/.emacs.d/issues/1.

**Comment by hartzell** [comment]
I'm coming at this from a position of relative naïveté ...

If you clone the repository, the branch that is checked out by default is the default branch.  In the case of ensime, 2.0 is the default branch, so you're good to go.  Just don't try to check out something else unless you're told to.

If there's some repo out there that wants you to use a branch that they don't have set as their default, then there's more work to be done...

In theory you could hit API and ask for the default branch, but you'd probably need a token and etc...  https://developer.github.com/v3/repos/#get

Actually,  it seems I can ask for it without authenticating.  You just have to figure out whether to ask for an `/orgs/...` repo or a `/users/...` repo.  Not sure that's really viable.

```
curl https://api.github.com/orgs/ensime/repos
```

**Comment by SkySkimmer** [comment]
`git ls-remote --symref "$remote" HEAD` will produce something like
```
ref: refs/heads/trunk   HEAD
12aa0caf5a4a4f595f3bc3af5631a674bc8cece4        HEAD
```
(on https://github.com/ocaml/ocaml)

So maybe you could have a special value `:branch :default`. The main issue is that you need a network call to figure out if you're on the right branch, or some special purpose cache.

**Comment by raxod502** [comment]
Checking the remote `HEAD` is a good idea, @SkySkimmer. I think that will work. Updating the code will entail looking at everywhere `straight-vc-git-default-branch` is used and having it do this instead. (Although I think we still want to have `straight-vc-git-default-branch`, e.g. in the case of a local repository with no remotes.

**Comment by xendk** [comment]
No way that it can be figured out for local repositories too? I foresee a imminent future where the name of the default branch is a pretty fluid concept.

**Comment by raxod502** [comment]
Are you referring to this comment?

> e.g. in the case of a local repository with no remotes

What I meant by that was a package that is taken from a repository that only exists on your local machine, with nothing on the Internet anywhere. This is something supported by `straight.el`, so by definition there is no concept of a default branch for that configuration.

**Comment by xendk** [comment]
Yes, I was referring to:

> (Although I think we still want to have straight-vc-git-default-branch, e.g. in the case of a local repository with no remotes.)

I was thinking if I have an old repository with a master branch, and a newer with a main branch (I saw that there's talk about killing master on the git developers list), I can't set `straight-vc-git-default-branch` to something that'll work with both. But I'm not sure what `straight-vc-git-default-branch` is used for. Maybe requiring `:branch` for local repos would make more sense.

I think we're going to see a lot of non-master default branches in the time coming...

**Comment by raxod502** [comment]
> I can't set straight-vc-git-default-branch to something that'll work with both.

Well, yes. It's a default; if you need different packages to use different values, then one of them will have to override the default.

> But I'm not sure what straight-vc-git-default-branch is used for.

It is the default value of `:branch`, nothing more and nothing less. Unfortunately, the name does make it sound like the variable relates in some way to GitHub's concept of a "default branch", which it does not.

> I think we're going to see a lot of non-master default branches in the time coming...

Yes, I agree. This ticket will need to be solved.

**Comment by xendk** [comment]
> It is the default value of :branch, nothing more and nothing less. Unfortunately, the name does make it sound like the variable relates in some way to GitHub's concept of a "default branch", which it does not.

Ah, thanks for the explanation. I think it would make sense to simply drop and requrie `:branch` for local repos. It can at most be "my personal preference for main branch", but even that might vary with the age and branching model of the repo. Also means one less variable for users to deal with.

**Comment by raxod502** [comment]
It's not clear to me why that would be an improvement in user experience. Most people use the same primary branch for all of their repositories, so having the ability to specify a default seems ideal.

**Comment by xendk** [comment]
Well, it's obviously not. But lets zoom out a bit: What's the default value of `straight-vc-git-default-branch` going to be? If you stick with `master`, you're going to get pull requests that change it to `main`, and as Github, Gitlab and later git itself moves over, it'll get harder to defend the default. OTOH, if you switch over to `main`, you'll probably get flack from those resisting the change. In other words, no matter what you do you'll be seen as taking sides in the political issue that's behind the movement. I don't know if you want that.

Making the branch required is the easy way out. Alternatively, letting `straight-vc-git-default-branch` have no default value, but require that it's set before usage. But I don't like the latter as it forces people to make a decision about their future behavior right now. 

> Most people use the same primary branch for all of their repositories, so having the ability to specify a default seems ideal.

Well, I'm not fan of configurable defaults, because, they're really not, and they take a piece of configuration and moves elsewhere. Most of the time you wont touch your defaults, because if you do, you'll mess up all the configurations relying on the default value. It's handy in the few cases when you need to change everywhere, but I doubt that happens very often. And because the default is configurable, I can't look at a repo spec and see what branch it uses, I have to remember what branch I configured as default. Having to specify the branch explicitly might be an inconvenience, but it is a rather important detail, and it's easier to grep for something specified.

Just my thoughts, anyway.

**Comment by raxod502** [comment]
I will keep this in mind and consider making such a change in the future, when there is serious disagreement about which default branch name to use. For now, I think it's enough of a standard that I do not want to disrupt the user experience.

**Comment by ahyatt** [comment]
How about changing the default to a list of standard default branch names, which can be tried in precedence order?

**Comment by raxod502** [comment]
At first, I thought that would be dangerous for reproducibility. But I can't think of any specific problem it would cause. I suppose the ordering could be `main` -> `develop` -> `master`, or something like that. I would be fine with merging such a change.

**Comment by progfolio** [comment]
Taken care of by #630
If I'm mistaken please reopen.

**Comment by raxod502** [comment]
Just to add some context: most of the discussion in this thread is in reference to an approach that we did not end up taking. The implemented solution does what I suggested in https://github.com/raxod502/straight.el/issues/279#issuecomment-392834194, and seems to work optimally with little to no downsides.
