### ISSUE TITLE
delete-directory: modified directory doesn't exist

### ISSUE THREAD

**Issue by kaiwk** [raxod502/straight.el#287]
After recent updating, restart emacs gives:

> delete-directory: Opening directory: No such file or directory, /my-home-path/.emacs.d/straight/modified

environment:
emacs 25

I also tested it on emacs24.5 and emacs26.1, it seems it would give this error on emacs 24.5 and emacs 25, but it works fine on emacs 26.

**Comment by raxod502** [comment]
Great! Thanks for the report and solution.
