### ISSUE TITLE
Minor gripe: *straight-process* buffer contains peaceful failures

### ISSUE THREAD

**Issue by tummychow** [raxod502/straight.el#289]
Just did a [big update](https://github.com/tummychow/emacs/commit/368d5cf089fc85c0ebc1e70377152c7231b872c5) and now every time I boot up emacs I see this in `*straight-process*`:

```
$ cd /home/sjung/.emacs.d/straight/repos/epkgs/
$ git config --file .gitmodules --get submodule.let-alist.url

[Return code: 1]

$ cd /home/sjung/.emacs.d/straight/repos/epkgs/
$ git config --file .gitmodules --get submodule.let-alist.url

[Return code: 1]
```

spent a while debugging it before realizing that this really isn't even an error (`let-alist` is a built-in). This has probably always had a nonzero return code, but wasn't opening a buffer for it until now. I would prefer to only see this buffer spawned for genuine breakages that need my attention.

**Comment by raxod502** [comment]
Was the buffer displayed in a popup? If so, it shouldn't be. If not, why were you looking at it?

`*straight-process*` is always created. It logs all external processes that were run; it's not just a tool for presenting errors to the user.

If you dislike the buffer showing up in your buffer list, maybe consider this?

```elisp
(setq straight-process-buffer " *straight-process*")
```

Suggestions welcome.

**Comment by tummychow** [comment]
ahh, I understand. I figured it was an error buffer because that was the only output in it. I'm cool with this.
