### ISSUE TITLE
Explicit support for forks

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#29]
After #25, we may want to consider enhancing the Git support. In particular, I'd like explicit support for a fork-based workflow. Something like:

```
(straight-use-package
  '(use-package
    :repo (github . "raxod502/use-package")
    :upstream (github . "jwiegley/use-package")))
```

It would certainly be possible to automatically transform MELPA recipes into this style, so this is doable.

**Comment by PlasmaShift** [comment]
You should look at borg, Its an emacs package for git type workflow. You might be able to add support for integration like use package.
[https://emacsair.me/2016/05/17/assimilate-emacs-packages-as-git-submodules/](url)

Also for documentation you should compare this to use package and borg, which i saw on a reddit thread
and other tools of intrest like your el-patch.el package

**Comment by raxod502** [comment]
@PlasmaShift Yes, I have seen borg. I think that straight.el is going to very similar in spirit to borg, except in two respects:

1. borg uses submodules, straight.el is agnostic to the VCS used
2. borg explicitly does not intend to be a full-featured package manager (it provides only those features not already provided by epkg, magit, auto-compile), whereas straight.el does intend to be a full package manager

use-package is orthogonal to straight.el, since it is not a package manager. In essence, package.el and straight.el are both "backends" for use-package (or more properly, backends for a small part of use-package, the :ensure keyword). I use both use-package and straight.el.

el-patch is similarly orthogonal, although it and straight.el have the commonality that both were developed to make it easier for me to hack on Emacs packages. el-patch makes it easier to override functionality without directly modifying the code of a package, while straight.el makes it easier to modify the code.

Once straight.el reaches a 1.0 release, there will be specific documentation about these things.

**Comment by raxod502** [comment]
@PlasmaShift I'm currently considering a number of large conceptual refactors. (In particular, eliminating the build step and supporting automatic upstream/fork repository management and pluggable version-control backends.) I keep going back and forth on whether submodules are the best solution to the problem. (Jonas uses them, but he also admits that they have some UI problems.) At the moment, I'm thinking that it makes more sense to continue with the independently-managed-repository model, since it provides the same basic functionality as submodules, except more flexibly and with the potential to add more features (such as upstream/fork management). Concerning the borg model, its simplicity appeals to me—but at the end of the day, somebody is going to have to manage all those remotes and branches that spring up when I fork packages and modify them locally, and I trust a package manager to do a much better job of that than I trust myself to. Hence my wanting to support this in straight.el instead of managing things manually with submodules.

**Comment by raxod502** [comment]
Closed in the monster commit https://github.com/raxod502/straight.el/commit/0dbabca40c50bcc38ef3a21570cd95f1896ed619.
