### ISSUE TITLE
Conflicting documentation in README 

### ISSUE THREAD

**Issue by Silex** [raxod502/straight.el#297]
Hello,

https://github.com/raxod502/straight.el#integration-with-use-package

``` elisp
(use-package el-patch
  :straight (el-patch :type git :host github :repo "your-name/el-patch"
                      :upstream (:host github
                                 :repo "raxod502/el-patch")))
```

https://github.com/raxod502/straight.el#integration-with-use-package-1

``` elisp
(use-package el-patch
  :straight (:host github :repo "raxod502/el-patch"
             :branch "develop"))
```

In the last one the recipe name is omitted. It's not clear wether that is at typo or if it's the first one that is a typo and that it should be omitted.

**Comment by raxod502** [comment]
Neither is a typo. Both forms are accepted, and if you omit the package name then it defaults to the `use-package` feature name. This is documented [here](https://github.com/raxod502/straight.el/tree/8bd2caac3ef363abc55a40d47cd38c7e71293481#integration-with-use-package-1), although I'd be happy to receive suggestions on how to make it clearer.

**Comment by Silex** [comment]
Ah, ok then. Thanks!

**Comment by Silex** [comment]
Hum, while we are discussing clarifications: when you install from MELPA, what happens exactly? From what I understand, it actually figures out the git repository to install then installs that?

**Comment by Silex** [comment]
Nevermind I found https://github.com/raxod502/straight.el/blob/develop/straight.el#L2180

**Comment by raxod502** [comment]
You are correct. This is documented in https://github.com/raxod502/straight.el/tree/5a2c18ef8134f0ddc47c8bf2ea3f59982ebed4a5#where-do-recipes-come-from, and you can also add your own recipe repositories.

**Comment by Silex** [comment]
Thanks! Atm I use `use-package` with `package.el`, but I'm considering switching to `straight.el` because package management using git makes sense, and would avoid me having to use things like https://github.com/Silex/package-utils
