### ISSUE TITLE
Preview-latex is not working.

### ISSUE THREAD

**Issue by bitsandscraps** [raxod502/straight.el#299]
Auctex works perfectly, but preview-latex is not(no "Preview" tab in the toolbar and none of the preview functions exist).
The contents of ~/.emacs.d/straight/build seems similar to what `M-x package-install RET auctex RET` will produce.
Not sure what to look for next. Any suggestions?
I'm currently using emacs 26.1 and my init.el looks something like this.
```elisp
(setq straight-recipes-gnu-elpa-use-mirror t)

;; bootstrap straight.el
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 4))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'auctex)
```

**Comment by raxod502** [comment]
Thanks for the report. This should be fixed if you update to https://github.com/emacs-straight/auctex/commit/94981bd97e5ca914053c5a5a596828b2de8ebd4b.
