### ISSUE TITLE
Nix compatibility question

### ISSUE THREAD

**Issue by jhenahan** [raxod502/straight.el#307]
I use Nix to build my Emacs with a bunch of packages already installed, but I'm also trying to get my config to a point where I can share it with people who don't use Nix (or who do, but not the same package set as I do). I'd love it if there were a way for `straight` to skip doing its work of cloning and so on if the packages are already present through Nix, but I don't know if that's possible given that `package.el` machinery isn't available to `straight`.

I'd love to be able to use the same config on systems with and without Nix, without having to maintain what amounts to two separate configs or duplicating effort on the Nix ones.

**Comment by raxod502** [comment]
You can tell `straight.el` that package `foo` is already provided and does not need to be cloned/built/loaded, like so:

```elisp
(straight-register-package '(foo :type built-in))
```

Does that solve your problem?

**Comment by raxod502** [comment]
I forgot that you can also, more directly, use

```elisp
(add-to-list 'straight-built-in-pseudo-packages 'foo)
```

for this purpose.

**Comment by jhenahan** [comment]
Oh, that'd be perfect. Thanks very much. I'll see what I can do to make those work for my use-case.
