### ISSUE TITLE
Could not find package blacken in recipe repositories

### ISSUE THREAD

**Issue by apnewberry** [raxod502/straight.el#311]
I'm trying to install `blacken` with `straight-use-package RET blacken RET` but it can't find the package: 

`error: Could not find package blacken in recipe repositories: (melpa org-elpa emacsmirror)`

Here is the recipe. https://github.com/melpa/melpa/blob/master/recipes/blacken

I'm not sure what I'm doing wrong or how to fix it. I'm on Emacs 26.1 Ubuntu 17.10. (I would include the straight version but not sure where to find it.) Thanks.

**Comment by raxod502** [comment]
It works for me. The simplest explanation is that your clone of MELPA is out of date (the recipe for `blacken` was added on April 3, 2018); have you tried

```
M-x straight-pull-package RET melpa RET
```

?

NB: If you are using revision https://github.com/raxod502/straight.el/commit/6abe699e1ecf9431e65f044f1ce07f0ab0ca2247 of `straight.el`, then please first upgrade to revision https://github.com/raxod502/straight.el/commit/72a758dd71dab648896784b1d7babb7c90b9c1e7 which fixes a severe logic bug affecting `M-x straight-pull-package` and related functions.

You can find the revision of `straight.el` in use simply invoking `git rev-parse HEAD` in `~/.emacs.d/straight/repos/straight.el`. You can find the revision of MELPA by doing the same in `~/.emacs.d/straight/repos/melpa`, and so on for other packages. See also [the documentation on how `straight.el` uses the filesystem](https://github.com/raxod502/straight.el/tree/72a758dd71dab648896784b1d7babb7c90b9c1e7#what-does-this-look-like-on-disk).

**Comment by apnewberry** [comment]
Ah, I didn't realize that `melpa` was a _package_ that could be updated with `straight-pull-package`. That worked great. Thank you!
