### ISSUE TITLE
Setting `straight-recipes-gnu-elpa-use-mirror` has no effect

### ISSUE THREAD

**Issue by Kwarrtz** [raxod502/straight.el#312]
This is a continuation of a discussion started on #240.

I've been trying to install AUCTex through `straight.el`. As per the above issue, I've trying to use the GNU Elpa mirror, and added the necessary flag to my `init.el`:

    (setq straight-recipes-gnu-elpa-use-mirror t)

    (defvar bootstrap-version)
    (let ((bootstrap-file
           (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
          (bootstrap-version 5))
      (unless (file-exists-p bootstrap-file)
        (with-current-buffer
            (url-retrieve-synchronously
             "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
             'silent 'inhibit-cookies)
          (goto-char (point-max))
          (eval-print-last-sexp)))
      (load bootstrap-file nil 'nomessage))

      (straight-use-package 'auctex)

      ;; other packages

However, this fails with the error 

    Could not find package auctex in recipe repositories: (org-elpa melpa gnu-elpa emacsmirror)

which seems to indicate that `straight-recipes-gnu-elpa-use-mirror` is not having the expected behavior (the recipes list still has `gnu-elpa` instead of `gnu-elpa-mirror`.

The `straight.el` installation in `straight/build` is version 1.0.

**Comment by raxod502** [comment]
`straight.el` has no tagged versions. What do you mean by "version 1.0"?

The only way to identify the revision of `straight.el` is with the commit SHA, obtained by

```
$ git -C ~/.emacs.d/straight/repos/straight.el rev-parse HEAD
```

and you can update it either manually or interactively via `M-x straight-pull-package`.

**Comment by Kwarrtz** [comment]
It looks like my `straight.el` installation really was just out of date. `M-x straight-pull-package RET straight` fixed the issue!
