### ISSUE TITLE
Hydra for straight.el

### ISSUE THREAD

**Issue by aqua36** [raxod502/straight.el#313]
I made a simple [hydra](https://github.com/abo-abo/hydra) for this package and [included it](https://github.com/abo-abo/hydra/wiki/straight.el) in the hydra wiki. (It doesn't include absolutely every straight interactive function, because I didn't think some functions are used often enough to justify being included, but you may not share my view on this)

I figured I should let you know, because you might want to include a link to it in the documentation, or utilize it in some other way

**Comment by raxod502** [comment]
Neat, thanks. I don't have time right now to make code changes but I would happily merge a pull request that either links to this from an appropriate place in the documentation (new section for integrations with other packages, possibly near the section on integration with `use-package`?) or includes the code directly in `straight.el`, analogously to how `use-package` integration is handled (in this case some additional review would be necessary), or includes the code in `straight-x.el`, in which case additional review isn't necessary.

**Comment by raxod502** [comment]
Great, no rush :)

**Comment by aqua36** [comment]
I chose to change the documentation. If you think that the code should be included in straight-x.el as well, I'd be happy to make a PR about that.

**Comment by raxod502** [comment]
Where to put the code is up to you. I agree it would not be a good idea to have it in two places. Since we have a pull request now, I'll close this issue. Thanks for your help!

**Comment by aqua36** [comment]
>  Where to put the code is up to you

I'll leave it as it is, then
