### ISSUE TITLE
Easy way to use GitHub pull requests of a package?

### ISSUE THREAD

**Issue by blaenk** [raxod502/straight.el#315]
I'm wondering if there is, or there should be, an easy way to try out pull requests with straight.el. This package is already great for using packages not pushed to e.g. melpa, or using forks of packages, etc. I think it would be great if maybe the `:host github` configuration supported a `:pull-request 123` option.

Then again, maybe that's a host-specific option that you don't want to add. I have seen that [it's possible](https://help.github.com/articles/checking-out-pull-requests-locally/) to check out pull requests locally but I'm not sure how to actually use that through straight.el's recipe format, because I think it would entail fetching that pr's ref to a branch and then using it with `:branch`?

I'm probably overthinking it. I admit I'm a little rusty with this.

**Comment by dieggsy** [comment]
@blaenk pull requests are usually just based on a fork or a branch of a fork. you could probably just use the :fork and :branch keywords as described in the docs.

**Comment by blaenk** [comment]
Good point, but not in the case that prompted me to create this issue. It's one created by the repository owner. It's something I've seen developers do sometimes to get comments or eyes on a proposed change before actually merging it in.

**Comment by raxod502** [comment]
If there is a pull request to merge `feature` into `master`, then you can use `:branch "feature"` in your recipe. Does this solve your problem?

**Comment by blaenk** [comment]
Yes it does! Thank you, I figured I was overthinking it.
