### ISSUE TITLE
Minimal working example

### ISSUE THREAD

**Issue by azzamsa** [raxod502/straight.el#317]
Hi.

This package has extremely great description in README. I use `use-package` for enough time. But I think it's easier to give user a MWE (minimal working example) to see what to change/leave in their config with less time reading the documentation.

Borg has [starter kit](https://github.com/emacscollective/emacs.g). I *think* it's good to provide MWE with some package inside.

Thanks

**Comment by raxod502** [comment]
I agree. This is however a duplicate of https://github.com/raxod502/straight.el/issues/74 so I am merging this issue to that one.

**Comment by azzamsa** [comment]
Thank you.
