### ISSUE TITLE
:fork doesn't work when cloning fresh

### ISSUE THREAD

**Issue by andschwa** [raxod502/straight.el#318]
I discovered this when my Travis CI build failed after I added a `:fork` to some of my recipes. Such as:

```
(use-package dtrt-indent
  :straight (dtrt-indent :host github :repo "jscheid/dtrt-indent"
                         :fork (:host github :repo "andschwa/dtrt-indent")) ...)
```

In `straight-vc-git-clone`, if `:fork` is present, it doesn't `cd` into the cloned Git repo, and so instead executes `git remote` in `straight/repos` (which is in my `.emacs.d` repo). The first time it does this, it doesn't fail, since you can add the `fork` remote to the repo; but the second time (for another recipe with a fork), it finally fails because `fork` already exists as a remote. Both of these executions are incorrect anyway, because it should be done in the cloned repo of the package.

I think I have a fix, but I'm not having fun figuring out how to use my own fork of `straight.el` without hacks...

**Comment by andschwa** [comment]
Ah ha, figured out how to use my [fork](https://github.com/raxod502/straight.el-support/blob/8805112d6846411920595e7643112d21c7e039f9/benchmark/init.el#L76)... maybe we should put that example in the readme.

**Comment by dieggsy** [comment]
I also just ran into this exact issue a few minutes ago, don't have much to add.

**Comment by andschwa** [comment]
@dieggsy Tests show my fix is working... opening a PR in a minute here 😄

**Comment by raxod502** [comment]
Sorry about this; should be fixed now thanks to your pull request.
