### ISSUE TITLE
Make it easier to use a custom fork of straight.el

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#320]
Here is how to use a custom fork of `straight.el`:

```elisp
;; before bootstrap snippet
(setq straight-recipe-overrides
      '((nil . (straight :host github :repo "raxod502/straight.el"
                         :files ("straight*.el") :branch "develop"
                         :fork (:repo "your-name/straight.el")))))
```

I think this deserves to be explicitly documented in the README. Then the code should be updated so that it's simpler:

```elisp
(setq straight-repository-fork "your-name")
```

This is just a matter of a simple update to the logic in `bootstrap.el` used to generate the default recipe (and don't forget to add the new variable to `install.el`; see also [#88](https://github.com/raxod502/straight.el/issues/88)).

Inspired by #319.

**Comment by raxod502** [comment]
You are correct, this seems to be a bug. The value of `straight-repository-branch` will be irrelevant but somehow it seems that `straight-vc-git-default-branch` does not take effect in causing the correct branch to be checked out.

Quite unfortunately, I am not likely to have the bandwidth to debug this very soon. However I would be happy to assist in anyone who would like to look into it.

To keep each issue thread about one independent issue, I moved this problem to #322.

**Comment by andschwa** [comment]
Thanks @raxod502. Yeah it seemed that `straight-repository-branch` wouldn't matter, but I was being thorough. I appreciate the help, great package 😄
