### ISSUE TITLE
straight-pull-package warnings when using :fork

### ISSUE THREAD

**Issue by dieggsy** [raxod502/straight.el#321]
On packages where I specify a `:fork`, I'm getting a warnings like: 'package-name', HEAD (has diverged from/is ahead of) branch 'master' when calling `straight-pull-package`

Is this intended behavior? Shouldn't we not warn about such a state with forks, since this is the exact purpose of using a fork? (i.e. it's different/updated from the original package).

**Comment by raxod502** [comment]
Does resetting HEAD to master prevent the warning? If so, then this is just a result of bad UX as described in #294, fixable by #66. (I know exactly what needs to change to fix the problem, and am just lacking in time to implement the solution.)

Also, is this a problem specific to `:fork`? In principle, `:fork` and `:upstream` should not have independent bugs, since `:upstream` is internally translated into `:fork` before further processing occurs.

**Comment by dieggsy** [comment]
@raxod502 I don't think it's specific to fork - just that I changed how I used the keyword when switching to `:fork`. Previously, I set `:upstream` was the original package and the normal recipe was my fork - with `:fork`, of course, it made more sense to switch those around, which is probably why I didn't see this warning until now.

**Comment by dieggsy** [comment]
Of course, this means resetting HEAD to master isn't a solution - master _isn't_ the package I want, it's the original, unmodified package.

**Comment by raxod502** [comment]
> Previously, I set :upstream was the original package and the normal recipe was my fork - with :fork, of course, it made more sense to switch those around, which is probably why I didn't see this warning until now.

Internally, the information from `:upstream` is moved into the top level of the recipe, and the previous top-level metadata is moved into a new `:fork` keyword. Thus your change should not have introduced any change in behavior.

> this means resetting HEAD to master isn't a solution - master isn't the package I want, it's the original, unmodified package.

I think I have misunderstood something. Could you tell me (1) what is the branch of the upstream you want to track, (2) what is the branch of the fork you want to track, and (3) what branch you want to have checked out?

If the answers are (1) `origin/master`, (2) `fork/master`, and (3) `master`, then the configuration you want to have is `HEAD` is pointing to `master` pushing to `fork/master` and pulling from `origin/master`.

**Comment by dieggsy** [comment]
@raxod502 You're describing behavior i'id like, but on initial setup (i.e. specifying a package with a `:fork` recipe, starting up emacs, straight does a git clone, etc.) `HEAD` is detached at `fork/master`, and `master` is up to date with `origin/master`, _not_ `fork/master`.

**Comment by raxod502** [comment]
> This seems incorrect or at least unexpected.

Yes, it's bad UX as described in https://github.com/raxod502/straight.el/issues/294, fixable by https://github.com/raxod502/straight.el/issues/66. Right now, manual work is required to get the branch where it is supposed to be.

> ideally I'd want `straight-pull-package` to pull from `fork/master`

It should—does it not? `M-x straight-pull-package` should pull from `fork/master`, while `C-u M-x straight-pull-package` should pull from _both_ `fork/master` and `origin/master`.

> Maybe this is a silly use-case, and I should just not use the `:fork` keyword at all

No, this is _exactly_ the correct use case for this keyword. It is just that I did not fully think through the implications of using checkouts versus resets when I implemented the repository management code back in 2017.

> automatically setting up the other upstream in case that one does get changes I want to merge into my fork.

Yes, this is why the feature is provided.

**Comment by dieggsy** [comment]
> It should—does it not? M-x straight-pull-package should pull from fork/master, while C-u M-x straight-pull-package should pull from both fork/master and origin/master.

Oops, it does. To clarify/repeat: 

Like you said, I need to manually do this once to get `master` where I want it. I think that was the root of my original problem, but I was just misunderstanding it. The warning was generated because `master` was not automatically updated with `fork/master`, which it _should_ when `:fork` is specified. If that's covered by #294 and #66, then feel free to close this now.

**Comment by raxod502** [comment]
Yes, sounds like we both understand the situation and it's covered by #66.
