### ISSUE TITLE
Changing revision in a repo doesn't cause rebuild

### ISSUE THREAD

**Issue by wedens** [raxod502/straight.el#329]
Changing current revision in a package repository (swiper in my case) via `git checkout` doesn't cause straight.el to rebuild it. Doing `straight-check-all` doesn't cause rebuild either.

straight.el version: 5d4d23d (latest develop)
emacs: 27.0.50

**Comment by raxod502** [comment]
* Could you let me know what modification checking you are using, i.e. the value of `straight-check-for-modifications`? And what versions of the relevant tools (`find`, `python`, as appropriate) are installed?
* To use a particular revision, generate a lockfile using `M-x straight-freeze-versions`. When the package is installed (for example, if you transfer your configuration to another machine), then that revision will be used automatically. Your configuration need not (and should not) be changed.

**Comment by wedens** [comment]
`(setq straight-check-for-modifications '(watch-files find-when-checking))`

Python 3.7.1
watchexec 1.9.2
find (GNU findutils) 4.6.0

> To use a particular revision, generate a lockfile using M-x straight-freeze-versions. 

What if I already have a lockfile. Should I checkout the revision first and re-generate a lockfile or change it directly in a lockfile?

**Comment by raxod502** [comment]
* You must set `straight-check-for-modifications` _before_ bootstrapping `straight.el`. Are you doing that?
* Is the watcher running? If so, you should get some results for `ps aux | grep straight_watch`.
* What is in the logs? Check if `nohup` started correctly by inspecting the ` *straight-process*` buffer (note the leading space, which hides the buffer by default; see also the variable `straight-process-buffer`), and check the log for the current Emacs session (after making a modification to a package) in the file `~/.emacs.d/straight/watcher/nohup.out`.
* Are other modifications detected? Is it just `git` commands which aren't noticed?
* To update a lockfile, run `M-x straight-freeze-versions` again. The expected workflow for updating packages is to update the packages manually or using one of the interactive commands, and then to regenerate (overwrite) the lockfile. This is similar, though not exactly equivalent, to tools such as Yarn and Pipenv.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)
