### ISSUE TITLE
Hint for hooking up go-guru

### ISSUE THREAD

**Issue by hartzell** [raxod502/straight.el#330]
I'm currently hooking up go-mode like so:

```lisp
(use-package go-mode
  :commands go-mode
  :config
  (setq gofmt-command "goimports")
  :init
  (add-hook 'before-save-hook 'gofmt-before-save)
  )
```

I'd like to also use `go-guru`, which is included in [the go-mode repo](https://github.com/dominikh/go-mode.el).  The `go-guru` instructions say to load it with:

```lisp
(require 'go-guru)
```

I've poked around a bit but haven't had any luck getting it to load.  I thought that perhaps something based on [the last example in the Integration with use-package](https://github.com/raxod502/straight.el#integration-with-use-package-1) section might work, e.g.

```lisp
(use-package go-guru
  :straight go-mode)
```

but no luck.

Is there a clean way to share the repo between the two, or to load `go-guru` as part of loading `go-mode`?

**Comment by raxod502** [comment]
I suggest the following:

```elisp
(setq straight-use-package-by-default t)
(setq use-package-always-defer t)

(use-package go-mode
  :config

  (setq gofmt-command "goimports")
  (add-hook 'before-save-hook #'gofmt-before-save nil 'local))

(use-package go-guru)
```

* You don't need `:commands go-mode`, since `go-mode` is autoloaded.
* I recommend adding the `before-save-hook` buffer-locally for cleanliness, and it's unnecessary to do it at all until `go-mode` is loaded.

You would encounter the same problem when using `package.el` with `:ensure` rather than `straight.el` with `:straight`; this is not package-manager-specific.

Let me know if the above code works for you, and if you have any questions.

**Comment by hartzell** [comment]
THANKS!

That works for the go-mode bits.  Setting `(setq use-package-always-defer t)` causes something in my (ancient, cruft-laden) config of the VM mail reader to explode with:

```
Eager macro-expansion failure: (void-function defun*)
```

If I start with `--debug-init` and let it sit for a minute or two, it eventually produces a stack trace, I've pasted [it into a gist](https://gist.github.com/hartzell/b2ba58193df865af306bf5d2c2c11409).

My VM setup doesn't use `use-package`, I'll dig and see if there's something that I'm doing or if this is an issue w/ VM itself.

**Comment by raxod502** [comment]
You should not use `defun*`. It is a deprecated alias for `cl-defun`. (Make sure to load `cl-lib` before using `cl-defun`.)

You may be encountering the problem that macroexpansion doesn't work properly if you load a library and then use a macro from that library within the same `with-eval-after-load` form. If that's the case, you can use `eval-when-compile` or `eval-and-compile` on the library load to fix the problem.

**Comment by hartzell** [comment]
Thanks for the followup.  I'll dig into it.

For the record, this isn't *my* code, it's something inside [the VM mail reader](https://launchpad.net/vm), the mail app that is burned deeply into my fingertips but seems to be moribund.

I suppose that I'll need to move to something else, someday.  :cry:

**Comment by raxod502** [comment]
You can still paper over the problem by means of

```elisp
(require 'cl)
```

before loading the code that uses `defun*`.

**Comment by hartzell** [comment]
Indeed, that works like a charm.  **Thank you!**

**Comment by raxod502** [comment]
Good to hear it. Presumably, the reason you observed this behavior is because you use some other package that loads `cl`, which happened to appear earlier in your configuration. When that package was no longer loaded immediately (improving startup time), you needed to load `cl` manually.

**Comment by hartzell** [comment]
I've noticed that various other things that I'm using, such as 

```lisp
;; undo-tree
;; Treat undo history as a tree.
(use-package undo-tree
  ;; :straight (undo-tree :type git :host github :repo "martinp26/undo-tree")
  :delight undo-tree-mode
  :config
  (global-undo-tree-mode)
  (setq undo-tree-visualizer-timestamps t)
  (setq undo-tree-visualizer-diff t)
  (unbind-key "C-x u" undo-tree-map)
  (key-chord-define-global "uu" 'undo-tree-visualize))
```

and 

```lisp
;; avy
;; A better jump to char and line.
(use-package avy
  :config
  (setq avy-style 'at)
  (key-chord-define-global "jk" 'avy-goto-char)
  (key-chord-define-global "jl" 'avy-goto-line)
  (key-chord-define-global "jj" 'avy-goto-word-1))
```

aren't working now.  Presumably I've been getting away with something sloppy.

It's odd that I can do a `M-x` and get prefix predictions for the `avy-*` functions but not for any of the `undo-*` ones.

Time to dig.

**Comment by hartzell** [comment]
Looks like I can work around those particular issues by taking advantage of use-package's `:chord` support, which will register and autoload *et voila*!

**Comment by hartzell** [comment]
Yep, that made the chords work cleanly.  Where the `use-package` instructions call for `:ensure t`, I used `:demand` and everything seems happy.  E.g.

```lisp
(use-package use-package-chords
  :demand
  :config (key-chord-mode 1))
```
