### ISSUE TITLE
No support for "single symbol" entries in Package-Requires

### ISSUE THREAD

**Issue by jrosdahl** [raxod502/straight.el#335]
https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html#Library-Headers says this about the Package-Requires header: "An entry that lacks a version (i.e., an entry which is just a symbol, or a sub-list of one element) is equivalent to entry with version "0". It then gives the following example:

    ;; Package-Requires: ((gnus "1.0") (bubbles "2.7.2") cl-lib (seq))

straight.el does not seem to handle "single symbol" entries like `cl-lib` in the example above, which made me confused for a while when I used such a "single symbol" entry for a package I just wrote.

**Comment by raxod502** [comment]
Thanks for reporting this problem; it should be fixed with the above commit.
