### ISSUE TITLE
Installing "forge" doesn't install "closql" dependency

### ISSUE THREAD

**Issue by wedens** [raxod502/straight.el#336]
I've tried installing new package https://github.com/magit/forge. `closql` is listed in dependencies, but for some reason it's not being installed by straight.el automatically.

straight.el 3414e71
emacs 27.0.50

**Comment by raxod502** [comment]
You are probably doing this (it's what I tried first):

```elisp
(straight-use-package '(magit-forge :host github :repo "magit/forge"))
```

You have to do this instead:

```elisp
(straight-use-package '(forge :host github :repo "magit/forge"))
```

That's because the package name is `forge`, not `magit-forge`. And you need to have the package name right so that `straight.el` knows to look in `<packagename>-pkg.el` for dependency information.

**Comment by wedens** [comment]
I was using `(use-package forge :straight t)`. forge is on melpa: https://melpa.org/#/forge
