### ISSUE TITLE
resume from recursive edits

### ISSUE THREAD

**Issue by CeleritasCelery** [raxod502/straight.el#337]
First let me say I love this package. It so feature full and well thought out. 

I do have a question, when I am doing `straight-pull-all` and I see a repo that I have modified, I can use magit with recursive edit. However when I am done I just use `straight-pull-all` again which starts all over. I have a lot packages, so this makes it take much longer starting over every time I need to make an edit. Is there a way to resume `straight-pull-all` after a recursive edit?

**Comment by raxod502** [comment]
`exit-recursive-edit`, bound to `C-M-c`. See [Recursive Editing Levels](https://www.gnu.org/software/emacs/manual/html_node/emacs/Recursive-Edit.html).

**Comment by CeleritasCelery** [comment]
I had no idea this was an Emacs feature. Thanks.
