### ISSUE TITLE
How does the transaction system work?

### ISSUE THREAD

**Issue by DonHugo69** [raxod502/straight.el#343]
I have some troubles to understand and how to implement the transaction system of straight.el. What I think I understood is that it is beneficial in terms of load times to wrap `use-package` calls in a `straight-transaction` call because "... `straight.el` checks all packages for modifications at the beginning of a transaction, because this is faster than checking each package individually. So if you don't wrap in a transaction, then you're checking all 320 packages for modifications 320 times. O(n²) makes everybody cry." (from [here](https://github.com/raxod502/straight.el/issues/128#issuecomment-325264689)). 

However, in the linked example, all packages are added in one, big call, whereas my `init.el` uses a structure like

```el
;; Load the core
(add-to-list 'load-path "~/.emacs.d/core")
(require 'rg-core-constants)
(require 'rg-core-packages) ; <- straight is loaded here
(require 'rg-core-emacs-settings)
(require 'rg-core-keybindings)
(require 'rg-core-hooks)
(require 'rg-core-lib)
(require 'rg-core-ui)

;; Modules
(require 'rg-module-base)
(require 'rg-module-buffers)
(require 'rg-module-checkers)
(require 'rg-module-completion)
(require 'rg-module-dired)
(require 'rg-module-ediff)
(require 'rg-module-emacs-lisp)
(require 'rg-module-eshell)
(require 'rg-module-ess)
(require 'rg-module-evil)
(require 'rg-module-fira)
;; .... and so on
```
Within the modules I use `use-package` like in the following example:

```el
(use-package ess
  :defer t
  :init
  (setq ess-offset-continued 'straight
        ess-expression-offset 2
        ess-nuke-trailing-whitespace-p t
        ess-default-style 'DEFAULT)
;; and so on
```

Am I now supposed to wrap every `use-package` call into `straight-transaction` or can do it one level above in my `init.el` like below?

```el
;; Modules
(straight-transaction
(require 'rg-module-base)
(require 'rg-module-buffers)
(require 'rg-module-checkers)
;; .... and so on
)
```

**Comment by raxod502** [comment]
Wrapping every individual invocation of `straight-use-package` in a transaction block would defeat the purpose of using transaction blocks, which is to group together as many consecutive invocations of `straight-use-package` as possible. In fact, each invocation of `straight-use-package` implicitly establishes another `straight-transaction` block to group together that package with all of its dependencies (transactions can be nested arbitrarily deeply; the important point for user-facing behavior is that there is at least one layer).

The simplest way to interface with the `straight.el` transaction system is to load `straight.el` first and then wrap the remainder of your init-file in a `straight-transaction` block.

There are alternative strategies for more complex use cases. [I use one such strategy in my own configuration.](https://github.com/raxod502/radian/blob/e40fc1dfc5477363394dc5013d1e9cb1fa78d034/emacs/radian.el#L250-L259)
