### ISSUE TITLE
Using 'ivy-explorer results in unbalanced parentheses

### ISSUE THREAD

**Issue by FelipeLema** [raxod502/straight.el#345]
Can't `(straight-use-package 'ivy-explorer)`  from either melpa or github repo (currently https://github.com/clemera/ivy-explorer/commit/783816afda31d1b75487b906257e23e273bad6fa)

Looks like there's some problem around escaping parentheses in `ivy-explorer-autoloads.el` which results in unbalanced parentheses.

**Comment by raxod502** [comment]
The following configuration works without error for me, from an otherwise empty `~/.emacs.d`:

```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'ivy-explorer)
```

Perhaps there is something else wrong with your configuration (did you accidentally edit the code for Ivy, for example?).

**Comment by FelipeLema** [comment]
Can concur as I finally got to test it in my other machine.

I'm sorry about the inconvenience
