### ISSUE TITLE
Issue installing haskell-mode on Windows

### ISSUE THREAD

**Issue by bradyt** [raxod502/straight.el#346]
With `(use-package haskell-mode)`, I get the following error on startup.

``` 
Warning (initialization): An error occurred while loading ‘c:/Users/Administrator/AppData/Roaming/.emacs.d/init.el’:

error: haskell-font-lock.el:0:0: error: error: (Local variables entry is missing the suffix)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Unfortunately I'm not getting a backtrace as Emacs crashes on further attempts. Googling, I found the following at https://github.com/rgoulter/dotfiles/blob/master/emacs.el.

``` elisp
;; When running this, I encounter the error:
;;> Building haskell-mode...
;;> apply: haskell-font-lock.el:0:0: error: error:
;;  (Local variables entry is missing the suffix)
;; ^ The solution to this is to config git to use autoclrf is input
;;   (IIRC)
(straight-use-package 'haskell-mode)
```

I'm only posting here first, this could be an issue with straight.el, or haskell-mode, or Windows and git, or PEBCAK.

**Comment by raxod502** [comment]
It seems unlikely that this is a problem explicitly with `straight.el`, although I'm certainly not opposed to installing some code to make things "just work" even when the user's Git configuration is broken.

I guess to find the location of the problem, you would want to check:

* What line endings does `haskell-font-lock.el` use in your local checkout?
* What line endings does it use in the Git index?
* Does Git think `haskell-font-lock.el` is a text file?
* Is your Git configured to perform line ending conversion on checkout?
* What line endings does Emacs expect `haskell-font-lock.el` to use?
* Does the local variable setting `coding: utf-8-unix` have anything to do with it? Does the file use special characters and Git doesn't detect it as text for some reason?

**Comment by bradyt** [comment]
Thank you @raxod502 , I'm now seeing some of what you see! I've posted a new issue at https://github.com/haskell/haskell-mode/issues/1631.

I'm not sure there's any reasonable way for `straight.el` to intercede in this issue. The two ends to this issue are the git checkout, and the byte-compile, I suspect. And so `straight.el` is really caught in the middle and cannot effect these two causes? If this is correct, please close issue, and I thank you for helping me isolate the issue.

**Comment by raxod502** [comment]
I think your analysis seems legit. Congrats on figuring out the issue!

Indeed, if—as you say—even opening the file leads to errors, then there's probably little I can do on my end to smooth things over :)
