### ISSUE TITLE
Set arbitrary git config after cloning

### ISSUE THREAD

**Issue by Fuco1** [raxod502/straight.el#353]
I use Emacs on 4 workstations outside of my "control" (i.e. workplace).  I have a global config for git to commit under my company credentials.

I would like to checkout packages (especially those I maintain) with straight and set the user/email to those I normally use for personal projects. 

This can extend to additional settings that I would want to maintain uniformly without having to manually edit the `.git/config` for every package (which I now do with submodules and it's like 50 or so very boring operations).

**Comment by raxod502** [comment]
Wouldn't it be easier to solve this problem by the use of a [conditional include file](https://git-scm.com/docs/git-config#_conditional_includes)?

**Comment by Fuco1** [comment]
I don't understand how I could use this.  When I clone a repository it has no config stored with it, the config file is generated, am I not correct?

So I would still need to do some manual operation.

**Comment by raxod502** [comment]
In your `~/.gitconfig`:

```
[user]
	name = "Work Name"
	email = "Work Email"
[includeIf]
	gitdir:~/.emacs.d/straight/repos/ = ~/.gitconfig.personal
```

In your `~/.gitconfig.personal`:

```
[user]
	name = "Personal Name"
	email = "Work Email"
```

**Comment by Fuco1** [comment]
This is pretty cool.  I think I can find a solution to this since I version my dotfiles and all.

We can close (the proposed fix WFM) but if you think this is valuable it's up to you.

**Comment by raxod502** [comment]
Best to maintain orthogonality by having one solution to every problem :)
