### ISSUE TITLE
Log of changes of updated packages

### ISSUE THREAD

**Issue by blaenk** [raxod502/straight.el#354]
Something I really miss from [Paradox](https://github.com/Malabarba/paradox) is the ability to very easily see a git log of the changes to a package since it was last updated. This was amazing for discovering new features added to a package, or otherwise keep up with its development, which in my case encouraged involvement (contribution, feedback, etc.) in package development. One could argue this benefits the emacs package ecosystem.

I feel like it should be even more possible/appropriate with straight given that with Paradox it would have to find the GitHub git repo, assuming it was even on GitHub, and then query the GitHub API to obtain the commit list, since it can't assume an existing local repo. Straight could instead invoke `git log old..new` or whatever the syntax for that is, and present it in a neat format.

It would be amazing if a magit-like interface were presented. In fact, maybe magit features themselves can be leveraged, given they already are when intervention of certain problems is required. Just did a quick skim of the manual and trying `(magit-log-other '("oldrev..newreg"))` accomplishes this, though I have no clue if that would be the best way. If magit were delegated to, the only remaining link would be an easy list/dash view of all updated packages which upon pressing Enter (for example) would open this buffer.

**Comment by raxod502** [comment]
Yep, agreed and sounds good. We should use Magit for this. The main technical problem to be solved is figuring out what the old revision was. I think the best paradigm is to copy Git and keep a file on disk somewhere that records these revisions (à la `FETCH_HEAD`)—or maybe we can even leverage Git itself to keep track of it (would using `FETCH_HEAD` directly work)?

This feature has been proposed before, but has never had a dedicated issue. Thanks for making one :)

**Comment by SkySkimmer** [comment]
`(setq straight-vc-git-auto-fast-forward nil)`

When I want to update my packages I do
- `M-x straight-fetch-all` (go watch cat videos or someting while it downloads)
- `M-x straight-merge-all`

For every package with possible updates straight will say something like "remote is ahead of local" (not verbatim) and offer to open in magit with `g` (without the `setq` above it silently updates).
Then for magit I have `'([unpulled status] . show)` in `magit-section-initial-visibility-alist` so it shows the list of unpulled commits, or I can magit-log. Looks like this: 
![magit](https://user-images.githubusercontent.com/2461932/53046224-df219b00-348f-11e9-9184-45900f29c64c.png)

To go back to the straight prompt `C-M-c`. If you updated in magit it will go to the next package, otherwise you can tell straight to update with `f`.

If you only want to look at 1 package you can `straight-{fetch,merge}-package` for it.

>If magit were delegated to, the only remaining link would be an easy list/dash view of all updated packages which upon pressing Enter (for example) would open this buffer.

I don't have a system for this though.

**Comment by raxod502** [comment]
FYI, you can use `M-x straight-x-fetch-all` for faster execution of package fetching (thanks @xuchunyang in https://github.com/raxod502/straight.el/pull/257). I'd love to see this interface integrated into `straight.el` proper; maybe we can extend that UI paradigm to cover reviewing changes as well.

**Comment by blaenk** [comment]
> or maybe we can even leverage Git itself to keep track of it

I think that's certainly possible, either with a tag or branch or something that straight updates after merging (even if it's never actually checked out), then it would just be a matter of `git log theref..`.

As you noted with `FETCH_HEAD`, this may already be tracked out of the box. For example I've used [reflog](https://git-scm.com/docs/git-reflog) shortname [`@{1}`](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#_git_reflog) in `git log @{1}..` to basically log from the second-to-last reflog entry onward.

> Reference logs, or "reflogs", record when the tips of branches and other references were updated in the local repository.

Source: https://git-scm.com/docs/git-reflog

So the last (most recent) reflog entry `@{0}` would be the current HEAD (IIUC), and so `@{1}` would be what HEAD was before that. So I use an alias with this to see a log of the changes since the revision before the pull, for example. Maybe something similar can be leveraged.

[This page](https://git-scm.com/docs/gitrevisions#gitrevisions-emltrefnamegtltngtemegemmaster1em) documents these shortnames succinctly. You can specify the refname, i.e. `master@{1}`, or you can omit it for the current branch to be inferred.

**Comment by progfolio** [comment]
Fixed by: #711
