### ISSUE TITLE
Don't ask user to implement their own eval function(s)

### ISSUE THREAD

**Issue by glasser** [raxod502/straight.el#358]
If I understand correctly, if one is editing one's init file to add new packages, one should not just evaluate the newly added straight-use-package expression, and should instead re-evaluate the whole init file in a transaction. The docs have an example of a command that does that. Is there a good reason to not include that command in straight, eg `M-x straight-reload-init`?

**Comment by raxod502** [comment]
Sounds reasonable, yes. But even further, we may want to consider a new minor mode, enabled by default, which advises the various evaluation functions to inject transactions. Some thought is needed as to the best way to address as many problems as possible with the same solution.

**Comment by raxod502** [comment]
I found an even better solution, namely don't require any user code at all.
