### ISSUE TITLE
can't get new packages from melpa

### ISSUE THREAD

**Issue by CeleritasCelery** [raxod502/straight.el#359]
Straight can't find the new magit dependency `transient`. When I look it up with `straight-use-package` it is not present. I can't seem to find any way to refresh the archive listings. I am using the latest version of straight.el. I have tried restarting multiple times.

However if I use the package.el code recommended by [melpa](https://melpa.org/#/getting-started) it shows up under `package-list-packages` and I can clone it from there. Still does *not* show up in straight though.

**Comment by raxod502** [comment]
`M-x straight-pull-package RET melpa RET`?

**Comment by CeleritasCelery** [comment]
That worked. I didn't know that package archives are treated as packages. 

I think the issue here is that I was pulling all packages, but ended up aborting part way through and restarted emacs. I must have been in a state where it pulled magit, but had not pulled melpa yet.
