### ISSUE TITLE
Support org-elpa

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#36]

**Comment by raxod502** [comment]
There is no repository backing org-elpa. It is only an implementation of the package.el protocol that allows you to download Org (named as org-plus-contrib) and a version of Org that excludes the contrib/ folder (named as org). It is therefore impossible to support org-elpa in straight.el.

Users may already install Org from EmacsMirror by default using straight.el; if they for some reason wish to clone insecurely using HTTP from the official repository, then they may specify that in the recipe.

**Comment by moyamo** [comment]
I came here looking for how to install org-contrib. It turns out that the default build recipe of emacsmirror excludes the org-contrib directory, so you have to override the build recipe with `(... :files ("lisp/*.el" "contrib/lisp/*.el") ... )`.

I'm not sure if there is a better way to install org-contrib.

**Comment by raxod502** [comment]
I think that's the best way. Org is kind of a special case, so I might be convinced to add some specific support for it. If anyone has an idea for that I'd be glad to hear it.

**Comment by SkySkimmer** [comment]
Wouldn't it work to consider org-contrib a separate package that has the same repository as org, like how swiper and ivy share repositories?

**Comment by raxod502** [comment]
Of course. The question is what mechanism is best for implementing this special case. I suppose what would make the most sense is creating a new virtual recipe repository just for Org that has recipes for `org` and `org-plus-contrib`. That would require adding support for recipe repositories that do not have backing local repos, which is not hard but does require some thought.

**Comment by moyamo** [comment]
Emacsmirror doesn't actually provide a `:files` directive in it's recipe. We could try to fix this by adding `"contrib/lisp/*.el"` to `straight-default-files-directive`

**Comment by raxod502** [comment]
Support for Org ELPA was implemented, see #192.
