### ISSUE TITLE
Support overriding only part of a recipe

### ISSUE THREAD

**Issue by CeleritasCelery** [raxod502/straight.el#360]
I make a lot of forks of repos (which is something I love about straight!!), but being required to provide the entire recipe seems more verbose then really needed. For example:

```elisp
(use-package swiper
  :straight
  (:files ("swiper.el" "swiper-pkg.el")
   :type git :host github :repo "abo-abo/swiper"
   :fork (:host github
          :repo "CeleritasCelery/swiper")))
```

The only info that straight.el did not already have is the forked repo. It seems like we could support syntax like this

```elisp
(use-package swiper
  :straight
  (:fork (:repo "CeleritasCelery/swiper")))
```
if other parameters changed, they could be optionally added as well (for example add `:host gitlab` if you forked to gitlab, or change the original host, etc). Currently you have to know what the original recipe was to even create a fork, which seems unnecessary. 

The same could be said for updating the local repo. Currently this is required:
```elisp
(use-package challenger-deep-theme
    :straight (:host github :repo "challenger-deep-theme/emacs"
               :local-repo "challenger-deep-theme"))
```
However we could make this simpler because all the rest of the info is already known.

```elisp
(use-package challenger-deep-theme
    :straight (:local-repo "challenger-deep-theme"))
```

**Comment by raxod502** [comment]
Yes, indeed. See #116. Thanks for providing the examples; I agree with all of them :)
