### ISSUE TITLE
straight.el doesn't work with bbdb 3

### ISSUE THREAD

**Issue by greened** [raxod502/straight.el#362]
I have this in my init.el:

```
(use-package bbdb
  :straight t)
```

I get this error:

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "bbdb-site")
require(bbdb-site)
eval-buffer(#<buffer  *load*-430253> nil "/Users/dag/.emacs.d/straight/build/bbdb/bbdb.el" nil t)  ; Reading at buffer position 1718
```

bbdb-site.el is actually bbdb-site.el.in.  Apparently bbdb needs some kind of configuration step before it can be used but straight wants to load bbdb before running that step.

**Comment by raxod502** [comment]
Let me know if this fixes the problem.

**Comment by greened** [comment]
It works!

**Comment by greened** [comment]
Oops, not sure you want this closed before merging to master.

**Comment by raxod502** [comment]
I think it is fine to close issues before the relevant changes are merged to master. The issue tracker is for tracking work that needs to be done.
