### ISSUE TITLE
Straight does not work with async-sandbox

### ISSUE THREAD

**Issue by codygman** [raxod502/straight.el#364]
While trying to use [org-wild-notifier](https://github.com/akhramov/org-wild-notifier.el) a function it that uses [async-sandbox](https://github.com/jwiegley/emacs-async/blob/d17c11e6082aa51f421bb037b828bdb15f405618/async.el#L350) called [org-wild-notifier--retrieve-events](https://github.com/akhramov/org-wild-notifier.el/blob/db143f812ed65f5ab6c75d0d686b73da20300b32/org-wild-notifier.el#L223) does not see straight installed packages.

This results in error:

```
helm-M-x: Cannot open load file: No such file or directory, straight
```

**Comment by raxod502** [comment]
I'm sorry, I don't understand what you've done to produce this error. Could you give me a step-by-step description, [starting from `emacs -Q`](https://github.com/raxod502/straight.el/tree/7f1bf09d6017dc17365bb22ac3af2cbf8f8b76b3#using-straightel-to-reproduce-bugs)?

**Comment by codygman** [comment]
Not doing it as we speak, but this is how it would go:

```
emacs -Q
```

bootstrap straight

```
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))```

straight install async

straight install org-wild-notifier

Now in emacs you have access to `org-wild-notifier`. When you run `async-sandbox` it is like running `-Q` though. So if you do:

```
(async-sandbox
   (org-wild-notifier-check))
```

it doesn't know where the straight installed packages are. I need the straight equivalent of [package-initialize](https://github.com/akhramov/org-wild-notifier.el/blob/db143f812ed65f5ab6c75d0d686b73da20300b32/org-wild-notifier.el#L230) for straight.

I suppose I could change the source of the above to do the straight bootstrap and then the sandbox could see straight installed packages?

**Comment by codygman** [comment]
In summary: I need the straight equivalent of `package-initialize`.

I made things work for now by doing the simplest low level thing I could think of... just loading all elisp files in the straight directory I need inside of the `async-sandbox` command:

```
(defun org-wild-notifier--retrieve-events ()
  "Get events from agenda view."
  (async-sandbox
   (let ((agenda-files org-agenda-files))
     (lambda ()
       (let ((org-agenda-use-time-grid nil)
             (org-agenda-compact-blocks t))

         ;; cody straight hack
	 (require 'subr-x)
         (load-file "~/.emacs.d/straight/repos/alert/alert.el")
         (load-file "~/.emacs.d/straight/repos/dash.el/dash.el")
         (load-file "~/.emacs.d/straight/repos/dash.el/dash-functional.el")
         (load-file "~/.emacs.d/straight/repos/org-wild-notifier.el/org-wild-notifier.el")
         ;; end cody straight hack
         (require 'org-wild-notifier)

         (setf org-agenda-files agenda-files)
         (org-agenda-list 2
                          (org-read-date nil nil "today"))

         (->> (org-split-string (buffer-string) "\n")
              (--map (plist-get
                      (org-fix-agenda-info (text-properties-at 0 it))
                      'org-marker))
              (-non-nil)
              (org-wild-notifier--apply-whitelist)
              (org-wild-notifier--apply-blacklist)
              (-map 'org-wild-notifier--gather-info)))))))
```

**Comment by raxod502** [comment]
I played around with this a bit and didn't quite figure out how everything works, but shouldn't it be sufficient to `(async-inject-variables "load-path")` inside the `async-sandbox`?

**Comment by codygman** [comment]
Thank you for your time. Sorry if I wasn't clear enoughand that I couldn't
give a proper repro.

I'll try async-inject-variables as soon as possible and see if it works.

If it does I can make sure org-wild-notifier works for other straight users
as well.

**Comment by codygman** [comment]
looks like this will work:

```
(defun org-wild-notifier--retrieve-events ()
  "Get events from agenda view."
  (async-sandbox
   `(lambda ()
      ,(async-inject-variables "load-path")
      (require 'org-wild-notifier)
      (let ((agenda-files org-agenda-files))
        (lambda ()
          (let ((org-agenda-use-time-grid nil)
                (org-agenda-compact-blocks t))

            (setf org-agenda-files agenda-files)
            (org-agenda-list 2
                             (org-read-date nil nil "today"))

            (->> (org-split-string (buffer-string) "\n")
                 (--map (plist-get
                         (org-fix-agenda-info (text-properties-at 0 it))
                         'org-marker))
                 (-non-nil)
                 (org-wild-notifier--apply-whitelist)
                 (org-wild-notifier--apply-blacklist)
                 (-map 'org-wild-notifier--gather-info))))))))
```

**Comment by raxod502** [comment]
Great! It does seem like that is correct usage to me—otherwise how would one expect the code to be loaded inside the child Emacs process?

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)
