### ISSUE TITLE
Creating *straight-process* buffer when run emacs

### ISSUE THREAD

**Issue by juev** [raxod502/straight.el#367]
Hello,

Thank you for straight.el! This is great package. But one question. When I start Emacs I see one more buffers with name `*straight-process*`, which contains these lines:

```
$ cd /Users/d.evsyukov/
$ find /dev/null -newermt 2018-01-01\ 12\:00\:00

/dev/null

[Return code: 0]
```
How I can close this buffer automatically? Or why this buffer was created?

**Comment by raxod502** [comment]
This buffer is used to capture the output of external processes spawned by `straight.el`. If you don't want to see it, I suggest customizing the value of the variable `straight-process-buffer` to include a leading space.

**Comment by juev** [comment]
Thank you very much!
