### ISSUE TITLE
Update package and all dependencies

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#379]
I frequently need to update a package, but then find that its dependencies also need to be updated in order for it to work properly. Currently, the only way to update both a package and its dependencies is to either update all packages, or manually identify the dependencies and update them individually. Neither strategy is ideal. We should provide a good UI for this frequent operation.

**Comment by zoechi** [comment]
Is this the way to update to latest and greatest of all installed packages?
Is there a way to see 
- what packages have newer versions
- what packages were affected by for example `straight-fetch-all`?

**Comment by raxod502** [comment]
As mentioned in (some issue thread that I know exists but cannot find), you can figure out what was changed by doing a diff on your lockfile before and after the update. This of course requires you to version-control your lockfile and write it after each update, which is strongly recommended in any case.

To identify which packages have newer versions, you need to do a `straight-fetch-all` (or `straight-x-fetch-all`). It can't be done without fetching because unlike with `package.el` there's no central database. Now as for inspecting the result and seeing what needs to be updated, you could write a little function that would inspect the difference between `master` and `origin/master` in each repository. (Actually, you can do better, because `straight.el` knows what primary branch is used in each repo even if it's not `master`.) Such a function hasn't been added to `straight.el` yet, but it should be. Feel free to open an issue or pull request on the topic, if you'd like.

**Comment by zoechi** [comment]
That sounds great already. 
Can you please point me to where I find the relevant lockfile?

**Comment by raxod502** [comment]
This is in the documentation: https://github.com/raxod502/straight.el#lockfile-management
