### ISSUE TITLE
bootstrap on Windows 10 fails to find python

### ISSUE THREAD

**Issue by priyadarshan** [raxod502/straight.el#381]
I am testing straight.el on Windows 10 now, after having it run on Ubuntu flawlessly.

Starting with empty `.emacs.d`, I add the bootstrap code as per docs.

Both both watchexec.exe and python3.exe are available. I have also this code, borrowed from radian,

```
(if (and (executable-find "watchexec")
         (executable-find "python3"))
    (setq straight-check-for-modifications '(watch-files find-when-checking))
  (setq straight-check-for-modifications '(find-at-startup find-when-checking)))
```

So, `straight-check-for-modifications` is set to `(watch-files find-when-checking)`

At first boot, emacs (27.0.50) stops with message:

```
$ cd "c:/tools/emacs27/bin/"
$ "c:/home/.emacs.d/straight/watcher/virtualenv/bin/python" "-m" "pip" "install" "-e" "c:/home/.emacs.d/straight/repos/straight.el/watcher"

[File error while searching for program]
```

I can see `python` is missing there,

```
.emacs.d/straight/watcher/virtualenv/bin/python
```
but I saw it was installed here:

`.emacs.d\straight\watcher\virtualenv\Scripts\python.exe`

Could it be straight is looking for a linux bin, while it should look for the Windows one?

**Comment by priyadarshan** [comment]
With

```
(setq python (straight--watcher-file "virtualenv" "Scripts" "python.exe"))
```

`(file-executable-p python)` returns `t`.

Basedo on that, I tried to modify the source (changing `bin` with `Script`, and `python` with python.exe`, but still it show same error message.

**Comment by priyadarshan** [comment]
Sorry, I edited the wrong file. Editing `.emacs.d/straight/repos/straight.el/straight.el` with the values allows me to have a succesful bootstrap.

I am not sure how to cleanly propose a system-dependant fix, though.

**Comment by raxod502** [comment]
I think it is fine to have `straight-watcher--virtualenv-setup` use a `pcase` on `system-type`, and use your value for `python` only on `ms-dos`, `windows-nt`, or `cygwin`. Or whichever subset of those values actually corresponds to having the binaries in a different directory.

Thanks for diagnosing the problem!

**Comment by priyadarshan** [comment]
I am glad of I was of some little help. I have bene uisng Emacs since 2002, searching all the time for a suitable way to organise the Emacs-world, and I have finally found the graal in straight.el. Thank you for developing such a useful and meaningful tool.

**Comment by raxod502** [comment]
Your suggested change is implemented. Let me know if it fixes the problem for you.

**Comment by priyadarshan** [comment]
Thank you, it works.

I have tested with prepending `(setq straight-repository-branch "develop")` to my init.el and starting from an empty .emacs.d. Now the error message is gone.

I am also testing straight.el's different other watching systems, and I will report on a new issue.

This one could be closed if you wish.

Thank you!
