### ISSUE TITLE
What's the correct way to remove overrides without restarting?

### ISSUE THREAD

**Issue by ubolonton** [raxod502/straight.el#384]
I added overrides like this

```emacs-lisp
(defun ublt/straight-recipe (package &rest plist)
  (declare (indent 1))
  (let ((recipe (cl-copy-list (cdr (straight-recipes-retrieve package)))))
    (cl-loop for (key value) on plist by #'cddr
             do (plist-put recipe key value))
    (cons package recipe)))

(defun ublt/straight-override (package &rest plist)
  (declare (indent 1))
  (straight-override-recipe (apply #'ublt/straight-recipe package plist)))

(ublt/straight-override 'hydra
  :fork ...)
```

It worked.

How do I remove the overrides without restarting Emacs?
I tried changing `straight-recipe-overrides`, but it doesn't seem to be picked up.
`(straight--convert-recipe 'hydra)` still includes `:fork`, and `M-x straight-freeze-versions` still uses the fork.

**Comment by ubolonton** [comment]
On a second note, overriding like that seems to work only during startup, not afterwards.

**Comment by raxod502** [comment]
Try reloading your init-file.

**Comment by ubolonton** [comment]
Reloading init file works, but that's to coarse-grained.

Just `(load straight-bootstrap-file nil 'nomessage)` works as well.
Is that the recommended way, or is there a more fine-grained API?

**Comment by raxod502** [comment]
Honestly, I would not suggest using `straight-recipe-overrides` for this. It is primarily intended for overriding the recipe for `straight.el` itself, conditionally overriding the recipe for a dependency that might or might not be present, and other such advanced usage. As such, the API is inflexible. Why not just pass your modified recipe to `straight-use-package` directly?

**Comment by ubolonton** [comment]
Ah ok, I misunderstood the doc then.

I use `straight-register-package` now.
Is there a way to rebuild the cache without reloading `init-file`, which has many other (potentially unwanted) side effects?

**Comment by raxod502** [comment]
No, currently the only supported way to change existing package configuration is by reloading your init-file. This is because the API to support arbitrary post-hoc changes to configuration without a full reload would be very complex, in my opinion. If you can think of a straightforward way to support your use case, I would be happy to hear it, though.

Nevertheless I recommend making your init-file idempotent, if possible. [Mine is](https://github.com/raxod502/radian/blob/b04ba5eaf5600ac25b1f90b2197f30f5b29f5181/emacs/radian.el), and it simplifies many things.

**Comment by ubolonton** [comment]
> This is because the API to support arbitrary post-hoc changes to configuration without a full reload would be very complex

Can you give a bit more details on this, or some examples?
One I can think of is user adding several custom recipes, then forgetting to evaluate one of them.

In my configuration, all custom recipes are included in a single file, within a `straight-transaction` block, not in `use-package` blocks in different locations. The above is then a non-issue.

Idempotency in terms of functionality configuration is easy, but there can be other types of side effects, for examples:
- Slow startup-only operations (even though the end state would be the same).
- State changes of module loading mechanism (`load-history` (`require` vs. `load`)), configuration mechanism (`use-package`). I think reloading `init-file` is even more problematic for this. In my case specifically, not letting `straight-freeze-versions` reload `init-file` gives the correct lockfile, while letting it reload results in the incorrect lockfile below (most packages removed):
    ```emacs-lisp
    (("epkgs" . "932c173480e505c40cb510ebaae4ccae6efdee3a")
     ("gnu-elpa-mirror" . "e979b4211660a2cc4377ef04918979fe9b4323ed")
     ("hydra" . "a2bb124a3f2e57c032fc264bcd08219fa3d513d9")
     ("melpa" . "fe8fe6af7826a4b73ac784fde8859130b9ad7096")
     ("straight.el" . "46aa1b1ee10bfd3a20a419c3f70d7a9c6d369fb4")
     ("use-package" . "0ee88b5cac41acf974c4bedb8859931ead8bfc79"))
    :saturn
    ```

My opinion is that, reloading `init-file` is a middle ground between restarting Emacs (basic), and using the low-level functions to incrementally tweak things (advanced). Getting this middle ground right is trickier than it's worth.

**Comment by ubolonton** [comment]
My use case is updating the lockfile after overriding recipes to use forks.

The following works for me though, so I'm closing this.

```emacs-lisp
(straight-freeze-versions 'force)
```
