### ISSUE TITLE
Switching to fork of previously configured package doesn't work

### ISSUE THREAD

**Issue by romatthe** [raxod502/straight.el#385]
Hi,

This might be a bug or simply me failing to RTFM.

I've previously configured the `emacs-dashboard` package with `straight.el` and `use-package`, like so:

```elisp
(use-package dashboard
  :straight t
  :config
  (setq dashboard-startup-banner "~/.emacs.d/img/ness_transp.png"
	dashboard-items '((recents  . 5)
                          (projects . 5)
			  (agenda . 5)))
  (dashboard-setup-startup-hook))

```
The `emacs-dashboard` package has a problem however when `package.el` is never initialized (which is the case for me, as I want to rely purely on `straight.el`, and I never call `package-initialize` in my configuration).

I forked the package, implemented a very quick workaround and wanted to switch my configuration over to my fork, like so:

```elisp
(use-package dashboard
  :straight (dashboard :type git :host github :repo "emacs-dashboard/emacs-dashboard"
                       :fork (:host github
				    :repo "romatthe/emacs-dashboard"))
  :config
  (setq dashboard-startup-banner "~/.emacs.d/img/ness_transp.png"
	dashboard-items '((recents  . 5)
                          (projects . 5)
			  (agenda . 5)))
  (dashboard-setup-startup-hook))

```
After I restart Emacs, I still seem to be using the package from `emacs-dashboard/emacs-dashboard` instead of `romatthe/dashboard`.

I tried both `straight-check-package` and `straight-rebuild-package`, but this didn't seem to resolve anything.

My build `build-cache.el` does seem to be listing things correctly:

>  "dashboard" ("2019-05-31 23:22:02" ("emacs" "page-break-lines") (:type git :host github :repo "emacs-dashboard/emacs-dashboard" :fork (:host github :repo "romatthe/emacs-dashboard") :package "dashboard" :local-repo "emacs-dashboard")

However, when I drop down into the actual git repository,  it still seems to be pointing to the original repository:

```
$ pwd
/home/romatthe/.emacs.d/straight/repos/emacs-dashboard
$ git remote -v
origin	https://github.com/emacs-dashboard/emacs-dashboard.git (fetch)
origin	https://github.com/emacs-dashboard/emacs-dashboard.git (push)
```

Is this an issue with `straight.el` or am I doing something wrong? Despite the extensive documentation (which is much appreciated) I didn't immediately spot anything I was doing wrong.

**Comment by raxod502** [comment]
You're doing something wrong, but mostly because the documentation does not make it clear what you have to do. See https://github.com/raxod502/straight.el/issues/166.

**Comment by romatthe** [comment]
Yeah, I was afraid the problem was going to be on my end. I think it might be a good idea to add a note to the documentation about this.
Considering the issue you referenced is still open pending those changes, I'll close this one instead.

Thanks for maintaining this cool package btw!
