### ISSUE TITLE
Support for building dynamic modules

### ISSUE THREAD

**Issue by Fuco1** [raxod502/straight.el#389]
I have no idea if package.el provides anything at all, so this might not be "feature parity", rather simply new feature.

Now that we have possibility to build modules in C and load them into Emacs, people are still basically not using it because it seems a bit tedious.  I have one package (https://github.com/Fuco1/sql-workbench) which would greatly benefit from having the SQL logic implemented in C, because right now I'm parsing text dumps from `mysql` CLI and that is... stupid /shrug

Have you at all looked at the modules stuff, or is that a goal for 2.0?

**Comment by raxod502** [comment]
Can you elaborate on what would be required of `straight.el` to support this? Would #72 be sufficient?

**Comment by Fuco1** [comment]
@raxod502 I'm not really sure, but having `make` is a good first step.

**Comment by AmaiKinono** [comment]
I happen to know 2 packages that use dynamic modules. [emacs-tree-sitter](https://github.com/ubolonton/emacs-tree-sitter) has some build scripts, and [fuz.el](https://github.com/cireu/fuz.el) offers a elisp function for that. Don't know if there exits other ways. I'd say the simplest way is to allow user to put functions in the recipe, that runs after installing a new package or the code of the module being changed, but not after elisp code being changed. A user can run the build script or do whatever that builds the dynamic module in the functions.

**Comment by raxod502** [comment]
An easy solution is to add `straight-use-package-post-build-functions` in addition to `straight-use-package-pre-build-functions`.

**Comment by progfolio** [comment]
I'm hoping #535 takes care of this. Now merged into develop. @Fuco1 @AmaiKinono Testing appreciated if you have time.
