### ISSUE TITLE
How to work around 'could not read Username'

### ISSUE THREAD

**Issue by AmaiKinono** [raxod502/straight.el#399]
Hi. I've been using the command line git all the time, and today I want to see if straight.el can help me contributing my code to Emacs packages easier. I set up `:fork` in the recipe, and the "origin" and "fork" remotes are set correctly by straight.el. But when I finished my change and using `straight-push-package`, but there's the error

```
fatal: could not read Username for 'https://github.com': No such file or directory
```

I hope straight.el ask me for username/password and push my change, but it didn't. I assume if I use ssh remote URL, these problems will be solved since username/password are not needed. However, set `straight-vc-git-default-protocol` to `'ssh` makes me cannot clone other people's packages, and seems there's no way to use ssh URL only for my packages/forks using straight.el.

Am I doing it right? If not, what's the correct way to develop other people's packages with straight.el?

Thanks!

**Comment by raxod502** [comment]
* You can force SSH for a single recipe simply by specifying e.g. `:host nil :repo "git@github.com:raxod502/straight.el.git"`.
* `straight.el` does not currently pass through interactive prompts to the minibuffer but this is a planned feature (#334).
* Consequently, for SSH, you need to set up [ssh-agent](https://www.ssh.com/ssh/agent), and for HTTPS, you need to set up [git-credential-cache](https://git-scm.com/docs/git-credential-cache).

Personally, I use SSH for everything. If SSH works for pushing your own package, it's going to work for cloning everyone else's packages too.

**Comment by AmaiKinono** [comment]
I see, thanks for your help!

> If SSH works for pushing your own package, it's going to work for cloning everyone else's packages too.

Yes, I misunderstood it. SSH works great.

**Comment by raxod502** [comment]
Great, I'll close this issue then. Feel free to let me know if you have any other trouble :)
