### ISSUE TITLE
straight-check-all/package does nothing

### ISSUE THREAD

**Issue by SwiftLawnGnome** [raxod502/straight.el#400]
I regularly do a `straight-pull-all` and `straight-check-all`, but for a while now the latter hasn't done anything despite plenty of repos fast-forwarding. Same goes for `straight-check-package` on an updated package. One time, a week or so ago, the commands were working, but once I restarted Emacs it no longer worked and hasn't since. I hadn't modified my straight.el configuration before this issue arose. The value of `straight-check-for-modifications` is `(find-at-startup find-when-checking)`. Not sure what other information is relevant to this, so let me know what else I can provide.

**Comment by raxod502** [comment]
I can reproduce this issue. Thanks for reporting it. I'm not sure what's wrong.

**Comment by darth10** [comment]
I've got a similar issue where `straight-rebuild-all` does nothing in Emacs batch mode despite several packages being fast-forward merged.
Might be related to #412 as well.

**Comment by raxod502** [comment]
`M-x straight-rebuild-all` should rebuild everything completely independent of whether any files have changed. If that's not the case, then something is seriously wrong.

**Comment by igroen** [comment]
It looks that this is fixed by: [09184470234416f595fb3e661796e9fea375dd6b](https://github.com/raxod502/straight.el/commit/09184470234416f595fb3e661796e9fea375dd6b)

**Comment by raxod502** [comment]
Oh lol I always forget to check which bugs I'm fixing
