### ISSUE TITLE
(use-package :bind) seems being ignored in byte-compiled script

### ISSUE THREAD

**Issue by reedom** [raxod502/straight.el#401]
I made the following `init.el` and tested on GNU Emacs 26.2.
Hit `C-x C-f C-s` and it should output "Hello, world" in the mini-buffer.
But with `init.elc`(byte-compiled), it doesn't.

```lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(defun my-hello ()
  (interactive)
  (message "Hello, world"))

(use-package icomplete
  :bind (:map icomplete-minibuffer-map
              ("C-s" . my-hello)))

(custom-set-variables '(icomplete-mode t))
```

With `package.el`, `init.elc` works as expected.
```lisp
(require 'package)
(package-initialize)
(require 'use-package)

(defun my-hello ()
  (interactive)
  (message "Hello, world"))

(use-package icomplete
  :bind (:map icomplete-minibuffer-map
              ("C-s" . my-hello)))

(custom-set-variables '(icomplete-mode t))
```

**Comment by raxod502** [comment]
You `(require 'use-package)` in the `package.el` example, but not in the `straight.el` example. That looks suspicious to me. If you make that change, then does it work?

`straight.el` doesn't load your packages, it makes them available for loading. Just like `package.el`. Otherwise the point of autoloading would be defeated.

**Comment by reedom** [comment]
> If you make that change, then does it work?

Yes, it does.

> `straight.el` doesn't load your packages, it makes them available for loading. Just like package.el. Otherwise the point of autoloading would be defeated.

Yeah.
What I know anything else with the `straight.el` version is that `:init` and `:config` can be processed via `init.elc`.

```lisp
(use-package icomplete
  :init (message "icomplete:init")  ;; the message can be seen in *Message* buffer
  :config (message "icomplete:config") ;; (same)
  :bind (:map icomplete-minibuffer-map ;; still being ignored...
              ("C-s" . my-hello)))
```

**Comment by raxod502** [comment]
Okay, so now that you've added `(require 'use-package)`, is your problem solved?

**Comment by reedom** [comment]
Sorry, I misunderstood what you had suggested.
And this time actually I applied `(require 'use-package)` and `:bind` was interpreted.
So, yeah the issue itself has been solved.

Yet it's mistery why only `:bind` had been ignored.
Anyway, thank you for your help!

**Comment by raxod502** [comment]
Great. I will point out that you should only need to load `use-package` at compile time, i.e.

```elisp
(eval-when-compile (require 'use-package))
```

But glad to hear you figured it out.
