### ISSUE TITLE
Error msg: Failed to run "git"; see buffer *straight-process*

### ISSUE THREAD

**Issue by arkhan** [raxod502/straight.el#403]
Greetings, I am performing a clean installation of my emacs configuration, it reaches a point where I throw the following error:

https://bin.disroot.org/?758b159f623ba015#NYcnakti5qRZ5bOmw8mKK69LemOYzOASElE9VnDwr8o=

And nothing installed after that.

Thank you

**Comment by raxod502** [comment]
Do you think you could run Emacs with English localization settings and post the log from that? I don't know any other languages, unfortunately.

**Comment by SkySkimmer** [comment]
It looks like it stops being able to find `git` after installing `exec-path-from-shell`

**Comment by arkhan** [comment]
@raxod502, @SkySkimmer the problem was with exec-path-from-shell

Thank you
