### ISSUE TITLE
install.el is causing error when using different home directory

### ISSUE THREAD

**Issue by dmusican** [raxod502/straight.el#405]
When I use a custom home directory for emacs, i.e.

`HOME=~/home-tryit emacs`

where `~/home/tryit/` has a .emacs.d directory with an init.el within, with the bootstrap code, it fails to work: I get the error message:

`error: Unknown recipe version: :alpha`

However, when I change the bootstrap code to pull install.el from the master branch (instead of from develop, as the home page suggests), everything works great. Is there something wrong with the newest update to install.el in develop?

**Comment by gcantieni** [comment]
I am getting the same behavior with default home location

**Comment by raxod502** [comment]
It's my bad, sorry -- see https://github.com/raxod502/straight.el/pull/404#issuecomment-522276127.

**Comment by gcantieni** [comment]
Works now, thank you!

**Comment by dmusican** [comment]
Works for me too, much appreciated!
