### ISSUE TITLE
Add option to only rebuild packages when changed in Emacs

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#41]
This would help with #9. Probably we should also handle some simple cases like the build directory or repository being deleted, which users might try if they didn't know about `straight-rebuild-package`.

**Comment by raxod502** [comment]
This is now available; let me know if the new option works for you:

```
(setq straight-check-for-modifications 'live)
```

* @nico202 
* @dieggsy 
* @tummychow 

(I'm pinging the people who have commented about the slowness of Emacs init with `straight.el`, especially on older or embedded systems.)

**Comment by tummychow** [comment]
:+1:, this is a huge improvement for my setup. First load after booting went down to 3s or something thereabouts (from 50+). Thanks.

**Comment by dieggsy** [comment]
@raxod502 Indeed this shaves off about a second from my startup time, but it's a little unclear to me exactly what this does or when packages are actually rebuilt?

**Comment by raxod502** [comment]
@dieggsy Instead of detecting modifications using `find(1)` at Emacs init, modifications are detected by checking `buffer-file-name` when `before-save-hook` is invoked in Emacs. When that happens, the name of the repository in which a file was modified is appended to `build-cache.el`. This information is then used at startup to rebuild the correct packages without having to check at that time. Does that answer your question?

The docstring is reproduced below for the benefit of future visitors.

```
straight-check-for-modifications is a variable defined in ‘straight.el’.

When to check for package modifications.
Value ‘at-startup’ means do it when straight.el is bootstrapped
during Emacs init. Value ‘live’ means hook into
‘before-save-hook’ to detect modifications as you make them (this
means modifications made outside Emacs are not detected, but
speeds up init). Value ‘never’ means don’t check automatically.
In this case you must use ‘straight-rebuild-package’ whenever you
modify a package, before restarting Emacs.
```

**Comment by dieggsy** [comment]
ah, yeah that clarified it. thanks!
