### ISSUE TITLE
straight-recipes-emacsmirror-mirror-retrieve doesn't work if mirror file is in CRLF encoding

### ISSUE THREAD

**Issue by r-darwish** [raxod502/straight.el#416]
aae8a57dc70077ba4afeaab6febe1f7bd2e63572 changed `straight-emacsmirror-use-mirror` to `t`. When launching [my configuration](https://github.com/drrlvn/.emacs.d/blob/b7a01affd97ae1741e6a97425cf5dde917f51c0d/init.el#L5) in Windows I get:

```
error: Could not find package syntax-subword in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)
```

This seems to happen only on Windows. What's even stranger is that setting the variable back to `nil` with `setq` after `(require 'straight)` doesn't fix it, only when calling `setq` before `require` fixes it.

**Comment by raxod502** [comment]
That package is available for me (and [it is listed in `emacsmirror-mirror` latest on GitHub](https://github.com/emacs-straight/emacsmirror-mirror/blob/c31546f458bc9ab59f964bfc83615ca06196fc60/mirror#L4985)). Run `M-x straight-pull-package RET emacsmirror-mirror RET` to pull the latest version of the recipe repository.

> This seems to happen only on Windows.

I think it is more likely that your Windows machine has a different revision of the `emacsmirror-mirror` repository than your other machines.

> What's even stranger is that setting the variable back to `nil` with `setq` after `(require 'straight)` doesn't fix it, only when calling `setq` before `require` fixes it.

This is not surprising at all. The value of that variable is read when `straight.el` is loaded for the first time (or when you are reloading your init-file). See [the bootstrap code](https://github.com/raxod502/straight.el/blob/11ae699d67114068e86f5e3ceb6646e42503ac6e/bootstrap.el#L97-L105). (This behavior [is documented in the README](https://github.com/raxod502/straight.el/tree/c870fca59bda58d00df3b2c4819b199f45ec394e#emacsmirror), although I will certainly admit that does not jump out at the reader.)

**Comment by r-darwish** [comment]
My `emacsmirror-mirror` pacakge is at `c31546f`, which is the latest. I can even see `syntax-subword` there, but the error still persist.

If it helps, here's the complete traceback:
```
Debugger entered--Lisp error: (error "Could not find package syntax-subword in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)")
  signal(error ("Could not find package syntax-subword in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)"))
  error("Could not find package %S in recipe repositories: %S" syntax-subword (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror))
  straight--convert-recipe(syntax-subword nil)
  straight-use-package(syntax-subword)
  eval-buffer(#<buffer  *load*> nil "c:/Users/roey/.emacs.d/init.el" nil t)  ; Reading at buffer position 30704
  load-with-code-conversion("c:/Users/roey/.emacs.d/init.el" "c:/Users/roey/.emacs.d/init.el" t t)
  load("c:/Users/roey/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1000be9b9>)()
  command-line()
  normal-top-level()
```

**Comment by raxod502** [comment]
Oh, huh. That's very odd then; you are probably right about it being a platform-specific problem. I am guessing if you run `(straight-recipes-emacsmirror-mirror-retrieve 'syntax-subword)` then you'll get nil? If so, that's the issue. The definition is quite simple:

```elisp
(defun straight-recipes-emacsmirror-mirror-retrieve (package)
  "Look up a PACKAGE recipe in the Emacsmirror mirror.
PACKAGE should be a symbol. If the package is available from
Emacsmirror, return a MELPA-style recipe; otherwise return nil."
  (cl-block nil
    (dolist (org '("mirror" "attic"))
      (with-temp-buffer
        (insert-file-contents-literally org)
        (when (re-search-forward (format "^%S$" package) nil 'noerror)
          (cl-return
           `(,package :type git :host github
                      :repo ,(format "emacs%s/%S" org package))))))))
```

Maybe you could debug why that is not finding the string in the file? Perhaps it is a character encoding problem, or something with line endings.

**Comment by raxod502** [comment]
(Note that that function should be run with a working directory of the `emacsmirror-mirror` repository.)

**Comment by r-darwish** [comment]
Found it. Git converted the file to CRLF and `(format "^%S$" package)` doesn't work because of the `\r`. I should probably configure my git not to do that, but maybe `straight` should support CRLF as well?

**Comment by raxod502** [comment]
Yeah, probably it should. Is that just updating the regexp to `"^%S\r?$"`? If so, I'd gladly merge such a pull request.

**Comment by r-darwish** [comment]
I'll test it and open a PR
