### ISSUE TITLE
[cygwin is not windows-os] [straight--windows-os-p] [Refer to #409]

### ISSUE THREAD

**Issue by owtk** [raxod502/straight.el#418]
Issue #409 introduced a new function to indicate which systems support symlinks:
```
(defun straight--windows-os-p ()
  "Check if the current operating system is Windows."
  (memq system-type '(ms-dos windows-nt cygwin)))
```
cygwin should not be in this list, it supports symlinks. It runs on windows-os, but in its own environment, with its own filesystem including /tmp, /proc, .. and its own python-distribution.  For applications, the emacs cygwin provides should behave like a *NIX-system.

Before the patch of issue #409 I could make emacs doom use straight with symlinks by advising the `file-exists`-function for the cmd-Parameter. Advising the `straight--windows-os-p`-Funktion does not work with the same result, I get lock-file-errros and renaming-file-errors. Maybe there are side-effects introduced with the use of `straight--windows-os-p`? There could also be changes in doom-emacs, but I can not get my head around doom and straight at the same time and try smaller steps.

**Comment by raxod502** [comment]
Okay, want to submit a pull request to fix this problem?

**Comment by owtk** [comment]
Unfortunately, right now I'm not proficient enough at git to do that. This is my first action on github and with git, i am still trying out.

**Comment by raxod502** [comment]
No worries. There is no rush, or perhaps someone else can help out.

**Comment by progfolio** [comment]
#439 addresses the function in `straight.el`, but the function still has the old definition in `install.el`.
Is this correct, or should it be removed in `install.el` as well?

**Comment by raxod502** [comment]
The definition in `straight.el` proper and the one in `install.el` should definitely be kept in sync, and a comment should probably be added in both places noting that they should be kept in sync, so that this doesn't happen again.
