### ISSUE TITLE
Defer initialisation until needed

### ISSUE THREAD

**Issue by manuel-uberti** [raxod502/straight.el#421]
This is a question not a bug report, so if there is another (better) place to ask questions such as this feel free to close the issue and redirect me elsewhere.

Is it possible to defer `straight.el` initialisation? I was wondering if `straight.el` could be bootstrapped only when actually needed, to save some startup time. I don't know much about `straight.el` internals to figure this out for myself, that's why I am asking.

I know this is a peculiar use case, and `straight.el` is already working greatly for me. So I will be happy even if deferring is not possible. :+1:

**Comment by raxod502** [comment]
I'm not sure how good of an idea this is. You still have to run a bunch of `straight.el` code during startup, for example to translate all of the recipes and see if there are conflicts and to check for package modifications. I feel like the only reasonable way to reduce load-related startup time is to split `straight.el` into two files, one which contains code needed during startup and one which has the interactive functions and such. I also don't think that will save more than a millisecond or two, and the added complexity would be significant. Keep in mind that everything that is more complicated than evaluating Elisp is already batched and cached come hell or high water (checking package modifications, looking up recipes, reading autoloads, ...), so it's probably a lot faster than you think.

Perhaps you are thinking of something slightly different, though?

**Comment by manuel-uberti** [comment]
You nailed it: I was thinking exactly of keeping the startup/bootstrap code separated, and load the second one only when actually needed. But if it's only a matter of milliseconds, going the extra mile makes no sense at all.

I've been tinkering with my configuration to understand the bottlenecks during startup, and the [Emacs Start Up Profiler](https://github.com/jschaf/esup) now shows only the code related to 'straight.el` as the heavyweight. It's not really about fast boots (~1s is already fast enough), but it's more about understanding what is involved during startup.

Thanks for the explanation, and do feel free to close this issue if you want. :)

**Comment by raxod502** [comment]
For what it's worth, my configuration starts up in ~0.6s for a fully configured graphical frame on Linux using ~115 packages via `straight.el`. The most important things are to use live modification detection and autoloads caching (the latter being enabled by default).

More insight into what exactly might cause delays during startup would certainly be very valuable. It would be great to have some tests that could be run automatically that would collect information about how the time breaks down. If you think that would be useful, feel free to open another issue for it.
