### ISSUE TITLE
Straight not checking packages on function call

### ISSUE THREAD

**Issue by dylanjm** [raxod502/straight.el#432]
I've noticed latley that my straight installation is not checking for file modifications. I have to do some weird order of straight-rebuild-package and restart my emacs a number of times before my changes are reflected in my setup. 

My `*straight-process*` buffer never changes and only ever reads

```
$ cd /
$ find /dev/null -newermt 2018-01-01\ 12\:00\:00

/dev/null

[Return code: 0]
```

Not quite sure what the problem is. Currently I setup straight in my early-init like so:

```
    (eval-and-compile
      (defvar straight-recipes-gnu-elpa-use-mirror t)
      (defvar bootstrap-version 5)
      (defvar bootstrap-file
        (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory)))

    ;; Clear out recipe overrides (in case of re-init).
    (with-no-warnings
      (setq straight-cache-autoloads t)
      (setq straight-recipe-overrides nil)
      (setq straight-check-for-modifications '(find-when-checking check-on-save))
      (setq straight-repository-branch "develop")
      (setq straight-use-package-by-default t))

    (with-no-warnings
      (setq use-package-verbose nil)
      (setq use-package-always-defer t)
      (setq use-package-enable-imenu-support t)
      (setq use-package-compute-statistics t))

    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))

    (load bootstrap-file nil 'nomessage)
    (straight-use-package 'use-package)
```

**Comment by raxod502** [comment]
I cannot reproduce the problem. I pasted your code into an empty `~/.emacs.d` under `early-init.el` and started Emacs. All packages were built. I restarted, and no packages were built. Then I navigated to `~/.emacs.d/straight/repos/use-package/use-package-core.el` and edited it, then saved the file. When restarting Emacs, `use-package` and `bind-key` were rebuilt. As desired. Are you seeing something different, or are you following different steps?

**Comment by dylanjm** [comment]
Here are the steps I am following, starting from bootstrapping straight.

- Start emacs and allow straight to clone and and build everything
- Restart emacs, and everything works great. 
- Edit `~/.emacs.d/straight/repos/emacs-theme-gruvbox/gruvbox.el`
- Save my changes and run `M-x straight-check-package gruvbox`
- I get a message `Building Gruvbox... done`
- For good measure I run `M-x straight-rebuild-package gruvbox`
- Restart emacs, no messages saying it has detected changes, but I'm not expecting that message since I forced straight to check in my last session. 
- None of my edits show up in my theme. 
- Make sure my custom.el file is deleted so I'm not accidentally overwriting anything on startup.
- Repeat in some fashion until my changes show up. 

Sometimes I go into the build directory and manually delete all `*.elc` files and then run `M-x straight-rebuild-package` and that works.

**Comment by dylanjm** [comment]
Just tried a different way. 

- Start emacs
- edit `~/.emacs.d/straight/repos/emacs-gruvbox-theme/gruvbox.el`
- save file
- restart emacs
- Changes do not show up, no message saying Gruvbox being rebuilt.

**Comment by raxod502** [comment]
I'm sorry, but unless you provide complete code that can be dropped into an empty `~/.emacs.d`, I won't be able to help you. I simply do not have the extra time to figure out what's wrong based on an incomplete description.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)
