### ISSUE TITLE
how to make a list of recipes?

### ISSUE THREAD

**Issue by OrionRandD** [raxod502/straight.el#433]
You have this in the documentation, but I cannot find an example:
"Instead of passing just a package name to straight-use-package, you can pass a list ("recipe") ..."

I tried with:
(straight-use-package '(evil company))    -> then C-x e   -> but did not work
(straight-use-package '("evil" "company"))    -> then C-x e   -> but did not work
(straight-use-package '((evil (company)))    -> then C-x e   -> but did not work
(straight-use-package '((evil (company))))  -> then C-x e   -> but did not work

Could you tell me how do I make the list?
Also, could you put examples in the official documentation?
Thx a lot

**Comment by vyp** [comment]
The recipe itself for a package *is* a list, is what it means. So it's not a list of packages or package recipes.

So to do something like `straight-use-package` over a list of package names, I believe you can just do something like:

``` elisp
(mapc #'straight-use-package '(evil company))
```

**Comment by raxod502** [comment]
@OrionRandD Right after the sentence you quoted, the documentation goes on to explain exactly what a "recipe" is, and gives numerous examples. Could you suggest what might make the situation more clear?

**Comment by OrionRandD** [comment]
Thx for the suggestion.
I will try it.
:)

**Comment by OrionRandD** [comment]
@vyp that worked. Thx.
Now. How do I bind these keys in telega, using these config:

(straight-use-package 'telega)
       (add-to-list 'load-path "~/.emacs.d/straight/repos/telega.el")  

 :bind 
     ;;   (:map telega-msg-button-map
     ;;  ("j" . nil)
     ;;  ("k" . nil)
     ;;  ("h" . nil)
     ;;  ("l" . nil))
     ;;   :custom (telega-use-notifications t))

**Comment by OrionRandD** [comment]
https://github.com/zevlg/telega.el/blob/master/README.md

**Comment by vyp** [comment]
That looks like it's supposed to be in a use-package form, here's how you could do it:

``` elisp
(setq straight-enable-use-package-integration t
      straight-use-package-by-default t
      use-package-always-defer t)

(straight-use-package 'use-package)

(use-package telega
  :bind (:map telega-msg-button-map
              ("j" . nil)
              ("k" . nil)
              ("h" . nil)
              ("l" . nil))
  :custom
  (telega-use-notifications t))
```

You shouldn't need to `(add-to-list 'load-path "~/.emacs.d/straight/repos/telega.el")` since straight.el should do that for you.

**Comment by OrionRandD** [comment]
On Mon, Nov 11, 2019 at 04:43:43PM -0800, vyp wrote:


Thx,
I had written 
the instructions like this
before and it worked.
The only difference between what you showed 
me was the keyword

:straight t

that I wrote

:)

 ----------------

(use-package telega
 :straight t
 :bind 
 (:map telega-msg-button-map
   ("j" . nil)
   ("k" . nil)
   ("h" . nil)
   ("l" . nil))
  :custom
   (telega-notifications-mode t))

 ----------------

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)
