### ISSUE TITLE
Add command that rebuilds package in default-directory

### ISSUE THREAD

**Issue by brotzeit** [raxod502/straight.el#435]
It would be nice to have a command similiar to `straight-rebuild-package`, but that checks which package you are currently visiting without asking the user. It would also be good if the command checks if there are buffers that need saving. Something similiar to `save-some-buffers`, but ideally only buffers are considered that are visiting files of the current project(not all buffers).

I couldn't find a command or issue like this in straight.el.

**Comment by raxod502** [comment]
Seems like a reasonable feature, but just so we're all on the same page, in what case would you prefer to use this command rather than just `M-x eval-buffer` or restarting Emacs (in which case the package should be rebuilt automatically)?

**Comment by brotzeit** [comment]
Usually I try to run `magit-status` which checks if there are unsaved buffers because I often make changes that touch multiple files and then `eval-buffer` is not enough. When I add a feature I test it in a second emacs session because I often need to change my init.el in order to test the feature and it's annoying to fix my config(when I accidentally break it while I'm testing) without a working config.

**Comment by raxod502** [comment]
Yes, but why not just start a new Emacs session, then? The package will be rebuilt automatically, there is no need to do it manually with `M-x straight-rebuild-package`. In fact, I have [a keybinding just for doing this](https://github.com/raxod502/radian/blob/5fee7937e94d9567441d3332cec9be83dcb41c38/emacs/radian.el#L5102).

**Comment by brotzeit** [comment]
Looks like a good idea. IMO emacs should have a builtin command like this.

**Comment by andersjohansson** [comment]
A hacked together command that I sometimes use for this case. I wouldn’t say it’s guaranteed to do the right thing, and I can’t say that it’s based on a that solid understanding of how straight works.
```emacs-lisp
(defun aj/straight-rebuild-this-package (&optional recursive)
  "Rebuild package in current dir. Prefix argument for recursive"
  (interactive "P")
  (if-let ((m (string-match (concat "^"
                                    (regexp-opt (list
                                                 (straight--repos-dir)
                                                 (straight--build-dir)))
                                    "\\(.+\\)$")
                            default-directory))
           (path (car (f-split (match-string 1 default-directory))))
           ;; reverse lookup from path to package name 🙂
           ;; if repo to package is one to many (the case for some packages I believe)
           ;; this will choose one of the packages, no guarantees about which:
           (package (alist-get path 
                               (cl-loop for package being the hash-keys of straight--recipe-cache
                                        using (hash-values recipe)
                                        collect
                                        (cons (plist-get recipe :local-repo) package))
                               nil nil #'string=)))
      
      (straight-rebuild-package package recursive)
    (call-interactively #'straight-rebuild-package)))
```

**Comment by raxod502** [comment]
For that command I would suggest mapping `straight-rebuild-package` over _all_ the packages built from the current local repository. One thing that `straight.el` could use better support for is rebuilding multiple packages without building mutual dependencies more than once, but this feature request should go in a separate issue.

**Comment by andersjohansson** [comment]
Yeah, maybe that’s a bit saner. Something like:
```emacs-lisp
(defun aj/straight-rebuild-this-package (&optional recursive)
  "Rebuild package in current dir. Prefix argument for recursive"
  (interactive "P")
  (if-let ((m (string-match (concat "^"
                                    (regexp-opt (list
                                                 (straight--repos-dir)
                                                 (straight--build-dir)))
                                    "\\(.+\\)$")
                            default-directory))
           (path (car (f-split (match-string 1 default-directory))))
           ;; reverse lookup from path to package names 🙂:
           (packages (cl-loop for package being the hash-keys of straight--recipe-cache
                              using (hash-values recipe)
                              if (string= path (plist-get recipe :local-repo))
                              collect package)))
      (cl-loop for p in packages do
               (straight-rebuild-package p recursive))
    (call-interactively #'straight-rebuild-package)))
```

**Comment by progfolio** [comment]
This seems to work as well:

```emacs-lisp
(defun straight-rebuild-repo (&optional recursive)
  "Rebuild packages of repo associated with `default-directory'.
RECUSRIVE is passed to `straight-rebuild-package'."
  (interactive "P")
  (straight-rebuild-package
   (or (straight--determine-repo default-directory)
       (user-error "No repo associated with default-directory."))
   recursive))
```

**Comment by progfolio** [comment]
> Yes, but why not just start a new Emacs session, then? The package will be rebuilt automatically, there is no need to do it manually with M-x straight-rebuild-package. In fact, I have a keybinding just for doing this.

I agree this is the best way to deal with rebuilds. My workflow is usually to develop in one instance, and then start a fresh Emacs instance which will rebuild the package without affecting the instance I'm editing the source in.

Considering the availability of methods to deal with this and the lack of demand, I'm closing this issue.
If anyone feels this is incorrect, please comment and we can reopen.
