### ISSUE TITLE
Empty build directories

### ISSUE THREAD

**Issue by nuance** [raxod502/straight.el#436]
## What's wrong

I can't run the bootstrap / use-package. Adding additional `use-package` calls to an existing config seems to generate empty `build` directories.

## Directions to reproduce

Pointing emacs at an empty directory (~/test-emacs), I've repro'ed the same thing with an empty .emacs.d but this was easier for debugging / testing.

```
(setq user-emacs-directory "~/test-emacs")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

(use-package el-patch
  :straight t)
```

```
$ emacs --batch --load init.el 
Bootstrapping straight.el...
Bootstrapping straight.el...done
Building straight...
Building straight...done
Looking for use-package recipe → Cloning melpa...
Looking for use-package recipe → Cloning melpa...done
Cloning use-package...
Cloning use-package...done
Building use-package...
Building use-package...done
Symbol’s function definition is void: use-package
```

`$ tree ~/test-emacs`
[tree.txt](https://github.com/raxod502/straight.el/files/3870153/tree.txt)

### Version information

* Emacs version: GNU Emacs 26.3 (build 1, x86_64-apple-darwin17.7.0, NS appkit-1561.60 Version 10.13.6 (Build 17G65))
* Operating system: macOS 10.15.1

**Comment by raxod502** [comment]
I can't reproduce this issue. My steps were `docker run -it --rm silex/emacs:26.3 bash` to get a shell, then `apt update && apt install -y git`, then putting the code you provided into an `init.el` file in the current directory and running `emacs --batch --load init.el` as you suggested. Is there something else I might be missing?

**Comment by mhj-hawkfish** [comment]
I'd believe this is an issue with my local machine, but I can't seem to figure out what might be going on. Is there a way to turn on more verbose logging or tracing that I'm missing?

**Comment by nuance** [comment]
I'd believe this is an issue with my local machine, but I can't seem to find any failures or errors anywhere. Do you have any suggestions on ways to turn on verbose logging or tracing or similar?

**Comment by nuance** [comment]
(similarly, I see the same issue without batch mode / with the file in ~/.emacs.d)

**Comment by nuance** [comment]
I figured out the problem, and I'm not sure if this is a bug in straight or use-package:

- I ran emacs using `strace` / `dtruss` and grepped around in the resulting sys call log to see anything suspicious. I specifically looked for places that touched the build directory. I noticed it was stat'ing a binary called `/Users/mhj/bin/cmd`, which seemed a little odd.
- It looks like the binary was a test script I had created recently (no idea why I named it that)
- I deleted that binary and use-package now works.

I guess the question is - what's looking for a `cmd` binary? Is this some well-intentioned windows compatibility code (eg cmd.exe or something?)?

**Comment by nuance** [comment]
It looks like this is the same issue as https://github.com/hlissner/doom-emacs/issues/1715

**Comment by raxod502** [comment]
The problem is then already fixed. Since several people have run into the issue, I've backported the fix to `master`, so you should see an improvement immediately :)

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)
