### ISSUE TITLE
changes to straight-format-timestamp lead to failed find command on start

### ISSUE THREAD

**Issue by cwhatley** [raxod502/straight.el#442]
## What's wrong

Recent commit breaks on OSX.  See 

https://github.com/raxod502/straight.el/commit/dce8208f5d9d95127f0a47ff39d5a98eac1cfc7b

Contents of `*straight-process*`:

```
$ cd /
$ find /dev/null -newermt 2018-01-01\ 12\:00\:00

/dev/null

[Return code: 0]

$ cd /Users/cwhatley/.emacs.d/straight/repos/melpa/
$ find . -name .git -prune -o -newermt 2019-12-05\ 18\:54\:12.656686 -print

find: Can't parse date/time: 2019-12-05 18:54:12.656686

[Return code: 1]
```

## Directions to reproduce

Run with straight.el off develop branch.

### Version information

* Emacs version: 27.0.50 built from head on 12/3/2019
* Operating system: MacOS 10.15.2 beta

**Comment by asf-stripe** [comment]
I've run into the same issue. I thought you could work around it for now by using this adjusted find-flavor determining function:

```elisp
(defun asf--straight--determine-find-flavor ()
  "Determine the best default value of `straight-find-flavor'.
This uses -newermt if possible, and -newer otherwise."
  (if (straight--check-call
       "find" "/dev/null" "-newermt" "2018-01-01 12:00:00.000000")
      `(newermt)
    nil))
(setq straight-find-flavor '(asf--straight--determine-find-flavor))
```

But unfortunately, straight then switches to `touch`, but using a GNU fileutils option, `-d`.

`brew install findutils` and overriding the PATH to pick up that gnu find worked, though: 

```elisp
;;; Use GNU find for https://github.com/raxod502/straight.el/issues/442:
(push "/usr/local/opt/findutils/libexec/gnubin" exec-path)
(setenv "PATH" "/usr/local/opt/findutils/libexec/gnubin:/usr/bin:/bin:/usr/local/bin")
```

**Comment by raxod502** [comment]
Is there any syntax for specifying milliseconds on the BSD find? If not I'm going to be pretty sad. (In that case I'll just round up to the next second for the timestamps we save in the build cache.)

**Comment by asf-stripe** [comment]
I believe neither `find` nor `touch` support millisecond timestamps: I couldn't find any docs on the time format in the `find` manpage, but `touch`'s has this:

     -t      Change the access and modification times to the specified time
             instead of the current time of day.  The argument is of the form
             ``[[CC]YY]MMDDhhmm[.SS]'' where each pair of letters represents
             the following:

                   CC      The first two digits of the year (the century).
                   YY      The second two digits of the year.  If ``YY'' is
                           specified, but ``CC'' is not, a value for ``YY''
                           between 69 and 99 results in a ``CC'' value of 19.
                           Otherwise, a ``CC'' value of 20 is used.
                   MM      The month of the year, from 01 to 12.
                   DD      the day of the month, from 01 to 31.
                   hh      The hour of the day, from 00 to 23.
                   mm      The minute of the hour, from 00 to 59.
                   SS      The second of the minute, from 00 to 61.

**Comment by eamonnsullivan** [comment]
As mentioned by @asf-stripe, the workaround for now is to install the GNU find (`brew install findutils`) and make sure it is first in the path:
`export PATH=/usr/local/opt/findutils/libexec/gnubin:$PATH`

**Comment by cwhatley** [comment]
I certainly would welcome a solution to this that doesn't involve that.

**Comment by raxod502** [comment]
Okay, should be fixed now.

**Comment by cwhatley** [comment]
Worked for me. Thanks.
