### ISSUE TITLE
Using 'ssh for straight-vc-git-default-protocol raises an odd error

### ISSUE THREAD

**Issue by ndw** [raxod502/straight.el#449]
I don't believe this is actually an error in `straight.el` but I encountered it as a consequence so I'm wondering if you've already seen the answer. Feel free to simply close this without comment if the answer isn't obvious.

Per our earlier discussion (#441), I switched to using `ssh` as the default protocol for git. That allowed me to get packages from my non-github private repo.

In the course of exploring a broader re-write of my Emacs init file (what else are holidays for?), I had occasion to "start over" in a clean home directory. During the bootstrap process, straight.el comes to a github repo it wants to clone and falls over.

```
Cloning into '/Users/ndw/testhome/.emacs.d/straight/repos/git-timemachine'...
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.
```

I'm running on MacOS and there's no `/usr/X11R6/bin/ssh-askpass` in sight. There is `/usr/local/bin/pinentry-mac` which I imagine would do the trick. So I go looking for where the X11R6 reference occurs. I expect to find a variable I can set to the correct pinentry program and all will be well.

1. It's not in straight.el
2. It's not under ~/.emacs.d
3. It's not AFAICT *in any of the lisp files* in `/Applications/Emacs.app/Contents/Resources/lisp` (and yes, I did unzip them before grepping 😄 )
4. And just FYI, I did start Emacs from the command line and the environment does seem to have the ssh-agent settings, but apparently it still wanted to ask.

I nudged the system to make sure it hadn't simply timed out, but no, ssh and friends were happy to go along with the agent values without asking me to refresh my password.

The workaround was simply to change the default protocol back to `https`, run the initial bootstrap, and then change it back to `ssh`. That'll be fine until the next time it tries to clone a new package, I guess, but hopefully I'll remember what to do.

Anyway, I'm just wondering if my ignorance is showing?

**Comment by raxod502** [comment]
See #334. You should be able to work around the problem more easily by configuring `ssh-agent` and then running `ssh-add` in a terminal to get your passphrase cached. I've tried a couple of times to solve the issue, but I keep running into weirdness and race conditions in trying to handle process filters synchronously.

**Comment by raxod502** [comment]
Alternatively, I believe you should be able to install an `ssh-askpass` program and it will prompt you graphically. The problem is that `straight.el` doesn't currently know how to attach a tty to the processes it starts, like Magit does.

**Comment by ndw** [comment]
I have `ssh-agent` running and point 4 in my initial report was an attempt to demonstrate that I've started Emacs with an environment that includes the relevant environment variables. I can see if the brew version of ssh-askpass will work graphically.

**Comment by ndw** [comment]
I have `ssh-agent` running and point 4 in my initial report was an attempt to demonstrate that I've started Emacs with an environment that includes the relevant environment variables. I can see if the brew version of ssh-askpass will work graphically.

(Nope. Maybe if I could change /usr/X11R6/bin/... somewhere...)

**Comment by raxod502** [comment]
On Linux, I can install an ssh-askpass program and then export the `SSH_ASKPASS` variable to point at the full path of the executable, and then I get prompted graphically. That said, the _usual_ way to work around this problem is by configuring ssh-agent correctly. I do not know what might be going wrong for it on your system. If you have the agent working from the command line, I assume you have `AddKeysToAgent yes` in your `~/.ssh/config` already. Do the relevant variables show up from inside of Emacs using `M-x getenv`?

```
SSH_AGENT_PID=1354
SSH_AUTH_SOCK=/tmp/ssh-YfpfmKRyaOOj/agent.1352
```

Perhaps you have some package like `exec-path-from-shell` which is messing with your environment. Alternatively, sometimes upgrades and such can mess up the agent state, in which case restarting might help. You could also check to see what arguments `ssh-agent` is being started with. Maybe it's something you don't expect. I personally use `ssh-agent -t 86400` in my shell init.

**Comment by ndw** [comment]
Ok. Thanks for the suggestions; it's clearly not a straight.el problem, but I appreciate the advice.

**Comment by raxod502** [comment]
Well, it definitely is a `straight.el` problem in the sense that #334 needs to be solved, but yeah the environmental stuff I can't do much about here.

**Comment by ndw** [comment]
FYI: I found an easy workaround. If I add a new package, I start emacs in a shell without a window manager:

```
/Applications/Emacs.app/Contents/MacOS/Emacs -nw
```

And *then* it uses ssh-agent and ssh works fine. I don't know why `-nw` is different in this case, but it is.
