### ISSUE TITLE
Way to support checkout tag and commit

### ISSUE THREAD

**Issue by vuquangtam** [raxod502/straight.el#452]
I've just switch to straight recently and wonder if straight has support checkout when package is cloned (checkout before package is loaded) or not ? I saw it has :branch options but seem like it doesn't support tag and commit. I've used el-get before and it has supported something like 
```
(el-get org :url "https://xxxxxxxx" :checkout "release_9.1.14")
```

**Comment by raxod502** [comment]
Not currently supported, but see #31. Also, you can work around the problem by simply checking out the release manually after clone, and then writing a lockfile with `M-x straight-freeze-versions`. Then the same revision will be checked out on all future clones, until you update the lockfile.
