### ISSUE TITLE
magit-commit will abort all recursive edits

### ISSUE THREAD

**Issue by CeleritasCelery** [raxod502/straight.el#453]
## What's wrong

This is continuation of https://github.com/raxod502/straight.el/issues/223#issuecomment-496717424 . I took some time to track down the problem. When straight enters a recursive edit due to an issues in the repo (something is not staged, etc) one of the options to edit with magit. `magit-commit` uses `with-editor` which relies on `server-process-filter`. That function will call `server-goto-toplevel` which will call `top-level`. The [top-level](https://www.gnu.org/software/emacs/manual/html_node/elisp/Recursive-Editing.html) function will exit out of **all** recursive edits. This means that you loose your straight recursive edit level any time you try to commit with magit. Unfortunately I don't see a way around this since being able to commit is pretty essential to managing git repos. The only real solution I can think of is to advise `server-goto-toplevel` to prevent it from calling `top-level`. 

## Directions to reproduce

1. Make some changes in a straight repo
2. run `straight-pull-package` and pull the modified package
3. when the popup is displayed, chose magit (`g`)
4. stage the changes and commit them.
5. Try to resume the recursive edit with `C-M-c`

### Version information

* Emacs version: 26.3
* Operating system: SUSE Linux

**Comment by raxod502** [comment]
Thanks for tracking down the bug, that's very helpful. I think advising `server-goto-toplevel` is a perfectly fine solution, since getting this fixed in Emacs core will be very time-consuming.
