### ISSUE TITLE
Track master or develop?

### ISSUE THREAD

**Issue by CeleritasCelery** [raxod502/straight.el#454]
I am not sure the relationship between `master` and `develop`. I see that some commits (like the recipe inheritance 8c209c90c980af64db8c3a7528da2b89e751fad2) are only in `develop` but others like a5cc868291ed4f883e135373d9bf9d941e65d918 are only in `master`. The melpa recipe is tracking the master branch but your repo has `develop` as the default. Which one are you expecting users to track?

**Comment by raxod502** [comment]
`master` is stable, `develop` has the latest commits. The idea is that you can choose between stability or the latest features. Occasionally `develop` is merged into `master`. However, to increase stability of `master`, bugfix commits from `develop` are also cherry-picked onto `master`. All commits appear on `develop`, although not necessarily with the same hashes.
