### ISSUE TITLE
Require 'om fails

### ISSUE THREAD

**Issue by ndw** [raxod502/straight.el#462]
This is possibly related to #451 but I can't tell. It's also possibly user error.

## What's wrong

A package that uses `defconst` inside `eval-when-compile` seems not to be loaded
correctly.

## Directions to reproduce

I load `om` with:

```
(straight-use-package
 '(om :type git :host github :repo "ndwarshuis/om.el"))
```

If, after straight has downloaded and compiled `om`, I restart Emacs and `(require 'om)`, I get:

```
Debugger entered--Lisp error: (void-variable om-elements)
  (-intersection om-branch-nodes-permitting-child-objects om-elements)
  (defconst om-branch-elements-permitting-child-objects (-intersection om-branch-nodes-permitting-child-objects om-elements) ("/Users/ndw/.emacs.d/straight/build/om/om.elc" . 741))
  require(om)
  eval((require (quote om)) nil)
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp(nil)
  funcall-interactively(eval-print-last-sexp nil)
  call-interactively(eval-print-last-sexp nil nil)
  command-execute(eval-print-last-sexp)
```

### Version information

* Emacs version: 26.3
* Operating system: MacOS

**Comment by raxod502** [comment]
That is a bug in the package as far as I can tell. It should not be using `eval-when-compile` for that code. When I run `make compile` from the package's Makefile, then manually evaluate the resulting `.elc` files, I get the same error. Given that, I don't think the problem lies with `straight.el`.

**Comment by ndw** [comment]
Right. Sorry to bother you. I'll report that upstream.

**Comment by raxod502** [comment]
No problem. I know it is hard to tell where the issue lies when something goes wrong in a complex system. For what it's worth, you can easily work around the problem by including `:no-byte-compile t` in your recipe :)
