### ISSUE TITLE
Straight.el and load-path

### ISSUE THREAD

**Issue by rileyrg** [raxod502/straight.el#465]
I always like to have the ability to ensure MY versions of something are picked up first. 

So I stick my elisp directory (and some host-specific ones) at the start of load-path.

Yes, I could branch the local repos etc but that seems too much effort for a simple "use this instead" case.

The "problem" (and I say this hesitantly) is that straight.el updates the load path pushing its repo paths to the front of the load-path as each use-package or direct "straight-use-package" is called.
 
Can this be altered so that it adds at the end? Maybe there is already a use-package flag? I really can see the need for me to want a certain (require 'X) to load from my elisp directory despite it being in the straight.el repos.

Not high priority or anything, and more casual enquiry.

**Comment by raxod502** [comment]
* Why do you need this feature?
* Can you accomplish it by simply adding your directory to the `load-path` _after_ invoking `straight.el`?

**Comment by rileyrg** [comment]
Hmm. I'd hoped I'd explained why. So that I can add a path to the front of
load-path after bootstrap so any use-package uses my locally cloned
versions and not the straight/repos version. But now I'm thinking, and I'll
check tomorrow, I might have jumped the gun. The resulting path after
processing my load file has the repos paths ahead of mine because I hadn't
installed my own copies when I was tinkering so the repos ones were adding
their paths.

So... I shall check and get back to you.

And if so, I'll shut up and close.

**Comment by raxod502** [comment]
By "why do you need this feature" I mean "why do you need your own version of a package to override the one provided by `straight.el`". There likely exists a better solution that leverages `straight.el` rather than working around it.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
