### ISSUE TITLE
[Meta] Use master as default branch on github

### ISSUE THREAD

**Issue by paulbdavis** [raxod502/straight.el#467]
When setting up, I was trying to get the inheritance to work, only to discover that the docs presented by default are on the develop branch. 

If the default branch for github matches what would be installed by the docs, this confusion would not happen.

**Comment by raxod502** [comment]
I originally did that because people kept opening pull requests against master instead of develop, but it is a better solution to just add a pull request template with the instructions for that. Thanks for pointing out the issue. It should be fixed now.
