### ISSUE TITLE
Code for reproducible bug reports

### ISSUE THREAD

**Issue by ThibautVerron** [raxod502/straight.el#471]
Hi,

As discussed on https://github.com/raxod502/straight.el/issues/470, moving `.emacs.d` around to create bug reports is not really easy. There are way arounds, but it should be possible to offer some code so that users do not have to figure them out themselves.

I would imagine something like this:

```
(setq user-emacs-directory (make-temp-file ".emacs-" t))

(message "Starting emacs in the temporary directory %s" user-emacs-directory)

(setq straight-repository-branch "develop")
;; Insert other necessary straight settings here

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el"
	       user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; Insert other necessary code here

```

It can then be called with `emacs -q -l <file>.el`, and should be equivalent to starting emacs in an empty `.emacs.d` (but a temporary folder instead).

**Comment by progfolio** [comment]
I think #574 takes care of this for now. Closing this issue.
