### ISSUE TITLE
RFI: Setting straight-vc-git-default-protocol  and straight-vc-git-force-protocol

### ISSUE THREAD

**Issue by rileyrg** [raxod502/straight.el#472]
I set straight.el up to use ssh after I did my first fork and realised I was getting password prompts. I had ssh setup for github from before so better use it:

> straight-vc-git-default-protocol is a variable defined in ‘straight.el’.
> Its value is ‘ssh’
> Original value was ‘https’

Reading the docs I also set straight-vc-git-force-protocol to 't and then executed  

> straight-normalize-all

I was then prompted to deal with the remote url protocol change. Which I did: d,y for each repo.

Q1) Is there a way to "remember" in such batch updates so I don't need to manually select for each repo change? Not important as this was a one off.

and, more importantly,

Q2) why are only some of my repo's .git/config remote URLs updated to git@github? many of them are still https. What am I missing? eg company-box (github - I checked ;)) is still https. 

Many thanks. This is my first use of the straight.el recipe formula and the builtin "fork" ingredient. Very nice indeed.

**Comment by raxod502** [comment]
> Is there a way to "remember" in such batch updates

No, but I'd love that. Want to open an issue requesting such?

> why are only some of my repo's .git/config remote URLs updated to git@github?

I have no idea. Sounds like a bug but I'd need a way to reproduce it to check.

**Comment by rileyrg** [comment]
To reproduce simply change the default protocol to git (or toggle it I guess) and enable the force flag.

(I've had awful issues since then. I'm currently on a somewhat dodgy 3g "wifi hub" in a remote location and the straight pull falls over regularly unable to complete git operations : until I'm back in civilisation I can't really comment more but it does seem git on my debian system could be a bit more robust and tolerant in the timeout stakes)

**Comment by raxod502** [comment]
I don't believe this happens to me. It resets all repositories correctly. If you can provide instructions for reproducing from empty `~/.emacs.d`, I can check it out.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
