### ISSUE TITLE
watcher not working

### ISSUE THREAD

**Issue by aaronjensen** [raxod502/straight.el#475]
## What's wrong

The watcher does not appear to work. Nothing gets written to straight/modified/ and things do not appear to rebuild when they should.

## Directions to reproduce

I can reproduce it here and it's likely something specific to my machine or setup. Are there any debug steps I can do on my end to help narrow down the issue? 

### Version information

* Emacs version: 27
* Operating system: macOS 10.15.3

**Comment by aaronjensen** [comment]
Ah, this may be the issue: 

```
*** Ignoring "/Users/aaronjensen/.emacs.d/straight/repos/straight.el/straight.el": matched gitignore file
```

I have this in my `.gitignore`:

```
/straight/
```

You don't have this issue because it looks like you symlink your emacs config into `.emacs.d`, which seems like a good idea given how much trouble it is to ensure things don't litter. That said, I wonder why others don't have this issue?  Should you use `--no-vcs-ignore` with `watchexec`?

**Comment by raxod502** [comment]
It sounds like a bug for watchexec to pay attention to a `.gitignore` that is outside of the current Git repository. But, whatever.

**Comment by raxod502** [comment]
Thanks for the report.

**Comment by aaronjensen** [comment]
No problem, thanks for the quick fix.

I don't believe it's outside of the current git repository, since it's watching `~/.emacs.d/straight/repos`. Unless you mean that it should be checking the `.gitignore` of every nested repo, which I could see an argument for, but I could also see the complication that that would introduce.

**Comment by raxod502** [comment]
You are correct. I forgot that the working directory of the watcher was `repos` instead of a specific local repository. This is definitely not the fault of watchexec.
