### ISSUE TITLE
Regression prevents straight from resolving dependencies

### ISSUE THREAD

**Issue by hlissner** [raxod502/straight.el#476]
## What's wrong

Straight fails to resolve (and thus, install) dependencies due to https://github.com/raxod502/straight.el/commit/260b388a96bb20af430e2935c92529a8bbde14cc. This new regexp leaves the cursor on the ~~colon~~ whitespace just after the colon in the `Package-Requires:` header. The old regexp would place the cursor directly on the opening parentheses of the package list (assuming the header is well-formed).

Then `(looking-at "(")` returns nil, and no dependencies are computed.

The following works around it:

```diff
                  (let ((case-fold-search t))
                    (re-search-forward "^;; *Package-Requires *:"))
-                 (when (looking-at "(")
+                 (when (looking-at " *(")
                    (straight--process-dependencies
                     (read (current-buffer)))))))))
```

Relevant to: https://github.com/hlissner/doom-emacs/issues/2517

EDIT: Corrected my diagnosis.

### Version information

* Emacs version: 26.3 (on Doom Emacs)
* Operating system: NixOS

**Comment by raxod502** [comment]
This should be fixed by https://github.com/raxod502/straight.el/commit/370059b2769a8100a03339a7ef245025ba55f6ea. I am very sorry for the inconvenience.

**Comment by hlissner** [comment]
No worries! I can confirm that the fix resolves this. Thanks for the prompt response (and for this fantastic package!)
