### ISSUE TITLE
Unrecognized keyword: :straight 

### ISSUE THREAD

**Issue by Linuus** [raxod502/straight.el#479]
When I have an init.el file like this:

```elisp
(let ((gc-cons-threshold most-positive-fixnum))

  (defvar bootstrap-version)
  (let ((bootstrap-file
        (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
          "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
          'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)

  (setq-default load-prefer-newer t)
  (setq-default straight-use-package-by-default t)
  (setq-default
   use-package-always-defer t
   use-package-verbose t)

  (setq byte-compile-warnings '(not free-vars unresolved noruntime lexical make-local))

  (straight-use-package 'org-plus-contrib)
  (use-package org
    :straight org-plus-contrib)

  ;; Tangle configuration
  (org-babel-load-file (expand-file-name "emacs.org" user-emacs-directory))

  (garbage-collect))
```

I get the error:

```
Error (use-package): Failed to parse package org: use-package: Unrecognized keyword: :straight
```

It used to work, I think, but then suddenly I got this error 🤔 Not sure what I might have messed up...

Any ideas?

**Comment by raxod502** [comment]
Are you byte-compiling your init-file? If so, you can't use a macro in the same top-level form that you define it. Try putting the body of the `let` inside another file that is loaded from your init-file, and byte-compile it separately.

**Comment by Linuus** [comment]
I’m not. That’s all there is that I’ve shown above :) I removed the org-babel line and it’s the same.

**Comment by raxod502** [comment]
I removed the org-babel line and put your code in an empty `~/.emacs.d`. I don't get that error. Can you see if you can reproduce the problem without the rest of your configuration?

**Comment by Linuus** [comment]
I found the issue... Apparently there was a lingering `elpa` directory in my `.emacs.d` directory which seems to have been loaded. It probably caused some funky stuff to happen.

Works fine now it seems.

Thanks for straight.el btw. It's great 👍
