### ISSUE TITLE
Add way to jump to straight-use-package usage

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#48]

**Comment by Fuco1** [comment]
Also nice would be to jump to the cloned repository so I can start hacking on it.

Could be as simple as

```elisp
(let ((default-directory (straight--repos-dir)))
  (call-interactively 'find-file))
```

**Comment by raxod502** [comment]
I do not think this feature (the one in the issue title) is a good idea, as navigating within your Emacs configuration is probably best done with a text-search package such as [CTRLF](https://github.com/raxod502/ctrlf). Trying to special-case all the weird things people put in their configurations is a road to madness.
