### ISSUE TITLE
Cannot determine Magit’s version

### ISSUE THREAD

**Issue by taigacute** [raxod502/straight.el#480]
## What's wrong

@raxod502 , thanks for your great work. I used straight to install magit. then open emacs. i got an error.
```
Cannot determine Magit’s version (error "/Users/stephen/.config/emacs/straight/repos/magit/lisp/magit.el" repo t static elpa dirname)
```
![image](https://user-images.githubusercontent.com/41671631/74625954-0ab19100-5189-11ea-96a5-1ff8024d1477.png)

## Directions to reproduce

I can reproduce with this min init.el
```elisp
(setq straight-recipes-gnu-elpa-use-mirror    t
      straight-repository-branch              "develop"
      straight-vc-git-default-clone-depth     1
      straight-enable-use-package-integration nil
      straight-check-for-modifications        '(find-when-checking))

(defvar bootstrap-version)

(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

(require 'use-package)

(straight-use-package 'magit)

(use-package magit)

```

### Version information

* Emacs version:   28.0.50
* Operating system: Mac os catalina 15.10.3

**Comment by raxod502** [comment]
You configured `straight.el` to use shallow clones, but Magit is unable to determine its version in a shallow clone according to the source code:

```elisp
        ;; The repository is a sparse clone.
        (message "Cannot determine Magit's version %S" debug)))
```

I don't think there's anything that `straight.el` can do about this.

**Comment by raxod502** [comment]
This is unrelated, but I noticed that your setting of `straight-check-for-modifications` will result in package modifications never being detected automatically. So you will have to manually run `M-x straight-rebuild-package` when you modify package code. Was that intentional?

**Comment by taigacute** [comment]
@raxod502  thanks for your reply. this is a minial config for test magit verison error. this is my straight settings on my config
```
;;; straight
(setq straight-base-dir galaxy-local-dir
      straight-repository-branch "develop"
      straight-cache-autoloads nil
      straight-check-for-modifications nil
      straight-enable-package-integration nil
      straight-vc-git-default-clone-depth 1
      autoload-compute-prefixes nil)
```

**Comment by taigacute** [comment]
by the way i used this advice solved this issue 
```elisp
  (advice-add #'magit-version :override #'ignore)
```

**Comment by raxod502** [comment]
> this is my straight settings on my config

Those settings also disable modification detection entirely. If that's your goal, then there's nothing wrong with it. I just wanted to make you aware of it, since that is not a common configuration and might be surprising if you did not intend it.

> should be close this issue?

Sure. I would also suggest reporting an issue against Magit upstream about the fact that byte-compiling Magit in a shallow clone prints a warning message, which violates the convention of byte-compilation having no side effects other than defining functions and variables.

**Comment by raxod502** [comment]
Sorry, rather than "byte-compilation" I meant "loading a package" above.
