### ISSUE TITLE
Add way to prune unused repositories

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#49]
Over time, you can accrue a large number of unused Git repositories that were cloned at various points but are no longer used. I don't want to prune these (they might contain useful development history), but some people who don't modify their Emacs packages might.

**Comment by s-kostyaev** [comment]
This should be customizable. I don't want re-clone some big repos what was removed silently. Indeed automatic clearing is good thing when it's customizable.

**Comment by raxod502** [comment]
Certainly. I don't want this to be automatic under any circumstances. It would be an interactive function you could call, which would make sure to ask you individually for each repository.

Does this mean there are actually people other than me using this package manager?? :o

**Comment by s-kostyaev** [comment]
> Does this mean there are actually people other than me using this package manager?? 

Not yet. But I observe this project development and maybe try to use it later.

**Comment by raxod502** [comment]
Excellent. I really hope I can make a 1.0 release sometime this summer, although I can't guarantee it.

**Comment by thiagowfx** [comment]
> Does this mean there are actually people other than me using this package manager??

So far, so good! I just started to use it.

**Comment by casouri** [comment]
Is there any progress on this? Sometimes an ample disk space is not available. I want to be able to automatically remove unused repos that I didn't modify, and manually remove the unused repos that I modified.

**Comment by raxod502** [comment]
I don't have time to implement this fully right now, sorry. However, it is easy to hack together something that does the job; try this:

https://github.com/raxod502/straight.el/blob/ac00deb78a8d04e244f06e1b7f583ddc7f046cb9/straight-x.el#L132-L137

**Comment by progfolio** [comment]
> I don't have time to implement this fully right now,

I've been using `striaght-x-clean-unused-repos` successfully for some time now. Is there anything you feel is lacking design wise or any corner case we haven't considered here?
Seems like a simple enough command to move into straight.el proper.

**Comment by raxod502** [comment]
Hehe, yeah, that seems totally reasonable. Just rename the function (maybe adding a backwards compatibility alias in `straight-x.el` since it's been there for a few years), and add a docstring, I think!
