### ISSUE TITLE
Failed to load tramp due to (void-variable tramp-archive-file-name-regexp)

### ISSUE THREAD

**Issue by kurnevsky** [raxod502/straight.el#490]
When installing tramp via (use-package tramp :straight t) `straight.el` clones `https://github.com/emacsmirror/tramp.git` and it fails to load due to `(void-variable tramp-archive-file-name-regexp)`. This variable is defined inside `tramp-archive.el` but used inside `tramp.el` and `tramp.el` doesn't require `tramp-archive.el` explicitly, so I'm not sure that this is correct place to report it.

I encountered it when tried to specify `(setq straight-use-package-by-default t)` and my config had
```el
(setq use-package-always-ensure t)

(use-package tramp
  :custom
  (tramp-default-method "ssh"))
```

**Comment by raxod502** [comment]
Remove your setting of `use-package-always-ensure`. It is irrelevant to `straight.el` and will tell Emacs to use both `package.el` and `straight.el` to install the same package, which is almost certainly not what you want.

With that setting removed, I was unable to reproduce your problem. If you still get the problem, try pulling the latest version of TRAMP from Emacsmirror, or let me know if that doesn't work.

**Comment by kurnevsky** [comment]
I already removed it but it's still there, `use-package-always-ensure` doesn't affect it. Just try to write
```elisp
(use-package tramp
  :demand t
  :straight t)
```
Tramp will fail to load. I use emacs 26, probably that's the problem...

**Comment by raxod502** [comment]
With the following init-file

```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(straight-use-package 'tramp)
(require 'tramp)
```

running in Emacs 26, I do not experience the error you are describing.

> tramp is builtin and shouldn't be installed via straight.el

This is not entirely correct. Built-in packages are typically obsolete, so `straight.el` is intentionally designed to clone an external version if one is available. There are a few exceptions, for example GNU ELPA offers old backwards-compatibility versions of some built-in packages like `cl-lib`, so we disregard these.

**Comment by raxod502** [comment]
You probably need to update your packages.

**Comment by kurnevsky** [comment]
Yes, works now. It seems it was tramp issue. Sorry for the disturbance.

**Comment by cnnrro** [comment]
Hey there, just stumbled on this issue as I was having the same problem.

Using the init file you mentioned @raxod502, I'm still seeing the error.

@kurnevsky What ended up solving the problem for you?

**Comment by raxod502** [comment]
What I suggested was `M-x straight-pull-package RET tramp RET`. I do not know if that is what solved the issue, though.

**Comment by cnnrro** [comment]
That hasn't seemed to solve it for me. I'll keep trying, must be something to do with my environment if you're not able to reproduce the issue. Hopefully @kurnevsky can give some guidance.

**Comment by kurnevsky** [comment]
I just don't have this error anymore. Latest tramp checks if `tramp-archive-enabled` is defined before accessing `tramp-archive-file-name-regexp`. So you probably have it `t`?
