### ISSUE TITLE
Advice on installing mu4e

### ISSUE THREAD

**Issue by falloutphil** [raxod502/straight.el#491]
Hi,

The installation of mu4e fails, I'm guessing because its build requires C build of mu as well as installation the lisp for mu4e.  The build directory ends-up empty.  I get the following warning:
`Error (use-package): Cannot load mu4e`

Reading a few other posts this might be that the recipe is wrong?

I can install this package use `apt install` or build it manually using `make`, meaning the output is placed here (or the local directory equivalent if using `make`):

mu binary goes here - /usr/bin/mu
lisp goes here - /usr/share/emacs/site-lisp/mu4e
etc...

My question is can I make this package install under straight given it needs autogen/configure/make, and if not what is the best practice/least disruptive way to marry this with the rest of my straight setup using an external build?

For example this hack seems to work, but is ugly:
`cd /home/some_user/.emacs.d/straight/build/mu4e`
`ln -s /usr/share/emacs/site-lisp/mu4e/*.el  .`

Am I right that it's the underlying package straight is pulling in rather than a problem with straight itself which is the issue?

If it's not sensibly possible to fix the straight install of this package, should an exclusions list be maintained to prevent installation of known broken packages?

**Comment by raxod502** [comment]
This problem is because the authors of mu4e declined to publish the package to MELPA, _and_ they decided to be special and put the Lisp files in a weird subdirectory, so there does not exist any metadata which tells `straight.el` where to find the Lisp files.

Solution for you:

```elisp
(straight-use-package
 '(mu4e :files (:defaults "mu4e/*.el")))
```

To solve this problem in general, mu4e must be published to a package registry. After all, it isn't reasonable to expect a package manager to "just know" how to install a weird nonstandard package that hasn't been published anywhere.

Luckily, it seems that the el-get repository has mu4e (see [here](https://github.com/dimitri/el-get/blob/master/recipes/mu4e.rcp)), so by [adding support for el-get](#115), we'd solve this problem. This is the approach that I would recommend to contributors.

**Comment by falloutphil** [comment]
Thanks for response.  Totally agree that if packages are non-standard there is little a generic package manager can reasonably do.

Agreed that https://github.com/raxod502/straight.el/issues/115 looks like it will take care of autogen/make requirements.

For now the advice on https://github.com/raxod502/straight.el/issues/386 looks like a good starting point for me producing a basic custom build, or I could simply maintain the non emacs lisp components outside of straight.

The fix you've provided above, which I believe should at least install the emacs lisp correct by appending to the default patterns matches for files - I get an error generating the repo name.  I suspect I'm doing something dumb?

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("^.*/\\(.+\\)\\.git$" nil)
  straight-vc-git-local-repo-name((:files (:defaults "mu4e/*.el") :package "mu4e" :type git))
  apply(straight-vc-git-local-repo-name (:files (:defaults "mu4e/*.el") :package "mu4e" :type git))
  straight-vc(local-repo-name git (:files (:defaults "mu4e/*.el") :package "mu4e" :type git))
  straight-vc-local-repo-name((:files (:defaults "mu4e/*.el") :package "mu4e" :type git))
  straight--convert-recipe((mu4e :files (:defaults "mu4e/*.el")) nil)
  straight-use-package((mu4e :files (:defaults "mu4e/*.el")))
```

**Comment by raxod502** [comment]
You are expecting recipe inheritance (#116), but this feature is not in `master` yet. Either upgrade to `develop` (i.e. set `straight-repository-branch` to `"develop"` and run `straight-normalize-package`), or specify all the required keys:

```elisp
(straight-use-package '(mu4e :host github :repo "emacsmirror/mu4e"
                             :files (:defaults "mu4e/*.el")))
```

**Comment by progfolio** [comment]
I believe this is possibly related to #72 as well.

mu4e has elisp files which are generated during the `make` process.
e.g. https://github.com/djcb/mu/blob/master/mu4e/mu4e-meta.el.in

If they are not generated when the mu server is updated, the variables in the linked file will be outdated. This can be worked around by manually updating them, but it'd be nice if one could programatically detect the change and trigger a rebuild.

**Comment by raxod502** [comment]
I really wish package maintainers wouldn't do this. There's no good technical reason to require a build step, and it makes everything so complicated.

**Comment by progfolio** [comment]
I may have time to contribute a pull toward #72 soon. Do you have any ideas for an implementation? At first glance it would seem to involve adding a `:build` keyword to recipes which specifies the commands to be run in the package directory before installation.

**Comment by raxod502** [comment]
@progfolio That's great! For approach: I think it would be best if we did something that is compatible with the [el-get](https://github.com/dimitri/el-get) recipe format. They already have a whole interface worked out, and if we conform to it then we get to steal all of their recipes for very little effort. Stealing other people's good ideas: the `straight.el` way™. (It's what we did with MELPA.) el-get uses a `:build` key, plus some `:build/...` keys for system types. I kind of don't like that, because it makes automatic recipe transformations harder if the set of keys isn't fixed. Maybe we can refactor to just a `:build` key that can be either the commands to run or an alist mapping the system types to commands to run.

Now luckily el-get is WTFPL'd, so we don't have to be super careful about lifting bits of code to parse the recipe format. (I still have bad memories of [pbl](https://github.com/raxod502/pbl).) Although I doubt we want to copy very much wholesale.

I think it is fine to make build commands be synchronously run and to throw an error if they fail. If we start trying to allow build commands to fail, then we get into the awkward situation of having to deal with "was this package fully built? or did the build command fail? if the latter, how do we tell when we should try re-running the build command?" This forces your Emacs configuration to have a hard dependency on the build command, but in my view that's your problem because packages shouldn't be using this stuff if they want to be portable.

You could add a step to `straight--build-package`, maybe after dependency resolution but before autoload generation. Then put in some new subroutines, a la `straight-expand-files-directive`.

See also #115. And feel free to let me know if you have further questions.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)

**Comment by LoganBarnett** [comment]
I wound up here after chasing down a problem with `mu4e` after switching to `nixpkg`. Inspired by the workaround above, I have done this to get me onto my next Nix related error ;)

``` sh
# Remove the directory first or the path will be:
# ~/.emacs.d/.local/straight/build/mu4e/mu4e
rmdir ~/.emacs.d/.local/straight/build/mu4e || true
ln -snf ~/.nix-profile/share/emacs/site-lisp/mu4e \
    ~/.emacs.d/.local/straight/build/mu4e
```

As a Doom Emacs user I've transitively gotten a lot of mileage out of `straight.el`. Thanks for the hard work!

**Comment by raxod502** [comment]
> Remove the directory first or the path will be

You can pass the `-T` argument to `ln` to eliminate this behavior (`ln` will throw an error if the path exists already, instead of putting the target inside of it when it's a directory).

**Comment by raxod502** [comment]
> Thanks for the hard work!

Oh, and thank you! ^_^

**Comment by rileyrg** [comment]
Hi, Glad I found this was going crazy. So whats the current use-package form when using straight?

**Comment by progfolio** [comment]
Here's what I use. It builds mu in the mu repo and I ise that executable. You could alter the `:pre-build` commands to change the prefix during the `configure` script and/or run `make install`. In either case you need to point the `mu4e-mu-binary` to the `mu` executable. 

```emacs-lisp
(use-package mu4e :straight ( :host github :files ("mu4e/*") :repo "djcb/mu" :branch "master" :pre-build (("./autogen.sh") ("make"))) :commands (mu4e mu4e-update-index) :custom (mu4e-mu-binary (expand-file-name "mu/mu" (straight--repos-dir "mu")))
```

**Comment by rileyrg** [comment]
thanks. I'll give it a try. )

**Comment by rileyrg** [comment]
Error (use-package): mu4e/:catch: Cannot open load file: No such file or
directory, mu4e-meta
Error (use-package): mu4e-alert/:catch: Cannot open load file: No such file
or directory, mu4e-meta

Sigh. I give up. I'll just install from git into
usr/local/share/emacs/site-lisp and be done with it. Thanks anyway.

**Comment by progfolio** [comment]
Sorry, I should have checked: What version of straight.el are you using?
`M-x straight-version`?

**Comment by rileyrg** [comment]
Nicholas Vollmer writes:

> Sorry, I should have checked: What version of straight.el are you using?
> `M-x straight-version`?

,----
| prerelease (HEAD -> master, origin/master, origin/HEAD) 2d407bc 2020-12-20
| You can run the command ‘straight-version’ with M-x st-ve RET
`----

"self" bootstrapped from scratch.

I'd really like to be reliant just on straight rather than needing to
install mu4e from git I must admit.

**Comment by rileyrg** [comment]
I should add I can also install from Debian repos but, again, I prefer not
to.

**Comment by progfolio** [comment]
Ah, I see the issue. You're on the "master" branch. The features required to run the `:pre-build` commands are on the "develop" branch. There are a few options:

1. Update straight.el to track the "develop" branch. You should be able to use the recipe I provided earlier in that case. Bear in mind this is where development takes place, so you may encounter some bugs. You can always freeze the version of straight to help mitigate this.

2. Use straight.el to clone/install mu4e. Manually run the `:pre-build` commands in a shell in the mu repo. I did this while implementing the feature which allows running `:pre-build` commands from a recipe. The disadvantage being you'll have to repeat this process any time you update mu/mu4e.

3. Rely on your OS package manager. I did this before I used straight and, as you've expressed, I wasn't too keen on it- but it works so long as your satisfied with the version of mu the package manager provides. This may be the most painless if you do not have time for any of the previous options at the moment.

**Comment by rileyrg** [comment]
Or, as I've done, I can install mu4e from a git clone to
/usr/local/share/emacs/site-lisp and use use-package as normal with no
recipes. I'll do that for now as then I have latest mu.


Nicholas Vollmer writes:

> Ah, I see the issue. You're on the "master" branch. The features required to run the `:pre-build` commands are on the "develop" branch. There are a few options:
>
> 1. Update straight.el to track the "develop" branch. You should be able to use the recipe I provided earlier in that case. Bear in mind this is where development takes place, so you may encounter some bugs. You can always freeze the version of straight to help mitigate this.
>
> 2. Use straight.el to clone/install mu4e. Manually run the `:pre-build` commands in a shell in the mu repo. I did this while implementing the feature which allows running `:pre-build` commands from a recipe. The disadvantage being you'll have to repeat this process any time you update mu/mu4e.
>
> 3. Rely on your OS package manager. I did this before I used straight and, as you've expressed, I wasn't too keen on it- but it works so long as your satisfied with the version of mu the package manager provides. This may be the most painless if you do not have time for any of the previous options at the moment.

**Comment by rileyrg** [comment]
Changed my mind and put the full recipe back in and manually did the autogen inside straight repos. All good now.  And it seems s long as mu4e has a matching mu it doesn't matter if that clashes with the system one that my mbsync systemd service launches. So... many thanks and all good.

**Comment by mroll** [comment]
@progfolio I was able to build mu4e using your recipe, I just had to figure out how to switch to the `develop` branch. Thanks for posting that solution!

For anyone who wants to try this build recipe but does not know how to switch straight.el to use the a different branch:

- Before loading the snippet for bootstrapping straight.el, set the variable `straight-repository-branch` to the name of the branch you'd like to use. The value of the branch name must be a string. For example, to use the `develop` branch:
    - ```(setq straight-repository-branch "develop")```
- Delete the contents of `~/.emacs.d/straight/` and restart Emacs to cause straight to download the new branch.

**Comment by LoganBarnett** [comment]
I recently got drawn into issues with `mu4e` again. I've got a fix below.

I encountered this during a `doom upgrade`:
```
      > Building mu4e...
      x There was an unexpected error
        Message: error
        Data: (error . ":pre-build command error in \"mu4e\" recipe in command \"(\\\"./autogen.sh\\\")\"")
        Backtrace:
          (signal error (":pre-build command error in \"mu4e\" recipe in command \"(
          (error ":pre-build command error in %S recipe in command %S" "mu4e" "(\"./
          (condition-case err (if (cl-every #'stringp command) (if (apply #'straight
          (let ((command (car --dolist-tail--))) (condition-case err (if (cl-every #
          (while --dolist-tail-- (let ((command (car --dolist-tail--))) (condition-c
          (let ((--dolist-tail-- (if (cl-every #'listp commands) commands (list comm
          (let ((default-directory repo) (commanderror nil)) (let ((--dolist-tail-- 
          (if repo (let ((default-directory repo) (commanderror nil)) (let ((--dolis
          (let* ((commands (and t (if post post-build pre-build))) (repo (and comman
          (let* ((--cl-rest-- recipe) (pre-build (car (cdr (plist-member --cl-rest--
```

My `mu4e` is symlinked out of a `nix` directory. `nix` likes to keep everything read-only, and I see no `autogen.sh` to run. There are already `.elc` files there (I assume the `nix` derivation build put them there). So I disabled the `pre-build` step:

```
(package! mu4e
  :recipe (
           :local-repo "~/.nix-profile/share/emacs/site-lisp/mu4e"
           ;; pre-build must be disabled when using the nix derivation - in part
           ;; because it is alreadt built, but also because the directory is
           ;; read-only because that's how nix likes to do things.
           :pre-build ()
           )
  )
```
`"~/.nix-profile/share/emacs/site-lisp/mu4e"` comes from a symlink, which is documented earlier in this thread.

I apologize if this necro-posting is considered distasteful. My (perhaps poor) justification is that searches for `pre-build` issues relating to `straight.el` and `mu4e` bring me back here. Perhaps this will help someone else.

**Comment by baracunatana** [comment]
I'll continue with the necro-posting started by @LoganBarnett for other NixOS users that are struggling with this.

    (use-package mu4e
    :straight (:local-repo 
               "/run/current-system/sw/share/emacs/site-lisp/mu4e"
               :pre-build 
               ())

This works for me in vanilla emacs with `straight` and `use-package`.

**Comment by ne9z** [comment]
I'll chime in here, also using vanilla emacs on NixOS.

For me, the solution provided by @baracunatana does not work, namely straight.el will treat local-repo as a git repo and attempt to update it. We need to tell straight.el to treat it as is. Here's my solution:
```
(use-package mu4e
  :straight
  (:local-repo "/run/current-system/sw/share/emacs/site-lisp/mu4e"
   :type built-in)
  :commands (mu4e)
  :config
  ;;...)
```

**Comment by nicodebo** [comment]
hello,
the recipe posted on 14 Jan 2021 seems to only work on the branch release/1.6 of mu.
```
(use-package mu4e
  :straight ( :host github 
                  :repo "djcb/mu"  
                  :branch "release/1.6"
                  :files ("mu4e/*")   
                  :pre-build (("./autogen.sh") ("make"))) 
  :custom   (mu4e-mu-binary (expand-file-name "mu/mu" (straight--repos-dir "mu"))))
```

For the mu master branch, i tried this:
```
(use-package mu4e
  :straight ( :host github
                  :repo "djcb/mu"
                  :branch "master"
                  :files ("build/mu4e/*")
                  :pre-build (("./autogen.sh") ("make")))
  :custom   (mu4e-mu-binary (expand-file-name "build/mu/mu" (straight--repos-dir "mu"))))
```

but I get the following error: Error (use-package): mu4e/:catch: Symbol’s function definition is void: mu4e~main-action-str

**Comment by progfolio** [comment]
mu/mu4e's build scripts have recently changed. I haven't updated either in a bit, but this is the most current recipe I have:

```emacs-lisp
( :host github :files ("build/mu4e/*.el") :repo "djcb/mu"
              :pre-build (("./autogen.sh")
                          ("ninja" "-C" "build")))
```

**Comment by kenranunderscore** [comment]
> ```
> (use-package mu4e
>   :straight
>   (:local-repo "/run/current-system/sw/share/emacs/site-lisp/mu4e"
>    :type built-in)
>   :commands (mu4e)
>   :config
>   ;;...)
> ```

I'm using `home-manager`, and `mu` isn't installed globally on the system (just for my user). Changing the `:local-repo` path to `"~/.nix-profile/share/emacs/site-lisp/mu4e"` works for me.

**Comment by aNaravi** [comment]
I'd like to add a slight variation to @ne9z's solution that resolved the issues I had with `mu 1.8.8` that was built from source:
```
(use-package mu4e
:straight (:type nil :local-repo "/usr/local/lib/mu/build/mu4e" :pre-build ())
:config ...)
```

1. `mu` is installed in the folder `/usr/local/lib/mu`.
2. using `:type nil` rather than `:type built-in` causes straight to copy all the `*.el` files into the `straight/build/mu4e` folder, making the `mu4e` command available while preventing any issues with `straight-pull-all`
3. The `mu4e-mu-binary` variable was already set to `/usr/local/bin/mu` by default.

**Comment by nicodebo** [comment]
```
(:host github
		   :files ("build/mu4e/*.elc")
                   :branch "release/1.8"
		   :repo "djcb/mu"
		   :pre-build (("meson" "build")
                               ("ninja" "-C" "build"))
```
The following recipe seems ok with mu v1.8.11.

**Comment by PaddyPatPat** [comment]
This issue has plagued me for days.
I'm on MacOS running Emacs 28.2. I finally figured out to run the `autogen.sh` file. I found `autogen.sh` in `~/.emacs.d/straight/repos/mu4e/`.

So in the Terminal 
`zsh ~/.emacs.d/straight/repos/mu4e/autogen.sh`

This complained that I didn't have Meson installed. Using Homebrew to install this...

`brew install meson`

... and then restarting Emacs and Mu4e built!

As part of my search for an answer I installed the Development branch of `Straight.el`. I'm not sure if this was important or not though in the end as I don't have a `:pre-build` line in my config file entry for Mu4e.

`(straight-use-package '(mu4e :host github :repo "emacsmirror/mu4e"
                               :files (:defaults "mu4e/*.el")))`

But I am very pleased that I've got Mu4e working now under Straight.el in Emacs 28.2. Thanks to those above for this thread.

**Comment by rsa4046** [comment]
> > ```
> > (use-package mu4e
> >   :straight
> >   (:local-repo "/run/current-system/sw/share/emacs/site-lisp/mu4e"
> >    :type built-in)
> >   :commands (mu4e)
> >   :config
> >   ;;...)
> > ```
> 
> I'm using `home-manager`, and `mu` isn't installed globally on the system (just for my user). Changing the `:local-repo` path to `"~/.nix-profile/share/emacs/site-lisp/mu4e"` works for me.

At the risking of summoning this thread from the dead, thanks for this -- your version finally worked for me. My config has only a slight change in `home-manager` user's path:

```
(use-package mu4e
             :straight
             (:local-repo "/etc/profiles/per-user/<your username here>/share/emacs/site-lisp/mu4e"
                          :type built-in)
             :commands (mu4e)
             :config
             (setq mu4e-maildir "~/mbsync"))
```
