### ISSUE TITLE
Auto recompiling build directory when using vc-follow-symlinks and editing in the repos package dir.

### ISSUE THREAD

**Issue by rileyrg** [raxod502/straight.el#493]
When I'm editing a repo file eg straight/repos/package/p.el then when I invoke magit I see the git status for that repo. This is good. But when I save the file it doesn't recompile in the build directory, eg straight/build/package/p.elc is't refreshed. If I open the symlink in straight/build/package and do NOT follow symlink, so am effectively in straight/build/package, then when I save the elc is correctly recompiled BUT magit doesn't know which git repo it should be dealing with. I had a peruse of the docs and have maybe missed what to do here : (a)  How, when I invoke magit, do I tell it to use the repo package dir if I don't "follow symlink" or (b) simply follow the symlink and have the save know to recompile the build directory.

Thanks for any info you can provide.

**Comment by raxod502** [comment]
Are you saying that you expect that .elc file to be recompiled _immediately_, or are you saying you have restarted Emacs and it doesn't get recompiled?

**Comment by rileyrg** [comment]
I'll put this down to a glitch in the matrix. I had intended to come back and correct. For some unrelated reason, it wasn't being recompiled at the restart. It is now and all is good. Closing.
