### ISSUE TITLE
repos with the same name conflict, but shouldn't

### ISSUE THREAD

**Issue by aaronjensen** [raxod502/straight.el#495]
## What's wrong

```
Warning (straight): Packages "org-variable-pitch" and "ruby-electric" have incompatible recipes (:repo cannot be both "cadadr/elisp" and "ruby/elisp")
```

## Directions to reproduce

I'll work on a repro, but you may know the answer off the top of your head. I have two different recipes that both have repos named `elisp` on github, though with different users:

```
(use-package ruby-electric
  :straight (
             :host github
             :repo "ruby/elisp"
             :files ("ruby-electric.el")))

(use-package org-variable-pitch)
```

### Version information

* Emacs version: 27
* Operating system: macOS

**Comment by raxod502** [comment]
See https://github.com/raxod502/straight.el/issues/265. There are a few options:

* Generate a more informative warning or even error in this situation, since it is not uncommon.
* Tell upstream to name their repositories more reasonably. GitHub will set up redirects for them automatically.
* Create a `straight.el`-specific recipe repository that can be a collection of small hacks for packages like this that don't cause problems when using other package managers, but do with `straight.el` for reasons that can't reasonably be fixed in `straight.el`.
* Completely rethink how local repositories are handled (very hard).

**Comment by aaronjensen** [comment]
At least a more informative warning would be good. I ended up not using the package (and before that, I forked it and renamed the repo).

I can see the complexity, since you may have more than one package coming from one repo. I wonder if actually including the user/org name in the repo path would be sufficient. It means that if you change from one fork to another, you end up in a different directory, which sucks, but maybe that's okay.

Alternatively, if we could assign our own repo name override, would that fix this?

**Comment by raxod502** [comment]
> if we could assign our own repo name override

You can. That _is_ how you deal with this situation. Add `:local-repo "ruby-elisp"` to your recipe :)

> if you change from one fork to another, you end up in a different directory, which sucks, but maybe that's okay

That's definitely not okay. It breaks the version-control workflow. Git is designed for you to have one local repository with multiple remotes.

**Comment by aaronjensen** [comment]
> You can. That _is_ how you deal with this situation. Add `:local-repo "ruby-elisp"` to your recipe :)

Ah! Well then, a warning that told me what to do would be sufficient in my opinion. I think I missed that because `local-repo` sounded to me like it was when the source repo was on my disk rather than on github, so I clearly misunderstood that option.

**Comment by raxod502** [comment]
> so I clearly misunderstood that option

Fair enough, then it was poorly documented. Do you have any ideas for what the keyword could be called that would make the function more obvious?

**Comment by aaronjensen** [comment]
I'm not sure. I just read the docs for it and it's reasonable. Maybe if it was more explicit and it referred to it as the "local copy of the repo in the `packages`" directory. Even then, I may not have found that option and connected it to the warning I was seeing. I think if the warning gave said that I could change the name of one of them with `:local-repo` I would have had everything I needed and not opened this issue.

**Comment by raxod502** [comment]
Migrated to #500.
