### ISSUE TITLE
Symlink to libgit2.pc.in is named libgit2.pc

### ISSUE THREAD

**Issue by tastytea** [raxod502/straight.el#497]
## What's wrong

The symlink from the build directory to the repo is wrong, the `.in` is dropped.

**It is:** `[…]/build/libgit/libgit2/libgit2.pc` → `[…]/repos/libegit2/libgit2/libgit2.pc.in`  
**It should be:**  `[…]/build/libgit/libgit2/libgit2.pc.in` → `[…]/repos/libegit2/libgit2/libgit2.pc.in`

**Update:** It's not limited to symlinks, the same happens if I set `straight-use-symlinks` to `nil`.

## Directions to reproduce

``` elisp
(setq straight-repository-branch "develop")
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'libgit)
```

``` shellsession
% ls -l ~/.emacs.d/straight/build/libgit/libgit2/libgit2.pc*
[…] /home/tastytea/.emacs.d/straight/build/libgit/libgit2/libgit2.pc -> /home/tastytea/.emacs.d/straight/repos/libegit2/libgit2/libgit2.pc.in
```

### Version information

* Emacs version: GNU Emacs 27.0.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13, cairo version 1.16.0) of 2020-03-11
* Operating system: Gentoo Linux

**Comment by raxod502** [comment]
Should be fixed now. Thanks for the report.

**Comment by tastytea** [comment]
Thanks. I can confirm that it's fixed.
