### ISSUE TITLE
Generate warning when local repository names are in conflict

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#500]
Currently, if you use two packages from MELPA (or any source) which result in the same auto-generated local repository name (`:local-repo`), e.g.

* https://github.com/eschulte/emacs-web-server (web-server)
* https://github.com/skeeto/emacs-web-server (simple-httpd)

then `straight.el` generates a warning

```
Warning (straight): Packages "web-server" and "simple-httpd" have incompatible recipes (:repo cannot be both "eschulte/emacs-web-server" and "skeeto/emacs-web-server")
```

However, this is not a very informative warning to the user, because it does not suggest the resolution of the issue, which is to manually specify `:local-repo` for one of the recipes. A better warning should be shown.

Related issues:

* https://github.com/raxod502/straight.el/issues/265
* https://github.com/raxod502/straight.el/issues/495

**Comment by raxod502** [comment]
Huh. So apparently merging that pull request doesn't close this issue, despite GitHub's claims to the contrary.

**Comment by SkySkimmer** [comment]
Merging in develop doesn't count, it needs to get merged to the default branch AFAIK

**Comment by raxod502** [comment]
Ah! That would make sense. Thank you for the explanation :)

**Comment by yiufung** [comment]
My setup is as below:

```emacs-lisp
(use-package pdf-tools
	...
	:straight web-server
	...)

(use-package ein
	...
	:straight (simple-httpd :host github :repo "skeeto/emacs-web-server" :local-repo "simple-httpd")
	...)
```

(Also available in [yiufung/dot-emacs/init.el#L2879](https://github.com/yiufung/dot-emacs/blob/master/init.el#L2879) and [yiufung/dot-emacs/init.el#L3795](https://github.com/yiufung/dot-emacs/blob/master/init.el#L3795))

I delete `web-server` and `simple-httpd` folders under `straight/repo` and `straight/build` folder to have a clean rebuild. However, a warning message still prompts:`Warning (straight): Two different recipes given for "simple-httpd" (:local-repo cannot be both "emacs-web-server" and "simple-httpd")`

Under `straight/repo`, both `simple-httpd` and `emacs-web-server` come from `skeeto/emacs-web-server`. As a result, `straight/build/web-server` and `straight/build/simple-httpd` always points to `simple-httpd`. 

Incidentally, `straight-get-recipe` returns correct results for both repos:

- (web-server :type git :flavor melpa :host github :repo "eschulte/emacs-web-server")
- (simple-httpd :type git :flavor melpa :host github :repo "skeeto/emacs-web-server")

`straight-version` returns `prerelease (HEAD -> master, origin/master) 2d407bc 2020-12-20`

Did I miss anything obvious?

**Comment by progfolio** [comment]
Does `M-x straight-normalize-package simple-httpd` followed by a restart help?

**Comment by yiufung** [comment]
@progfolio No it doesn't, neither for `simple-httpd` nor `web-server`.

Digged into the function definition, and find that:

- `(gethash "simple-httpd" straight--recipe-cache)`: `(:host github :repo "skeeto/emacs-web-server" :local-repo "simple-httpd" :package "simple-httpd" :type git)`
- `(gethash "web-server" straight--recipe-cache)` returns **wrong** result: `(:flavor melpa :package "web-server" :local-repo "emacs-web-server" :type git :repo "skeeto/emacs-web-server" :host github)`

It seems to involve cache file `build-cache.el`, so I backup the file, and restarted Emacs. `straight` then rebuild all packages. However, the error remains after all rebuild is done.

**Comment by progfolio** [comment]
try evaluating the following and sharing the results:

```emacs-lisp
(cl-remove-if-not
 (lambda (package)
   (member "web-server" (nth 1 (gethash package straight--build-cache))))
 (hash-table-keys straight--recipe-cache))
 ```

**Comment by yiufung** [comment]
Try both and rebuilt both, still to no avail.

**Comment by progfolio** [comment]
Sorry, I should have been more clear. I meant for you to evaluate the above code and see if it printed anything to your *Messages* buffer. It should tell us if there are other packages which depend on "web-server".

**Comment by progfolio** [comment]
You can try this as well:

```emacs-lisp
(cl-some
 (lambda (package)
   (and (member "web-server" (nth 1 (gethash package straight--build-cache)))
     package))
 (hash-table-keys straight--recipe-cache))
```
And if it finds a package which depends on "web-server" it should echo it/ print it to Messages.

**Comment by yiufung** [comment]
```emacs-lisp
ELISP> (cl-some
 (lambda (package)
   (and (member "web-server" (nth 1 (gethash package straight--build-cache)))
     package))
 (hash-table-keys straight--recipe-cache))
nil
ELISP> (cl-some
 (lambda (package)
   (and (member "simple-httpd" (nth 1 (gethash package straight--build-cache)))
     package))
 (hash-table-keys straight--recipe-cache))
"org-roam-s..."
ELISP> (cl-some
 (lambda (package)
   (and (member "simple-httpd" (nth 1 (gethash package straight--build-cache)))
     package))
 (hash-table-keys straight--recipe-cache))
"org-roam-server"
ELISP> (cl-remove-if-not
 (lambda (package)
   (member "web-server" (nth 1 (gethash package straight--build-cache))))
 (hash-table-keys straight--recipe-cache))
nil
ELISP> (cl-remove-if-not
 (lambda (package)
   (member "simple-httpd" (nth 1 (gethash package straight--build-cache))))
 (hash-table-keys straight--recipe-cache))
("org-roam-server" "jupyter" "impatient-mode")
```

**Comment by jasonhemann** [comment]
I'm experiencing what @yiufung was running into. Running @progfolio 's commands, I see `org-roam-server` and `org2web` depending on `simple-httpd`, and `markdown-preview-mode` depending on `web-server`.  Curiously, though, my version of the error message is slightly different from what @raxod502 points to for the same issue: my version mentions `emacs-web-server`

**Comment by raxod502** [comment]
You may want to open a new issue for this with the full configuration (see `straight-bug-report`), for visibility.
