### ISSUE TITLE
After straight-pull-package, branch "master" has 1 commit unpushed to "origin/master"

### ISSUE THREAD

**Issue by doolio** [raxod502/straight.el#501]
Not sure how I initially created this issue without any details. Anyway, this issue is most likely user error. I've searched all the issues and read the README but I'm still confused. It is probably a lack of understanding on the fundamentals of git rather than an issue with straight.

So, I updated the ESS package with `straight-pull-package` after the upstream resolution for #498.  I then try to update my lockfile (is this the correct worklow?) but straight informs me that 
```
In repository "ESS", branch "master" has 1 commit unpushed to "origin/master".
```
I have not forked ESS so I presume by default the `origin/master` remote is that of upstream. Now `master` (and `HEAD`) correspond to the latest commit `1c2387f`. So it seems `master` was updated with the latest upstream commit which I thought would be coming from `origin/master` but for me it is `625041ad` the parent of `1c2387f`. What is the correct way to do what I want to do? Thanks for your time.

**Comment by raxod502** [comment]
What does `git log --all --graph` show in your ESS repository? It seems like the fetch did not work correctly for some reason, or it could be a bug in the repository management code.

**Comment by doolio** [comment]
Ok, so a partial screenshot of `git log --all --graph` shows [this](https://i.imgur.com/R1VfaaX.png). Now I notice today upstream have made a new commit which I haven't yet pulled in.

**Comment by raxod502** [comment]
That commit is the reason you are getting the message from `straight.el`. Because the only reason you get into a state where `master` is ahead of `origin/master` normally is that you have done local development and you need to push it to the remote. Since that's not the case here I have no idea how the branch pointers ended up there. But it should be sufficient to `M-x straight-fetch-package` on ESS.

**Comment by doolio** [comment]
That did the trick. Thanks.

How I ended up in this situation is likely user error. I was trying to understand the vc features of `straight` and on recollection I can't be certain of the sequence I followed so most likely I caused it somehow.
