### ISSUE TITLE
Add programmatic interface for dependency information

### ISSUE THREAD

**Issue by aGolduck** [raxod502/straight.el#503]
How can I find out which packages depend on a specific package? In general, is there a way to inspect dependency information programmatically?

**Comment by raxod502** [comment]
There is no way to do this using the current API, which is considered a bug. Here is how you can do it using the internal functions:

```elisp
(nth 1 (gethash "magit" straight--build-cache))
```

**Comment by wpchou** [comment]
Actually I mean, how to find out packages which are dependent on some installed package. Am I speak it wrong? English is not my mother tongue.

**Comment by raxod502** [comment]
Sorry! What you said in your first comment was correct, but I misread it because people have asked much more frequently about dependencies rather than dependents. There's still no public API, but you can try this:

```elisp
(cl-remove-if-not
 (lambda (package)
   (member "dash" (nth 1 (gethash package straight--build-cache))))
 (hash-table-keys straight--recipe-cache))
```

**Comment by wpchou** [comment]
It works. I was trying to find out packages that introduce some installed package. Thanks!

**Comment by progfolio** [comment]
> It works. I was trying to find out packages that introduce some installed package. Thanks!

You should be able to use `straight-dependents` now to do this. See: #787 for details.

**Comment by raxod502** [comment]
Awesome, that seems like a great improvement!

**Comment by aGolduck** [comment]
Thank you. @progfolio
