### ISSUE TITLE
Moving a package declaration from straight.el recipe pointing to repo to pull from MELPA

### ISSUE THREAD

**Issue by nrvale0** [raxod502/straight.el#506]
Is there a documented way to adjust a package when it moves from git repo hosting to being listed on MELPA?

Specifically, I have a straight.el recipe which installed org-roam from GH repo when that was the only package hosting available. It has since moved to being part of MELPA and I'd now like to adjust my package declaration to point to MELPA however I don't see any documentation as to whether or not this would require any adjustments to striaght.el and/or the build cache beyond just removing the recipe and using the use-package integration.

Thx.

**Comment by raxod502** [comment]
`M-x straight-pull-package` on `melpa` and then replace your custom recipe with just the package symbol, like you usually do to pull a package from MELPA. It sounds like you already knew this though; were you concerned there might be additional steps required?

**Comment by nrvale0** [comment]
Not at all. The above was helpful. thx

**Comment by raxod502** [comment]
Do you have any suggestions about what could be added or changed in the documentation of `straight.el` so that the answer to this question would have been easier to find?

**Comment by nrvale0** [comment]
Thanks for asking.

I was working from the README in the root of the repository. It's quite comprehensive.

I doubt that everyone learns/works the same way but over the past few years what I've noticed is that I learn fastest and get to the point of self-sufficiency fastest when I first view "getting started" videos on a topic and then start to look at the documentation after my usage has gone beyond beginner phase. I call this "fractal learning" for lack of a better term. straight.el mostly just works (I use the use-package integration) and thus I've never invested in reading through the docs for depth as opposed to just trying to find answers to very specific questions.

So maybe as penance for asking too many questions ( ;) ), I should create some "getting started" videos on straight.el usage a la:

- https://www.youtube.com/watch?v=IofHvutUWV0
- https://www.youtube.com/watch?v=Gk9-q8tXbMs

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
