### ISSUE TITLE
"Process failed" error is very poor

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#509]
Currently when a subprocess invocation fails unexpectedly, you get

```
(error "Failed to run \"git\"; see buffer *straight-process*")
```

which is pretty bad. Firstly we should show part of the output from the subprocess in the minibuffer. Secondly we should just pop to the `*straight-process*` buffer automatically, instead of telling the user to do it themselves.

**Comment by progfolio** [comment]
Safe to close now that #573 has landed on develop?

**Comment by raxod502** [comment]
I think so. Thanks!
