### ISSUE TITLE
Images included with info docs not copied to build [minor]

### ISSUE THREAD

**Issue by gcentauri** [raxod502/straight.el#514]
## What's wrong

I installed the `sly` package using `straight.el` and noticed that the image links in the info doc that comes with it were broken. I'm guessing its probably not all that common to have images in info docs, but here's at least one case. The broken links are easily fixed by manually copying the directory they are in. 

## Directions to reproduce

- `(straight-use-package 'sly)`
- `C-h i` select the SLY docs
- navigate to section 3 "A SLY tour for SLIME users`
- you should see a broken image link

### Version information

* Emacs version: 28.0.50
* Operating system: PureOS GNU/Linux

**Comment by raxod502** [comment]
That's because the MELPA recipe doesn't include those images. You will encounter the same problem under `package.el`. I would suggest submitting a ticket against SLY.

**Comment by gcentauri** [comment]
Thanks for the info! I'm working on updating some other things in the documentation as well on SLY, so I can look into it. I will open an ticket with SLY. I'm pretty new to packaging, sorry I erroneously assumed it was a problem with the build step here.

**Comment by gcentauri** [comment]
It took me a little while to figure out how to rebuild sly with the recipe that was just merged into MELPA https://github.com/melpa/melpa/pull/6879 , but i fiddled around with the straight commands enough to successfully rebuild the SLY package with the images added :)

this was a somewhat silly, minor issue, but thanks to your suggestions, it seems like the issue has been resolved for both straight.el and package.el users

**Comment by raxod502** [comment]
Thanks!
