### ISSUE TITLE
Every package rebuilt on every emacs startup under Windows NT + Tries to create scratch file in Emacs bin

### ISSUE THREAD

**Issue by aashwin-rs** [raxod502/straight.el#515]
On every Emacs startup Straight will rebuild every package installed. I am using vanilla Emacs 26.3 installed via msi (https://github.com/arbv/emacs-msi-installer) under Windows 10 1909. Straight is configured with the recommended (from the readme) bootstrap setup and symlinks and cache-autoloads are both enabled. This issue started when I moved most of my init.el to another file so I could byte-compile and load it. It has continued even after I had moved everything back to init.el and reinstalled straight and all packages. Additionally, the error `make-temp-file: Creating file with prefix: Permission denied, c:/Program Files/GNU Emacs/bin/#%2Ascratch%2A` has also become persistent. This one doesn't happen then i use `--debug-init`. I can't figure out why either of these are happening.

**Comment by aashwin-rs** [comment]
I was naive enough to not go through all  the messages. Before Straight starts rebuilding it says `Rebuilding all packages due to malformed build cache`

**Comment by raxod502** [comment]
That message is quite buried. It would be nice to expose it more directly, but I don't want to make it a warning because that's quite annoying.

Anyway, can you check if `make-temp-file` is working for you manually? E.g. `(make-temp-file "hello")`.

**Comment by raxod502** [comment]
Oh, and that filename looks like your Emacs is trying to create an autosave file for the `*scratch*` buffer for some reason? Not sure though.

**Comment by aashwin-rs** [comment]
I went back to using my previous Emacs config and when I used my `straight.el` based one to run `(make-temp-file "hello")` but the problem was no longer present. I tried recreating the environment in which the problem was happening but was unsuccessful. I don't know how it happened but it seems to have resolved itself so I'll just close this.

**Comment by raxod502** [comment]
OK, good to know -- thanks!
