### ISSUE TITLE
straight--convert-recipe: Could not find package tex in recipe repositories

### ISSUE THREAD

**Issue by Nathan-Furnal** [raxod502/straight.el#516]
## What's wrong

I'm trying to use ``tex`` in my ``init`` but I'm faced with this issue :

`straight--convert-recipe: Could not find package tex in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)`

## Directions to reproduce

This is the very top of my ``init`` : 

```
;;; .emacs --- Initialization file for Emacs
;;; Commentary: Emacs Startup File --- initialization for Emacs

;; Setting up straight.el for package management docs @ https://github.com/raxod502/straight.el

(setq straight-use-package-by-default t)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
```
The offending line : 

```
(use-package tex
  :defer t
  :config (...my config...) )
```

### Version information

* Emacs version: GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.12) of 2020-04-30

* Operating system: Ubuntu 19.10 

Thanks for the good work and the great package!

**Comment by billop** [comment]
I think adding this snippet from the README fixed it for me.

```
(use-package tex
  :straight (auctex :host github
                    :repo "emacsmirror/auctex"
                    :files (:defaults (:exclude "*.el.in"))))
...
```

**Comment by Nathan-Furnal** [comment]
@billop 

thank you !

Actually simply 

```
(use-package tex
  :straight auctex
  :config 
  (...my config...))
```

Fixed it ! It seems that calling ``:straight`` on the underlying package fixes the issue, though I had the same problem with a different package called ``dap-mode`` and ``dap-java``.

For example, following the [above package docs](https://github.com/emacs-lsp/lsp-java#quick-start) : 

```
(use-package dap-java
  :after (lsp-java))
```

will throw an error because there is no such package as ``dap-java``, it's a mode I think?

and 

```
(use-package dap-java
  :straight (lsp-java))
```

fixed it!

@raxod502 I've seen the problem mentioned in a different form in some issues I think but I'm not sure if this is documented behavior or if there is a "best" way to go about it?

Thank you =)

**Comment by raxod502** [comment]
> there is no such package as dap-java

The problem is that code is written assuming `use-package-always-ensure` is nil, but the equivalent variable `straight-use-package-by-default` in your configuration is non-nil. Provide `:straight nil`.

> if this is documented behavior

Is [this](https://github.com/raxod502/straight.el/tree/21c431c0d5144790df666b3888122a1594090d4f#integration-with-use-package-1) good enough?

**Comment by Nathan-Furnal** [comment]
@raxod502 Ouch, that means I didn't read the docs well enough. Thanks for your patience!
I'll go ahead and close the issue.

**Comment by raxod502** [comment]
You're not the first person to be confused. I added an FAQ entry.

**Comment by Nathan-Furnal** [comment]
I appreciate it, thanks!
