### ISSUE TITLE
Recipe for package has been overridden (:flavor changed from melpa to nil)

### ISSUE THREAD

**Issue by xzz53** [raxod502/straight.el#518]
Hi! I've switched from using melpa version of a package (`org-noter`) to a personal fork, and now I get the subject warning on *every* emacs startup. Well, I know that the recipe has been overridden (by myself, on purpose). Is there any option to silence the warning?

Thanks in advance!

Relevant parts of `init.el`:

```elisp
(setq straight-check-for-modifications '(check-on-save))

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(straight-use-package 'use-package)
(put 'use-package 'lisp-indent-function 1)
(setq straight-use-package-by-default t)


(use-package org-noter
  :straight (org-noter :host github :repo "weirdNox/org-noter"
                       :fork (:host github
                              :repo "xzz53/org-noter"
                              :branch "fix-pdftools-location-autosave"))
  :custom
   <...>
   :bind
   <...>
)
```

**Comment by raxod502** [comment]
That warning does not mean what you think it does, but it was written in a very confusing manner, so I reworded it. The warning is produced when a package is requested with one recipe, and then subsequently requested with a _different_ recipe _in the same init-file_. Typically this happens when a package is pulled in as a dependency (which uses the default recipe), and then you try to request it explicitly with a custom recipe. Is that what happened in your case? I don't get the warning with your reduced init-file.

**Comment by raxod502** [comment]
See also https://github.com/raxod502/straight.el/issues/523.

**Comment by xzz53** [comment]
You are right, I had two more packages from melpa in my `init.el` requiring `org-noter` as dependency:
```elisp
(use-package org-pdftools
  :after org
  :config
  (org-link-set-parameters "pdftools"
                           :follow #'org-pdftools-open
                           :complete #'org-pdftools-complete-link
                           :store #'org-pdftools-store-link
                           :export #'org-pdftools-export)
  (add-hook 'org-store-link-functions 'org-pdftools-store-link))

(use-package org-noter-pdftools
  :after org-noter)
```
I was somehow misled that the order of `use-package`'s doesn't matter in cases like this. Moving the above block below `(use-package org-noter)` fixed the issue for me.

I can confirm that the new message from #523 is much more helpful for my taste.

Thanks for the great job!
