### ISSUE TITLE
zetteldeft package

### ISSUE THREAD

**Issue by OrionRandD** [raxod502/straight.el#521]
I am having problem to install zetteldeft with straight

M-x straight-use-package RET zetteldeft 

in not in repository.

I have tried with:

(use-package zetteldeft
ensure t
:after deft
:config
 (zetteldeft-set-classic-keybindings))

But it straight seems to interfere in the installation

https://www.eliasstorms.net/zetteldeft/

**Comment by OrionRandD** [comment]
I cannot find zetteldeft receipt through straight-get-recipe  :(

**Comment by andersjohansson** [comment]
Try following the instructions here:
https://github.com/raxod502/straight.el#updating-recipe-repositories

**Comment by OrionRandD** [comment]
@andersjohansson Thx a lot! I used 
M-x straight-pull-all 
and that updated my repo.
I had to fix some small issues.
But, this did the trick.  :)
