### ISSUE TITLE
^M in package names on Windows

### ISSUE THREAD

**Issue by kwshi** [raxod502/straight.el#526]
When trying to install a package via `straight-use-package`, certain package names are listed as containing trailing `^M` characters.  (Inserting `^M` via `C-q C-m` and acting as though the `^M` were actually part of the package name doesn't fix it and leads to an "invalid argument" error, presumably because `^M` is not allowed in file/folder names.)  That makes it impossible, afaik, to install those packages via `straight-use-package`.

![image](https://user-images.githubusercontent.com/3887189/82489209-440edb00-9aaf-11ea-88b4-5c963a8f6c34.png)

**Comment by raxod502** [comment]
Please run `C-u M-x straight-use-package`. This will let you pick which recipe repository to view packages from. Judging by your screenshot, the bug only affects packages from certain recipe repositories. Can you check which ones?

As a workaround, you can type `M-: (straight-use-package 'package-name) RET` to perform the same action as `M-x straight-use-package RET package-name RET`.

**Comment by Whil-** [comment]
Hi, I get the same issue on my machine. And it is `emacsmirror-mirror` that shows the added ^M.

**Comment by raxod502** [comment]
Should be fixed, please test.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
