### ISSUE TITLE
Straight fetches tags even with shallow repository

### ISSUE THREAD

**Issue by bepvte** [raxod502/straight.el#532]
Straight.el seems to fetch tags when updating a shallow repository. Without `--no-tags`, instead of just the required or recent history being fetched, all the tags and their connected revisions are fetched as well. If a git repository is cloned with `git clone --depth=1 --no-tags`, the .git/config file contains
```
[remote "origin"]
	tagOpt = --no-tags
```
which prevents tags from being fetched in the future. Otherwise, running `git fetch --no-tags` also prevents tags from being fetched. A way to solve this would be adding `--no-tags` to the clone command when the depth option is set to anything but `'full`.

I'm not sure if this is a bug or a feature request, as it seems to be following expected behavior.

See also: hlissner/doom-emacs#3279

**Comment by raxod502** [comment]
Your idea seems like a good one. I added `--no-tags --single-branch` to the shallow clone command used by `straight.el`. Let me know if that fixes your use case.

**Comment by bepvte** [comment]
Works great! Thank you.
