### ISSUE TITLE
Where can I find information about straight.el package mirror?

### ISSUE THREAD

**Issue by tmalsburg** [raxod502/straight.el#550]
`straight-pull-all` wants to redirect some of my packages to git repos in [emacs-straight](https://github.com/emacs-straight).  Where can I read up on that?  I'd like to know: Why is this happening? Who is maintaining this mirror? What are the implications of using it opposed to the original repos?  Thank you.

**Comment by raxod502** [comment]
![image](https://user-images.githubusercontent.com/6559064/88924948-27222100-d231-11ea-95bb-740128e5cd55.png)

I added a pointer to the relevant parts of the documentation. Does this help, or should more information be added?

**Comment by tmalsburg** [comment]
I suppose you mean `straight-recipes-gnu-elpa-use-mirror`. Thanks that helps.
