### ISSUE TITLE
Installing ESS for ob-julia with straight.el

### ISSUE THREAD

**Issue by SebastianCallh** [raxod502/straight.el#552]
I love the idea of `straight.el`, so I switched from plain `use-package`  using the config

```listp
 (straight-use-package 'use-package)
 (setq straight-use-package-by-default t)
```

but  my integration between `ob-babel` and  `ess` seem to have broken. I use ESS to run Julia in org so I initialize org with

```lisp
  (use-package org
      :after (ess)
      :config
      (org-babel-do-load-languages
       'org-babel-load-languages
       '((emacs-lisp . t)
         (julia . t))))
```

and install add ESS with

```listp
(use-package ess
    :config
    (setq inferior-julia-program "/usr/local/bin/julia")))
```

However, loading the `org` config results in `Error (use-package): org/:config: Cannot open load file: No such file or directory, ob-julia` and running `ess-version` outputs `ess-version:  [<unknown>] (loaded from /home/sebastian/.emacs.d/straight/build/ess/)` leading me to think that ESS is not properly installed, even though this setup worked with `use-package`. How should I installed `ess` correctly with `straight.el` to make it work with Julia in org mode?

**Comment by SebastianCallh** [comment]
I have tried to run Julia code with `ess` in a .jl file and it works as intended. So the issue seems to be in the interactions between `org`, `ess` and `straight`. Any advice? Please let me know if I should take this issue to some other package repo.

**Comment by SebastianCallh** [comment]
I was barking up the wrong tree on this one. Turns out I had forgotten to add the necessary `(add-to-list 'load-path "/path/to/ob-julia.el")`. Thank you for `straight.el`, it made experimenting with various settings to find the issue super comfortable.

**Comment by raxod502** [comment]
You should be using `org-plus-contrib`, not plain `org`. The latter doesn't include `ob-julia`. You should never have to manually adjust the `load-path`.
