### ISSUE TITLE
(straight-use-package 'eldoc) still uses built-in eldoc package, not latest

### ISSUE THREAD

**Issue by garyo** [raxod502/straight.el#553]
Using Emacs 20.0.50 (nightly of 2020-05-24) on Linux, I can' make straight.el load the latest version of eldoc. Instead I get the built-in one which is old.

To repro, use this emacs init file:
```
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'eldoc)
```
Start emacs as `emacs -Q -l /tmp/emacs-bug-test.el` and do `C-h f eldoc-mode` and you will see it finds it in emacs's lisp dir, rather than downloading eldoc from somewhere like https://elpa.gnu.org/packages/eldoc.html.

I ran into this because the latest eglot calls a function in eldoc that has a new arg signature, so it doesn't work with the old version. At least I think that's what's going on.

Perhaps there's a config I need to set to allow straight to override the built-in emacs version of eldoc?

**Comment by raxod502** [comment]
When I use that code, `straight.el` clones `eldoc` as an external package from GNU ELPA Mirror at revision `5a2423e144035c2638823a0bf4f9a568a21a2989`. However, the issue is that ElDoc is already loaded at Emacs startup, so the fact that `straight.el` added the new version earlier on the `load-path` doesn't really do a lot.

I'm open to suggestions about what to do with this problem. You can work around it by explicitly invoking `(load "eldoc")`, for now.

**Comment by raxod502** [comment]
To be frank, if EGLOT calls a function that is only defined in the `eldoc` available on GNU ELPA, I would consider that a bug in EGLOT.

**Comment by raxod502** [comment]
Does this work with `package.el`?

**Comment by garyo** [comment]
Haha, I haven't used `package.el` for a long time, so I'm not sure what it would do in this case. 
As for whether there's an eglot bug: I'm trying to pretest `eglot` so I'm loading it straight from github. So I'm not surprised that a bleeding-edge `eglot` requires a bleeding-edge `eldoc`. I just want a way to make sure I've got the latest `eldoc` to match.

**Comment by raxod502** [comment]
> So I'm not surprised that a bleeding-edge `eglot` requires a bleeding-edge `eldoc`

Well, _I_ am surprised. I have never seen a package rely on Emacs HEAD features. Is the new version of EGLOT not going to be compatible with any released version of Emacs?

Anyway, I tested and `package.el` appears to do the same thing (I cannot really imagine how it would do something different). I call it a bug in EGLOT.

**Comment by garyo** [comment]
OK, I guess I will `(load "eglot")` for now, thanks!
