### ISSUE TITLE
:fetcher is undocumented

### ISSUE THREAD

**Issue by aspiers** [raxod502/straight.el#562]
Hi there, I've just switched to `straight.el` from the misery of `package.el` and so far am delighted by the very many improvements and stellar documentation.  So firstly thanks for your great work!

I discovered by accident that straight.el nicely supports `:fetcher github`, and verified by reading the source that this is deliberate.  However I see no reference to `:fetcher` in the otherwise extremely comprehensive `README.md`, so it would be nice if that was added.

**Comment by aspiers** [comment]
Hrm, actually maybe it only worked by accident because `straight-allow-recipe-inheritance` was `t` and the package was already defined in MELPA.  I'm now trying this:

```lisp
(use-package epoch
  :straight (epoch :fetcher github :repo "progfolio/epoch"))
```

and I get this error:

```
Debugger entered--Lisp error: (error "Failed to run \"git\"; see buffer *straight-process*")
  signal(error ("Failed to run \"git\"; see buffer *straight-process*"))
  error("Failed to run %S; see buffer %s" "git" "*straight-process*")
  straight--get-call-raw("git" "clone" "--origin" "origin" "--no-checkout" "progfolio/epoch" "/home/adam/.emacs.d/straight/repos/epoch/")
  apply(straight--get-call-raw "git" ("clone" "--origin" "origin" "--no-checkout" "progfolio/epoch" "/home/adam/.emacs.d/straight/repos/epoch/"))
  straight--get-call("git" "clone" "--origin" "origin" "--no-checkout" "progfolio/epoch" "/home/adam/.emacs.d/straight/repos/epoch/")
  straight-vc-git--clone-internal(:depth full :remote "origin" :url "progfolio/epoch" :repo-dir "/home/adam/.emacs.d/straight/repos/epoch/")
  straight-vc-git--clone-internal(:depth 10 :remote "origin" :url "progfolio/epoch" :repo-dir "/home/adam/.emacs.d/straight/repos/epoch/" :branch "master" :commit nil)
  straight-vc-git-clone((:fetcher github :repo "progfolio/epoch" :package "epoch" :type git :local-repo "epoch") nil)
  apply(straight-vc-git-clone ((:fetcher github :repo "progfolio/epoch" :package "epoch" :type git :local-repo "epoch") nil))
  straight-vc(clone git (:fetcher github :repo "progfolio/epoch" :package "epoch" :type git :local-repo "epoch") nil)
  straight-vc-clone((:fetcher github :repo "progfolio/epoch" :package "epoch" :type git :local-repo "epoch"))
  straight--clone-repository((:fetcher github :repo "progfolio/epoch" :package "epoch" :type git :local-repo "epoch") nil)
  #f(compiled-function () #<bytecode 0x1697869>)()
  straight--transaction-exec(use-package-\(:fetcher\ github\ :repo\ \"progfolio/epoch\"\ :package\ \"epoch\"\ :type\ git\ :local-repo\ \"epoch\"\)-nil-nil :now #f(compiled-function () #<bytecode 0x1697869>))
  straight-use-package((epoch :fetcher github :repo "progfolio/epoch"))
```

If I change `:fetcher` to `:host` then it works, but based on:

https://github.com/raxod502/straight.el/blob/5d046ad09413f3aba6198229e392cdd3f07e77ee/straight.el#L2687-L2691

I'm not sure why it doesn't also work with `:fetcher`.

**Comment by aspiers** [comment]
Ahhh d'oh, of course - it's because that code only applies when there is a MELPA recipe ...

I think this reinforces the relevance of the original issue - it would be really helpful if `:fetcher` was documented to set expectations about how it can and can't be used.

**Comment by raxod502** [comment]
`:fetcher` is not supported, has never been supported, and never will be supported. Any special behavior that occurs when you provide `:fetcher` is a bug, recipe inheritance or no. That's why the keyword is not documented. Use `:host`.

The reason why your first recipe worked was not related to `:fetcher`, and you would observe the same behavior if you removed the keyword entirely. It is because `:host` (not `:fetcher`) was inherited from the MELPA recipe.

Sorry for the confusion! I'm glad you are enjoying the package.

If you have a suggestion about how the documentation could be improved so that it is clear that there is this difference in recipe format vis-à-vis MELPA, I'd be happy to incorporate it :)

**Comment by aspiers** [comment]
[**@raxod502**](https://github.com/raxod502) commented on [August 25, 2020 2:27 PM](https://github.com/raxod502/straight.el/issues/562#issuecomment-680024496 "2020-08-25T13:27:30Z - Replied by Github Reply Comments"):
> `:fetcher` is not supported, has never been supported, and never will be supported. Any special behavior that occurs when you provide `:fetcher` is a bug, recipe inheritance or no. That's why the keyword is not documented. Use `:host`.

Ah OK.  So I guess that code is in there purely to support `:fetcher` from MELPA recipes, not `:fetcher` in native straight.el recipes - right?

> The reason why your first recipe worked was not related to `:fetcher`, and you would observe the same behavior if you removed the keyword entirely. It is because `:host` (not `:fetcher`) was inherited from the MELPA recipe.

Yeah, I already figured that out as you can see from the comments above ;-)

> Sorry for the confusion! I'm glad you are enjoying the package.
> 
> If you have a suggestion about how the documentation could be improved so that it is clear that there is this difference in recipe format vis-à-vis MELPA, I'd be happy to incorporate it :)

Sure!  I think that currently it is not very clear; for example the [Features section](https://github.com/raxod502/straight.el#features) says:

> Specify package descriptions using a powerful recipe format that supports everything from MELPA recipes and more.

which *on the surface* seems to directly contradict what you just said about the difference in recipe format.  [MELPA recipes clearly support `:fetcher`](https://github.com/melpa/melpa#recipe-format), so if straight.el doesn't, then it should state that it only *partially* supports MELPA recipes.  Or perhaps a more accurate way of expressing it would be something like:

> `straight.el` has its own native recipe format which is slightly different from MELPA and other recipe formats; however it can also fully understand any MELPA recipe.

I do note that later on in the README, in [the "Where do recipes come from?" section](https://github.com/raxod502/straight.el#where-do-recipes-come-from), you write:

> Note that `straight.el` uses its own recipe format which is similar, but not identical, to the one used by MELPA.

However the README is so long that it is far too easy to miss that, especially given that it is not mentioned anywhere in [the recipe format section](https://github.com/raxod502/straight.el#the-recipe-format) which would be a more logical place for that statement.  So in addition to tweaking the entry in the Feature list, I would also suggest explaining the differences in more detail in the recipe format section, and then crosslinking to that from the "Where do recipes come from?" section.  Hope those three suggested tweaks make sense?

**Comment by raxod502** [comment]
> that code is in there purely to support :fetcher from MELPA recipes, not :fetcher in native straight.el recipes - right?

Exactly right.

> However the README is so long

Indeed, I cannot fault you for not reading all of it :P 

> Hope those three suggested tweaks make sense?

Perfect sense -- I really appreciate your patience in explaining. I have implemented them in the above-linked commit; let me know what you think, and if you have any further suggestions.

**Comment by aspiers** [comment]
Looks perfect!  Many thanks!
