### ISSUE TITLE
Feature request(?): Equivalent of try

### ISSUE THREAD

**Issue by haji-ali** [raxod502/straight.el#565]
Is there a way to try a package with `straight` without permanently installing it? 
Something like what [larstvei/Try](https://github.com/larstvei/Try) allows one to do with `package.el`

**Comment by raxod502** [comment]
You can `M-x straight-use-package` to pull a package into the current session; it will be gone as soon as you restart (unless you add `(straight-use-package ...)` to your init-file), with the exception that the repository will still exist on disk (advantage: if you try it again, it will be faster; disadvantage: it's not fully gone, and if you pull it into your configuration again you'll get the same version unless you update it). How does that work for you?

**Comment by haji-ali** [comment]
Yes, that's perfect! I also use Emacs Doom which cleans up any unused packages (which I imagine can also done directly with straight).

**Comment by raxod502** [comment]
See `straight-x-clean-unused-repos`, although I cannot recommend its use.
