### ISSUE TITLE
Git error: No url found for submodule path

### ISSUE THREAD

**Issue by WorldsEndless** [raxod502/straight.el#567]
## What's wrong
I use projectile to jump to some recent project from anywhere. In general Projectile identifies projects by git information, so before it gives me my list of recent projects it scans my current location's git setup. The result is that, when I try to use projectile from somewhere that Git includes Straight stuff, I get this failure about submodules:

> In ‘Projectile files’ source: ‘#[0 \\301 \\205;\0r\\302!\\203\0\\206\0p\\211q\\210\\303 \\304 \\305\\211:\\2036\0@\\262\\306"BB\\262A\\262\\202\0\\211\\237\\266\\204)\\207 [helm-current-buffer projectile-project-p buffer-live-p projectile-project-root projectile-current-project-files nil expand-file-name] 8]’ (file-missing "Setting current directory" "No such file or directory" "*home/torysa/emacs/fatal: No url found for submodule path ’.emacs.d/straight/repos/a.el’ in .gitmodules .emacs.d/counsel-bbdb*")

If I try to add a URL for that repo by hand, I just get the same error for another submodule, and another, and &#x2026;

Is there a setting I should change, or perhaps something I should add to my `.gitignore`?

## Directions to reproduce
All my emacs, including straight, is under git version control. 

Use `helm-projectile` in a directory including the straight git repo. 

Witness "No url found for submodule path" error preventing Projectile from working.

### Version information

* Emacs version: 27.1
* Operating system: OpenSUSE Tumbleweed

**Comment by raxod502** [comment]
You should either add those repositories as submodules, or put the `repos` directory into `.gitignore`. I don't see why Projectile would produce an error in any case, but you would certainly need to do one of these two things eventually, if you want to keep the entire `~/.emacs.d` in a Git repository.

**Comment by WorldsEndless** [comment]
> You should either add those repositories as submodules, or put the `repos` directory into `.gitignore`. I don't see why Projectile would produce an error in any case, but you would certainly need to do one of these two things eventually, if you want to keep the entire `~/.emacs.d` in a Git repository.

This was a good answer. The solution to remove the git from watching all those repos was the following: 

`git rm -r --cached ./.emacs.d/straight/repos`

Maybe it would have been nice to "add as submodules," but I don't know how to do that en masse...

**Comment by raxod502** [comment]
You could always

```
$ for repo in *; do git submodule add $(git -C $repo remote get-url origin) $repo; done
```

or some shenanigan :) 

(above code is totally untested)
