### ISSUE TITLE
Implement rebuilding of orgmode docs

### ISSUE THREAD

**Issue by aspiers** [raxod502/straight.el#568]
I just hacked a patch to the org-mode manual (`org-manual.org`) and initiated a rebuild of the `org` package, but it didn't rebuild the texinfo file (`doc/org.texi`).  I think this is because `straight.el` currently has no way of knowing that the `.texi` file is generated from `org-manual.org` via an `info` target in Org's `Makefile` system.  So perhaps addressing #541 might be one way of enabling a fix for this?

**Comment by aspiers** [comment]
Doh - duplicate of #72.  Sorry for the noise!

**Comment by aspiers** [comment]
Actually, this isn't technically a duplicate since #72 was about a much more general feature.

If I understand [this comment](https://github.com/raxod502/straight.el/issues/71#issuecomment-339720202) in #71 correctly, now that #72 is now implemented supporting arbitrary build commands (yay!), once #115 (el-get recipe support) is resolved by PR #549, straight.el will be able to automatically run Org's Makefiles which build the Org manual by taking advantage of the build step's in [el-get's recipe for org-mode](https://github.com/dimitri/el-get/blob/6138ce5b0a9df779e33ef42eadc4c15a5cf65f39/recipes/org-mode.rcp#L7-L14).

Is that all correct?

**Comment by progfolio** [comment]
@aspiers straight implements a psuedo `org-elpa` recipe repository which (as of #72) provides a recipe similar to el-get's for org/org-plus-contrib. `straight-get-recipe` should return:

```emacs-lisp
`(org-plus-contrib :type git :repo "https://code.orgmode.org/bzg/org-mode.git"
                   :local-repo "org"
                   :files (:defaults "contrib/lisp/*.el")
                   :build ,(let ((make (if (eq system-type 'berkeley-unix) "gmake" "make"))
                                 (emacs (concat "EMACS=" invocation-directory invocation-name)))
                             `(,make "oldorg" ,emacs)))
```

Which `straight--convert-recipe` will convert to the system specific build commands. For example, on my gnu/linux system the recipe is converted to:

```emacs-lisp
(org-plus-contrib :type git :repo "https://code.orgmode.org/bzg/org-mode.git"
                  :local-repo "org"
                  :files (:defaults "contrib/lisp/*.el")
                  :build ("make" "oldorg" "EMACS=/usr/bin/emacs"))
```
I just made a test edit to `doc/org-manaul.org` to be sure and everything seemed to work fine. Let me know if that's the case for you or if you run into any problems.

**Comment by aspiers** [comment]
Ah, thanks - I'd forgotten that the Org recipes were hardcoded in `straight.el`.  Yep, seems to work so I'm closing again - thanks a lot!!
