### ISSUE TITLE
How to silence FIND: Invalid switch?

### ISSUE THREAD

**Issue by juhanoi** [raxod502/straight.el#581]
How to silence *straight-process* messages?
It gets printed during bootstrap

```
$ cd "c:/Users/Juhani/scoop/apps/emacs/current/bin/"
$ "find" "/dev/null" "-newermt" "2018-01-01 12:00:00"

FIND: Invalid switch

[Return code: 2]
```

**Comment by raxod502** [comment]
You don't want to silence that warning, you want to fix it. It indicates that modification detection is completely broken, so your packages will never be recompiled when changes occur. You need to put a version of `find` onto your executable search path that will be compatible with that command line, or alternatively propose an alternative syntax that will be compatible with what you have.

Or are you attempting to use live modification detection, and annoyed that you still get this warning despite not actually needing a dependency on `find`?

**Comment by juhanoi** [comment]
im guessing i get this message on windows emacs because straight finds the wrong "find" program (powershell find or something?), not the unix find
then it defaults to check-on-save, which is fine, but prints this error message on boot anyway

**Comment by raxod502** [comment]
Oh, that's right -- I had forgotten that we automatically switch to live modification checking by default on Windows. You are correct that the warning being printed in addition is a bug. I will fix it.

**Comment by raxod502** [comment]
Try the latest commit and let me know if it fixes the problem. Thank you for the report!

**Comment by juhanoi** [comment]
works now
thanks 👍
