### ISSUE TITLE
Figure out why ESS wants to make autoloads

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#61]
For some reason, every time I build ESS, it inserts an `ess-autoloads.el` file in its *repository* (not its build directory!). This is annoying, and we'll have to figure out what's going on there.

**Comment by therockmandolinist** [comment]
Is this related? On attempting to `(straight-use-package 'evil-anzu)` I get `(file-missing "Cannot open load file" "No such file or directory" ".../.emacs.d/straight/build/evil-anzu/evil-anzu-autoloads.el")`

**Comment by raxod502** [comment]
I can't reproduce the error. Can you let me know what revision of `straight.el` you are running?

You may also try running `M-x straight-rebuild-package` on `evil-anzu` to fix the problem.

**Comment by therockmandolinist** [comment]
`M-x straight-rebuild-package` leads to the same error. I haven't changed the `straight.el` recipe, so whatever the bootstrap script on the readme installs is what I'm using. I think it's up to date with master at the moment.

**Comment by therockmandolinist** [comment]
Weird. I've got that commit (I'm up to date with master), but listing the `evil-anzu` build directory just doesn't have `evil-anzu-autoloads.el`. FWIW tried just deleting everything `evil-anzu` and starting over again, leading to the same result.

**Comment by raxod502** [comment]
That's bizarre. I'm not sure I can do much more from here other than point you to the relevant area of the code. Luckily, said code is extremely simple (as compared to the rest of `straight.el`). First, verify that `straight--generate-package-autoloads` is called from [here](https://github.com/raxod502/straight.el/blob/d4bda8ff1e803ea1ffdd88e083806a68e188a552/straight.el#L2544). Then see what is happening such that `update-directory-autoloads` is called [here](https://github.com/raxod502/straight.el/blob/d4bda8ff1e803ea1ffdd88e083806a68e188a552/straight.el#L2392-L2433) but the autoloads file somehow isn't getting generated.

(Also luckily, debugging `straight.el` is trivial, compared with `package.el`: you just stick debugging code in it [and restart, if the error only happens during init], and it will use the new version without asking questions. Then just `git checkout` to discard your changes later.)

**Comment by therockmandolinist** [comment]
So, something I probably should have mentioned is I'm running emacs from master (26.0.50). I've been investigating a bit and as I understand it, at its core, the autoload generation from `straight.el` for `evil-azu` is trying to do this
```
(let ((generated-autoload-file "/home/diego/.emacs.d/straight/build/evil-anzu/evil-anzu-autoloads.el"))
  (update-directory-autoloads "/home/diego/.emacs.d/straight/build/evil-anzu/"))
```

So I tried evaling this on its own, which also did not produce an autoload file. But it worked fine for some other packages. Then I realized `evil-anzu` doesn't actually specify any autoloads. My only conclusion from this is that perhaps at some point in emacs master, they decided to just not generate an autoload file if autoloads aren't specified. I haven't found the commit yet if that's the case.

This is still unconfirmed, but _if_ that's the case, it would seem `straight.el` would have to check if the file exists first in `straight--activate-package-autoloads`.

**Comment by raxod502** [comment]
Sounds like a good idea and your diagnosis sounds correct. Pushed to e87b97c6dda6ef738bd0504ddca7749d3106560e. Let me know if that fixes the problem.

**Comment by raxod502** [comment]
You might be able to use `git bisect test` to find the commit that introduced the change. I may do this out of curiosity, though I do not have time at the moment.

**Comment by therockmandolinist** [comment]
https://github.com/raxod502/straight.el/commit/e87b97c6dda6ef738bd0504ddca7749d3106560e seemed to do it, thanks.
