### ISSUE TITLE
geiser is pointing to a git repository at gitlab.com

### ISSUE THREAD

**Issue by dadinn** [raxod502/straight.el#614]
## What's wrong

The repository is private repository, so ssh access doesn't work, and the cloning fails.

## Directions to reproduce

I have `straight-vc-git-default-protocol` set to `ssh`.

**Comment by raxod502** [comment]
It looks like a public repository for me: https://gitlab.com/jaor/geiser
You probably need to upload your SSH key to your GitLab account.

**Comment by dadinn** [comment]
I don't have account at gitlab, as it isn't a free service.

I have also set `straight-vc-git-default-protocol` to `ssh`, which I would like to be my default protocol.

Unfortunately I don't see a way to change the protocol on a per-package basis to https.
That could be a work-around together with using `straight-allow-recipe-inheritance`.

**Comment by raxod502** [comment]
The develop branch supports a `:protocol` key that can be used to override the protocol per-recipe. A possible future improvement would be to extend the work of @progfolio in https://github.com/raxod502/straight.el/pull/571 to also allow overriding protocols on a per-host basis (SSH for GitHub, HTTPS for others, e.g.).

Some repositories on the Emacsmirror are direct mirrors, others are not. It's a bit of a complicated affair.

> shouldn't your emacsmirror repo already have this recipe in it?

It does, as you can verify with `C-u M-x straight-get-recipe`. You could use `(geiser :source emacsmirror-mirror)` to direct `straight.el` to pull the recipe from there.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
