### ISSUE TITLE
Installation of prettier.el seems faulty

### ISSUE THREAD

**Issue by adimit** [raxod502/straight.el#621]
Hi, I'm new to `straight.el` so I hope this is the right place to bring this up…

## What's wrong

Installing [prettier.el](https://github.com/jscheid/prettier.el) works:

```
(straight-use-package 'prettier)
```

But when I try to enable prettier by using `M-x prettier-mode RET` I get the following error:

```
insert-file-contents-literally: Opening input file: No such file or directory, /home/aleks/.emacs.d/straight/build/prettier/prettier-el.js.gz.base64
```

I'm currently migrating my installation from `package.el` & `use-package` to `straight.el` & `use-package`, so I know that in the former setup, `prettier` worked.

## Directions to reproduce
Add to basic snippet:

```
(straight-use-package 'prettier)
```
Then `M-x prettier-mode` in any buffer.

### Version information

* Emacs version: GNU Emacs 27.1.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-09-21
* Operating system: Ubuntu 20.4

### Additional Information:

This is what the directory looks like:

```
.emacs.d/straight/build/prettier/
├── bootstrap.js -> /home/aleks/.emacs.d/straight/repos/prettier.el/bootstrap.js
├── externs.js -> /home/aleks/.emacs.d/straight/repos/prettier.el/externs.js
├── prettier-autoloads.el
├── prettier.el -> /home/aleks/.emacs.d/straight/repos/prettier.el/prettier.el
├── prettier.elc
└── prettier-el.js -> /home/aleks/.emacs.d/straight/repos/prettier.el/prettier-el.js
```

**Comment by adimit** [comment]
Ah, I dug around a bit, and it seems that the following will help:

```
cd straight/repos/prettier.el/
npm install --frozen-lockfile
make
```

Then copy over the files:
```
cd ../../build/prettier
cp ../../repos/prettier.el/dist/prettier-el.js.gz.base64 .
cp ../../repos/prettier.el/dist/bootstrap-min.js .
```

Then everything works as exected. I guess it's a problem with prettier not providing a way to install using `straight` then? Is there a way to automate these steps with `straight`?

Feel free to close this, as I'm not sure anymore that this is a bug with `straight.el`

**Comment by progfolio** [comment]
Perfect timing! We've just added support for running build commands on the develop branch.
You should be able to add to the build steps to prettier's recipe (the rest of the defaults will be inherited).
For example, using the steps you've provided:

```emacs-lisp
(use-package prettier
  :straight (:build (("npm" "install" "--frozen-lockfile")
                     ("make")))
  ;;etc
  )
```

The default recipe for prettier can be obtained by running `M-x straight-get-recipe prettier`.
On my system it returns:

```emacs-lisp
(prettier :type git :flavor melpa
          :files (:defaults "*.js" "*.base64" "prettier-pkg.el")
          :branch "release"
          :host github
          :repo "jscheid/prettier.el")
```

Note the `:files` keyword should already copy over the js, base64 and prettier-pkg.el files to `straight/build/prettier`. They copying takes place after the `:build` step, too- so any files generated by those commands can be considered. If you need to extend that you can override it in the recipe as well.

```emacs-lisp
(use-package prettier
  :straight ( :build (("npm" "install" "--frozen-lockfile") ("make"))
              :files (:defaults "*.js" "*.base64" "prettier-pkg.el" "example-file"))
  ;;etc
  )
```

Check out the docs on the recipe format for more info about `:build` and `:files`.
Happy to help if you have any questions or run into any problems.


~ Nick

**Comment by raxod502** [comment]
I don't know, that sounds like a bug in `straight.el`. All the MELPA recipes should work out of the box, after all `package.el` does not work with build steps either. I'll check on it. Of course, what @progfolio suggested should also get things working, until we figure out what is going on that causes this package to work in `package.el` but not `straight.el`.

**Comment by adimit** [comment]
@raxod502 I think that [this prettier.el issue](https://github.com/jscheid/prettier.el/issues/11) might help shed some light on the situation. Unfortunately, I know virtually nothing about how packages are built/distributed in Emacs.

@progfolio Thanks for the instructions. I actually wanted to stay on the main branch for now, as I just tried straight.el out for the first time. Unfortunately, the `make` step has quite some dependencies that it requires on the building system (including a compiler, pandoc and python-panflute) so it'd be nice if we could avoid having to use `make` at all. Maybe @jscheid could bring some light in the situation?

**Comment by progfolio** [comment]
@adimit Thanks for the extra info. I have a hunch, but I'm not able to get to my computer right now. What does `M-x straight-get-recipe prettier` return for you?

**Comment by adimit** [comment]
@progfolio Here's the output of `straight-get-recipe`:

```
(prettier :type git :flavor melpa :files (:defaults "*.js" "*.base64" "prettier-pkg.el") :host github :repo "jscheid/prettier.el")
```

Using the release branch as you indicated does not copy the necessary files to the `straight/build/prettier` folder :frowning_face:.

**Comment by jscheid** [comment]
Let me know if you need anything specific from me, but sounds like you're on the right track. You definitely want the `release` branch, the `master` branch doesn't have all the files required.

**Comment by raxod502** [comment]
Whoopsies. You've successfully found one of only 13 recipes in all of MELPA that use the `:branch` property, which was not handled correctly by `straight.el` until https://github.com/raxod502/straight.el/pull/609 was merged recently (thanks @isker!). I've backported that fix from `develop` to `master`, so if you update `straight.el` then you should be good to go and `prettier` should work out of the box.

**Comment by progfolio** [comment]
It appears like it's building cleanly now for me.
`build/prettier' has the following files:

```shell
├── bootstrap-min.js -> /tmp/prettier-branch-test.straight/straight/repos/prettier.el/bootstrap-min.js
├── dir -> /tmp/prettier-branch-test.straight/straight/repos/prettier.el/dir
├── prettier-autoloads.el
├── prettier.el -> /tmp/prettier-branch-test.straight/straight/repos/prettier.el/prettier.el
├── prettier.elc
├── prettier-el.js.gz.base64 -> /tmp/prettier-branch-test.straight/straight/repos/prettier.el/prettier-el.js.gz.base64
└── prettier.info -> /tmp/prettier-branch-test.straight/straight/repos/prettier.el/prettier.info
```

<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "prettier-branch-test.straight"
  :preserve t
  :pre-bootstrap 
  (setq straight-repository-branch "master")
  :post-bootstrap 
  (straight-use-package 'prettier)
  (prettier-mode))
```
</details>

- Test run at: `2020-10-26 12:10:36`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> feat/el-get-recipe-support, fork/feat/el-get-recipe-support) 797314a 2020-10-26`
- emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.3, Xaw3d scroll bars)
 of 2020-10-14`

<details><summary>Output</summary>

```emacs-lisp
Prettier syncing config


```
</details>

**Comment by adimit** [comment]
Yes, it works for me now with a clean Emacs installation. Thanks a lot for your quick responses!

I think I had to remove the build cache in order to enable the new behaviour in my running Emacs installation. It works now :smiley:

**Comment by raxod502** [comment]
Hmm, it's always a bit unfortunate when you have to remove the build cache. That "should" never happen; feel free to open a bug if you observe a situation where you always have to do something manual in order to get things to update.

**Comment by adimit** [comment]
OK, I'll see if I can reproduce the behaviour and open an issue if I can.

**Comment by einSelbst** [comment]
I did run into the very same problem with straight and prettier. Happy that updating just updating straight solved it. 

Regarding the build cache, since I had it also installed before, what needs to be removed is the `prettier` folder in the `repos` folder, otherwise it will always build it from this (which is/was based on the wrong branch if installed before straight had that fix). Maybe that's why I didn't work for @adimit in a 'non-clean' emacs installation.
