### ISSUE TITLE
notdeft package

### ISSUE THREAD

**Issue by OrionRandD** [raxod502/straight.el#622]
Hi,
Could you add notdeft package to straight?
It is a wonderful package 
https://github.com/hasu/notdeft
https://tero.hasu.is/notdeft/

**Comment by progfolio** [comment]
Thank you for bringing this package to my attention. It looks interesting.

It doesn't appear as if notdeft is available on MELPA or any other elisp package archive that we currently support.
There is an issue open to see if the author has any interest in submitting the package to MELPA, but it hasn't recieved a response yet:

https://github.com/hasu/notdeft/issues/13

However, you can still use straight to install notdeft with a custom recipe.
This works on my system:

```emacs-lisp
(straight-use-package '(notdeft :type git :host github :repo "hasu/notdeft"
                                :build (("make")
                                        ("bash" "-c" "cd xapian && make"))))
```

I also had to make sure I had the TCLAP library installed on my system as per notdeft's installation instructions:


> If the make command fails, then you will need to ensure that you have the required libraries installed, and find the right C++ compiler incantation for building the notdeft-xapian program on your system. A notable library requirement for compiling the program is TCLAP.

Does that help? Let me know if you have any other questions.

**Comment by OrionRandD** [comment]
Great! I love this package.
I have it installed in my doom-Emacs,
But, I was trying to install in another instance of Emacs, since a use two
instances here with chemacs
https://github.com/plexus/chemacs
Anyways, I have already managed to do that manually...
Many thanks for replying me.
I hope that the owner gets interested in adding that to MELPA.
Will see...
