### ISSUE TITLE
Validate defcustom :type specifications in CI

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#634]
As per discussion in https://github.com/raxod502/straight.el/pull/628#issuecomment-726825989, we could catch some bugs by checking the `defcustom` forms in `straight.el` to see that their default values are compatible with their `:type` specifications. An example of doing this is at https://github.com/progfolio/doct/blob/dabb30ebea866ef225b81561c8265d740b1e81c3/tests/doct-test.el#L148-L165.

**Comment by progfolio** [comment]
Came across this package which looks relevant:
https://endlessparentheses.com/validate-el-schema-validation-for-emacs-lisp.html

**Comment by raxod502** [comment]
Nice, yeah, that looks like exactly what we would need!

**Comment by progfolio** [comment]
I took a look over our defcustoms, and for most of them we can get away with simple assertions.
Added tests for them in #798

**Comment by raxod502** [comment]
See also https://github.com/raxod502/straight.el/pull/825.
