### ISSUE TITLE
Loading config in a org file does not properly load org

### ISSUE THREAD

**Issue by nettoyoussef** [raxod502/straight.el#639]
Hi, thanks for the awesome package.
It has been a lifesaver for preventing unwanted changes/quick fixing bugs that come with package updates.

Most use-package declarations of my configuration just worked when converting from package.el to straight.el.
However, since my configuration is quite big, I use an org file to keep everything organized and neat.

My problem is that, since I use init.el to call org to load an org file, apparently any package that is org-related and/or hooks
to the org-package are not being configured. Any package declaration that I put after my `(use-package org)` declaration also doesn't load.

My init.el file:
```lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage)
  )

;; Install use-package
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
(use-package diminish)
(use-package bind-key :straight use-package)

;; set file for custom variables
(setq custom-file (locate-user-emacs-file ".emacs-custom.el"))
(unless (file-exists-p custom-file)
  (write-region "" nil custom-file))
(load custom-file)

;; This needs to be before loading config.org so I don't have to give
;; permission to load the file when it is symlinked.
(customize-set-variable
 'vc-follow-symlinks t "Follow Symlinks without asking")

;; load org file
(let ((config-el (expand-file-name "config.el" user-emacs-directory))
      (config-org (expand-file-name "config.org" user-emacs-directory)))
  (if (and (file-exists-p config-el)
           (time-less-p (file-attribute-modification-time (file-attributes config-org))
                        (file-attribute-modification-time (file-attributes config-el))))
        (load-file config-el)
    (org-babel-load-file config-org)))


```

Then my org declaration:

```lisp
;;#+BEGIN_SRC emacs-lisp   
;;(setq straight-fix-org nil)

(use-package org 
  :straight t 
  ;;:straight (:type built-in)
  :defer 2
  :init
  ;; set line wrap at 90 characters
  (add-hook 'org-mode-hook '(lambda () (setq fill-column 90)))
  (add-hook 'org-mode-hook '(lambda () (setq display-fill-column-indicator "t")))

  ;; disable evil-auto-indent on org buffers - it reindents 
  ;; every time you add a new line with `o` or `i` + RET
  (add-hook 'org-mode-hook #'ey--org-disable-evil-auto-indent)

  ;; == Agenda Specific Hooks == 

  ;; Agenda post-processing
  ;; Highlight the "!!" for stuck projects (for emphasis)
  (add-hook 'org-agenda-finalize-hook 'gs/org-agenda-project-highlight-warning)

  ;; Remove empty agenda blocks
  (add-hook 'org-agenda-finalize-hook 'gs/remove-agenda-regions)

  ;; Clocking hooks
  :config
  ;; Set org default directories
  (ey--load-org-directory)

  ;; Highlight latex code 
  (setq org-highlight-latex-and-related '(latex script entities))
  
  ;; Display inline images
  (setq org-startup-with-inline-images t)


  ;; change display of verbatim to red highlight
  (add-to-list 'org-emphasis-alist
               '("=" (:foreground "red")
                 ))

  ;; set agenda config
  (setq org-agenda-files '("~/notes/to-do-list.org"))
  (ey--load-org-agenda)

  ;; Toggle smart quotes (org-export-with-smart-quotes).
  ;; Depending on the language used, when activated, 
  ;; Org treats pairs of double quotes as primary quotes, 
  ;; pairs of single quotes as secondary quotes, and single quote marks as apostrophes. 
  (setq org-export-with-smart-quotes t)

  ;; load latex packages for preview
  (ey--load-org-latex-packages)

  ;; babel config
  (ey--load-org-babel-config)
  (ey--load-org-babel-templates)

  ;; org capture templates 
  (ey--load-org-capture-templates)

  ;; Edit size of inline preview of images in latex
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 2.0))

)
;;#+END_SRC
```
This org declaration, of course, depends on several other functions which I didn't included, and other packages also add hooks to org. But this configuration worked without any bugs with package.el.

Do you have any tips on how should I approach this problem or what could I do to better debug it?

What I tried:
- include the org use-package declaration before loading the org file (i.e., in the init.el)
- `(setq straight-fix-org nil)`
-  `:straight (:type built-in)`

None of those worked.

**Comment by nettoyoussef** [comment]
Ok, I think I found the culprit.

I had to do two things:
- declare the `(use-package org)` on my init file
- remove the block below

This declaration from use package was causing some problems:
```lisp
(use-package ox-word
 :load-path "~/.emacs.d/functions"
 :after ox
 :defer t
)
```
Any guess why? I see I don't use the straight declaration there. How do I load package files using straight?
I tried:
```elisp
(use-package ox-word
 :recipe (:local-repo "~/.emacs.d/functions/ox-word")
 :after ox
 :defer t
)
```
And while the previous error didn't happen, the functions still don't load.

**Comment by progfolio** [comment]
Calling `org-babel-load-file` loads Org. This is probably not what you want since you're trying to configure Org after that.
This means the `:defer` in your use-package declaration for Org has no effect. 

```emacs-lisp
(use-package org
  :straight t)
```

expands to:

```emacs-lisp
(progn
  (straight-use-package 'org)
  (require 'org nil nil))
```

Which attempts to install Org from (unless you have overridden the recipe beforehand) from the org-elpa recipe repository.
This can lead to a mixed Org installation because Org is already loaded when straight is trying to build it.

The solution depends on what you are trying to achieve. What version of Org are you trying to use (the version bundled with Emacs, or one of the versions from org-ELPA)? It would also be useful to have the output of `straight-version`.

**Comment by nettoyoussef** [comment]
Hi @progfolio, thanks for the fast response.

The information you asked me:
- org version: version 9.4 (release_9.4-137-g6e5399 @ ~/.emacs.d/straight/build/org-plus-contrib/)

I could not find how to output straight-version.
I tried adding:
 ```lisp
(setq straight-repository-branch "develop")
```
But still could not find anything with this name using `C-h c`.

Instead of using a init.el to tangle a config.org, I changed to a manually tangled init.el, adding:
```lisp
#+PROPERTY: header-args :tangle init.el
```
At the top of my config.org file, and generating a init.el with `org-babel-tangle`.
So everything now lives on a single file, and I don't need to load a org file anymore.

This solved the problems with the hooks.
But the functions in the `:config` part of the `(use-package org)` are still not being loaded:

```lisp
#+BEGIN_SRC emacs-lisp   
(use-package org-plus-contrib
  :straight t 
  ;;:straight (:type built-in)
  ;;:straight (:local-repo nil)
  :defer 2
  :init
  ;; set line wrap at 90 characters
  (add-hook 'org-mode-hook '(lambda () (setq fill-column 90)))
  (add-hook 'org-mode-hook '(lambda () (setq display-fill-column-indicator "t")))

  ;; disable evil-auto-indent on org buffers - it reindents 
  ;; every time you add a new line with `o` or `i` + RET
  (add-hook 'org-mode-hook #'ey--org-disable-evil-auto-indent)

  ;; == Agenda Specific Hooks == 

  ;; Agenda post-processing
  ;; Highlight the "!!" for stuck projects (for emphasis)
  (add-hook 'org-agenda-finalize-hook 'gs/org-agenda-project-highlight-warning)

  ;; Remove empty agenda blocks
  (add-hook 'org-agenda-finalize-hook 'gs/remove-agenda-regions)

  :config
  ;; PROBLEM STARTS HERE
  ;; below this part nothing is being loaded
  ;; Set org default directories
  (ey--load-org-directory)

  ;; Highlight latex code 
  (setq org-highlight-latex-and-related '(latex script entities))
  
  ;; Display inline images
  (setq org-startup-with-inline-images t)


  ;; change display of verbatim to red highlight
  (add-to-list 'org-emphasis-alist
               '("=" (:foreground "red")
                 ))

  ;; set agenda config
  (setq org-agenda-files '("~/notes/to-do-list.org"))
  (ey--load-org-agenda)

  ;; Toggle smart quotes (org-export-with-smart-quotes).
  ;; Depending on the language used, when activated, 
  ;; Org treats pairs of double quotes as primary quotes, 
  ;; pairs of single quotes as secondary quotes, and single quote marks as apostrophes. 
  (setq org-export-with-smart-quotes t)

  ;; load latex packages for preview
  (ey--load-org-latex-packages)

  ;; babel config
  (ey--load-org-babel-config)
  (ey--load-org-babel-templates)

  ;; org capture templates 
  (ey--load-org-capture-templates)

  ;; Edit size of inline preview of images in latex
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 2.0))
)
#+END_SRC

```

**Comment by nettoyoussef** [comment]
I think I solved the problem. By using org without the contrib part, I was able to load the `:config` part.

Changing from:
```lisp
#+BEGIN_SRC emacs-lisp   
(use-package org-plus-contrib
  :straight t 
  ;;:straight (:type built-in)
  ;;:straight (:local-repo nil)
  :defer 2
...)
```
To:
```lisp
(use-package org
  :straight t 
  ;;:straight (:type built-in)
  ;;:straight (:local-repo nil)
  :defer 2
...)
```
org-plus-contrib version:
version 9.4 (release_9.4-137-g6e5399 @ ~/.emacs.d/straight/build/org-plus-contrib/)

org version:
Org mode version 9.4 (release_9.4-137-g6e5399 @ ~/.emacs.d/straight/build/org/)

**Comment by progfolio** [comment]
> ;;this doesn't work (with or without the ' )

You don't want to quote the package name when passing it to use-package as it's a macro. 
Doing so will cause a parsing failure.

**Comment by progfolio** [comment]
nettoyoussef <notifications@github.com> writes:

> I could not find how to output straight-version.
> I tried adding:
>  ```lisp
> (setq straight-repository-branch "develop")
> ```
> But still could not find anything with this name using `C-h c`.

This means you're not on the develop branch.

```emacs-lisp
(setq straight-repository-branch "develop")
```

needs to go before straight's bootstrapping code:

```emacs-lisp
(setq straight-repository-branch "develop")
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" 
       user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
```

> Instead of using a init.el to tangle a config.org, I changed to 
> a manually tangled init.el, adding:
> ```lisp
> #+PROPERTY: header-args :tangle init.el
> ```
> At the top of my config.org file, and generating a init.el with 
> `org-babel-tangle`.
> So everything now lives on a single file, and I don't need to 
> load a org file anymore.

This is a better approach. Personally, I just have a config.org 
which tangles to init.el. You can set a buffer-local, 
after-save-hook function to tangle/reload the file if you want to 
have the changes reflected immediately. I also use a command line 
script to bootstrap the whole thing on a new machine:

https://github.com/progfolio/.emacs.d/blob/master/init-dev.el
https://github.com/progfolio/.emacs.d/blob/master/emacs-batch-tangle

> This solved the problems with the hooks.
> But the functions in the `:config` part of the `(use-package 
> org)` are still not being loaded:
>
> ```lisp
> #+BEGIN_SRC emacs-lisp
> (use-package org-plus-contrib
>   :straight t
> )
> #+END_SRC
>
> ```

Since you've set `straight-use-package-by-default` to `t`, you can 
skip the `:straight` keyword here.
However, for other use-package declarations for Org packages, 
you'll want to add either a `straight: nil` or `straight: 
org-plus-contrib` (which is a no-op after the first install). 
Otherwise straight will try to install the package (and most 
likely fail as a recipe doesn't exist). For example:


```emacs-lisp
;;straight-use-package-by-default is t
(use-package org-capture)
```

Expands to:

```
(progn
  ;; This will fail!
  (straight-use-package 'org-capture)
  (require 'org-capture nil nil))
```

While:

```emacs-lisp
;;straight-use-package-by-default is t
(use-package org-capture :straight nil)
```

Expands to:

```emacs-lisp
(require 'org-capture nil nil)
```

**Comment by nettoyoussef** [comment]
> This means you're not on the develop branch. ```emacs-lisp (setq straight-repository-branch "develop") ``` needs to go before straight's bootstrapping code: ```emacs-lisp (setq straight-repository-branch "develop") (defvar bootstrap-version) (let ((bootstrap-file (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory)) (bootstrap-version 5)) (unless (file-exists-p bootstrap-file) (with-current-buffer (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straight.el/develop
/install.el" 'silent 'inhibit-cookies) (goto-char (point-max)) (eval-print-last-sexp))) (load bootstrap-file nil 'nomessage)) ```

Well, I did exactly that, and just tried again with your version, I still could not find it.
I just see `straight-thaw-versions` and `straight-freeze-versions`.


> This is a better approach. Personally, I just have a config.org which tangles to init.el. You can set a buffer-local, after-save-hook function to tangle/reload the file if you want to have the changes reflected immediately. I also use a command line script to bootstrap the whole thing on a new machine: https://github.com/progfolio/.emacs.d/blob/master/init-dev.el https://github.com/progfolio/.emacs.d/blob/master/emacs-batch-tangle

Thanks! I liked your approach.
I ended up adding this local variables at the end of my config file (from [here](https://raw.githubusercontent.com/joseph8th/literatemacs/master/README.org) ):

```lisp
# Local Variables:
# eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)))
# End:
```


> Since you've set `straight-use-package-by-default` to `t`, you can skip the `:straight` keyword here. However, for other use-package declarations for Org packages, you'll want to add either a `straight: nil` or `straight: org-plus-contrib` (which is a no-op after the first install). Otherwise straight will try to install the package (and most likely fail as a recipe doesn't exist). For example: ```emacs-lisp ;;straight-use-package-by-default is t (use-package org-capture) ``` Expands to: ``` (progn ;; This will fail! (straight-use-package 'org-capture) (require 'org-capture nil nil)) ``` While: ```emacs-lisp ;;straight-use-package-by-default is t (use-package org-capture :straight nil) ``` Expands to: ```emacs-lisp (require 'org-capture nil nil) ```

I tried again the code with `org-plus-contrib` with the approach you said, but the problem there persists.
Only when I changed to org (without the contributions), the `:config` part works.
Maybe it is a problem with the package `org-plus-contrib`?

```lisp
;; doesn't load the config part
(use-package org-plus-contrib
  :defer 2
  :init
  ;; set line wrap at 90 characters
  (add-hook 'org-mode-hook '(lambda () (setq fill-column 90)))
  (add-hook 'org-mode-hook '(lambda () (setq display-fill-column-indicator "t")))

  ;; disable evil-auto-indent on org buffers - it reindents 
  ;; every time you add a new line with `o` or `i` + RET
  (add-hook 'org-mode-hook #'ey--org-disable-evil-auto-indent)

  ;; == Agenda Specific Hooks == 

  ;; Agenda post-processing
  ;; Highlight the "!!" for stuck projects (for emphasis)
  (add-hook 'org-agenda-finalize-hook 'gs/org-agenda-project-highlight-warning)

  ;; Remove empty agenda blocks
  (add-hook 'org-agenda-finalize-hook 'gs/remove-agenda-regions)

  :config
  ;; Set org default directories
  (ey--load-org-directory)

  ;; Highlight latex code 
  (setq org-highlight-latex-and-related '(latex script entities))
  
  ;; Display inline images
  (setq org-startup-with-inline-images t)


  ;; change display of verbatim to red highlight
  (add-to-list 'org-emphasis-alist
               '("=" (:foreground "red")
                 ))

  ;; set agenda config
  ;;(setq org-agenda-files '("~/notes/to-do-list.org"))
  (ey--load-org-agenda)

  ;; Toggle smart quotes (org-export-with-smart-quotes).
  ;; Depending on the language used, when activated, 
  ;; Org treats pairs of double quotes as primary quotes, 
  ;; pairs of single quotes as secondary quotes, and single quote marks as apostrophes. 
  (setq org-export-with-smart-quotes t)

  ;; load latex packages for preview
  (ey--load-org-latex-packages)

  ;; babel config
  (ey--load-org-babel-config)
  (ey--load-org-babel-templates)

  ;; org capture templates 
  (ey--load-org-capture-templates)

  ;; Edit size of inline preview of images in latex
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 2.0))

 (defun hello ()
      "Hello World and you can call it via M-x hello."
      (interactive)
      (message "Hello World!"))
)
```
Following your suggestion, I removed the flag `:straight` from esup, and it worked. 

```lisp
;;this doesn't work
(use-package esup
  :straight t
  :config
;; Work around a bug where esup tries to step into the byte-compiled
;; version of `cl-lib', and fails horribly.
;;source: https://github.com/jschaf/esup/issues/54#issuecomment-651247749
 (setq esup-depth 0)
)

;;this works
(use-package esup
  :config
;; Work around a bug where esup tries to step into the byte-compiled
;; version of `cl-lib', and fails horribly.
;;source: https://github.com/jschaf/esup/issues/54#issuecomment-651247749
 (setq esup-depth 0)
)
```
What is the logic in this case? I should probably remove all `straight: t` tags since they appear to be breaking something when
the option `(setq straight-use-package-by-default t)` is set.

Since I already solved my configuration problems, I am closing this issue. Thanks for all the help :)
