### ISSUE TITLE
Error in installation of eshell-syntax-highlighting

### ISSUE THREAD

**Issue by nanounanue** [raxod502/straight.el#642]
## What's wrong
Can't install `eshell-sysntax-highlighting`

## Directions to reproduce

I am trying to install `eshell-syntax-highlighting` using the following:

```
(use-package eshell-syntax-highlighting
  :after esh-mode
  :config
  (eshell-syntax-highlighting-global-mode +1))

```
But I am getting the following error:

```
straight--convert-recipe: Could not find package eshell-syntax-highlighting in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)
```

But the package is in MELPA: https://melpa.org/#/eshell-syntax-highlighting

What I am doing wrong?

### Version information

* Emacs version: GNU Emacs 27.1.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2020-09-05
* Operating system: PopOS 20.10

**Comment by progfolio** [comment]
Perhaps your recipe repository for MELPA needs to be updated?
First `(setq debug-on-error t)`.
Then try `M-x straight-pull-package melpa` before re-evaluating the use-package declaration for eshell-syntax-highlighting. If you get an error or any messages that refer you to the `*straight-process-buffer*`, please copy the entire debug stacktrace and/or process buffer here.

**Comment by progfolio** [comment]
Please also try evaluating the following test case in the `*scratch*` buffer.
It will build straight and attempt to install the minimal set of packages to reproduce your problem in a clean environment.
When it it does, another buffer will pop up which you can copy here.
For me the following test is passing:


<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :pre-bootstrap 
  (setq straight-repository-branch "develop")
  (setq straight-use-package-by-default t)
  :post-bootstrap 
  (straight-use-package 'use-package)
  (use-package eshell-syntax-highlighting))
```
</details>

- Test run at: `2020-12-03 00:19:23`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 3277e1c 2020-11-24`
- emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.3, Xaw3d scroll bars)
 of 2020-11-24`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 3277e1c 2020-11-24
Cloning use-package...
Cloning use-package...done
Building use-package...
Building use-package → Building bind-key...
Building use-package → Building bind-key...done
Building use-package...
Building use-package...done
Cloning eshell-syntax-highlighting...
Cloning eshell-syntax-highlighting...done
Building eshell-syntax-highlighting...
Building eshell-syntax-highlighting...done

```
</details>

**Comment by nanounanue** [comment]
That fixed. Thank you. I was trying to run `straight-pull-package RET eshell-syntax-highlighting RET` without success, but now I can see that I need to use the repo name, not the package name. 

My mistake

**Comment by progfolio** [comment]
`straight-pull-package` should work for `eshell-syntax-highlighting` once the recipe is found, but if new packages are added to any recipe repositories (e.g. MELPA), you'll have to pull that recipe repository first. Glad you got it worked out. Thank you.
