### ISSUE TITLE
Suggestion : make byte-compile output optional

### ISSUE THREAD

**Issue by gagbo** [raxod502/straight.el#644]
I'm specifically thinking about the progress variables 
https://github.com/raxod502/straight.el/blob/f6663b1de0fb5d9c64528e4f7f8bb914f49bb6d2/straight.el#L4339

Basically, having a switch to set a `straight-debug` mode to be able to inspect byte compilation if we want to would be really useful

**Comment by raxod502** [comment]
Yep, seems like a good idea to me.

**Comment by progfolio** [comment]
#657 may obviate the need for such an option, as the byte-compilation output could be redirected to a `straight-byte-compile-buffer`. This could be a defcustom which, when set to `nil`, would simply drop the output.

**Comment by raxod502** [comment]
Yes, that seems like an elegant solution.

**Comment by progfolio** [comment]
@gagbo: Merged #657 which implements a defcustom, `staright-byte-compilation-buffer`.
It defaults to `"*straight-byte-compilation*"`, so you should see all the output in that buffer on the latest develop branch.
