### ISSUE TITLE
Why hasn't this package been published on MELPA?

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#648]
On [MELPA](https://melpa.org/#/), I try to search with `straight` as the filter term but find nothing. So, I want to know why this package hasn't been published on MELPA?

Regards,
HY

**Comment by progfolio** [comment]
Installing straight from MELPA would require the use of a package manager (e.g. Emac's built-in package.el, or any of the various package managers listed here: 

https://github.com/raxod502/straight.el/tree/develop#comparison-to-other-package-managers)

While it may be possible to run more than one package manager, I wouldn't recommend it, as they may conflict with each other.
For example, see: 

https://github.com/raxod502/straight.el#integration-with-packageel

straight.el provides its own bootstrapping code to install istelf here:

https://github.com/raxod502/straight.el#bootstrapping-straightel

I hope that's helpful. If you have any more questions please let me know.

~ Nick

**Comment by hongyi-zhao** [comment]
> straight.el provides its own bootstrapping code to install itself here:
> https://github.com/raxod502/straight.el#bootstrapping-straightel

What about the following method?

Clone the git repo into local machine:

`$ git clone https://github.com/raxod502/straight.el ~/Public/repo/github.com/raxod502/straight.el`

And then add the following snippet into the initialization file fo emacs, say, ~/.emacs.d/init.el:
```
(defun add-subdirs-to-load-path (dir)
  "Recursive add directories to `load-path'."
  (let ((default-directory (file-name-as-directory dir)))
    (add-to-list 'load-path dir)
    (normal-top-level-add-subdirs-to-load-path)))
(add-subdirs-to-load-path "~/Public/repo/github.com/raxod502/straight.el")

(require 'straight)
```

**Comment by raxod502** [comment]
See previous discussion at https://github.com/raxod502/straight.el/issues/134. I would not like to support installing `straight.el` any way other than the bootstrap snippet, for the reasons outlined in that issue. While I could provide a shim package to MELPA which would take care of setting up the bootstrap snippet, the maintainers have declined as a matter of policy: https://github.com/melpa/melpa/issues/4939.

> What about the following general method

This has a number of problems. Firstly I'm not convinced it will actually work at all; `bootstrap.el` takes care of a number of required initialization tasks without which `straight.el` may not function correctly. Probably the self-byte-compilation will be broken. Secondly the ability of `straight.el` to update itself will be broken. Thirdly, you've introduced manual steps into the installation process, which are normally not required. The magic used by the bootstrap snippet to make sure the correct version of `straight.el` is installed as specified in your lockfile, handling all edge cases correctly, is also absent. And I am sure more things will go wrong; these are only the first things that come to mind.

**Comment by hongyi-zhao** [comment]
Got it. It seems that the installation/bootstrapping process of straight.el is complicated to some extent which beyonds my original imagination.

**Comment by raxod502** [comment]
Yeah... it's surprisingly complex, and quite arguably over-engineered. But hey, I made it work, and it does do a lot of cool things that nobody asked for, so there! :P
