### ISSUE TITLE
Packages don't work when the default branch isn't named master

### ISSUE THREAD

**Issue by riscy** [raxod502/straight.el#650]
Hello,

Apologize if I'm misinformed, but I'm coming from https://github.com/melpa/melpa/pull/7269 where it sounds like straight.el does not support pulling packages when the default branch isn't specified, but defaults to something that isn't `master`.  For example, `main`.  This has caused package authors such as the one linked to put workarounds in their recipes:

- https://github.com/melpa/melpa/pull/7269
- https://github.com/melpa/melpa/pull/7274
- https://github.com/melpa/melpa/issues/7204
- https://github.com/melpa/melpa/pull/7246

I have used and enjoyed straight.el in the past, but I'm not currently an active user, so I'm unable to file a proper bug report or confirm the problem.  Maybe someone can help confirm this and provide more details.  And if I'm mistaken, close this immediately! :)

**Comment by progfolio** [comment]
Thanks for bringing this to our attention. This should be a non-issue on the development branch of straight as of #543/#630.

**Comment by raxod502** [comment]
Seems like this is coming up more and more. I originally thought it was a niche thing but I guess not. We might want to port this from develop to master, along with any associated bugfixes, or just do another merge. I don't currently have the bandwidth but you could do it perhaps.

**Comment by raxod502** [comment]
Happy to advise though!

**Comment by progfolio** [comment]
I'd like to fix #624 by implementing #76 before the next merge.
I have a WIP branch, but it raises some design questions.
I'll gather my thoughts  on that in another PR.

**Comment by progfolio** [comment]
Think that should take care of it. Test case in #651 passed all repos mentioned in MELPA issues.

**Comment by riscy** [comment]
Thanks so much for this - I've followed up with the original PR author.

**Comment by raxod502** [comment]
By the way, feel free to do as you see fit with the release process @progfolio. I go through all of my projects every three months, in an effort to stop myself from drowning in my sea of chores, but more frequent attention never hurts. I guess in practice what this means is feel free to backport anything from develop to master that seems like it will improve stability more than it will break things, and feel free to do a full merge whenever seems appropriate.
