### ISSUE TITLE
Revamp build keywords

### ISSUE THREAD

**Issue by progfolio** [raxod502/straight.el#659]
While working on #658, I noticed there is no `:no-info` build keyword to prevent straight from compiling the texinfo for a package.
Implementing this keyword is simple enough, but thinking about it gave me an idea: Rather than having individual `:no-` keywords to control different aspects of a package build, we could  have a `:build` keyword which operates like the `:files` directive.
Allowed values could be:

- `:build nil`  
  which replaces `:no-build`
- a list of symbols specifying which build steps to execute, e.g. `:build (autoloads compile native-compile info)`. 
Steps are executed in the order they are declared. In the future, we could make these steps asynchronous and allow a syntax to specify callbacks. e.g. given `:build ((one two) (three four))` each pair is run asynchronously with `two` executing after `one` and `four` after `three`. 
- a list of symbols prefixed by `:not` to prevent a build step, e.g. `:build (:not compile native-compile)`. These would inherit from a default list of build steps.

Admittedly, this costs a few more characters than the `:no-` prefixed keywords, but it simplifies the list of build keywords and (when combined with #654) clarifies straight's notion of building a package.

It also opens the door for extensibility. We could enforce a naming scheme for these build step functions similar to the naming scheme for recipe-repository functions. Adding a new step would be a matter of implementing that function and inserting it in the `:defaults` list.

Hope that was clear. Here's a final example which illustrates what  `org-plus-contrib`'s recipe could look like when combined with #654:

```emacs-lisp
(org-plus-contrib :type git
                  :repo "https://code.orgmode.org/bzg/org-mode.git"
                  :local-repo "org"
                  :files (:defaults "contrib/lisp/*.el" "lisp/*.el")
                  :pre-build ("make" "autoloads" "EMACS=/usr/bin/emacs")
                  :build (:not autoloads)
                  :post-build (message "example"))
```

Thoughts?

**Comment by raxod502** [comment]
Excellent! This is a great improvement.
