### ISSUE TITLE
Should straight delete the /elpa folder?

### ISSUE THREAD

**Issue by countvajhula** [raxod502/straight.el#663]
Hi there, this is a great package!

I migrated my config to straight and discovered that there were still packages found to be missing in a new environment. It turned out that this was because the `/elpa` directory still contained all of the locally installed packages in the original environment, some of which weren't indicated in the init config.

Should straight do one of the following:
1. delete the /elpa folder, or, as this may be too invasive,
2. unset the `package-user-dir` variable in some way, maybe by setting it to `nil`, since it looks like this path is used by Emacs to find packages (and is set to `~/.emacs.d/elpa` by default)
3. document some other appropriate manual way to handle this

**Comment by progfolio** [comment]
Good question.
I agree that deleting the folder may be a bit much. Say someone just wants to try straight, but decides they like their previous set-up better. A combination of 2 & 3 sound reasonable to me.

**Comment by raxod502** [comment]
Disabling `package.el` is already done automatically out of the box by `straight.el`. However, if you're using Emacs 27 or more recent, then `package.el` is initialized before loading the init-file, which bypasses this mechanism. In that case, you should put

```elisp
(setq package-enable-at-startup nil)
```

into `early-init.el`. See https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html for docs on the early init-file.

The informational content of this comment should be part of the official `straight.el` documentation; see #420.

**Comment by countvajhula** [comment]
I've confirmed that adding that line in `early-init.el` prevents the contents of `/elpa` from being used locally 👍 

I also added this step to [this blog post](https://countvajhula.com/2020/12/27/turn-your-emacs-d-into-an-emacs-distribution-with-straight-el/) on the subject (please let me know if I missed anything 🧛  ).
