### ISSUE TITLE
Cannot install eglot with straight-use-package

### ISSUE THREAD

**Issue by alfons4966** [raxod502/straight.el#672]
Dear Radon,

I cannot install `eglot`. This is not due to `straight`. This is not a bug report. But `eglot `uses an external package version of `project`, not the built-in `project` package (without version number and dependencies) and they are not the same. Have you any idea what can I do to get `eglot` working?  Note, `eglot` also doesn't work if you install it with `package.el`, but that changes if you follow this with a package-initialize.  I am using Emacs 26.3.

Regards,

Anton Moolenaar

**Comment by progfolio** [comment]
Please see: https://github.com/raxod502/straight.el/issues/551

**Comment by alfons4966** [comment]
Manually loading the correct `project.el` file solves the issue.

**Comment by marcora** [comment]
I still have this problem even after upgrading to Emacs 27.1

Is there a fix for this issue? Manually loading the package is not really a solution.

**Comment by progfolio** [comment]
@marcora: We'll need more information to help.
Can you provide:

- The errors/behavior you are seeing.
- Output of `M-x straight-version`
- A minimal init file or `straight-bug-report` form to reproduce the error.

**Comment by marcora** [comment]
This is the error that I am seeing when loading a Python or R file, for which I have eglot configured to start automatically. Everything works fine when using package.el to install packages.

`
Error in post-command-hook (#[0 "\303\304\301\242\305#\210\300\306!\205r\211q\210
?\205\307\310\311 \")\207" [#<buffer test.R> (#0) eglot--managed-mode remove-hook post-command-hook nil buffer-live-p apply eglot--connect eglot--guess-contact] 4]): (cl-no-applicable-method project-root (transient . "/Users/XXX/tmp/"))
`

`
Error in post-command-hook (#[0 "\303\304\301\242\305#\210\300\306!\205r\211q\210
?\205\307\310\311 \")\207" [#<buffer test.py> (#0) eglot--managed-mode remove-hook post-command-hook nil buffer-live-p apply eglot--connect eglot--guess-contact] 4]): (cl-no-applicable-method project-root (transient . "/Users/XXX/tmp/"))
`

straight-version -> `prerelease (HEAD -> master, origin/master, origin/HEAD) 2d407bc 2020-12-20`

the following is how I install and config eglot in my init.el
`
(use-package eglot
  :commands eglot
  :hook ((python-mode-hook . eglot-ensure)
         (ess-r-mode-hook . eglot-ensure)
         (haskell-mode-hook . eglot-ensure)))
`

**Comment by progfolio** [comment]
Try evaluating the following in your scratch buffer:

```emacs-lisp
(straight-bug-report
  :user-dir "eglot.test"
  :interactive t
  :pre-bootstrap
  (setq straight-repository-branch "develop")
  (setq straight-use-package-by-default t)
  :post-bootstrap
  (straight-use-package 'use-package)
  (use-package eglot
    :commands eglot
    :hook ((python-mode-hook  . eglot-ensure)
           (ess-r-mode-hook   . eglot-ensure)
           (haskell-mode-hook . eglot-ensure))))
```
It should install straight.el and eglot in a clean environment.
It will launch a second, interactive Emacs instance.
You can try editing a python file from that instance.
If you hit any errors, copy them here.

**Comment by marcora** [comment]
It works! No errors

**Comment by progfolio** [comment]
That's good to hear. There's a number of factors I would try out.
First I would recommend upgrading to the "develop" branch of straight.el.
You can do that by adding:

```emacs-lisp
  (setq straight-repository-branch "develop")
```

Before the straight bootstrapping code in your init file.
Then you would can run `M-x straight-normalize-package straight`, and rebuild straight.el either with `straight-rebuild-package` or by restarting Emacs.

If the issue persists after this, it may either by an issue with your configuration or (possibly) stale byte-compiled code. I'd rebuild eglot and any packages interacting with it first, and then try bisecting your init to find the source of the error.

**Comment by marcora** [comment]
thanks for your help
