### ISSUE TITLE
Sourcing from custom recipe

### ISSUE THREAD

**Issue by agsdot** [raxod502/straight.el#68]
(use-package projectile
  :ensure t
  :recipe (:fetcher github
           :repo "abo-abo/projectile"))

doesn't source projectile from abo-abo's fork.

Rather I get 
Warning (initialization): An error occurred while loading ‘/home/userdirectory/.emacs.d/init.el’:

error: Command failed: git clone --origin origin --no-checkout abo-abo/projectile (output: "fatal: repository 'abo-abo/project\
ile' does not exist
") (default-directory: "/home/userdirectory/.emacs.d/straight/repos/")

++++

Using straight.el off the develop branch.
System: archlinux

The other packages install just fine. Just not off of the recipe fetcher option.

**Comment by agsdot** [comment]
Closing issue. 

The new / more up to date documentation in the README.md helped me get this working:

(use-package projectile
  :ensure t
  :recipe (projectile :type git :host github :repo "abo-abo/projectile"))

**Comment by raxod502** [comment]
Oh, dear. I hadn't realized that I wasn't being notified about issues on this repository. Sorry about that, glad you figured it out!

**Comment by raxod502** [comment]
Oh, and because I haven't gotten to writing the user manual yet (which covers the new recipe format in full detail), check out https://github.com/raxod502/straight.el/issues/37#issuecomment-307639746.

**Comment by agsdot** [comment]
You're updated README.md in the develop branch led me to the correct solution.

Looking forward to your updates of the [FIXME](https://github.com/raxod502/straight.el/blob/master/FIXME) temporary links.

Great work by the way. Really enjoying following this project. I look forward to inspecting the [Radian](https://github.com/raxod502/radian) to see your history of commits and the evolution of going from package.el to straight.el .
