### ISSUE TITLE
Package does not work when compile

### ISSUE THREAD

**Issue by ram535** [raxod502/straight.el#682]
I installed [pair-tree](https://github.com/zainab-ali/pair-tree.el) package.
With `:no-byte-compile t` the package work.
Without `:no-byte-compile t` the package does not work.

I was expecting that the package would work when it is compile.

```
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq straight-use-package-by-default t)

(use-package pair-tree
:straight (pair-tree :type git
                     :host github
                     :repo "zainab-ali/pair-tree.el"
                     :no-byte-compile t))

```

```
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-03-09
```
@zainab-ali
zainab-ali/pair-tree.el#1
Thanks

**Comment by progfolio** [comment]
Please be specific. What do you mean when you say "the package does not work"? Are any errors thrown? How are you attempting to use the package and what happens?

**Comment by progfolio** [comment]
I've adjusted the regexp we were using to detect package dependencies.
On the develop branch, straight should properly build dash as a dependency of pair-tree (assuming it hasn't already been installed explicitly or as a dependency of another package).
The following interactive test case works when I try using `M-x pair-tree`:

```emacs-lisp
(straight-bug-report
  :user-dir "pair-tree-test.straight"
  :interactive t
  :pre-bootstrap
  (setq straight-repository-branch "develop")
  :post-bootstrap
  (straight-use-package '(pair-tree :type git
                                    :host github
                                    :repo "zainab-ali/pair-tree.el")))
```

@ram535 what is the output of `M-x straight-version`?

**Comment by ram535** [comment]
Thanks, it works now with your change.

```
prerelease (HEAD -> master, origin/master, origin/HEAD) 2d407bc %cs
```
