### ISSUE TITLE
Mirrored version of TRAMP hangs when using /sudo::

### ISSUE THREAD

**Issue by rileyrg** [raxod502/straight.el#687]
trying to sudo-edit a file (the /etc/hosts file as good as any) on my setup results in emacs hanging when using emacs 27.1 on Debian and the Tramp it ships with, also using the one in emacs-straight.  Typing "/sudo::" at the find file prompt locked up emacs at the typing of the second colon. Using selectrum with prescient btw. My authinfo had the correct root credentials. 

I  downloaded the elpa version  2.5 and everything works. Took a long time to find this so I'm happy to have it working. 

Just an "FYI", as I don't have the time to do a bar bones repro of this issue, especially with something as complex as tramp ;)  Maybe this will help someone else if they get the same issue.

**Comment by progfolio** [comment]
Considering this issue does not seem to affect many users and we have no reproduction case, I'm closing this issue.
If anyone can provide a reproduction case or feels this needs to be opened again, comment and we can open this issue.

**Comment by raxod502** [comment]
Yeah, I'm guessing this is just a case of the version of TRAMP being installed by the two package managers is slightly different---probably nothing to do with the actual packaging.
