### ISSUE TITLE
To hide straight-process buffer by default

### ISSUE THREAD

**Issue by bataak** [raxod502/straight.el#703]
Hello,

I wanted to disable *straight-process* buffer by default and tried to customize with adding a leading space to the name nothing happened. Would you mind correcting me?
```
(custom-set-variables
 '(straight-process-buffer " *straight-process*"))
```
Thanks in advance!

**Comment by raxod502** [comment]
Well, the easiest way is to avoid Customize:

```elisp
(setq straight-process-buffer " *straight-process*")
```

**Comment by bataak** [comment]
I've tried both but same result. If I understood you correctly this code will disable *straight-process* buffer when emacs initializes, right?

**Comment by raxod502** [comment]
Well, you need to set that variable _before_ bootstrapping `straight.el`.

**Comment by bataak** [comment]
Got it. Thank you. Now it works!
