### ISSUE TITLE
Spurious rebuilds of packages with :pre-build commands

### ISSUE THREAD

**Issue by haji-ali** [raxod502/straight.el#712]
I have the following `use-package` statement

```elisp
(use-package mu4e
  :demand t
  :straight `(:fork (:host github
                     :repo "haji-ali/mu"
                     :branch "al/private")
              :pre-build
              (("./autogen.sh" ,(format "--prefix=%s/.local" (getenv "HOME"))) ("make" "install"))
              :files ("mu4e/*.el"))
```

When I execute the command in emacs (using `eval-region` or as part of my init file) the package is built and after a few minutes seems to be in working order. Inspecting `*straight-process*`, I see that the commands I specified in `:pre-build` ran successfully. However, when I gracefully exit emacs and restart it, the package is built again when the previous command is executed! In other words the `:pre-build` commands are run again and I have to wait a few minutes for them to complete. The buffer `*straight-process*` does not report any errors and inspecting `straight/build/mu4e` I see the linked el files (with their `elc` compilation). Note that I am not changing the files in the repo at all so I wouldn't expect a re-building step.

How does `straight.el` decide that a package needs rebuilding? I want to troubleshoot this issue but I am not sure where to look first.

EDIT: When running
```
(gethash "mu4e" straight--build-cache)
```
after restarting Emacs, I get nil. Before restarting emacs, and after building mu4e, I get the expected 
```
(("./autogen.sh" "--prefix=/home/abdo/.local") ("make" "install")) :files ("mu4e/*.el") ...))
```

So for some reason the build cache is not being saved/read correctly. In fact, checking the value of `straight--build-cache` I see that there's no mention of mu4e. Similarly, grepping for `mu4e` in `straight/build-cache.el` returns nothing. This is incredibly weird. I am using Radian to configure my Emacs, so I am not sure if there's some extra configuration that I should be aware of.

Unfortunately, `straight-bug-report` doesn't show this problem.

<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "org-rebuild-test.straight"
  :preserve t
  :post-bootstrap 
  (straight-use-package
   `(mu4e :fork
          (:host github :repo "haji-ali/mu" :branch "al/private")
          :pre-build
          (("./autogen.sh" ,(format "--prefix=%s/.local"
                                    (getenv "HOME")))
           ("make" "install"))
          :files
          ("mu4e/*.el"))))
```
</details>

- Test run at: `2021-03-08 18:15:48`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) ac4df5c 2021-01-26`
- emacs-version: `GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)
 of 2020-09-14`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) f88f828 2021-03-06
Cloning mu (for mu4e)...
Cloning mu (for mu4e)...done
Building mu4e...
Building mu4e...done

```
</details>

Second run
<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "org-rebuild-test.straight"
  :preserve t
  :post-bootstrap 
  (straight-use-package
   `(mu4e :fork
          (:host github :repo "haji-ali/mu" :branch "al/private")
          :pre-build
          (("./autogen.sh" ,(format "--prefix=%s/.local"
                                    (getenv "HOME")))
           ("make" "install"))
          :files
          ("mu4e/*.el"))))
```
</details>

- Test run at: `2021-03-08 18:16:38`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) ac4df5c 2021-01-26`
- emacs-version: `GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)
 of 2020-09-14`

<details><summary>Output</summary>

```emacs-lisp
Test run with version: prerelease (HEAD -> develop, origin/develop) f88f828 2021-03-06

```
</details>

**Comment by raxod502** [comment]
Documentation at:

* https://github.com/raxod502/straight.el#how-does-straightel-know-when-to-rebuild-packages
* https://github.com/raxod502/straight.el#customizing-when-packages-are-built

I've noticed that this has started to happen for Org recently. What I believe is happening is that the `:pre-build` command is modifying files in the repository itself, and those modifications are detected at next startup, leading to an additional, spurious rebuild.

Now `straight.el` writes a timestamp to the build cache when it builds a package---the package is detected as having modifications if there are changes more recent than that timestamp. We have two cases:

* Eager modification detection with `find(1)`: we need to make sure that the timestamp is computed and written to the build cache _after_ the `:pre-build` command, if any, is executed
* Live modification detection with `watchexec`: the filesystem watcher writes a file to `~/.emacs.d/straight/modified` when it detects a modification; we need to make sure that those files are cleared after the `:pre-build` command is executed. There might be a race condition in which the filesystem watcher is a bit asynchronous, and so those files end up getting written _after_ the directory is cleared out, even though the corresponding modifications that caused the files to get written were made _before_ the directory was cleared out. See the debounce argument `-d` at https://github.com/raxod502/straight.el/blob/f88f828f8d36d3cb94158b3ebc1f35295203185e/watcher/straight_watch.py#L50

We might want to set a timer to clear out the directory asynchronously after 200ms or something. Feels kinda bad, though---open to better suggestions.

**Comment by progfolio** [comment]
> What I believe is happening is that the `:pre-build` command is modifying files in the repository itself, and those modifications are detected at next startup, leading to an additional, spurious rebuild.

That stands to reason. I'll experiment to see if I can find a test case to reliably trigger this so we have something consistent to test against.

We also have `:post-build` commands which could do the same, I suppose. I've yet to see this in the wild, but it would be prudent to guard against the same issue cropping up there. So it would probably be best to write the time to the build-cache as late as possible.

The watchexec case sounds trickier and I agree we should try to think of something cleaner than calling a timer. I'll think on it and experiment to see if I can come up with anything.

**Comment by haji-ali** [comment]
While this is being investigated, what is a workaround to avoid a rebuild on every Emacs start?

**Comment by progfolio** [comment]
If you could create a minimal repro using `straight-bug-report` that whould be ideal.

**Comment by haji-ali** [comment]
> If you could create a minimal repro using `straight-bug-report` that whould be ideal.

Unfortunately, I haven't been able to reproduce this using `straight-bug-report` for some reason.
The problem is I don't know what is causing the rebuild. Which flag is being reset that is triggering this rebuild?

**Comment by progfolio** [comment]
What is the value of `straight-check-for-modifications`?

**Comment by haji-ali** [comment]
OK, after tracking how `straight-check-for-modifications` was being used, I figured out why the rebuilding is happening in my case. I am sorry to say it was completely my fault. 

My `use-package` statement was in a file which was lazy loaded and my Radian config was calling `straight-prune-build-cache` when emacs starts. This caused the build commands to be deleted from the build cache and a rebuild to happen the next time the file is loaded and the `use-package` statement is executed. 

I think printing a message when a package is pruned would be pertinent, considering how easy it is to run into such a situation while everything seemingly "works".

**Comment by progfolio** [comment]
I haven't found a way to reproduced the original issue. Closing for now. We can reopen if anyone else experiences this or is able to reproduce it.
