### ISSUE TITLE
Symbol’s value as variable is void: comp-ctxt (native-comp)

### ISSUE THREAD

**Issue by jdm204** [raxod502/straight.el#717]
## Issue
straight.el gives an error on the latest gccemacs:

`memq: Symbol’s value as variable is void: comp-ctxt`

running emacs with `./src/emacs -Q -l init.el`

where `init.el` just contains the straight.el bootstrap lines.

## Versions
Emacs native-comp: 79c83f79c5b618cb9ef5eca7be2245f15ff54626
System: Ubuntu 20.10

**Comment by progfolio** [comment]
This is likely an upstream bug. Please start Emacs with `emacs --debug-init` and copy the full backtrace buffer here.

**Comment by progfolio** [comment]
Thanks for the backtrace. My suspicion was correct. You should file a bug report upstream including that backtrace.

**Comment by maurelio1234** [comment]
Hi, @jdm204  was a bug filed somewheree else? Is there a link for that?
I'm trying to test the master emacs now that the native comp was merged, but i'm blocked by that.
Thanks in advance,

**Comment by AdamAtGradient** [comment]
I've just run into this bug today (4/27/21) with the newest 28.0.50 build for ubuntu. I too would be interested in where this bug was actually filed @jdm204. Thanks!

**Comment by jdm204** [comment]
Hi both, I never filed a bug upstream, I couldn’t find a gitlab/hub and couldn’t get the report-bug inside emacs to send and gave up (I’m a biologist with no software background) sorry!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
