### ISSUE TITLE
How use `:config` with straight.el?

### ISSUE THREAD

**Issue by LinArcX** [raxod502/straight.el#723]
We know that when we're working with **use-package**, we can configure a particular package with: **:config** (like [this](https://emacs-lsp.github.io/lsp-mode/page/installation/#use-package)). How do the same thing in straight.el?

**Comment by progfolio** [comment]
straight.el integrates with use-package by adding the `:straight` keyword. See the documentation here:

https://github.com/raxod502/straight.el/tree/develop#integration-with-use-package

If you're asking if it's possible to do something similar *without* use-package, straight can be used to install packages via `straight-use-package` and the configuration code can be written in elisp. e.g.

```emacs-lisp
(straight-use-packge 'example)
(eval-after-load 'example
;;configuration goes here
)
```
