### ISSUE TITLE
What recipe for emacs-w3m?

### ISSUE THREAD

**Issue by WorldsEndless** [raxod502/straight.el#730]
I'm trying to use emacs-w3m and get `Error (use-package): Cannot load emacs-w3m`. I have installed the Linux repos and do seem to have emacs-w3m available on my system, but the Straight recipe won't load. I don't see anyone with a sample emacs-w3m invocation online. Any ideas? 

https://github.com/emacs-w3m/emacs-w3m

``` lisp
(use-package emacs-w3m
  :straight (emacs-w3m :type git :host github :repo "emacs-w3m/emacs-w3m")
  :demand w3m-load
  :custom
  (w3m-search-default-engine "duckduckgo")
  )
```

**Comment by progfolio** [comment]
Evaluate the following test case in a buffer with lexical binding enabled (\*scratch* will work fine for Emacs >= 27.1) and copy the results in this thread:


<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :pre-bootstrap 
  (setq straight-repository-branch "develop")
  :post-bootstrap 
  (straight-use-package 'emacs-w3m))
```
</details>

- Test run at: `2021-03-31 09:48:56`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop, fix/spurious-rebuilds) 626537c 2021-03-18`
- emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-03-24`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 770bbc6 2021-03-21
Cloning emacs-w3m...
Cloning emacs-w3m...done
Building emacs-w3m...
Building emacs-w3m...done

```
</details>

**Comment by progfolio** [comment]
straight.el has support for el-get recipes on the "develop" branch. That recipe works fine as shown in the above test case. Part of the problem with your use-package statement is that you're using emacs-w3m (the repo name) as the provided package name. Even so, emacs-w3m has a build step for installation (I haven't looked to see exactly what it is, so I can't comment on whether or not it's totally necessary).

The following should work on the "develop" branch of straight:

```emacs-lisp
(use-package w3m :straight emacs-w3m)
```

If you want to bypass the el-get recipe, something like this should work as well:

```emacs-lisp
(use-package w3m
  :straight (emacs-w3m :type git :host github :repo "emacs-w3m/emacs-w3m" :pre-build
                       (("autoconf")
                        ("./configure" "--with-emacs=/usr/bin/emacs")
                        ("make"))
                       :files
                       (:defaults)))
```

Does that help?

**Comment by progfolio** [comment]
Any luck with this @WorldsEndless ?

**Comment by WorldsEndless** [comment]
Yes, thank you very much! Here is what I've been using for a the past month, thanks to your stuff: 

```lisp
  (use-package w3m
    :straight (emacs-w3m :type git :host github :repo "emacs-w3m/emacs-w3m")
    :bind (("C-x M-e" . tsa/transient-w3m)
	   :map w3m-mode-map
	   ("e" . tsa/transient-w3m)
	   ("M-o" . ace-link-w3m))
    :demand w3m-load
    :custom
    (w3m-search-default-engine "duckduckgo")
    (w3m-quick-start nil)
    (w3m-display-mode 'plain)
    (w3m-use-title-buffer-name t))
```
