### ISSUE TITLE
Fix test deciding to native-compile

### ISSUE THREAD

**Issue by thierryvolpiatto** [raxod502/straight.el#742]
## What's wrong

The test you are using is no more working since native-compile have been merged in emacs master.

## Directions to reproduce

Rebuild your emacs without --with-native-compilation, restart emacs, straight will try to rebuild packages with native-compilation which is no more available.

```diff
diff --git a/straight.el b/straight.el
index 3915e86..2bec43f 100644
--- a/straight.el
+++ b/straight.el
@@ -4837,7 +4837,8 @@ function only modifies the build folder, not the original
 repository. Also note that native compilation occurs
 asynchronously, and will continue in the background after
 `straight-use-package' returns."
-  (when (and (fboundp 'native-compile-async)
+  (when (and (fboundp 'native-comp-available-p)
+             (native-comp-available-p)
              (member 'straight--build-compile straight--build-functions))
     (require 'comp)
     (straight--with-plist recipe (package)
```

### Version information

* Emacs version: emacs-28.0.50
* Operating system: Linuxmint

**Comment by progfolio** [comment]
Thanks for bringing this to our attention, Thierry.
I've applied a variation on your suggested patch (we still need to keep the fboundp check for `native-compile-async` to quiet the byte-compiler).
