### ISSUE TITLE
Unclear error message when using :host with full :repo

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#746]
Suppose you specify `:host github` and `:repo "https://git.savannah.gnu.org/git/hyperbole.git"` in a recipe. (It may not be obvious to the user that this is happening, in the case that `:host github` is inherited implicitly from the default recipe; see #745.)

In this case `straight.el` will attempt to clone a Git repository at `git@github.com:https://git.savannah.gnu.org/git/hyperbole.git.git`, which results in Git failing with `fatal: protocol 'git@github.com:https' is not supported`.

It would be a much better user experience to detect that `https://git.savannah.gnu.org/git/hyperbole.git` is not a valid name for a GitHub repository, and report an error earlier, rather than just blindly constructing a URL and passing it to Git.

**Comment by progfolio** [comment]
Agreed. I've been bitten by this myself.
