### ISSUE TITLE
How to switch repos on an existing package? 

### ISSUE THREAD

**Issue by WorldsEndless** [raxod502/straight.el#751]
I just had an issue in which I changed the repo of a packing I had been using (use-package) to a fork of it. Making that change in Straight proved that either there needs to be an easy way, or I need to know the easy way. Due to conflicting recipes I ended up changing the use-package statement (expected), editing the straight cache file (ugh), manually deleting folders in `/repos` and `/builds`, and restarting emacs.

How should one go about switching repos on an already used package without all this to-do?

**Comment by progfolio** [comment]
You should not need to edit the cache file or delete any folders.
After changing the recipe, re-evaluate the form containing the call to `straight-use-package` (or the use-package form if you're using that). Then execute `M-x straight-normalize-package` for that package. This should reconfigure the repository using the latest registered recipe. Please let us know if this does not work for you.

**Comment by WorldsEndless** [comment]
Ah! `straight-normalize-package` was the missing link! Thanks!
