### ISSUE TITLE
Changes in org-plus-contrib

### ISSUE THREAD

**Issue by alastairdb** [raxod502/straight.el#753]
## What's wrong

As indicated by a [message](https://orgmode.org/list/87v97ys26s.fsf@bzg.fr/T/#mdc7ef84ba10dd8ffd62178c74d652a2046dfceb7) to the org mailing list the contrib packages for org have been split off. Using org-plus-contrib as the package name with straight now pulls in the main org files but not the contrib ones. See also [reddit discussion](https://www.reddit.com/r/orgmode/comments/n56fcv/important_the_contrib_directory_now_lives_outside/)

The recommended sources for the install are now:

- https://code.orgmode.org/bzg/org-mode.git files lisp/*.el etc/styles/*

- https://git.sr.ht/~bzg/org-contrib files lisp/*.el

So the recipe returned by straight-recipes-org-elpa-retrieve must get code from two repos or org-plus-contrib must be split into two separate packages org and org-contrib
 
## Directions to reproduce

1. Fresh emacs
2. Use `(use-package org :straight org-plus-contrib ...)`
3. The main org files are in straight/build but not the contrib files

### Version information

* Emacs version:
* Operating system:

**Comment by progfolio** [comment]
Please include the output of `straight-version` at a minimum when reporting bugs.

I posted the reddit thread you've linked.
The org-elpa recipe repo has been updated on the develop branch:

https://github.com/raxod502/straight.el/commit/9eb2e058665ad1144c66d2b1b816f9effa37907e

You'll need to update your config to make use of the "org-contrib" recipe. If you are not on the develop branch you can use the recipe from above manually (the change has not been backported to the master branch yet).
