### ISSUE TITLE
EmacsGcc, Packages installed by straight are not natively compiled

### ISSUE THREAD

**Issue by d1egoaz** [raxod502/straight.el#755]
Hello

I'm trying to find the cause why packages installed by straight are not natively compiled.

I'm using `(setq straight-repository-branch "develop")`

My system packages are natively compiled, i.e:
```lisp
indent-region is an interactive and natively compiled function defined
in indent.el.gz.
```

Straight package is natively compiled:
```lisp
straight-vc-clone is a natively compiled function defined in
straight.el.
```

However, none of the packages installed by straight are natively compiled:
```lisp
evil-find-file-at-point-visual is an interactive and compiled function
defined in evil-commands.el.
helpful-mode is an interactive and compiled function defined in
helpful.el.
```

After reading the readme, my expectation is that these installed packages are natively compiled:
> When running on this version of Emacs, straight.el will perform native compilation of packages.

I can see in the directory `eln-cache` the natively compiled resource for all my packages, but I'm not sure why Emacs doesn't pick this version 🤷

Thanks

**Comment by progfolio** [comment]
Please include the output of the `straight-version` command.

**Comment by d1egoaz** [comment]
> Please include the output of the `straight-version` command.


```
prerelease (grafted, HEAD -> develop, origin/develop) 6246515 2021-05-05
```

**Comment by progfolio** [comment]
A few more questions:

- Are you using a framework such as Doom or Spacemacs?
- Does this problem persist across restarts of Emacs?
- What are the value of the `comp-deferred-compilation-deny-list` and `comp-deferred-compilation` variables?

**Comment by d1egoaz** [comment]
🤨 

```
comp-deferred-compilation-deny-list is a variable defined in

List of regexps to exclude matching files from deferred native compilation.
```

```
Files whose names match any regexp are excluded from native compilation.

```

**Comment by d1egoaz** [comment]
> 🤨
> 
> ```
> comp-deferred-compilation-deny-list is a variable defined in
> 
> List of regexps to exclude matching files from deferred native compilation.
> ```
> 
> ```
> Files whose names match any regexp are excluded from native compilation.
> ```

ohh it makes sense, as all of the native compiled packages are available in `eln-cache`

**Comment by d1egoaz** [comment]
sorry for the late reply, I've being doing lots of changes, still same issue, but now I don't have compiled packages in eln-cache. Let me check fist my setup, so I can have a stable setup where I can confirm/discard any issues.

Thanks for the help

**Comment by progfolio** [comment]
I've cleaned up some of the native-compile code now that I'm using the native-compilation feature myself.
There was a recent breaking change in comp.el upstream (https://github.com/emacs-mirror/emacs/commit/8bc91a6a3f6cc84f549d24467832f67b3130201d).

Once you've updated Emacs and straight, your packages should be compiling properly.
Testing is appreciated when you have the time. Thanks again.

**Comment by d1egoaz** [comment]
Hey @progfolio 

I've tested the latest changes, and now all packages are loaded with the native compiled version!

Thanks!
