### ISSUE TITLE
straight to manage ESS

### ISSUE THREAD

**Issue by ghowoo** [raxod502/straight.el#756]
I tried to use straight for all packages including ESS. However, it has problems with ESS. I am not sure what is wrong with my setting or with ESS or with straight.

This works:
  (use-package ess
    :defer t
    :init
    (require 'ess-r-mode)
    )

This cause Emacs to hang on r processing and gives ESSR loading error:
(use-package ess
  :straight t
  :init (require 'ess-site)
  )

Thanks.

**Comment by ghowoo** [comment]
With init:

(use-package ess
:straight t
:init (require 'ess-site)
)


When I start a R process, it sends a message saying ESSR loading error, but the actual R process starts. And if I type print(1:3) in the iESS buffer (or in ESS buffer), Emacs hangs on pri for a while. The *ESS*  buffer says:
 current-prefix-arg=nil
(inferior-ess: waiting for process to start (before hook)
(inferior-ess 3): waiting for process after hookDisabling output delimiter because CMD failed to parse (ess-search-list ... ) Disabling output delimiter because CMD failed to parse (ess-search-list ... ) Disabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parse

And the *Messages* buffer says:
Messages while loading ESSR: + + + Error in .ess.ESSR.load("/home/username/.emacs.d/elpa/ess-20200522.920/etc/ESSR/R") : 
  could not find function ".ess.ESSR.load"
ess-command: Timeout during background ESS command  options(STERM='iESS', str.dendrogram.last="'", editor='emacsclient', show.error.locations=TRUE) 
Mark set
next-line: End of buffer [2 times]
Error running timer  ac-update-greedy : (error "Timeout during background ESS command  search() ") [2 times]
Error running timer  ac-update-greedy : (error "Timeout during background ESS command  local({ r <- .ess_get_completions(\"1:\", 2, \" = \"); r[r != '...='] }) ")
Mark set [2 times]
next-line: End of buffer
Mark activated

**Comment by progfolio** [comment]
> "/home/username/.emacs.d/elpa/ess-20200522.920/etc/ESSR/R"

This path indicates that you are installing via package.el.
Ensure that you have followed the directions here:

https://github.com/raxod502/straight.el/tree/develop#getting-started

And here if you are using use-package:

https://github.com/raxod502/straight.el/tree/develop#integration-with-use-package

**Comment by ghowoo** [comment]
Thanks progfolio for help. I think my straight setting is right:


;; use straight to manage packages
(setq package-enable-at-startup nil)
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))


;; use straight to install use-package
(straight-use-package 'use-package)

And I have also set:
;; ensure automatically install pacakges once declared
;; (require 'use-package-ensure)
;; (setq use-package-always-ensure t)

By commenting the above two lines doesn't solve the problem.

I am not sure if the following setting may change anything:
;; automatically update package if needed
(use-package auto-package-update
  :straight t
  :config
  (setq auto-package-update-delete-old-versions t)
  (auto-package-update-maybe)
  )

;;Update Emacs's GPG keyring for GNU ELPA
(use-package gnu-elpa-keyring-update
  :straight t
  )

**Comment by progfolio** [comment]
>  (use-package auto-package-update

This package was designed with package.el in mind. It will not work with straight.el in its current form.
You can update all packages using `M-x straight-pull-all` followed by `M-x straight-rebuild-all`. 

>  (use-package gnu-elpa-keyring-update

Likewise this is not designed to be used with straight.el. I haven't vetted the source, but you should not need it if you are using straight.el for package management.

**Comment by ghowoo** [comment]
I have commented auto-package-update and gnu-elpa-keyring-update, and done M-x straight-pull-all and M-x straight-rebuild-all. But it doesn't solve the problem. So, I have to use the use-package to make it work.
 (use-package ess
:defer t
:init
(require 'ess-r-mode)
)

**Comment by progfolio** [comment]
Is this the current init file you are using?:

https://github.com/ghowoo/dot-emacs

**Comment by ghowoo** [comment]
Currently I set my init private. There are some settings relating to my work. Also, it is messy and I am trying to reorganize it. This is init.el:

;; Make all commands of the  package  module present.
;; (require 'package)

;; Internet repositories for new packages.
;; (setq package-archives '(("org"       . "http://orgmode.org/elpa/")
;;                          ("gnu"       . "http://elpa.gnu.org/packages/")
;;                          ("melpa"     . "http://melpa.org/packages/")))

;; Actually get  package  to work.
;; (package-initialize)
;; (package-refresh-contents)







;; use straight to manage packages
(setq package-enable-at-startup nil)
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))


;; use straight to install use-package
(straight-use-package 'use-package)

;; Bootstrap installing `use-package'
;; (unless (package-installed-p 'use-package)
;;   (package-install 'use-package))
;; (require 'use-package)

;; ensure automatically install pacakges once declared
;; (require 'use-package-ensure)
;; (setq use-package-always-ensure t)


;; automatically update package if needed
;; (use-package auto-package-update
;;   :straight t
;;   :config
;;   (setq auto-package-update-delete-old-versions t)
;;   (auto-package-update-maybe)
;;   )

;;Update Emacs's GPG keyring for GNU ELPA
;; (use-package gnu-elpa-keyring-update
;;   :straight t
;;   )




(when (eq system-type 'windows-nt)
  (org-babel-load-file (expand-file-name "~/.emacs.d/windows_init.org"))
  )

(when (eq system-type 'darwin)
  (org-babel-load-file (expand-file-name "~/.emacs.d/linux_init.org"))
  )

(when (eq system-type 'gnu/linux)
 (org-babel-load-file (expand-file-name "~/.emacs.d/linux_init.org"))
  )

(org-babel-load-file (expand-file-name "~/.emacs.d/myinit.org"))

**Comment by ghowoo** [comment]
And this is linux_init:



* Theme & Face

** Doom Theme

#+begin_src emacs-lisp

     (use-package doom-themes
     :straight t
     :config
     ;; Global settings (defaults)
     (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
     doom-themes-enable-italic t) ; if nil, italics is universally disabled
     (load-theme 'doom-vibrant t)
     ;; Enable flashing mode-line on errors
     (doom-themes-visual-bell-config)
     ;; Enable custom neotree theme (all-the-icons must be installed!)
     (doom-themes-neotree-config)
     ;; or for treemacs users
     (setq doom-themes-treemacs-theme "doom-colors") ; use the colorful treemacs theme
     (doom-themes-treemacs-config)
     ;; Corrects (and improves) org-mode's native fontification.
     (doom-themes-org-config)
     )

   (use-package all-the-icons
     :straight t)

  ;; (use-package zenburn-theme
  ;;   :straight t
  ;; ;
					  ;   :config (load-theme 'zenburn t))


#+end_src

** Pattern
#+BEGIN_SRC emacs-lisp
	    ;; Default values for frame creation
	    ;;(add-to-list 'initial-frame-alist '(fullscreen . maximized))
	    ;; full screen at startup, run the fullscreen function after initilization
	    ;; (add-hook 'after-init-hook #'toggle-frame-fullscreen)
	    
	   
	    ;;; setup appearance
	    (set-frame-font "Ubuntu Mono 16")
	    ;; (set-default-font "Consolas 14")
	
  


  ;; projectile: project interaction
	    (use-package projectile
	    :straight t)
	    (projectile-mode +1)
	    (define-key projectile-mode-map (kbd "C-x p") 'projectile-command-map)

	    ;; make yes/no prompts to y/n
	    (defalias 'yes-or-no-p 'y-or-n-p)

#+END_SRC

** Frame


#+BEGIN_SRC emacs-lisp

  ;; hide title margin on the top
  ;;(setq default-frame-alist '((undecorated . t)))
  ;;(add-to-list 'default-frame-alist '(drag-internal-border . 1))
  ;;(add-to-list 'default-frame-alist '(internal-border-width . 5))

#+END_SRC


* Editing

** Overall
#+BEGIN_SRC emacs-lisp
    ;; rewrite expand-regin with use-package
    ;; highlighted text being selected
    (use-package expand-region
      :straight t
      :bind (("C-=" . 'er/expand-region)
	     ("C--" . 'er/contract-region)
	     )
      )
    ;; replace selected words while editing, not work on iedit
    (delete-selection-mode 1)

    ;; multiple selecting/editing
    (use-package iedit
      :straight t)

  ;; popup kill ring
    (use-package popup-kill-ring
      :straight t
      :bind ("M-y" . popup-kill-ring))
    ;; undo tree
    (use-package undo-tree
      :straight t
      :init
      (global-undo-tree-mode))

    ;;movetext
    (use-package move-text
      :straight t)
    (move-text-default-bindings)
    ;; remove whitespace at the end of lines on save
   ;; (add-hook 'before-save-hook 'delete-trailing-whitespace)




    ;; autopair
    ;; (require 'autopair)
    ;; (autopair-global-mode 1)

  

    ;; set up convenient way to resize window
    (global-set-key (kbd "S-C-<left>") 'shrink-window-horizontally)
    (global-set-key (kbd "S-C-<right>") 'enlarge-window-horizontally)
    (global-set-key (kbd "S-C-<down>") 'shrink-window)
    (global-set-key (kbd "S-C-<up>") 'enlarge-window)

#+END_SRC



* Ivy/Swiper

#+BEGIN_SRC emacs-lisp
   (use-package ivy
     :straight t
     :demand
     :config
     (setq ivy-use-virtual-buffers t
	   ivy-count-format "%d/%d "))
   (ivy-mode 1)
   ;; use swiper instead of default i-search
   (use-package swiper
     :straight t)
   (global-set-key "\C-s" 'swiper)
   ;; (setq ivy-display-style 'fancy);; color of swiper

   ;; enable ag
   (use-package ag
     :straight t)

   ;; disable ido
   ;; (require 'ido)
   ;; (ido-mode t)

  
#+END_SRC



* Org Mode

** Bullets
#+BEGIN_SRC emacs-lisp
  ;; hide trailing dots of header
  (setq org-hide-emphasis-markers t)
  ;; Replace headline markers with unicode bullets
  (use-package org-bullets
    :straight t
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
  ;;make org-bullets not hang on (on Windows)
  (setq inhibit-compacting-font-caches t)
#+END_SRC

** org-ref
#+BEGIN_SRC emacs-lisp
  (use-package org-ref
    :straight t)
  ;; (setq reftex-default-bibliography '("~/Dropbox/bibliography/references.bib"))

  ;; see org-ref for use of these variables
  (setq org-ref-bibliography-notes "~/Dropbox/bibliography/notes.org"
	org-ref-default-bibliography '("~/Dropbox/bibliography/references.bib")
	org-ref-pdf-directory "~/Dropbox/bibliography/bibtex-pdfs/")
#+END_SRC


** Latex preview
#+BEGIN_SRC emacs-lisp
  ;;to enlarge the image of latex formula
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 2.0))
#+END_SRC
** babel
#+BEGIN_SRC emacs-lisp
  ;; org babel;
  ;;(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((R . t)))
  (use-package ob-async
    :straight t)
  (add-hook 'org-babel-after-execute-hook 'org-display-inline-images)
  (add-hook 'org-mode-hook 'org-display-inline-images)
#+END_SRC
* ESS/R/Markdown

#+BEGIN_SRC emacs-lisp


  (use-package ess
    :defer t
    :init
    (require 'ess-r-mode)
    )


  ;;Poly mode and Poly-markdown

  (use-package poly-R
    :straight t)
  (use-package poly-markdown
    :straight t)
  (use-package poly-noweb
    :straight t)


  (use-package polymode
    :straight t
    :after (poly-markdown poly-noweb poly-R)
    :init
    (require 'polymode-core)
    :mode
    ("\\.Rmd" . poly-markdown+r-mode)
    ("\\.rmd" . poly-markdown+r-mode)
    ("\\.md" . poly-markdown-mode)
    ("\\.Snw" . poly-noweb+r-mode)
    ("\\.Rnw" . poly-noweb+r-mode)
    ;;("\\.R" . poly-ess-help+r-mode)
    ;;("\\.r" . poly-ess-help+r-mode)
    )

				       ;;; ess view data.frame
  (use-package ess-view
    :straight t
    :diminish
    )


  ;; set up some functions to stop ESS
  (defun ess-abort ()
    (interactive)
    (interrupt-process (ess-get-process)))
  (define-key ess-mode-map (kbd "C-c C-a") 'ess-abort)
  (define-key inferior-ess-mode-map (kbd "C-c C-a") 'ess-abort)

#+END_SRC




* Python

#+BEGIN_SRC emacs-lisp


	(straight-use-package 'ein)


	  (use-package elpy
	    :straight t
	    :init
	    (elpy-enable)
	    )
	  (setq elpy-rpc-python-command "python3")
	  (setenv "IPY_TEST_SIMPLE_PROMPT" "1")
	  (setq python-shell-interpreter "ipython3"
		python-shell-interpreter-args "-i")
	  (elpy-enable)


		   ;;   (use-package lsp-mode
		   ;;     :config
		   ;;     (lsp-register-custom-settings
		   ;;      '(("pyls.plugins.pyls_mypy.enabled" t t)
		   ;; 	 ("pyls.plugins.pyls_mypy.live_mode" nil t)
		   ;; 	 ("pyls.plugins.pyls_black.enabled" t t)
		   ;; 	 ("pyls.plugins.pyls_isort.enabled" t t)))
		   ;;     :hook
		   ;;     ((python-mode . lsp)))



		   ;; (use-package pyvenv
		   ;;   :straight t
		   ;;   :config
		   ;;   (pyvenv-mode t)

		   ;;   ;; Set correct Python interpreter
		   ;;   (setq pyvenv-post-activate-hooks
		   ;; 	  (list (lambda ()
		   ;; 		  (setq python-shell-interpreter (concat pyvenv-virtual-env "pybert/bin/python3")))))
		   ;;   (setq pyvenv-post-deactivate-hooks
		   ;; 	  (list (lambda ()
		   ;; 		  (setq python-shell-interpreter "python3")))))


		   ;; 	;;
		;; (use-package python-mode
			 ;;   :straight t
			 ;;   :custom
			 ;;   (python-shell-interpreter "python3"))

			 ;;   ;;
		       ;;(use-package elpy
			   ;;   :straight t
			   ;;   :init
			   ;;   (elpy-enable)
			   ;;   )

			   ;; ;;(elpy-enable)
			   ;;(setq python-shell-interpreter "ipython"
			   ;;      python-shell-interpreter-args "-i --simple-prompt")
			       ;; default python version
			       ;;(setq python-shell-interpreter "python3.7")
			       ;;(setq python-python-command "/usr/bin/python3.7")

#+END_SRC

* Spelling/Linting

** flyspell

#+BEGIN_SRC emacs-lisp

  (dolist (hook '(text-mode-hook))
    (add-hook hook (lambda () (flyspell-mode 1))))
  (dolist (hook '(prog-mode-hook))
    (add-hook hook (lambda () (flyspell-prog-mode 1))))

  (use-package flyspell-correct
    :straight t
    :after flyspell
    :bind (:map flyspell-mode-map ("C-M-;" . flyspell-correct-wrapper)))

  (use-package flyspell-correct-ivy
    :straight t
    :after flyspell-correct)

#+END_SRC

* Autocomplete

#+BEGIN_SRC emacs-lisp

  (use-package auto-complete
    :straight t);; set autocompletion
  (global-auto-complete-mode t)
  (ac-config-default)
  (setq ac-use-quick-help nil);; disable open R help in browser
  (setq ess-use-company nil);; disable company mode

#+END_SRC


* Math Symbol
#+BEGIN_SRC emacs-lisp
  ;; pretty-mod to show math symbols
  ;; (require 'pretty-mode)
  ;; if you want to set it globally
  ;; (global-pretty-mode t)
  ;; (setq org-pretty-entitles t)

#+END_SRC






* yasnippet

#+BEGIN_SRC emacs-lisp
  ;; Set up yasnippet
  ;; Type the shortcut and press TAB to complete
  ;; Or M-/ to autoseggest a snippet
  (use-package yasnippet
    :straight t
    :diminish yas-minor-mode
    :config
    (add-to-list 'yas-snippet-dirs "~/.emacs.d/snippets")
    (yas-global-mode)
    (global-set-key (kbd "M-/") 'company-yasnippet)
    )
  ;; Set snippet with intended indents, otherwise being flat
    (setq yas/indent-line 'fixed)

#+END_SRC


* Tramp Mode

#+BEGIN_SRC emacs-lisp
  ;; password for Tramp plink
  (use-package tramp
    :straight t)
  (setq tramp-default-method "plink")
  (setq password-cache-expiry nil)
  (with-eval-after-load 'tramp-sh
    (add-to-list 'tramp-remote-path 'tramp-own-remote-path))
  (add-hook 'after-init-hook
	    '(lambda ()
	       (if (member "." load-path)
		   (delete "." load-path))))


#+END_SRC


* PDF Tools
#+BEGIN_SRC emacs-lisp

  ;; (use-package pdf-tools
  ;;   :straight t
  ;;   :config
  ;;   (pdf-tools-install)
  ;;   )
  ;; org-pdfview doesn't work
  ;; (use-package org-pdfview
    ;; :straight t)
#+END_SRC


* Leftover
#+BEGIN_SRC emacs-lisp

    ;; add magit key
(straight-use-package 'magit)
    (global-set-key (kbd "C-x g") 'magit-status)

    ;; disable save-place mode
  ;;(save-place-mode 0)









    ;; quote selected text
    ;; (global-set-key (kbd "M-[") 'insert-pair)
    ;; (global-set-key (kbd "M-{") 'insert-pair)
    ;; (global-set-key (kbd "M-\"") 'insert-pair)

    ;; un-quote
    ;; (global-set-key (kbd "M-)") 'delete-pair)





    ;;(require 'init-basic)
    ;;(require 'init-packages)
    ;;(require 'init-diminish)

    ;;(projectile-global-mode)
    ;;(set projectile-mode-line " Projectile")

    ;; killing ring

    ;; (use-package counsel
    ;;   :bind
    ;;   (("M-y" . counsel-yank-pop)
    ;;    :map ivy-minibuffer-map
    ;;    ("M-y" . ivy-next-line)))




    ;; setup dictionary
    ;; (require define-word)
    ;; (defun browse-dictionary-at-point ()
    ;;   (interactive)
    ;;   (browse-url (concat "https://dictionary.com/browse/" (thing-at-point 'word))))
    ;; (defun def-word ()
    ;;     (interactive)
    ;;     (browse-url (concat "https://www.merriam-webster.com/dictionary/" (thing-at-point 'word))))




    ;; save all backup files to the temp folder
    (setq
     backup-by-copying t     ; don't clobber symlinks
     kept-new-versions 10    ; keep 10 latest versions
     kept-old-versions 0     ; don't bother with old versions
     delete-old-versions t   ; don't ask about deleting old versions
     version-control t       ; number backups
     vc-make-backup-files t) ; backup version controlled files

    (defvar backup-location (expand-file-name "~/emacs-backups")
      "Base directory for backup files.")
    (setq backup-directory-alist
	  `(("" . ,(expand-file-name "per-save" backup-location))))


    (setq TeX-auto-save t)
    (setq TeX-parse-self t)
    (setq TeX-save-query nil)
    (setq TeX-PDF-mode t)


    ;;;something unknown
    ;; (defun my-noweb-hook ()
    ;;   (define-key ess-noweb-mode-prefix-map "b"
    ;;     #'(lambda () (interactive) (TeX-command "BibTeX" 'TeX-master-file)))
    ;;   (define-key ess-noweb-mode-prefix-map "P"
    ;;     #'(lambda () (interactive)
    ;;         (ess-swv-PDF "texi2pdf"))))





    ;;; fold block

    ;;; show hierarchy of markdown
  (use-package imenu-list
      :straight t
      :bind (("C-'" . imenu-list-smart-toggle))
      :config
      (setq imenu-list-focus-after-activation t
	    imenu-list-auto-resize nil))




    ;; (ido-mode 1)
    ;; (setq ido-separator "\n")


    ;;;; Key binding
    (defun clear-shell ()
       (interactive)
       (let ((old-max comint-buffer-maximum-size))
	 (setq comint-buffer-maximum-size 0)
	 (comint-truncate-buffer)
	 (setq comint-buffer-maximum-size old-max)))
    (global-set-key  (kbd "\C-x l") 'clear-shell)





#+END_SRC

**Comment by ghowoo** [comment]
and this is myinit:
* User Interface
** diminish
   #+begin_src emacs-lisp
     (use-package diminish
       :straight t
       :defer 5
       :config
       (diminish 'global-visual-line-mode)
       )

   #+end_src
    
** Display time on mode line

   #+begin_src emacs-lisp
     (setq display-time-24hr-format t)
     (display-time-mode +1)
   #+end_src
** Visual Appearance
    #+begin_src emacs-lisp
      ;; Disable the splash screen (to enable it again, replace the t with 0)
      (setq inhibit-splash-screen t)

      ;; hide toolbar and scrollbar
      (tool-bar-mode 0)
      (scroll-bar-mode 0)
      
      ;; setup highlight current line
      (global-hl-line-mode +1)
      ;; word wrap: each long logical line is divided into two or more screen lines
      ;;  at word boundaries near the right window edge
      (global-visual-line-mode t)

		  ;;; show line numbers
      (global-linum-mode t)

      ;; show x-position (ie column number) for point in buffer
      (column-number-mode 1)


      ;; show percentage of file size on the line;
      (size-indication-mode t)

   #+end_src
* Help

** which key
  which key mode, after input C-x, after 1 second, the mini-buffer show all possible commands

  #+begin_src emacs-lisp

    (use-package which-key
      :straight t
      :init
      (which-key-mode)
      (which-key-setup-minibuffer))

  #+end_src

* Customized Key-Binding

  #+begin_src emacs-lisp
    ;;map C-k to kill-line, it was remapped to kill-visual-line
    (global-set-key (kbd "C-k") 'kill-line)
  #+end_src

* Editing
** Parentheses
   #+begin_src emacs-lisp
     (show-paren-mode 1) ; turn on paren match highlighting
     (setq show-paren-style 'expression) ; highlight entire bracket expression
     ;; use smartparens, deminish is to not show mode on mode-line
     (use-package smartparens
       :straight t
       :diminish
       :config
       (add-hook 'prog-mode-hook 'smartparens-mode)
       )

	     ;; make color names such as "#FF0000" colorful
     (use-package rainbow-mode
       :straight t
       :diminish
       :init
       (rainbow-mode t))

	  ;; make parentheses colorful
     (use-package rainbow-delimiters
       :straight t
       :diminish
       :init
       (rainbow-delimiters-mode t)
       )
     (add-hook 'prog-mode-hook 'rainbow-mode)
     (add-hook 'prog-mode-hook 'rainbow-delimiters-mode)


	     ;; add space around operators
     (use-package electric-operator
	       :straight t
	       :init
	       (electric-operator-mode t)
	       )

     (add-hook 'ess-r-mode-hook 'electric-operator-mode)

				      ;; specify some special operators
				  ;;     (electric-operator-add-rules-for-mode 'ess-r-mode
				  ;; 					  (cons "->" " -> ")
				  ;; 					  (cons "=>" " => ")
				  ;; 					  (cons "=>" " => ")
				  ;; 					  (cons "=<==" " <= ")
				  ;; 					  (cons "<" " < ")
				  ;; 					  (cons "<-" " <- ")
				  ;; 					  (cons ":=" " := ")
				  ;; 					  (cons "=" " = ")
				  ;; 					  (cons "%notin%" " %notin% ")
				  ;; 					  )

   #+end_src
    

* dired

  #+begin_src emacs-lisp

    ;; direct-narrow, filter within dired, key "/", then input filter
    (use-package dired-narrow
      :straight t
      :bind (:map dired-mode-map
		  ("/" . dired-narrow)))

    ;; recent directory
    ;;C-x C-d to select a previously visited directory to open
    (use-package dired-recent
      :straight t
      :config
      (dired-recent-mode 1)
      )

    ;; dired sub-tree, key tab on a folder to show subfolders and files
    (use-package dired-subtree
      :straight t
      :diminish
      :after dired
      :config
      (bind-key "<tab>" #'dired-subtree-toggle dired-mode-map)
      )


    ;; treemacs, a treelike window shows directory
    (use-package s
      :straight t)
    (use-package treemacs
      :straight t
      :bind
      (:map global-map
	    ([f8] . treemacs)))

  #+end_src
  
* General Specification


** auto-revert-mode

Emacs to automatically update a buffer if a file changes on disk and auto refresh dired when file changes.

  #+begin_src emacs-lisp
  (global-auto-revert-mode 1)
  (add-hook 'dired-mode-hook 'auto-revert-mode)
  #+end_src

** Disable save-place-mode

  #+begin_src emacs-lisp
    (setq save-place-mode nil)
    (setq save-place-local_mode nil)
  #+end_src


** Restart emacs

   #+begin_src emacs-lisp
     (use-package restart-emacs
     :straight t)
   #+end_src

  
** recentf

  #+begin_src emacs-lisp
      ;;; show recent files and set up shortcut
      (use-package recentf
	:straight t
	:diminish)
      (recentf-mode 1)
      (setq recentf-max-saved-items 50)
      (setq recentf-max-menu-items 50)
      ;;; set save list every 10 minutes
      (run-at-time nil (* 10 60) 'recentf-save-list)
      (global-set-key "\C-x\ \C-r" 'recentf-open-files)
      ;; provent files from elpa folder showing
      ;;(add-to-list 'recentf-exclude (format "%s/([^\s]+)\/\\.emacs\\.d/elpa/.*" (getenv "HOME")))
      ;;(setq recentf-exclude '("c:/\\.emacs/\\.emacs\\.d/elpa/"));; M-x recentf-cleanup to remove excluded files
      (setq recentf-exclude '("c:/([^\s]+)/\\.emacs\\.d/elpa/"));; M-x recentf-cleanup to remove excluded files
    ;;(setq recentf-exclude '("\/home\/([^\s]+)\/\.emacs\.d\/documents\/brain\/"
	;;                          "^\/home\/([^\s]+)\/\.emacs\.d\/documents\/brain\/" ))
      ;; startup with recent file buffer
      (use-package init-open-recentf
	:straight t
	:diminish
	:config
	(init-open-recentf))

  #+end_src


** posframe
   let ivy use posframe to show its candidate menu

   #+begin_src emacs-lisp
     ;; (use-package ivy-posframe
     ;;     :ensure t
     ;;     :diminish
     ;;     )
     ;; (setq ivy-posframe-height-alist '((swiper . 20)
     ;; 				  (t      . 20)))

     ;; (setq ivy-posframe-display-functions-alist
     ;;       '((swiper          . ivy-display-function-fallback)
     ;; 	(complete-symbol . ivy-posframe-display-at-point)
     ;; 	(counsel-M-x     . ivy-posframe-display-at-window-bottom-left)
     ;; 	(t               . ivy-posframe-display)))
     ;; (ivy-posframe-mode nil)
   #+end_src


* Languages

** Emacs lisp
 * delight: don't show anything for the mode
   #+begin_src emacs-lisp
     (use-package eldoc
       :straight t
       :delight
       :hook (emacs-lisp-mode . eldoc-mode)
       )
   #+end_src


** CSS

   #+begin_src emacs-lisp
     (use-package css-mode
       :custom (css-indent-offset 2))
   #+end_src


** csv

   #+begin_src emacs-lisp
     (use-package csv-mode)
   #+end_src

**Comment by progfolio** [comment]
I've edited your comments to make them a little more readable. In the future please either use [markdown](https://guides.github.com/features/mastering-markdown/ ) or link to a file sharing host such as https://gist.github.com/ or pastebin for whole files.

What I would do is remove the folder at `/home/username/.emacs.d/elpa/` and restart Emacs.
Straight should install missing packages if you have it configured correctly.
If the `elpa` folder reappears, you are still using package.el.
If it doesn't and you hit another error, it's likely that you have misconfigured your packages in your init.el.

Unfortunately, I do not have much time to comb through your init, but if you hit a specific error after trying the above you can copy the entire backtrace for that error here and someone may be able to help you in the future.

**Comment by ghowoo** [comment]
Thanks Progolio. I removed the elpa folder, restarted Emacs, and this time worked. It is very interesting.

  (use-package ess
    :straight t
    :init (require 'ess-site))

**Comment by raxod502** [comment]
Yeah. If you're using Emacs 27 or later, you'll need to put `(setq package-enable-at-startup nil)` into `~/.emacs.d/early-init.el`, or else your `package.el` packages will already be loaded by time the normal init-file is loaded. The alternative is simply deleting all your `package.el` packages (in `~/.emacs.d/elpa`), so that loading them has no effect.
