### ISSUE TITLE
Symbol's function is void: comp-deferred-compilation-deny-list

### ISSUE THREAD

**Issue by Ultra-Hax** [raxod502/straight.el#764]
This started happening after updating Emacs. I am on pgtk-nativecomp

**Comment by Ultra-Hax** [comment]
I found a workaround `(defvar comp-deferred-compilation-deny-list ())` I just add this before bootstrap however I would like this to stay open until I don't need this.

**Comment by progfolio** [comment]
What is the output of `M-x straight-version`?

**Comment by progfolio** [comment]
Duplicate of #757

**Comment by progfolio** [comment]
I've merged the develop branch into the master branch, so both versions should work appropriately now.
