### ISSUE TITLE
clarification for freeze/thaw

### ISSUE THREAD

**Issue by greg-minshall** [raxod502/straight.el#765]
hi.  i wonder if the "manual" (readme file) might be updated to include some information i find lacking, to wit, if i "freeze", then under what conditions will new versions of packages be fetched, built, installed?  i had assume "thaw" would do this (after which i would re-freeze), but as i read it, thaw means "make it so".  is that right?  maybe the "lockfile management" section might be a good place.  (unless, of course, i totally missed it.)

thanks very much for straight.el, by the way.  cheers.

**Comment by raxod502** [comment]
It sounds like you're interpreting "freezing" and "thawing" as toggling between two states: "frozen" and "unfrozen". I can see why you would think that, based on the method names, and they should probably be renamed to conform to more standard nomenclature.

Actually, "freeze" is analogous to `git commit` and "thaw" is analogous to `git checkout`. These commands are for interacting with your lockfile: "freeze" means "copy from currently installed packages to the lockfile" and "thaw" means "copy from the lockfile to currently installed packages".

Does that help explain?

**Comment by greg-minshall** [comment]
thanks -- yes, that exactly explains it.
