### ISSUE TITLE
recipe for org doesn't build info pages

### ISSUE THREAD

**Issue by greg-minshall** [raxod502/straight.el#766]
## What's wrong

if you start with a clean .../straight/repos/org subdirectory, add a `(use-package org)`, you don't end up with the info pages from the cloned repository.

the make target (`autoloads`) in the recipe doesn't seem to build the `.texi` files.  my guess is  that this means straight.el won't install them.  adding `info` to the target seems to work.  (it's pretty pokey, though; i don't know if a separate `org-info-pages` recipe, sort of like, i guess, the previous `org-contrib` recipe, might make sense?)

## Directions to reproduce

<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  '((use-package org)))
```
</details>

- Test run at: `2021-05-21 18:16:40`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> master, origin/master, origin/HEAD) e1390a9 2021-02-27`
- emacs-version: `GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-26`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) e46292d 2021-05-12

```
</details>

note that at this point, if you bring up the Org Mode info page ([C-h i], then [morg mode<RET>]),
then, e.g., [C-x C-f], you will be somewhere like `/usr/share/info/`,
so looking at the previously, system-installed info pages.

### Version information

* Emacs version:

GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-26

prerelease (HEAD -> master, origin/master, origin/HEAD) e1390a9 2021-02-27

Org mode version 9.4.5 (release_9.4.5-519-gcbc1f9 @ /home/minshall/.emacs.d/straight/build/org-plus-contrib/)

* Operating system:

Arch linux -- pretty much up-to-date

**Comment by greg-minshall** [comment]
i meant to add this.  this recipe, which, other than formatting, (afaik) differs only in having a second make target, seems to work (but, as i mentioned, takes a while in the case one of the input `.org` files has changed):

````
`(org :type git
       :repo "https://code.orgmode.org/bzg/org-mode.git"
       :local-repo "org"
       :depth full
       :pre-build ,(list (concat (when (eq system-type 'berkeley-unix) "g") "make")
                         "autoloads"
                         "info"
                         (concat "EMACS=" invocation-directory invocation-name))
       :build (:not autoloads)
       :files (:defaults "lisp/*.el" ("etc/styles/" "etc/styles/*")))
````

**Comment by liebkne** [comment]
The default does not build `etc/csl` and `etc/styles` too (when using `oc` and `oc-csl`.

**Comment by progfolio** [comment]
> The default does not build etc/csl and etc/styles too (when using oc and oc-csl).

etc/styles should be accounted for in the latest recipe.
`M-x straight-get-recipe org` reports:

```emacs-lisp
(org :type git :repo "https://code.orgmode.org/bzg/org-mode.git" :local-repo "org" :depth full :pre-build
     (straight-recipes-org-elpa--build)
     :build
     (:not autoloads)
     :files
     (:defaults "lisp/*.el"
                ("etc/styles/" "etc/styles/*")))
```

and my local `build` folder includes the `etc/styles` dir.
Could you please provide the recipe you are using to build Org and a directory listing for `straight/build/org/`?

`etc/csl` is a very recent addition to Org and the recipe will have to be updated to reflect that. I will take care of that ASAP, but it can be manually changed via the `:files` directive in the recipe.

**Comment by liebkne** [comment]
@progfolio Hi, I've updated to the latest version of everything and you are right. Now I can get `etc/styles` in the `build` directory. Thank you for working on this.
