### ISSUE TITLE
Current git commands set a too high version compatibility limit (>= 2.28)

### ISSUE THREAD

**Issue by gagbo** [raxod502/straight.el#768]
Hello,

According to 
https://github.com/raxod502/straight.el/blob/5541697ceee7e7ba937eddebba44f1e8e8af6a4f/straight.el#L2485

and this comment https://github.com/hlissner/doom-emacs/issues/5088#issuecomment-847249596

straight is currently setting a hard limit on the version of git that’s in the PATH in order to operate. ~~Literally~~ Almost (`21.04` has `2.30`, sorry for being hyperbolic) no [Ubuntu](https://repology.org/project/git/versions) is compatible (`>= 2.28`), and while I’d agree that it’s really a Canonical issue at that point, it cuts off a very large part of potential users :(

**Comment by progfolio** [comment]
I'll have to look over our git usage to see what we're using and if we can easily substitute those commands for something backwards compatible.

A solution on the user end for the time being is to grab git from the git-core ppa:

https://launchpad.net/~git-core/+archive/ubuntu/ppa

**Comment by gagbo** [comment]
I didn’t think about looking for PPAs, it seems it’s the easiest way to get going. Personally I don’t really mind if compatibility options are added or not, it’s probably code one would not like to maintain; therefore just having the PPA for now would be enough for me. Then again, I don’t use Ubuntu

Thanks for your work on straight either way!

**Comment by raxod502** [comment]
I suspect that this will be an easy fix. We can't have introduced this dependency too long ago, or _I_ would have noticed already! (I'm running Ubuntu 20.04.)

Git has added a lot of alias options recently to make the commands more intuitive, so I guess going forward we should just double-check to make sure we're not using one of them when adding VC code.

**Comment by progfolio** [comment]
Here's a list of the current git commands and the options we're using:

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Sub-command</th>
<th scope="col" class="org-left">Options</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">branch</td>
<td class="org-left">-m -r</td>
</tr>


<tr>
<td class="org-left">checkout</td>
<td class="org-left">-B</td>
</tr>


<tr>
<td class="org-left">clean</td>
<td class="org-left">-ffd</td>
</tr>


<tr>
<td class="org-left">clone</td>
<td class="org-left">&#x2013;branch &#x2013;depth &#x2013;no-checkout &#x2013;no-single-branch &#x2013;no-tags &#x2013;origin &#x2013;single-branch</td>
</tr>


<tr>
<td class="org-left">config</td>
<td class="org-left">&#x2013;get &#x2013;file</td>
</tr>


<tr>
<td class="org-left">describe</td>
<td class="org-left">&#x2013;short &#x2013;match &#x2013;abbrev</td>
</tr>


<tr>
<td class="org-left">fetch</td>
<td class="org-left">&#x2013;depth &#x2013;no-tags</td>
</tr>


<tr>
<td class="org-left">log</td>
<td class="org-left">&#x2013;format=%h %s</td>
</tr>


<tr>
<td class="org-left">ls-files</td>
<td class="org-left">&#x2013;unmerged</td>
</tr>


<tr>
<td class="org-left">merge</td>
<td class="org-left">&#x2013;abort &#x2013;ff-only</td>
</tr>


<tr>
<td class="org-left">merge-base</td>
<td class="org-left">&#x2013;is-ancestor</td>
</tr>


<tr>
<td class="org-left">rebase</td>
<td class="org-left">&#x2013;abort</td>
</tr>


<tr>
<td class="org-left">remote show</td>
<td class="org-left">&#x2013;master</td>
</tr>


<tr>
<td class="org-left">reset</td>
<td class="org-left">&#x2013;hard</td>
</tr>


<tr>
<td class="org-left">rev-parse</td>
<td class="org-left">-q &#x2013;verify &#x2013;abbrev-ref &#x2013;symbolic-full-name &#x2013;git-dir</td>
</tr>


<tr>
<td class="org-left">show</td>
<td class="org-left">-s &#x2013;format=%d %h %cs</td>
</tr>


<tr>
<td class="org-left">stash push</td>
<td class="org-left">&#x2013;include-untracked</td>
</tr>


<tr>
<td class="org-left">stash save</td>
<td class="org-left">&#x2013;include-untracked</td>
</tr>


<tr>
<td class="org-left">status</td>
<td class="org-left">&#x2013;short</td>
</tr>


<tr>
<td class="org-left">submodule update</td>
<td class="org-left">&#x2013;init &#x2013;recursive</td>
</tr>
</tbody>
</table>

I think most of these look they will work for relatively older versions of git
(The only one I see off the top of my head that I remember being added "recently" was the `--no-tags` option for `git clone`, but even that was years ago.)
If anyone notices anything that looks like it forces a high version requirement let me know.

**Comment by progfolio** [comment]
#776 has been merged into "develop". I think that should remove the >=2.28 restriction. @gagbo: Testing appreciated if you have time.

Thanks.
