### ISSUE TITLE
README links to missing section?

### ISSUE THREAD

**Issue by bkaestner** [raxod502/straight.el#771]
Hi,

the current README.md links to a section called `#integration-with-org`, down in _["The wrong version of my package was loaded"](https://github.com/raxod502/straight.el#the-wrong-version-of-my-package-was-loaded)_. However, that section does not exist, it got removed during a merge (e1390a933b6f5a15079d6dec91eac97a17aad10c).

Unfortunately, I'm not a `straight.el` user, so I don't know whether that section is critical, but I believe that the link/mention of the old section should get removed to prevent confusion.

Hope that helps, and keep up the good work, the README.md was a fantastic tool for me to help others with their version mismatch!

**Comment by progfolio** [comment]
Thanks for bringing this to our attention, I've updated the references in #774.
