### ISSUE TITLE
Packages are rebuilt on every init when using busybox/find

### ISSUE THREAD

**Issue by nico202** [raxod502/straight.el#78]
Hi, I'm using straight on an android phone (with termux). If my init load time was ~1 minute, now with straight is more then 10 (~900sec). I don't know if I'm doing something wrong, since it's "building" every package every time, even if I "straight-freeze-version".
In the init i'm calling the functions straight-declare-init-succeeded and straight-declare-init-finished, and since I was using use-package (with almost all packages with :defer t), so I'm calling (after the bootstrap)
(straigh-use-package 'use-package) (with always-ensure = t)

My question is if the boot time is supposed to be that slower, or if it might be a problem with the find(1) call, or in general how to debug it.

This package manager seems promising (remember me a bit of [nix](https://nixos.org/nix/)) and I hope to be able to use it at its full potential.

Thanks, Nicolò

**Comment by nico202** [comment]
OK I found it. It was using busybox/find, that does not support newermt. I installed findutils and now it took 43s!

Maybe if there's a fast way to determine the find command (or a user switch) it would ne useful. I was almost about giving it up. I keep the issue open until I hear back from you

**Comment by raxod502** [comment]
Ah! This would be another manifestation of #32. I only tested the find(1) command with BSD and GNU find on macOS. It's obviously a bug, though, if it doesn't work on other platforms. I'll have to see if I can reproduce this in a Docker container as I don't have any Linux boxes sitting around to test with.

Certainly a user option for find(1) options is in order. In addition, I don't think it would be a bad idea to automatically set said user option based on the value of `system-type` or `$OSTYPE` or something. Although, does busybox/find even have any option that will allow you to check the mtime? I wouldn't want to force the user to install findutils just to use straight.el.

Beyond that, you noted that it still takes 43s. This is unsurprising to me, since there is even a 50–100ms delay in the best case (with ~50 packages) on my SSD. I anticipate solving this problem (i.e. reducing the additional startup delay to essentially zero) via #41, so keep an eye on that issue as well.

**Comment by nico202** [comment]
Hi, [here](https://linux.die.net/man/1/busybox)'s the busybox man page, if you look for find there are the options.

Just to be sure, here's the "--help" on my phone:
`BusyBox v1.26.2 (2017-02-09 15:33:00 CET) multi-call binary.                                   
                                                                                               
Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]                                                
                                                                                               
Search for files and perform actions on them.                                                  
First failed action stops processing of current file.                                          
Defaults: PATH is current directory, action is '-print'                                        
                                                                                               
        -L,-follow      Follow symlinks                                                        
        -H              ...on command line only                                                
        -xdev           Don't descend directories on other filesystems                         
        -maxdepth N     Descend at most N levels. -maxdepth 0 applies                          
                        actions to command line arguments only                                 
        -mindepth N     Don't act on first N levels                                            
        -depth          Act on directory *after* traversing it                                 
                                                                                               
Actions:                                                                                       
        ( ACTIONS )     Group actions for -o / -a                                              
        ! ACT           Invert ACT's success/failure                                           
        ACT1 [-a] ACT2  If ACT1 fails, stop, else do ACT2                                      
        ACT1 -o ACT2    If ACT1 succeeds, stop, else do ACT2                                   
                        Note: -a has higher priority than -o
        -name PATTERN   Match file name (w/o directory name) to PATTERN
        -iname PATTERN  Case insensitive -name
        -path PATTERN   Match path to PATTERN
        -ipath PATTERN  Case insensitive -path
        -regex PATTERN  Match path to regex PATTERN
        -type X         File type is X (one of: f,d,l,b,c,...)
        -perm MASK      At least one mask bit (+MASK), all bits (-MASK),
                        or exactly MASK bits are set in file's mode
        -mtime DAYS     mtime is greater than (+N), less than (-N),
                        or exactly N days in the past
        -mmin MINS      mtime is greater than (+N), less than (-N),
                        or exactly N minutes in the past
        -newer FILE     mtime is more recent than FILE's
        -inum N         File has inode number N
        -user NAME/ID   File is owned by given user
        -group NAME/ID  File is owned by given group
        -size N[bck]    File size is N (c:bytes,k:kbytes,b:512 bytes(def.))
                        +/-N: file size is bigger/smaller than N
        -links N        Number of links is greater than (+N), less than (-N),
                        or exactly N
        -prune          If current file is directory, don't descend into it
If none of the following actions is specified, -print is assumed
        -print          Print file name
        -print0         Print file name, NUL terminated
        -exec CMD ARG ; Run CMD with all instances of {} replaced by
                        file name. Fails if CMD exits with nonzero
        -exec CMD ARG + Run CMD with {} replaced by list of file names
        -delete         Delete current file/directory. Turns on -depth option
`

**Comment by raxod502** [comment]
I guess I'm stuck with creating a bunch of temporary files with specific mtimes, and then using `-mtime`. That's rather messy, but there's probably no other way to do it with that version of `find`.

**Comment by raxod502** [comment]
As of f689b59e93a22e14b6a674aeaaa2a0dfb32a5e03, if an error is reported by `find(1)`, it should be reported directly to the user rather than causing the build caching system to silently fail.

**Comment by raxod502** [comment]
This should now be fixed, please let me know if it works.

**Comment by nico202** [comment]
I'll try later in the morning

**Comment by nico202** [comment]
(Thanks)

**Comment by raxod502** [comment]
Just doing some spring cleaning. If it turns out to not work, just let me know and I'll reopen.
