### ISSUE TITLE
Always rebuild when filename contains unicode.

### ISSUE THREAD

**Issue by nasyxx** [raxod502/straight.el#780]
## What's wrong

`straight` always rebuilds when the filename contains Unicode.

## Directions to reproduce

A directory and a file:

```
;;; ~/.emacs.d/测试/测试.el
(defun 測試 () t)
(provide '测试)
```

```
;;; ~/.emacs.d/init.el

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package
  `(测试 :local-repo ,(locate-user-emacs-file "测试/")))
```

While starting emacs, the `测试` will always rebuild.

<img width="486" alt="Screen Shot 2021-06-04 at 06 04 27 AM" src="https://user-images.githubusercontent.com/5007613/120785035-bad01800-c4fa-11eb-8b8e-fb013bd4fcad.png">

In fact, I'm not sure if using a file name with non-ASCII chars will cause problems.  While I tried without `straight` and found no problems, still not sure if it is an issue of `straight.`

### Version information

* Emacs version: `GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.4.0, NS appkit-2022.44 Version 11.3.1 (Build 20E241)) of 2021-05-24`
* Operating system: macOS 11.3.1

**Comment by raxod502** [comment]
Can confirm, and it's definitely a bug with `straight.el`. I bet one of the places where I used `insert-file-contents-literally` is to blame.

**Comment by progfolio** [comment]
>  I bet one of the places where I used insert-file-contents-literally is to blame.

This sounds like a good place to investigate.
At first glance, my guess would be where we load the build-cache.

```emacs-lisp
(insert-file-contents-ilterally (straight--build-cache-file))
```

**Comment by progfolio** [comment]
@nasyxx: Could you try evaluating the following test case in your \*scratch* buffer?
It will install straight.el with a patch from my fork in a temporary environment and attempt to install your package.
After it's finished a results buffer will pop up. You'll want to run this once, let it finish, and then run it again.I'd be interested to see what the results buffer looks like after the second run.

```emacs-lisp
(straight-bug-report
  :user-dir "unicode-test.straight"
  :preserve t
  :pre-bootstrap
  (setq straight-repository-branch "fix/build-cache-decode-unicode"
        straight-repository-user "progfolio")
  :post-bootstrap
  (straight-use-package
   `(测试 :local-repo ,(locate-user-emacs-file "测试/"))))
```

**Comment by nasyxx** [comment]
> Could you try evaluating the following test case in your *scratch* buffer?

Hi, the `locate-user-emacs-file` one cannot find the repo.  And I also tried an absolute path one, which stuck at selecting coding system.

-------

<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "unicode-test.straight"
  :preserve t
  :pre-bootstrap 
  (setq straight-repository-branch "fix/build-cache-decode-unicode" straight-repository-user "progfolio")
  :post-bootstrap 
  (straight-use-package
   `(测试 :local-repo ,(locate-user-emacs-file "测试/"))))
```
</details>

- Test run at: `2021-06-06 15:55:14`
- system-type: `darwin`
- straight-version: `prerelease (grafted, HEAD -> master, origin/master, origin/HEAD) 5541697 2021-05-19`
- emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71))
 of 2021-06-06`

<details><summary>Output</summary>

```emacs-lisp
Test run with version: prerelease (HEAD -> fix/build-cache-decode-unicode, origin/fix/build-cache-decode-unicode) dc9159c 2021-06-06
Cloning /var/folders/ww/8t90n0r55wn8dpbbnfzdn7440000gn/T/unicode-test.straight/测试/ (for 测试)...

Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master eaa1de65 2021-06-05
"gnu-elpa-mirror"         n/a                  master 6417888 2021-05-29
"el-get"                  melpa                master 52df810e 2021-06-06
"emacsmirror-mirror"      n/a                  master a3cf645 2021-05-29
"straight"                n/a                  fix/build-cache-decode-unicode dc9159c 2021-06-06

Error: (error "No ‘:repo’ specified for package ‘测试’")

```
</details>


----

The absolute path one:

```
(straight-bug-report
  :user-dir "unicode-test.straight"
  :preserve t
  :pre-bootstrap
  (setq straight-repository-branch "fix/build-cache-decode-unicode"
        straight-repository-user "progfolio")
  :post-bootstrap
  (straight-use-package
   '(测试 :local-repo "/Users/Nasy/.emacs.d/测试/")))
```

Stuck at selecting a coding system.

```
Test run with version: prerelease (HEAD -> fix/build-cache-decode-unicode, origin/fix/build-cache-decode-unicode) dc9159c 2021-06-06
Building 测试...
Building 测试...done

Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master eaa1de65 2021-06-05
"gnu-elpa-mirror"         n/a                  master 6417888 2021-05-29
"el-get"                  melpa                master 52df810e 2021-06-06
"emacsmirror-mirror"      n/a                  master a3cf645 2021-05-29
"straight"                n/a                  fix/build-cache-decode-unicode dc9159c 2021-06-06
"测试"                    n/a                  master a0c54b1 2021-05-28

Select coding system (default raw-text): 
```

**Comment by progfolio** [comment]
Of possible interest:
https://nullprogram.com/blog/2014/06/13/

**Comment by raxod502** [comment]
I did some testing and https://github.com/raxod502/straight.el/pull/794 appears to resolve the problem.

**Comment by progfolio** [comment]
@nasyxx: I've pushed the patch in #780. Closing this issue, but if you run into this problem while testing, please comment and we'll reopen. Thanks.

**Comment by nasyxx** [comment]
Thanks!
