### ISSUE TITLE
Allow straight.el to use homebrew's texinfo on macOS

### ISSUE THREAD

**Issue by offbyone** [raxod502/straight.el#781]
As noted in #210, the macOS texinfo is really old. Homebrew provides a `texinfo` formula, but intentionally won't install it to avoid shadowing the system package. Right now, the `info` build command uses `(find-executable "makeinfo")` to locate the info builders, but I would far prefer to set that myself before running the build.

It would be nice if straight would use the existing makeinfo configuration for those executables, which I _have_ set, but failing that can there be a straight-specific way to set them?

**Comment by progfolio** [comment]
I'd have to look into using the existing makeinfo configuration. In the meantime, we could make a `defcustom` for the makeinfo program which could be set as follows:

```emacs-lisp
(setq straight-makeinfo-executable "/path/to/executable")
```
We should probably do this for other programs we're requiring (e.g. git, find), too.

Does this sound like it would help?

**Comment by offbyone** [comment]
That was what I'd figured would work, but I didn't want to dictate a solution.

**Comment by progfolio** [comment]
#784 has been merged into the "develop" branch. Two defcustoms, `straight-makeinfo-executable` and
`straight-install-info-executable`, have been added. You should be able to set the desired path with those. Testing is appreciated.

**Comment by progfolio** [comment]
@offbyone: Closing this, but feel free to comment if you run into any related issues.

**Comment by offbyone** [comment]
As far as I can tell, it's working. Getting doom emacs to a) update straight out-of-band and b) show me what it's doing when building is no trivial task, let me tell you...

Thank you!
