### ISSUE TITLE
Install and load auctex with straight.el.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#793]
On Ubuntu 20.04, I try to install and load the [auctex](https://git.savannah.gnu.org/git/auctex.git) package with the steps described below.

Add the following code to `~/.emacs.d/init.el`:
```emacs-lisp
(straight-use-package
 '( auctex :type git :host nil :repo "https://git.savannah.gnu.org/git/auctex.git"))
```
Start Emacs and the auctex will be cloned into `~/.emacs.d/straight/repos/auctex`, then do the following:

```
$ cd ~/.emacs.d/straight/repos/auctex/
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install
```
Finally, loading the package with the following code in `~/.emacs.d/init.el`:

```emacs-lisp
(load "auctex.el" nil t t) 
(load "preview-latex.el" nil t t)
``` 
I want to know if I can integrate all the above trivial jobs using straight, and complete all the work in a one-stop manner.

**Comment by raxod502** [comment]
Yes, certainly---read up on [using `:pre-build` to execute system commands when building a package](https://github.com/raxod502/straight.el/tree/521173e0b48a03b7094bb964da88ea5c008e35f6#the-recipe-format).

**Comment by raxod502** [comment]
Although, you probably want to `./configure --prefix somewhere-not-needing-root-access`, because you probably don't want to noninteractively install to a root-owned location from Emacs, and `straight.el` doesn't know how to receive interactive input during a package compilation anyway. See preview discussion at https://github.com/raxod502/straight.el/issues/725.

**Comment by hongyi-zhao** [comment]
> because you probably don't want to noninteractively install to a root-owned location from Emacs

It is also possible to use AUCTeX directly from a local Git repository without installation. Under the top level subdirectory of the cloned auctex local repo, there is a file named as `INSTALL` which says the following:
```
6.1 Using AUCTeX from local Git repo
====================================

With the techniques described above, it is also possible to use AUCTeX
directly from a local Git repository.  Let's assume you have your Git
repositories under '~/development/'.

   First, you have to fetch a copy of the AUCTeX Git repository.  In a
shell, change directory to '~/development/' and do:
     git clone https://git.savannah.gnu.org/git/auctex.git

   Now change directory to '~/development/auctex' and run
'./autogen.sh'.  Next thing is to run 'configure' like this:
     ./configure --without-texmf-dir --with-lispdir=.

When finished, simply enter
     make
and you're finished.  Note that the 'make install' step is not
necessary.

   Now you have to tell Emacs about the plan.  The following variables
must be set in your init file because their normal values are only
correct when AUCTeX is installed:
     (setq TeX-data-directory "~/development/auctex"
           TeX-lisp-directory TeX-data-directory)

The info files will be available with this:
     (eval-after-load 'info
        '(add-to-list 'Info-additional-directory-list
                      "~/development/auctex/doc"))

Now you're ready to load 'auctex.el' and 'preview-latex.el' out of this
directory:
     (load "~/development/auctex/auctex.el" nil t t)
     (load "~/development/auctex/preview-latex.el" nil t t)
```

**Comment by hongyi-zhao** [comment]
> Yes, certainly---read up on [using `:pre-build` to execute system commands when building a package](https://github.com/raxod502/straight.el/tree/521173e0b48a03b7094bb964da88ea5c008e35f6#the-recipe-format).

I compose the following bootstraping code for auctex in `~/.emacs.d/init.el`:
```
(straight-use-package
 `( auctex :type git :host nil :repo "https://git.savannah.gnu.org/git/auctex.git"
    :pre-build ,(pcase system-type
                (`berkeley-unix '("gmake"))
                (_ '(
                    ("cd" "~/.emacs.d/straight/repos/auctex")
                    ("./autogen.sh")
                    ("./configure")
                    ("make")
                    ("sudo" "make" "install"))))))
                  
(load "auctex.el" nil t t) 
(load "preview-latex.el" nil t t)
```
But it failed to start Emacs, as shown below:

![image](https://user-images.githubusercontent.com/11155854/121826959-f6ce5e80-ccec-11eb-931c-681064d12263.png)

**Comment by progfolio** [comment]
`cd` is a shell built-in, so it needs to be executed in the context of a shell.
e.g. `("bash" "-c" "cd /to/my/path")`

**Comment by hongyi-zhao** [comment]
> You should be able to avoid this step altogether, though.

Thank you for letting me know this.

> The sudo setp will stall out, too.

If you don't install it, then must work with the method like `Using AUCTeX from local Git repo` as I've mentioned previously.

> As @raxod502 mentioned, you can't provide input during the :pre-build steps. So you'll want to avoid that step.

In my case, I set the password free sudo for a specific user to do the job.

**Comment by progfolio** [comment]
Sounds like you've got it worked out!

**Comment by hongyi-zhao** [comment]
> Sounds like you've got it worked out!

Yep. See the bootstrap code I'm currently using above.
