### ISSUE TITLE
Can straight.el automatically deal with the load-path when using customzied git repoitories?

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#795]
On Ubuntu 20.04, according to the guide [here](https://oremacs.com/swiper/#installing-from-the-git-repository), I try to install ivy from its git repo using straight with the following bootstrap code:

```emacs-lisp
(straight-use-package
 `( swiper :type git :host github :repo "abo-abo/swiper"
    :pre-build (
                     ;("bash" "-c" "cd ~/.emacs.d/straight/repos/swiper")
                     ;https://github.com/abo-abo/swiper/issues/2886#issuecomment-860562001
                     ("make" "deps")
                     ("make" "compile")
                     )))
                    
;(add-to-list 'load-path "~/.emacs.d/straight/repos/swiper/")
(require 'ivy)                    
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq ivy-count-format "(%d/%d) ")  
```
Based on my tries, it seems that the `load-path` directive is useless. So, I think that there must be some mechanisms working under the hood in `straight.el` to automatically deal with the load-path.

Any hints will be highly appreciated.

Regards,
HY

**Comment by progfolio** [comment]
Yes, part of what straight does is generate an autoloads file and add directories to the `load-path` variable.
This autoload generation can be customized via the `:build` keyword on a per-recipe basis:

https://github.com/raxod502/straight.el#autoload-generation

You can check out the source of `straight--build-autoloads` function if you're curious how we generate the autoloads files.
