### ISSUE TITLE
Obtain the realpath/truepath of the package managed by straight.el gracefully. 

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#797]
On Ubuntu 20.04, I install my revised version of [screen2latex.el](https://github.com/hongyi-zhao/screen2latex.el) package via straight as shown below:

```emacs-lisp
(use-package screen2latex.el
  :straight (:host github :repo "hongyi-zhao/screen2latex.el")
    :bind
  ("C-x s" . screen2latex))
```
After the installation, the package's repo is located at `~/.emacs.d/straight/repos/screen2latex.el`, while the corresponding build files are located at `~/.emacs.d/straight/build/screen2latex.el`, as shown below:

```
$ ls -l ~/.emacs.d/straight/build/screen2latex.el/screen2latex.el
lrwxrwxrwx 1 werner werner 68 Jun 15 07:23 /home/werner/.emacs.d/straight/build/screen2latex.el/screen2latex.el -> /home/werner/.emacs.d/straight/repos/screen2latex.el/screen2latex.el
```
I want to obtain the script/repo's realpath/truepath from within [the script itself](https://github.com/hongyi-zhao/screen2latex.el/blob/master/screen2latex.el) gracefully/programmatically.

In one word, I want to based on the invoked file by Emacs, i.e., `/home/werner/.emacs.d/straight/build/screen2latex.el/screen2latex.el` to obtain the real filename and its directory, i.e.,  `/home/werner/.emacs.d/straight/repos/screen2latex.el/screen2latex.el` and `/home/werner/.emacs.d/straight/repos/screen2latex.el` in this script itself gracefully. All in all, I want to find a better way to use in this script to programmatically replace the following hard-coded version:
```emacs-lisp
(setq script-directory "~/.emacs.d/straight/repos/screen2latex.el")
```

I tried the following method:
```emacs-lisp
(setq script-directory (file-name-directory (file-truename (load-file-name))))
```
but failed with the error below:

`file-truename: Symbol’s function definition is void: load-file-name`

Any hints will be highly appreciated.

Regards,
HY

**Comment by progfolio** [comment]
Pay mind to the error message:

> Symbol’s function definition is void: load-file-name

`load-file-name` is a variable, not a function.

You can find information like this via the help system.
`M-x apropos` will allow you to search generally without needing to know whether a symbol refers to a function or variable.

Straight has `straight--repos-dir`, but it is not recommended to rely on functions which have a leading `--`, as that is a convention to denote that the function is "private" and no guarantee about it's API is made. You can, however, see how it accomplishes what it does and use that as inspiration for your own version of such a function.

**Comment by hongyi-zhao** [comment]
> M-x apropos

Thank you for letting me know this.

> Straight has straight--repos-dir, 

It seems this function is recursively calling others defined in straight:
```
$ rg -A5 -- 'defun straight--repos-dir '
straight.el
717:(defun straight--repos-dir (&rest segments)
718-  "Get a subdirectory of the straight/repos/ directory.
719-SEGMENTS are passed to `straight--dir'. With no SEGMENTS, return
720-the straight/repos/ directory itself."
721-  (apply #'straight--dir "repos" segments))
722-
$ rg -A5 -- 'defun straight--dir '
straight.el
651:(defun straight--dir (&rest segments)
652-  "Get a subdirectory of the straight/ directory.
653-SEGMENTS are passed to `straight--emacs-dir'. With no SEGMENTS,
654-return the straight/ directory itself."
655-  (apply #'straight--emacs-dir "straight" segments))
656-
$ rg -A5 -- 'defun straight--emacs-dir '
straight.el
626:(defun straight--emacs-dir (&rest segments)
627-  "Get a subdirectory of the `user-emacs-directory'.
628-The SEGMENTS are path segments which are concatenated with
629-slashes and postpended to the straight directory. With no
630-SEGMENTS, return the `user-emacs-directory' itself.
631-
```
So far, I still have not got the necessary inspiration from it.

BTW, due to these functions are "private", how to retrieve their definitions from Emacs conveniently?

**Comment by progfolio** [comment]
> It seems this function is recursively calling others defined in straight

That's not recursion, that's just functions calling other functions. Recursion would be a function calling itself.
I recommend reading the Intro to Programming with Emacs Lisp included with Emacs to learn the basics.
It will be much more thorough than I can be at the moment.

> BTW, due to these functions are "private", how to retrieve their definitions from Emacs conveniently?

The "privacy" is only by convention. It's more a warning to other people writing code that means "don't rely on this function in your own code, please". There's nothing in place to obscure the definitions. `M-x describe-function` will still work with them and you can always view the source of a library via `M-x find-library`, too.

**Comment by hongyi-zhao** [comment]
> That's not recursion,

Sorry for my conceptual confusion.

> the Intro to Programming with Emacs Lisp

Do you mean [this one](https://www.gnu.org/software/emacs/manual/pdf/eintr.pdf)?

> The "privacy" is only by convention. [...]

Thank you again.

**Comment by progfolio** [comment]
> Do you mean this one?

That's the one.
You can access the most recent version from within Emacs via `M-x info` as well.

**Comment by hongyi-zhao** [comment]
Even read this Intro, it still doesn't tell many things in a mnemonic manner, say, the following:
```
7.1 ‘car’ and ‘cdr’
===================

 Clearly, a more reasonable name for the ‘car’ function would be
‘first’ and this is often suggested.
 
Clearly, a more reasonable name for ‘cdr’ would be ‘rest’.
```
It tells me that the ‘car’ and ‘cdr’ are bad names, but doesn't tell me how do they come about.

**Comment by progfolio** [comment]
If you're interested in the history of those names, I believe wikipedia has an entire article dedicated to them.

**Comment by hongyi-zhao** [comment]
Yes. I find some hints/explanations [here](https://en.wikipedia.org/wiki/CAR_and_CDR):
```
    car ("contents of the address part of register number"),
    cdr ("contents of the decrement part of register number"),
    cpr ("contents of the prefix part of register number"), and
    ctr ("contents of the tag part of register number"),
```

**Comment by hongyi-zhao** [comment]
To summarize, the following does the trick:
```emacs-lisp
(setq script-directory (file-name-directory (file-truename load-file-name)))
```
