### ISSUE TITLE
You can run the command ‘straight-pull-package’ with M-x -pul-p RET

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#799]
See the following screenshot:

![image](https://user-images.githubusercontent.com/11155854/122141794-b0116d80-ce80-11eb-877b-3a3018f52093.png)

![image](https://user-images.githubusercontent.com/11155854/122141841-c8818800-ce80-11eb-8067-b3df2d40a50a.png)

As you can see,  the `straight-pull-package` command doesn't appear with `M-x -pul-p`, while it will appear with `M-x -pul -p`. So I'm very confused by the info given in `*Messages*` buffer:

`You can run the command ‘straight-pull-package’ with M-x -pul-p RET`

**Comment by progfolio** [comment]
Not related to straight. This is a question better suited for a general Emacs forum.

**Comment by hongyi-zhao** [comment]
Sorry for bothering here. Reposted it on <help-gnu-emacs@gnu.org>.
