### ISSUE TITLE
Change the variable's default value of a package with straight.el

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#802]
On Ubuntu 20.04, I use the following code snippet to install auctex:

```emacs-lisp
(straight-use-package
 `( auctex :type git :host nil :repo "https://git.savannah.gnu.org/git/auctex.git"
    :pre-build ,(pcase system-type
                (`berkeley-unix '("gmake"))
                (_ '(
                    `("bash" "-c" "cd" ,(straight--repos-dir "auctex"))
                    ("./autogen.sh")
                    ("./configure")
                    ("make")
                    ("sudo" "make" "install"))))
    :init
    (setq TeX-auto-global "~/.local/var/auctex/")
                    ))
```
In the above settings, I want to change the value of the variable `TeX-auto-global`, which will be used by the function `TeX-auto-generate-global` to hold the generated macros and environments info files.

But when I check its value with `C-h v TeX-auto-global RET`, it still assigned with its original value as shown below:

![image](https://user-images.githubusercontent.com/11155854/122334360-32c32700-cf6c-11eb-840f-36e7d9327381.png)

Any hints for this problem?

Regards,
HY

**Comment by progfolio** [comment]
You are confusing `straight-use-package` with `use-package`.  The former has no `:init` keyword.

**Comment by hongyi-zhao** [comment]
Thank you. Based on your hints, the following does the trick:
```emacs-lisp
(straight-use-package
 `( auctex :type git :host nil :repo "https://git.savannah.gnu.org/git/auctex.git"
    :pre-build ,(pcase system-type
                (`berkeley-unix '("gmake"))
                (_ '(
                    `("bash" "-c" "cd" ,(straight--repos-dir "auctex"))
                    ("./autogen.sh")
                    ("./configure")
                    ("make")
                    ("sudo" "make" "install")))))
                    (setq TeX-auto-global "~/.local/var/auctex/")
                                                                )
```

**Comment by progfolio** [comment]
That's an abuse of the `:pre-build` keyword. It was not designed to configure packages. The `:pre-build` steps are only run when the package is built/rebuild, so if you quit Emacs and restart and no build is necessary, `TeX-auto-global` will not be set to your desired variable.

**Comment by hongyi-zhao** [comment]
Thank you for pointing this out.

**Comment by hongyi-zhao** [comment]
Powered by `straight`, `auctex`, `eglot`, `texlab`, and `company`, I finally figured out a working vanilla Emacs based LaTeX document preparation system. See [here](https://github.com/astoff/digestif/issues/33#issuecomment-863134170) for more detailed info, and the following screenshot for a rough impression:

![image](https://user-images.githubusercontent.com/11155854/122501181-c8bb8800-d026-11eb-8a74-857e2467e16c.png)

**Comment by raxod502** [comment]
@progfolio Maybe we should make `straight-use-package` print a warning when it is passed a recipe that has an unknown keyword? Would help make this error more obvious.
