### ISSUE TITLE
Questions about building packages with nonstandard repo layout

### ISSUE THREAD

**Issue by mikereape** [raxod502/straight.el#807]
Hi hopefully this is a trivial question with a trivial answer. I have a local repo (of sorts) which is a collection of username/packagename repos so the directory structure for the whole thing is defined by paths like root_of_collection/username/packagename.

What I need to do in at least one case which is very important to me  is point at a repo on a  root_of_collection/username/packagename path and then refer to a .el file within that repo as if I was using one of your recipes like the one you give as an example::

`(straight-use-package
 '(el-patch :type git :host github :repo "your-name/el-patch"))`

except that `github` would be replaced by a file system path and where the .el file is treated as the name of the package (which in this case at least is not the name of the repo). I didn't write the repo in question and it contains lots and lots of code besides .el files.

I can just about see a case for making this relative to localhost to keep everything network-based (and in this case in addition the Win 10 equivalent) but anything beyond that ...?

I'd be very grateful for any advice. This is the last piece of a puzzle a very long long time in the making!

Thanks very much in advance

Mike

**Comment by mikereape** [comment]
Hi so the specific answer is in the README. Apologies. I missed it. Here's the relevant snippet:

`(straight-use-package
 '(:package "package" :host nil :type git
  :repo "http://myhost.tld/repo"))
`

and then do something like:

`(add-to-list 'load-path "path/to/package")`

However, the package in question (and many others I'm very interested in) require in straight's terms that the repo/package including all the non-el code actually be under the build directory. I say this based on straight's error messages. But then every time straight decides to do a rebuild or I forget about this and tell straight to the repo/package under build will get blown away. I've read where you say you symlink into the repo, but again, the package/repo in question and many like it, has to be under .emacs.d or it isn't going to work.

Mostly these types of "packages" have to do with the Emacs environment itself. So for example if you look at Dennis Gentry's (dgentry) version of François Pinard's (pinard) pymacs on github, dgentry has a script that does the right thing for pymacs in terms of virtual environments. But this is a more general desiderata if you want a functional approach generally to emacs and development, for example, in terms of things like conda and/or nix to not only manage project management _but to manage the Emacs environment itself_.

At any rate, how can I get straight to not blow away a package/repo I've installed under `.emacs.d/straight/build/` please?

For that matter, since you wrote straight, what is the proper approach to emacs packages (very often singular .el files) which appear in _no_ repo anywhere as far as Google Search knows and _probably never will_. For example, there are several such things which deal with various aspects of getting shells to behave under Win-NT Emacs.

Thanks in advance for any help

Mike

**Comment by raxod502** [comment]
Let me see if I understand the situation you're describing. It sounds like you have a repository containing a bunch of files, somewhere outside `~/.emacs.d`, and you need some Elisp files from a nested subdirectory of that repository to be available on `load-path`, and you also have some other non-Elisp files in that repository, and those need to be in the same directory as the Elisp files on `load-path` in `~/.emacs.d/straight/build`.

If that's the case, then you can accomplish what you want without any manual operations, by setting `:local-repo` to the root of your repository, and then using a custom `:files` directive to pick out only files from the nested subdirectory to symlink into `~/.emacs.d/straight/build`. The `:files` directive will let you include non-Elisp files, too. You can see the details in the docstring of `straight-expand-files-directive`.

Now to answer your second question, concerning how to manage packages that are not in repositories: I would venture to say that they are not really packages, they're just files. So why try to manage them with a package manager? What value would that add?

But if you want automatic byte-compilation and autoload generation, you can put those files in a directory (or multiple directories) and point `straight.el` at them with `:local-repo` and then specify `:type nil` to say that no version-control system is used.

Let me know if these answers help, or if I've missed something.

**Comment by hongyi-zhao** [comment]
Wonderful explanation.

**Comment by mikereape** [comment]
HI I haven't tried it yet but I'm sure your advice will work. Thanks very much for your answers! I will report back once I get to it. There's a lot of information to take in all at once in your README!

Thanks again,
Mike

**Comment by progfolio** [comment]
> I will report back once I get to it.

Please do. I'm going to close this issue for now, but you should still be able to comment with any updates. Thank you.
