### ISSUE TITLE
Preserve comments on unchanged lines in versions/default.el on straight-freeze-versions 

### ISSUE THREAD

**Issue by BlueSpaceCanary** [raxod502/straight.el#808]
I freeze some packages at tagged releases, and since the frozen versions have to be commit hashes, I put a comment at the end of the line for convenience, e.g.

```elisp
("selectrum" . "a9ecaa018f249c15fae8e1af5d4df337e846e92f") ; 3.1
```

Right now, running `straight-freeze-versions` nukes those comments even if the corresponding package is still frozen at the same commit, and it'd be nice not to have to re-add them each time I run it. 

I assume they get wiped because the whole file gets rewritten on every freeze and this is a really really minor inconvenience, so I won't be at all offended if you WONTFIX this as more effort to implement than it's worth, but I figured I'd ask in case it turned out to be an easy change to make 🙂

**Comment by progfolio** [comment]
> I assume they get wiped because the whole file gets rewritten on every freeze

I believe that is the case.
Rather than trying to preserve the comments in a programmatically generated file,
we can programmatically generate the comments. :)

The following is a minor-mode which will query each repository in the lockfile for the nearest tag
and append a display text property with it on each line.

```emacs-lisp
;;; straight-lockfile-tags-mode.el --- Display version tags for repos in straight's lockfiles  -*- lexical-binding: t; -*-

;;; Commentary:
;; Provided as is.

;;; Code:
(require 'straight)

(defvar straight--lockfile-tags-cache nil "Cache for repo tags.")

(defcustom straight-lockfile-tags-format " VERSION: %s"
  "Format of the tag string.
It must contain one reference to %s which is interpreted as the tag."
  :group 'straight
  :type 'string)

(defun straight--lockfile-tags-commits ()
  "Display nearest tag for each commit in a lockfile."
  (save-excursion
    (goto-char (point-min))
    (unless straight--lockfile-tags-cache
      (setq straight--lockfile-tags-cache
            (mapcar (lambda (cell)
                      (let* ((package (car cell))
                             (default-directory (straight--repos-dir package)))
                        (straight--process-with-result
                            (straight--process-run "git" "describe" "--abbrev=0")
                          (when success (string-trim stdout)))))
                    (save-excursion (read (current-buffer))))))
    (dolist (tag straight--lockfile-tags-cache)
      (when tag
        (put-text-property (1- (line-end-position)) (line-end-position) 'display
                           (concat (char-to-string (char-after (- (point) 2)))
                                   (propertize (format straight-lockfile-tags-format tag)
                                               'face 'font-lock-comment-face))))
      (forward-line 1))))

(defun straight--clear-lockfile-tags ()
  "Clear display of lockfile commit tags."
  (save-excursion
    (goto-char (point-min))
    (while (not (eobp))
      (remove-text-properties (line-beginning-position) (line-end-position) '(display))
      (forward-line))))

(define-minor-mode straight-lockfile-tags-mode
  "Minor mode to show tags instead of commits in lockfiles."
  :lighter " slt"
  (if straight-lockfile-tags-mode
      (straight--lockfile-tags-commits)
    (straight--clear-lockfile-tags)))

(provide 'straight-lockfile-tags-mode)

;;; straight-lockfile-tags-mode.el ends here
```

You can customize `straight-lockfile-tags-format` to your liking.
Try saving evaluating the above code, visiting your lockfile of choice and toggling `straight-lockfile-tags-mode`.
It should do what it claims on the tin, but I've only done very light testing.

Here's what it looks like on the lockfile I tested with:

![image](https://user-images.githubusercontent.com/44036031/124049274-1ac8ba00-d9e6-11eb-87ce-7e5f30c35e65.png)

**Comment by BlueSpaceCanary** [comment]
That snippet was super helpful, thanks! I had to make one change, `(char-to-string (char-after (- (point) 2)))` to `(char-to-string (char-after (1- (line-end-position))))` because `(point)` was 1 on the first run of the loop so `(char-after (- (point) 2)))` was nil, but I've written very little elisp so I don't know enough to know why `(point)` was behaving differently for me. With that minor tweak this is doing exactly what I need

**Comment by progfolio** [comment]
> (char-after (1- (line-end-position)))) because (point) was 1 on the first run of the loop so (char-after (- (point) 2))) was nil

Yes, that's certainly better than the magic constant I had there.
Glad it works well enough for you.
