### ISSUE TITLE
Equivalent of package.el's `package-initialize`?

### ISSUE THREAD

**Issue by declanqian** [raxod502/straight.el#809]
I've been try to replace Emacs built-in `package.el` with `straight.el` in my custom build of
Emacs. It's great if `straight.el` has some equivalent of package.el's `package-initialize`, which you
don't have to call explictly.

Basically we needs a commands which defers bootstrap process from `bootstrap.el` until first invoking of
`straight-use-package` and some other functions like `straight-get-recipe` etc

**Comment by declanqian** [comment]
I have some demo code from this branch.
https://github.com/declanqian/straight.el/commit/4b72338390485cf7db32c391f68c592fd288ca9c
The code inside `straight-bootstrap` are some copy/paste from `bootstrap.el`.

**Comment by raxod502** [comment]
Sorry, could you help me understand the use case for this change? Why is it helpful to have a separate function? Under what circumstances would you want to do that instead of using the standard bootstrap procedure?

**Comment by declanqian** [comment]
I was playing around with emacs-ng, and try to replace built-in `package.el` with
`straight.el` https://github.com/declanqian/emacs/commit/b35f1e05f2374d8a4d658b16863a9c13f77600fb
There is no ideal place to put `bootstrap` code.

Since the standard bootstrap procedure basically do two things:

- Download `straight.el` if needed and load the file.
- Resister recipes and do some setups

For my concern, I've already included straight.el file inside Emacs, and have
straight.el autoloads loaded. So I just need to resister recipes.

So a command to manually register recipes would be awesome, also,
we probably do not need to do this if we never invoke `straight-use-package`.

With `straight-bootstrap` in place, we can even submit straight.el as package to melpa

**Comment by declanqian** [comment]
After some testing/playing around my changes, defering/automating
bootstrap procedure is a little bit more complicated than just
putting the function on top of my init file. 

Now the PR is more than just wrap some code from `bootstrap.el` file
into an interactively function `straight-bootstrap` in straight.el file.
No serious changes really.

**Comment by raxod502** [comment]
Yeah. I'm not convinced this kind of thing would actually simplify user code. Sure, the bootstrap snippet does a bit of unnecessary work if you've already installed and loaded `straight.el`, but it's only one or two filesystem ops, and the behavior is identical to a more streamlined approach.

Regarding putting it on MELPA, see https://github.com/raxod502/straight.el/issues/134.
