### ISSUE TITLE
The possiable local repositories naming confliction problem for different projects with the same name hosted on different remote hosts.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#811]
Say, there are two different projects with the same name hosted on different remote hosts:

```
https://github.com/foo/baz.git
https://gitlab.com/bar/baz.git
```
How to solve the problem when both are installed at the same time with straight?

Regards,
HY

**Comment by progfolio** [comment]
In this case you would provide a unique `:local-repo` for one of the recipes.

**Comment by hongyi-zhao** [comment]
Thanks a lot. Based on the notes [here](https://gitter.im/raxod502/straight.el?at=5a7a83a5e217167e2c511c25), I figured out the following usage:


```emacs-lisp
(straight-use-package
 '(zenitani-elisp :local-repo "~/.emacs.d/straight/repos/zenitani-elisp" :type git :host nil :repo "https://github.com/zenitani/elisp.git"))
```

**Comment by raxod502** [comment]
Right. And you can abbreviate that to `:local-repo "zenitani-elisp"` as the base directory against which `:local-repo` is expanded is already `~/.emacs.d/straight/repos`. This has been reported before, see e.g. https://github.com/raxod502/straight.el/issues/265.

**Comment by hongyi-zhao** [comment]
Thank you, fixed it to the following:
```emacs-lisp
(straight-use-package
 '(zenitani-elisp :local-repo "zenitani-elisp" :type git :host nil :repo "https://github.com/zenitani/elisp.git"))
```
