### ISSUE TITLE
Combine the use-package's configuration into straight-use-package.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#815]
Consider the following configuration:
```emacs-lisp
(straight-use-package
 `(swiper :type git :host github :repo "abo-abo/swiper"
    :pre-build (
               ;("bash" "-c" "cd ~/.emacs.d/straight/repos/swiper")
               ;https://github.com/abo-abo/swiper/issues/2886#issuecomment-860605327
               ("make" "deps")
               ("make" "compile")
               )))

;https://github.com/jeremyf/dotzshrc/blob/e063baf78b8049dede98dea2c84ec3329310806a/emacs/jnf-ivy.el#L130
(use-package swiper
  :straight t
  :bind (("C-s" . swiper)))
```
How can I combine them into a single configuration with `straight-use-package`?

**Comment by progfolio** [comment]
Please see the following documentation:

https://github.com/raxod502/straight.el#integration-with-use-package

Particularly the section that mentions "You can still provide a custom recipe for the package".

**Comment by hongyi-zhao** [comment]
Thanks a lot. Based on the above guidance, the following will do the trick:
```emacs-lisp
(use-package swiper
  :straight `(swiper :type git :host github :repo "abo-abo/swiper"
              :pre-build (
                          ;("bash" "-c" "cd ~/.emacs.d/straight/repos/swiper")
                          ;https://github.com/abo-abo/swiper/issues/2886#issuecomment-860605327
                          ("make" "deps")
                          ("make" "compile")
                         ))
  :bind (("C-s" . swiper)))
```

**Comment by progfolio** [comment]
No need for the backquote^1 before the list if you're not evaluating anything within the list:

```emacs-lisp
(use-package swiper
  :straight (swiper :type git :host github :repo "abo-abo/swiper"
                    :pre-build (("make" "deps") ("make" "compile")))
  :bind (("C-s" . swiper)))
```

[1] https://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html

**Comment by hongyi-zhao** [comment]
> No need for the backquote1 before the list if you're not evaluating anything within the list:
 
How to input the superscript 1 here?

> 
> ```emacs-lisp
> (use-package swiper
>   :straight (swiper :type git :host github :repo "abo-abo/swiper"
>                     :pre-build (("make" "deps") ("make" "compile")))
>   :bind (("C-s" . swiper)))
> ```
> 
> [1] https://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html

Thanks again for pointing this out.

**Comment by progfolio** [comment]
> How to input the superscript 1 here?

Github's markdown flavor allows for some HTML tags. I used:

```markdown
<sup>1</sup>
```

**Comment by hongyi-zhao** [comment]
> <sup>1</sup>

Wonderful notes. I really don't know such a fancy thing till now.
