### ISSUE TITLE
Use straight-use-package in an embedded way.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#816]
Can I use straight-use-package in an embedded way, for example, by:
```emacs-lisp
(straight-use-package 'foo
  ...
     straight-use-package 'bar)
```
Regards,
HY

**Comment by progfolio** [comment]
If you mean can you nest a call within another call, it would depend where you were nesting it.
I suppose you could technically do it in the `:pre`/`:post-build` sections of a recipe, but that would most likely be an abuse of their intended usage. Do you have a specific example of what you're trying to achieve?

**Comment by hongyi-zhao** [comment]
> If you mean can you nest a call within another call, 

Yes.
> Do you have a specific example of what you're trying to achieve?

Something similar to the following. If I'm wrong in the usage, feel free to correct me:
```emacs-lisp
(straight-use-package 'prescient)
(straight-use-package '(ivy-prescient
  :after prescient
  :init (setq prescient-filter-method '(literal fuzzy regexp initialism))
  :config (ivy-prescient-mode t)))
```

**Comment by progfolio** [comment]
You can nest the `use-package` macro:

```emacs-lisp
(use-package a
  :config
  (use-package b))
```

I've seen this pattern in some configs, but I don't think it's any better than using
use-package's `:after` keyword:

```emacs-lisp
(use-package a :defer t)
(use-package b :after a)
```
However, straight's recipe format does not support any of the keywords in your example (`:after`, `:init`, `:config`).
The names are similar, but `straight-use-package` and `use-package` for two different purposes.
That sort of package configuration should be delegated to `use-package`.

**Comment by hongyi-zhao** [comment]
> You can nest the `use-package` macro:
> 
> ```emacs-lisp
> (use-package a
>   :config
>   (use-package b))
> ```
> 
> I've seen this pattern in some configs, but I don't think it's any better than using
> use-package's `:after` keyword:

Really. The following method gives us more control granularity, and it also makes modular configurations more robust and reusable.
> 
> ```emacs-lisp
> (use-package a :defer t)
> (use-package b :after a)
> ```
> 

Therefore, I should use something like the following in my example:

```emacs-lisp
(use-package prescient :defer t)
(use-package ivy-prescient
  :after prescient
  :init (setq prescient-filter-method '(literal fuzzy regexp initialism))
  :config (ivy-prescient-mode t))
```

> However, straight's recipe format does not support any of the keywords in your example (`:after`, `:init`, `:config`).
> The names are similar, but `straight-use-package` and `use-package` serve two different purposes.
> Straight is generally for installing/buildling packages, and use-package is generally for configuring them.
> That sort of package configuration in your example should be delegated to `use-package`.

Thank you very much for your detailed and in-depth explanation.

**Comment by progfolio** [comment]
> But with the :defer t option, it seems that the other packages invoking this package won't be activated immediately after I started Emacs. So, if I want to use all the features set in the configuration immediately after I started Emacs, the :defer shouldn't be used. Am I right?

Yes. `:defer` will defer the loading of the package. I recommend reading over the use-package documentation:

https://github.com/jwiegley/use-package

There are a number of keywords that will defer the loading of a package and other ways to force the immediate loading of a package.

**Comment by hongyi-zhao** [comment]
Thank you again. Based on the guidance [here](https://github.com/jwiegley/use-package#notes-about-lazy-loading) and [here](https://github.com/jwiegley/use-package#loading-packages-in-sequence), I tried the following methods, all of which force the load to happen immediately:

```emacs-lisp
(use-package prescient :demand t)
(use-package ivy-prescient
  :after prescient
  :init (setq prescient-filter-method '(literal fuzzy regexp initialism))
  :config (ivy-prescient-mode t))
```
or
```emacs-lisp
(use-package prescient :demand t
  :config
  (use-package ivy-prescient
  :init (setq prescient-filter-method '(literal fuzzy regexp initialism))
  :config (ivy-prescient-mode t)))
```
