### ISSUE TITLE
Recipe for org-plus-contrib not working anymore?

### ISSUE THREAD

**Issue by godeater** [raxod502/straight.el#818]
I've recently been trying to bootstrap my emacs config on a new machine, and noticed that one of my staples - the org-plus-contrib package no longer installs via straight. This *appears* to be because the org-mode repo seems to no longer contain it, and the content has been moved to it's own repo as of about a month ago.

I'm not sure if the idea here is that I update a personal recipe to get the missing files myself, or whether this is such a hugely popular package that straight's default recipes should be updated to manage where it comes from now?

The error I get is:
("Could not find package org-plus-contrib. Updating recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror) with 'straight-pull-recipe-repositories' may fix this")

Edit: I've just noticed that this page says the org-elpa package archive is now deprecated as of Org 9.5:
https://orgmode.org/elpa.html

**Comment by godeater** [comment]
I've just noticed there's another issue referencing this as well, so I'll just close this!

**Comment by Fuco1** [comment]
Please provide the link to the duplicate for future reference :)
