### ISSUE TITLE
Retrieve/Install/Manage a package which is not distributed with any version control system.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#820]
If a package is distributed without using any version control system, how to retrieve/install/manage it with straight?

Regards,
HY

**Comment by progfolio** [comment]
Do you have a specific example in mind, or are you asking in the abstract?

straight can work with local repositories, too. So if the maintainer or publisher does not use version control, you could put the package in version control yourself and point straight to that repository (locally or wherever you prefer to host it).

**Comment by hongyi-zhao** [comment]
> Do you have a specific example in mind, or are you asking in the abstract?

I try to use `mathematica` within Emacs based on the guidance [here](https://rgoswami.me/posts/org-mathematica/), which use some self-crafted el files not resided on any internet host for software development and version control. 

> you could put the package in version control yourself 

Do you mean that I must first put it into a version control based repo?

**Comment by progfolio** [comment]
> which use some self-crafted el files not resided on any internet host for software development and version control

From the article  you linked I see three resources mentioned:

> So to recap, use your favorite manager to get:

>    ob-mathematica (in contrib)
>    wolfram-mode (MELPA)
>    mash.pl (from here)1

I assume you're referring to mash.pl, which is hosted on the author's personal `.edu` site.
If that's the case, it's a standalone perl script, so I wouldn't use straight.el to manage that.
The file looks like it is pretty static (last touched 2010-08-01 according to the directory listing),
so it may or may not be worth keeping in version control locally depending on your plans with it.

> Do you mean that I must first put these stuff into a version control based repo?

If there are elisp packages you found that are hosted similarly, I would either contact the author to see if they're interested in contributing them to an elisp archive like MELPA, or keep a copy for yourself and check it into version control.

Does that help?

**Comment by hongyi-zhao** [comment]
> I assume you're referring to mash.pl, which is hosted on the author's personal `.edu` site.
> If that's the case, it's a standalone perl script, 

Yes. You're right. Thank you for correcting me.

> so I wouldn't use straight.el to manage that.

Does `straight.el` only make sense for elisp packages management?

> The file looks like it is pretty static (last touched 2010-08-01 according to the directory listing),
> so it may or may not be worth keeping in version control locally depending on your plans with it.

For example, if I want to make some enhancements to it, it might be convenient to keep track of it in version control.

BTW, if I don't let `straight.el` manage it, then I must manage the load path for it separately, am I right?

**Comment by progfolio** [comment]
> For example, if I want to make some enhancements to it, it might be convenient to keep track of it in version control.

yes.

> Does straight.el only make sense for elisp packages management?

That's certainly what it's geared toward.

> BTW, if I don't let straight.el manage it, then I must manage the load path for it separately, am I right? I mean, for a lot of such things, this will be a cumbersome work.

I don't see why you would need to manage the load-path for a perl script. It's not like Emacs will interpret/execute that script.

In general, for one-off elisp scripts, people typically add a directory under ~/.emacs.d and add that to their load-path recursively. see:

https://www.emacswiki.org/emacs/LoadPath

**Comment by hongyi-zhao** [comment]
> I don't see why you would need to manage the load-path for a perl script. It's not like Emacs will interpret/execute that script.

It's I that don't state clearly here. I mean, in general, for so much elisp files which don't managed by `straight.el`.
 
> In general, for one-off elisp scripts, people typically add a directory under ~/.emacs.d and add that to their load-path recursively. see:
> 
> https://www.emacswiki.org/emacs/LoadPath

Thank you, got it.

**Comment by raxod502** [comment]
See also the second part of my answer in https://github.com/raxod502/straight.el/issues/807#issuecomment-886115501.
