### ISSUE TITLE
Error (use-package): Cannot load emacs-sdcv

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#823]
I try to install [emacs-sdcv](https://github.com/gucong/emacs-sdcv) with `straight` through `use-package` as following:
```emacs-lisp
(use-package emacs-sdcv
  :demand t
  :straight (:host github :repo "gucong/emacs-sdcv"))
```
But I meet the following error:

`Error (use-package): Cannot load emacs-sdcv`

Any hints for solving this problem?

Regards,
HY

**Comment by progfolio** [comment]
See the comment here: https://github.com/raxod502/straight.el/issues/824#issuecomment-886102853

use-package doesn't want the name of the repository as it's first argument, it wants the name of the package. It looks like this package `provide`s a feature named `sdvc-mode`:

https://github.com/gucong/emacs-sdcv/blob/c51569ebf3fd1f8c02c33c289d229996bf2ff186/sdcv-mode.el#L53

So you'll want:

```emacs-lisp
(use-package sdvc-mode ;etc...
```

**Comment by raxod502** [comment]
I would personally recommend expanding the `use-package` macro with [macrostep](https://github.com/joddie/macrostep) and also consulting the [`use-package` documentation](https://github.com/jwiegley/use-package) and [issue tracker](https://github.com/jwiegley/use-package/issues) to gain a better understanding of how `use-package` operates. While we on the `straight.el` team have a fair amount of knowledge about `use-package` by happenstance and common usage, questions about `use-package` are related to `straight.el` only tangentially and you might be better served by other resources.

**Comment by hongyi-zhao** [comment]
> ```emacs-lisp
> (use-package sdvc-mode ;etc...
> ```

Thank you. It does the trick. Some additional comments:

1. Should be `sdcv-mode` here.
2. Based on my tries, the following also will work:

```emacs-lisp
(straight-use-package
  '(emacs-sdcv :type git :host nil :repo "https://github.com/gucong/emacs-sdcv.git")) 
```

**Comment by hongyi-zhao** [comment]
> I would personally recommend expanding the `use-package` macro with [macrostep](https://github.com/joddie/macrostep)

It seems this package is rather stale.

Thank you for your suggestions.

**Comment by progfolio** [comment]
> It seems that this package is rather stale.

I wouldn't judge it by how many recent commits it has had.
It works. It may not have needed anything new work added to it.
I use it daily.
