### ISSUE TITLE
failed to provide feature ‘mw-thesaurus.el’

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#824]
On Ubuntu 20.4, I try to install [mw-thesaurus.el](https://github.com/agzam/mw-thesaurus.el) with straight as following:

```emacs-lisp
(use-package mw-thesaurus.el
  :demand t
  :straight (:host github :repo "agzam/mw-thesaurus.el")
  :config
  (setq mw-thesaurus--api-key "MY-API-KEY"))
```

But I meet the following error:

`Error (use-package): mw-thesaurus.el/:catch: Loading file /home/werner/.emacs.d/straight/build/mw-thesaurus.el/mw-thesaurus.el failed to provide feature ‘mw-thesaurus.el’`

Any hints for this problem?

Regards,
HY

**Comment by progfolio** [comment]
> Loading file /home/werner/.emacs.d/straight/build/mw-thesaurus.el/mw-thesaurus.el failed to provide feature ‘mw-thesaurus.el’

The error message is the key here. What it's saying is that the package mw-thesauraus.el does not provide a feature by that name. Looking at the source code we can see that the provided feature name is `mw-thesauraus` (without the `.el`):

https://github.com/agzam/mw-thesaurus.el/blob/96f02694bc28f31c2a280a05d47e6ff589f525f3/mw-thesaurus.el#L263

In general, when you're having trouble with a macro such as `use-package`, it's beneficial to expand the macro
to see what elisp is generated. I recommend the macrostep package, which makes it very easy to see inline:

https://github.com/joddie/macrostep

For example, your use-package declaration: 

```emacs-lisp
(use-package mw-thesaurus.el
  :demand t
  :straight (:host github :repo "agzam/mw-thesaurus.el")
  :config
  (setq mw-thesaurus--api-key "MY-API-KEY"))
```

Expands to:

```emacs-lisp
(progn
  (straight-use-package
   '(mw-thesaurus\.el :host github :repo "agzam/mw-thesaurus.el"))
  (require 'mw-thesaurus\.el nil nil)
  (setq mw-thesaurus--api-key "MY-API-KEY")
  t)
```

See how require is being passed mw-thesauars.el?

What you want is:

```emacs-lisp
(use-package mw-thesaurus
  :demand t
  :straight (:host github :repo "agzam/mw-thesaurus.el")
  :config
  (setq mw-thesaurus--api-key "MY-API-KEY"))
```

which will expand to:

```emacs-lisp
(progn
  (straight-use-package
   '(mw-thesaurus :host github :repo "agzam/mw-thesaurus.el"))
  (require 'mw-thesaurus nil nil)
  (setq mw-thesaurus--api-key "MY-API-KEY")
  t)
```
I would also recommend reading up on named features in Emacs if you're curious:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Named-Features.html

**Comment by hongyi-zhao** [comment]
> In general, when you're having trouble with a macro such as `use-package`, it's beneficial to expand the macro
> to see what elisp is generated. I recommend the macrostep package, which makes it very easy to see inline:
> 
> https://github.com/joddie/macrostep

Thank you for your recommendation. I installed it with the following configuration:
```emacs-lisp
(use-package macrostep
  :demand t  
  :config 
  (define-key emacs-lisp-mode-map (kbd "C-c e") 'macrostep-expand))
```

Then I test the following elisp code in scratch buffer:

```emacs-lisp
(use-package mw-thesaurus
  :demand t
  :straight (:host github :repo "agzam/mw-thesaurus.el")
  :config
  (setq mw-thesaurus--api-key "c484bb22-a8c1-4c36-9926-0b520f8be7d4"))
```
With the point in any part of the above snippet, I hit `C-c e`, but the code won't expanded and Emacs complains the following message:

`  C-c e is undefined`

OTOH, `M-x macrostep-expand RET` will do the trick, as shown below:

![image](https://user-images.githubusercontent.com/11155854/126885199-01d90ab2-b2e6-4cf0-bb61-e7b043a46dc6.png)

But as you can see, my result is different to yours as far as the following line is concerned:

> ```emacs-lisp
>   (require 'mw-thesaurus nil nil)
> ```
