### ISSUE TITLE
About the usage of `:type nil`.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#827]
In [this comment](https://github.com/raxod502/straight.el/issues/807#issuecomment-886115501), you elaborated the following usage:

> But if you want automatic byte-compilation and autoload generation, you can put those files in a directory (or multiple directories) and point `straight.el` at them with `:local-repo` and then specify `:type nil` to say that no version-control system is used.

But I've checked carefully from beginning to end on [the source lisp file](https://github.com/raxod502/straight.el/blob/master/straight.el) of this package, and can't find any clue/docstring dedicated to the above-mentioned usage. If the above usage can only be checked/confirmed based on the lisp code's logic, it is better to add some clear instructions in the document. 

Any hints for clarifying this ambiguity will be appreciated.

Regards,
HY

**Comment by progfolio** [comment]
Thanks for bringing this to our attention.
We should improve the documentation with an example of this particular use-case.
I've referenced this in #671
