### ISSUE TITLE
About the usage of `straight-remove-unused-repos`.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#829]
I noticed the following function:

https://github.com/raxod502/straight.el/blob/1e27b0590df77a5d478970ca58fd6606971692f5/straight-x.el#L133

And I really want to clean the unused-repos managed by `straight.el`, but still can't figure out how to use it.

Any hints will be highly appreciated.

Regards,
HY

**Comment by progfolio** [comment]
`M-x straight-remove-unused-repos` should prompt you to delete each unused repo if any are found.

**Comment by hongyi-zhao** [comment]
Good. It would be even better if it had the option to let users confirm it once and for all.

**Comment by progfolio** [comment]
It can be used programmatically as well.
You could easily write a wrapper which always skips the prompt. e.g.

```emacs-lisp
(defun +straight-force-remove-unused-repos ()
  "Remove unused repos without prompting."
  (straight-remove-unused-repos 'force))
```

**Comment by hongyi-zhao** [comment]
I should have checked the definition for myself:

![image](https://user-images.githubusercontent.com/11155854/127169686-c060de51-c434-4a58-a75b-3021d6ff4b1d.png)

**Comment by hongyi-zhao** [comment]
I just wonder why don't it also supply the `straight-remove-unused-build` according to the directories structure used by `straight.el`?

**Comment by progfolio** [comment]
> I just wonder why it doesn't also supply the straight-remove-unused-build according to the directories structure used by straight.el?

Hasn't been implemented yet, that's all. I think it would make sense to remove the build dirs if they are present in addition to the repo dirs. I'm in the middle of a move currently, so I can't say I'll get to this any time soon. Pull request welcome if you're feeling up to it.

**Comment by hongyi-zhao** [comment]
> I think it would make sense to remove the build dirs if they are present in addition to the repo dirs.

To be sure, the dirs located under the build directory are named after the `<package-name>` or feature name, which may be the same or different from the package names located in the repos directory.

**Comment by hongyi-zhao** [comment]
> Pull request welcome if you're feeling up to it.

I try to adjust the `straight-remove-unused-repos` and tailor out the `straight-remove-unused-packages` for packages under build directory:

```emacs-lisp
;;;###autoload
(defun straight-remove-unused-packages (&optional force)
  "Remove unused packages from the build directory.
A package is considered \"unused\" if it was not explicitly requested via
`straight-use-package' during the current Emacs session.
If FORCE is non-nil do not prompt before deleting package."
  (interactive "P")
  (let ((r '()))
    (dolist (package (straight--directory-files
                   (straight--build-dir) nil nil 'sort))
      (unless (straight--checkhash package straight--build-cache)
        (when (or force (y-or-n-p (format "Delete package %S? " package)))
          (delete-directory (straight--build-dir package) 'recursive 'trash)
          (push package r))))
    (message (concat "%d " (if (eq (length r) 1) "package" "packages")
                     " deleted" (if r ": %s" "."))
             (length r) (nreverse r))))
```
Any suggestions/comments/improvements would be appreciated.

Regards,
HY

**Comment by progfolio** [comment]
Ideally we would have this all as one command.
I'll think on it and get back to you.
