### ISSUE TITLE
Adjust the `build` directory to `builds`.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#831]
I noticed that the files and directories structure used by `straight.el` are as follows currently: 

```
$ ls ~/.emacs.d/straight/
build  build-cache.el  repos
```
It seems that if we rename the `build` directory to  `builds`, better consistency in naming conventions can be achieved. 

Regards,
HY

**Comment by progfolio** [comment]
This is a fair point, but it may be a breaking change for some users and the benefit is limited.

**Comment by hongyi-zhao** [comment]
> This is a fair point, but it may be a breaking change for some users and the benefit is limited.

It can be ensured/fixed from the repos side when the user starts Emacs. To be simple: the `el` files in `build` directory are symlinks pointing to the corresponding ones located at `repos` directory, so, check and relink them should be not a cumbersome job. 

But BTW, if so, some currently used functions relevant to `build` directory also should be renamed accordingly to reflect this situation.

**Comment by progfolio** [comment]
> It can be ensured/fixed from the repos side when the user starts Emacs. To be simple: the el files in build directory are symlinks pointing to the corresponding ones located at repos directory, so, check and relink them should be not a cumbersome job.

Sure, but then the user pays the penalty of that check at the start of every Emacs session.

As you point out, we'd have to make some breaking changes as well:

> But BTW, if so, some currently used functions relevant to build directory also should be renamed accordingly to reflect this situation.

We'll have to reconsider this if we make a major version release. Closing for now.

**Comment by hongyi-zhao** [comment]
> Sure, but then the user pays the penalty of that check at the start of every Emacs session.

No, this type of check only needs to be performed once, that is, to create a new build package directory, where the el file is relinked to the source in the repos directory.

**Comment by progfolio** [comment]
I'm not sure I follow. Where/when would the check take place? When straight is loaded?

**Comment by hongyi-zhao** [comment]
When Emacs is started and straight is used as the package manager, just as the things done to build a new package.

**Comment by progfolio** [comment]
That would mean the check is conducted every time Emacs is started. It would add a compatibility path to the code and a number of aliases if we wanted to do it in a non-breaking fashion. The benefit is minimal IMO. Perhaps we can deal with it down the line,  but I consider this low priority at the moment.

**Comment by hongyi-zhao** [comment]
I'm still not so clear above the low-level package monitoring mechanism in straight, but I noticed that the file `~/.emacs.d/straight/build-cache.el` is used for preventing rebuilding, and make the check very quickly each time when Emacs is started.

**Comment by raxod502** [comment]
I'm with @progfolio here. While you're correct that a version counter could be installed into the build cache to handle one-time migrations like this, it would be a lot of work for no clear benefit.
