### ISSUE TITLE
Can straight.el do all the jobs of auto-package-update?

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#832]
I've noticed that [auto-package-update.el](https://github.com/rranelli/auto-package-update.el) provides functionality for automatically updating the installed Emacs packages periodically. I use [straight.el](url) and enabled its [use-package integration](https://github.com/raxod502/straight.el#integration-with-use-package). As far as I am concerned, the following configuration is currently used for automatic package updates:

```emacs-lisp
(use-package auto-package-update
  :config
  (setq auto-package-update-delete-old-versions t)
  (setq auto-package-update-hide-results t)
  (auto-package-update-maybe))
```
I want to know whether `straight.el` can do all the jobs of `auto-package-update` mentioned above? 

Regards,
HY

**Comment by progfolio** [comment]
There is no timer based update mechanism built into straight.el.
The timer-based approach would only work well in the case where no manual intervention is needed for an update.
From a quick glance it looks as if auto-package-update.el supports quelpa and package.el.
I'm sure it could be extended to work with straight, but that would require changes to its source.

**Comment by raxod502** [comment]
Yes, and I'm not sure I would advise this kind of thing in general. `straight.el` is intended to make package configurations more reproducible, not less.
