### ISSUE TITLE
How to prevent straight cloning a certain project? Problems with project and eglot

### ISSUE THREAD

**Issue by rileyrg** [raxod502/straight.el#833]
Whichever version of 'project straight clones is incompatible with 'eglot it seems.

I have an early (require 'project) in my init (after ensureing I had purged 'project from straight/repos & build) but later on something is triggering another load and straight is insisting on cloning it. I don't have a (use-package project) in my init.

How can I prevent or blacklist a package from being cloned and instead simply rely on the version shipped with emacs?

**Comment by progfolio** [comment]
Does any of the info in #551 help?

**Comment by progfolio** [comment]
Try evaluating the following test case:


<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "test"
  :preserve t
  :post-bootstrap 
  (straight-use-package
   '(project :local-repo nil))
  (straight-use-package 'eglot)
  (message "repos dir:\n%s\n"
           (string-join
            (straight--directory-files
             (straight--repos-dir))
            "\n")))
```
</details>

- Test run at: `2021-08-13 14:09:24`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 45eb611 2021-08-13`
- emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
 of 2021-08-02`

<details><summary>Output</summary>

```emacs-lisp
Test run with version: prerelease (HEAD -> develop, origin/develop) 45eb611 2021-08-13
repos dir:
straight.el
melpa
gnu-elpa-mirror
el-get
emacsmirror-mirror
eglot
jsonrpc
flymake
eldoc
xref

Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master c44eceaf 2021-08-09
"gnu-elpa-mirror"         n/a                  master 8ce05c5 2021-08-10
"el-get"                  melpa                master 463f5e98 2021-07-06
"emacsmirror-mirror"      n/a                  master 664c0cc 2021-08-09
"straight"                n/a                  develop 45eb611 2021-08-13
"project"                 gnu-elpa-mirror      n/a
"eglot"                   melpa                master 194b178 2021-07-22
"jsonrpc"                 gnu-elpa-mirror      master dbfa309 2021-02-08
"flymake"                 gnu-elpa-mirror      master c89cabb 2021-08-02
"eldoc"                   gnu-elpa-mirror      master 24ab6e0 2021-05-18
"xref"                    gnu-elpa-mirror      master c1d9ef0 2021-08-06


```
</details>

**Comment by progfolio** [comment]
Any luck with this?

**Comment by rileyrg** [comment]
Sorry. I was remiss. I'll check soon.  --Please note my email address is now ***@***.*** 20/08/2021, 17:43 Nicholas Vollmer ***@***.***> wrote:

   
  Any luck with this?

**Comment by progfolio** [comment]
Closing this for now. If you test any of the above and it doesn't work out, or you have any other info to add, please feel free and we can reopen if necessary.
