### ISSUE TITLE
[Question] how to install ssl.el under utils directory of wanderlust, :staright directive with use-package

### ISSUE THREAD

**Issue by yamatakau08** [raxod502/straight.el#834]
I'm using use-package and straight.

```
(use-package wl
  :straight `(wanderlust)
  ;; ...
  )
```

This downloads wanderlust package in under ~/.emacs.d/straight/reeos/wanderlust directory.
And also utlis files in "utils" directory with keeping directory hierarchy.

I want to use ssl.el in utils directory of wanderlust.

But the above :straight directive in use-package doesn't put ssl.el and ssl.elc in ~/.emacs.d/straight/build/wanderlust.
Could you how to write :straight directive to put ssl.el and ssl.elc in ~/.emasc.d/straight/build/wanderlust.

**Comment by progfolio** [comment]
The way the files are symlinked to the `build` directory is controlled by the `:files` recipe keyword.
Its behavior is documented in the following:

https://github.com/raxod502/straight.el#the-recipe-format

https://github.com/raxod502/straight.el/blob/1e27b0590df77a5d478970ca58fd6606971692f5/straight.el#L4679

I'm not all that familiar with the structure of Wanderlust, but `straight-get-recipe` returns this for me as a default recipe:

```emacs-lisp
(wanderlust :type git :flavor melpa :files
            ("doc/wl.texi" "doc/wl-ja.texi" "elmo/*.el" "wl/*.el" "etc/icons"
             (:exclude "elmo/elmo-database.el" "elmo/utf7.el" "wl/wl-dnd.el" "wl/wl-mule.el" "wl/wl-xmas.el")
             "wanderlust-pkg.el")
            :host github :repo "wanderlust/wanderlust")
```

The `;files` directive could be modified to include the `utils` directory like so:

```emacs-lisp
(wanderlust :type git :flavor melpa :files
            ("utils/*" "doc/wl.texi" "doc/wl-ja.texi" "elmo/*.el" "wl/*.el" "etc/icons"
             (:exclude "elmo/elmo-database.el" "elmo/utf7.el" "wl/wl-dnd.el" "wl/wl-mule.el" "wl/wl-xmas.el")
             "wanderlust-pkg.el")
            :host github :repo "wanderlust/wanderlust")
```

Does that help?

**Comment by yamatakau08** [comment]
Thank you for supporting, progfolio!
It works like a charm.

I'm new to straight, just started. 
You supporting is very appreciated.
