### ISSUE TITLE
straight.el on a guix system

### ISSUE THREAD

**Issue by reuleaux** [raxod502/straight.el#837]
I have been using `straight.el` successfully on Debian systems for quite some time.

Now I am getting my hands dirty with installing a (standalone) guix system - and to that end I would
want to take with me all the things (configs) that I have come to rely on, among them `straight.el` for
my emacs config.

Whether this is a good idea in the long run, remains to be seen: there are already quite a number
of emacs packages available in guix, for example (for me): 
  ```
      emacs 
      emacs-auto-complete
      emacs-company
      emacs-dash
      emacs-f
      emacs-s
      emacs-leaf
      emacs-markdown-mode
      emacs-flycheck
      emacs-flycheck-package
      emacs-flycheck-haskell
      emacs-haskell-mode
      emacs-prop-menu
      emacs-counsel
      emacs-ivy
      emacs-amx
      emacs-hy-mode
      emacs-highlight-defined
      emacs-poet-theme
      emacs-rainbow-delimiters
      emacs-dhall-mode
      ;; emacs-git-modes
      emacs-toml-mode
      emacs-highlight-defined
      emacs-peep-dired
      emacs-geiser
      emacs-geiser-gauche
      emacs-bm
```

and according to `https://www.reddit.com/r/emacs/comments/jhb2i6/guix_the_right_way_to_manage_your_packages/`
at least: creating/installing guix emacs-* packages is the preferred way to proceed (to be discussed maybe).

But of course, there are much more packages available for plain emacs via straight.el from elpa, etc.,
for example `leaf-keywords` is missing for me. And I would rather want to have straight.el install it
for me, than having to create a leaf-keywords guix package by hand.

Thus I am trying to get straight running on a guix system - I do have `git` installed: it just lives in
```
rx@dell ~$ type git
git is /run/current-system/profile/bin/git
```

Now when I set up a simple `init.el` with just the usual `straight.el` stanza

```emacs-lisp
  (defvar do-straight-checks nil)


  (defvar bootstrap-version)
  (let ((bootstrap-file
	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	(bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
	  (url-retrieve-synchronously
	   "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	   'silent 'inhibit-cookies)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (if do-straight-checks
      (progn
	(add-hook 'emacs-startup-hook
		  (lambda ()
		    (message "w/ straight checks...")
		    (run-with-timer 2 nil (lambda () (message "")))
		    ))
	)
    (progn
      (defvar straight-check-for-modifications)
      (setq straight-check-for-modifications '())
      )
    )
```
I get this (git is failing / not found - as I understand):
```Debugger entered--Lisp error: (error "straight.el bootstrap failed: Failed to run \"git\";...")
  signal(error ("straight.el bootstrap failed: Failed to run \"git\";..."))
  error("straight.el bootstrap failed: %s" "Failed to run \"git\"; see buffer *straight-process*...")
  (if (= 0 (call-process (let ((emacs-binary-path (expand-file-name invocation-name invocation-directory)) (runemacs-binary-path (if (straight--window$
  (progn (if (= 0 (call-process (let ((emacs-binary-path (expand-file-name invocation-name invocation-directory)) (runemacs-binary-path (if ... ...)))$
  (unwind-protect (progn (if (= 0 (call-process (let ((emacs-binary-path ...) (runemacs-binary-path ...)) (if (and runemacs-binary-path ...) runemacs-$
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (if (= 0 (call-process (let (... ...) (if ... runemacs-binary-path emacs-binary$
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (if (= 0 (call-process (le$
  (let ((temp-file (make-temp-file "straight.el~"))) (write-region nil nil temp-file nil 'silent) (let ((temp-buffer (generate-new-buffer " *temp*")))$
  (save-current-buffer (set-buffer (url-retrieve-synchronously (format (concat "https://raw.githubusercontent.com/" "raxod502/straight.el/install/%s/s$
  (let ((version nil) (straight-profiles (if (boundp 'straight-profiles) straight-profiles '((nil . "default.el")))) (straight-install-dir (or (and (b$
  (progn (message "Bootstrapping straight.el...") (let ((min-version "25.1")) (if (version< emacs-version min-version) (progn (error (concat "straight$
  eval((progn (message "Bootstrapping straight.el...") (let ((min-version "25.1")) (if (version< emacs-version min-version) (progn (error (concat "str$
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp()
  (save-current-buffer (set-buffer (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straigh..." 'silent 'inhibit-cookies)) (got$
  (if (file-exists-p bootstrap-file) nil (save-current-buffer (set-buffer (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/stra$
  (let ((bootstrap-file (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory)) (bootstrap-version 5)) (if (file-exists-p b$
  eval-buffer(#<buffer  *load*> nil "/home/rx/.emacs.d/init.el" nil t)  ; Reading at buffer position 634                                               
  load-with-code-conversion("/home/rx/.emacs.d/init.el" "/home/rx/.emacs.d/init.el" t t)
  load("/home/rx/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x4f2af9>) #f(compiled-function () #<bytecode 0x4f2b05>) t)
  command-line()
  normal-top-level()

```
Any ideas? thanks in advance
-A

**Comment by vyp** [comment]
What is the output of `(executable-find "git")`? And did you check if the `*straight-process*` buffer showed any errors?

**Comment by reuleaux** [comment]
Thanks for getting back to me about this issue.

I have meanwhile managed to get emacs running (with my personal
configuration of packages) without straight.el:

There are quite a number of packages available for emacs already in guix
(all named emacs-*, for example emacs-leaf for leaf.el), and the few
remaining ones that were missing for me (leaf-keywords, thing-commands,
with its dependency: hide-comnt, and auto-compile) I was able to create
guix packages for myself, and install them from my personal channel
(cf. http://git.a-rx.info/channel/, git://git.a-rx.info/channel/ -
i.e. I have created packages: emacs-auto-compile, emacs-hide-comnt,
emacs-thing-cmds, and emacs-leaf-keywords)

Thus I have no need for straight.el on guix any more, but I will have a
second look (as time permits), and see what went wrong at the time with
my installation of straight.el on guix. - It may well be, that I did not
have git installed properly at the time (I am sure, I have it installed
now). - I will get back to with more information about this.

Thanks again.
  -A

**Comment by progfolio** [comment]
> Thus I have no need for straight.el on guix any more, but I will have a
second look (as time permits), and see what went wrong at the time with
my installation of straight.el on guix

Glad you got your system working.
I'm going to close this issue for now, but feel free to add more info if/when time permits.

Thanks.
