### ISSUE TITLE
[Question] How to write recipe format to get the package specified Git’s Tag name

### ISSUE THREAD

**Issue by yamatakau08** [raxod502/straight.el#839]
I’d like to get the specified package, Git’s Tag name via straight.
I looked through gitbakend keyword in READM.md. 
But I can’t find that.
Could you teach me how to write recipe format if there was one?

Actually, I already succeeded in Lockfile management of straight.
But I’d like to archive that with recipe format, if there is.

**Comment by progfolio** [comment]
See previous discussion at #246

**Comment by yamatakau08** [comment]
Dear progfolio,

Thank you for introducing #246
I read that thread seems to be still in discussion.
I can’t understand that fully.

So,
I executed the following code to get e.g consult tag 0.9.

```
(use-package consult
   :straight (:branch “0.9”) 
   ;; …)
```
or 
```
(use-package consult
    :straight (:commit “ee58941308d83a717728f056ea753e80f68cfbc0")
    ;;...)
```

Both could download the consult tag 0.9.
Which one is the preferred on straight manner?
or have more suitable expression?

And I have the following warning.
`
Warning (straight): Could not check out branch "0.9" of repository "consult" Disable showing Disable logging
`
Could you teach me how to suppress it?

**Comment by yamatakau08** [comment]
> And I have the following warning.
> `Warning (straight): Could not check out branch "0.9" of repository "consult" Disable showing Disable logging`
> Could you teach me how to suppress it?

I could suppress it.

```
(use-package warnings
  :custom
  (warning-suppress-types '((straight))) ; https://github.com/raxod502/straight.el/issues/839#issuecomment-907731529
  )
```

**Comment by progfolio** [comment]
`:branch` isn't really intended to work with tags from what I read. So I would double check to make sure your repository is actually checked out to the revision you expect it to be. There may be other corner cases where using a tag here will fail.
Currently there is no `:commit` recipe keyword implemented.
There are several ideas pitched in #246, but, I believe the last idea discussed (a `:ref` recipe keyword) would be what we would want to implement. Pull requests welcome.

**Comment by yamatakau08** [comment]
progfolio, Thank you for additional comment.

At the moment, I understand that I should use version lock file ~/.emacs.d/straight/versions/default.el which straight provided as a right way.

>  (a :ref recipe keyword) would be what we would want to implement.

OK. I understand. After supported `:ref`, I’ll use that keyword.
I close this issue.
