### ISSUE TITLE
Straight doesn't load Org Properly

### ISSUE THREAD

**Issue by gluax** [raxod502/straight.el#840]
## What's wrong

Using straight to load org does not define the org function (required by org-roam).
Similarly when setting `straight-use-package-by-default` to `t` `:straight nil` is ignored.
I also tried loading use-package org before setting use package to use straight and it still uses the straight build :c.

## Directions to reproduce

```lisp
(setq package-enable-at-startup nil)

(setq straight-repository-branch "develop")
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

(use-package org
  :straight nil
  :hook (org-mode 'org-indent-mode)
  :bind (
	 ("C-c a" . 'org-agenda)
	 ("C-c l" . 'org-store-link)
	 ("C-c k" . 'org-capture)
         )
  :custom
  (org-directory "~/org")
  (org-export-html-postamble nil)
  (org-startup-indented t)
  (org-startup-folded (quote overview))
  (org-agenda-files '("~/org/agenda/")))

(use-package straight
   :custom (straight-use-package-by-default t))

(use-package org-roam
  :diminish org-roam-mode
  :config
  (org-roam-db-autosync-mode)
  :init (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory "~/org-roam")
  :bind (("C-c n l" . org-roam-buffer-toggle)
               ("C-c n f" . org-roam-node-find)
               ("C-c n g" . org-roam-graph))
              (("C-c n i" . org-roam-node-insert))
              (("C-c n c" . org-roam-capture)))
```

Debug info is long but it originates from
```lisp
Debugger entered--Lisp error: (error "Autoloading file c:/Users/jonat/AppData/Roaming/.emacs.d/straight/build/org/org.elc failed to define function org")
```

### Version information

    Emacs: GNU Emacs 27.2 (build 1, x86_64-w64-mingw32)
    of 2021-03-26
    Framework: N/A
    Org: Org mode version 9.4.6 (9.4.6-gb4e575 @ c:/Users/jonat/AppData/Roaming/.emacs.d/straight/build/org/)
    Org-roam: v2.1.0-15-ga8a36a4
    OS: Windows 10 Pro 19042.1165

**Comment by gluax** [comment]
I realized some update must have happened since I needed to update the `:hook` line in the `use-package org`, and the error goes away. Still interesting that the setting `:straight nil` is ignored, though.

**Comment by progfolio** [comment]
Are you able to reproduce this via `straight-bug-report `?

**Comment by gluax** [comment]
> 
> 
> Are you able to reproduce this via `straight-bug-report `?

Currently not facing the original bug anymore since I changed the config. Setting `:straight nil` doesn't generate an error, just still loads the package with straight when I don't want it to.

**Comment by progfolio** [comment]
Sorry, I should have been more specific.
I meant is `:straight nil` ignored if you use straight-bug-report`?

**Comment by gluax** [comment]
> 
> 
> Sorry, I should have been more specific.
> I meant is `:straight nil` ignored if you use `straight-bug-report`?

It is still ignored.

**Comment by progfolio** [comment]
Can you please share the report here?
You can copy and paste the entire \* straight-bug-report *

**Comment by progfolio** [comment]
Paste the following test case into your \*scratch\* buffer.
Then you should be able to move point to the end of the buffer and `M-x eval-last-sexp`.
This should print a message to the echo area similar to:

> Testing straight.el in directory: /tmp/nil-ignored.straight

A child Emacs process will install straight.el in a clean evironment and run the test.
After it finishes, a buffer named \*straight-bug-report-process\* should pop up in the Emacs session you evaluated the code in. You can copy the contents of that buffer into this issue. I've tested on my system and setting `:straight nil` seems to do the right thing. The built in version of Org mode is located:


<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "nil-ignored.straight"
  :post-bootstrap 
  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
  (use-package org :straight nil)
  (message "%S"
           (locate-library "org")))
```
</details>

- Test run at: `2021-09-06 11:29:54`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 45eb611 2021-08-13`
- emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-09-04`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 45eb611 2021-08-13
Cloning use-package...
Cloning use-package...done
Building use-package...
Building use-package → Building bind-key...
Building use-package → Building bind-key...done
Building use-package...
Building use-package...done

"/usr/share/emacs/28.0.50/lisp/org/org.elc"
Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 93cf8649 2021-09-05
"gnu-elpa-mirror"         n/a                  master a4cb567 2021-08-29
"el-get"                  melpa                master b5a5a405 2021-09-01
"emacsmirror-mirror"      n/a                  master fc970dc 2021-08-27
"straight"                n/a                  develop 45eb611 2021-08-13
"use-package"             melpa                master a7422fb 2021-02-10
"bind-key"                melpa                master a7422fb 2021-02-10


```
</details>

**Comment by gluax** [comment]
@progfolio ah thanks for telling me how to run that! That helped me track down the issue, and it wasn't a straight issue but rather a configuration issue.
