### ISSUE TITLE
Force-pushing to this repository's master branch breaks freezing straight.el

### ISSUE THREAD

**Issue by CyberShadow** [raxod502/straight.el#841]
Hi,

I noticed that commit 5541697ceee7e7ba937eddebba44f1e8e8af6a4f, which was what `master` was pointing at at some point, is now gone.

Incidentally, this was the commit at which I froze my straight.el version. When I attempted to thaw it on another machine, that failed, as the commit is no longer reachable from any refs fetched from this repository.

I believe that the only circumstance that could result in this situation is that the `master` branch had been force-pushed to.

I don't know whether this was a deliberate action or not; if it was, then I suppose you may disregard this issue.

Thanks!

**Comment by progfolio** [comment]
Apologies. That was the result of a merge issue. Should not happen again.
