### ISSUE TITLE
Can I specify the repository cloning format for URLs?

### ISSUE THREAD

**Issue by jdhao** [raxod502/straight.el#842]
Hi, I am a Nvim user and a new Emacs user. I have been using packer.nvim to manage my plugins. In packer.nvim, we have a setting to change the git url format used, see [this PR](https://github.com/wbthomason/packer.nvim/pull/434). 

I wonder if I can do the same with straight.el?

**Comment by progfolio** [comment]
Could you provide an example use case?

**Comment by jdhao** [comment]
I am currently in China, where directly cloning from GitHub repository is really slow without any VPN or proxy. So I usually use [fastgit](https://fastgit.org/) as a mirror site (what GNU mirror does to GNU main repository) so that I can clone repositories faster.

For example, in [here](https://github.com/jdhao/nvim-config/blob/master/lua/plugins.lua#L8), I specify the clone URL format to `"https://hub.fastgit.org/%s"`. Then when I install a package with `use 'foo/bar'`, the clone address would be `https://hub.fastgit.org/foo/bar` instead of the default `https://github.com/foo/bar`.

**Comment by jdhao** [comment]
If that is difficult to do. Is there a way just like what we can change the default repositories for the Emacs builtin package.el with the following snippet?

```
;; change to use tsinghua mirror instead of offical ELPA and MELPA
(setq package-archives '(("gnu"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
                         ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")))
```

**Comment by progfolio** [comment]
If you want to use fastgit as a proxy for github, you'll likely want to use git's URL rewriting tools.
Fastgit has a guide on how to do this:
https://doc.fastgit.org/en-gb/guide.html

However, we had a user who says they ran into issues when attempting something similar:
https://github.com/raxod502/straight.el/issues/750

You can give it a shot and see if this works for you. If it doesn't, please add more info to the linked issue.

**Comment by jdhao** [comment]
@progfolio  Thanks for the guide. The bootstrap script does not work for me (I suppose it is because the raw.githubusercontent accessing issue). I have to clone the repo manually.

Here is what works for me:

1. Go to `~/.emacs.d`, the directory varies based on your system (check [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Windows-HOME.html) for the actual path). 
2. clone the straight.el repo:

```bash
git clone https://github.com/raxod502/straight.el.git  straight/repos/straight.el
```
3. Change the git default url using the following command as per [guide here](https://doc.fastgit.org/en-gb/guide.html).
```bash
git config --global url."https://hub.fastgit.org/".insteadOf "https://github.com/"
git config protocol.https.allow always
```
4. Remove the straight.el bootstrap snippet from `init.el`.

Restart Emacs and just wait. All my packages are installed and build successfully.

**Comment by jdhao** [comment]
It seems that the function `url-retrieve-synchronously` just does not work somehow. I testes a URL which I can access without issue using this function, Emacs still hangs without a response.  For example, the following snippet hangs

```lisp
(with-current-buffer
    (url-retrieve-synchronously "https://baidu.com" 'silent 'inhibit-cookies)
  (goto-char (point-max)))
```

**Comment by progfolio** [comment]
You could experiment by changing the expression slightly:

```emacs-lisp
(with-current-buffer
    (url-retrieve-synchronously "https://baidu.com" nil 'inhibit-cookies)
  (buffer-string))
```

I removed the "silent" option and the buffer string should be printed after the url is retrieved. Perhaps the request is timing out or there is another network issue?

**Comment by progfolio** [comment]
@jdhao: Any luck with the above?

**Comment by jdhao** [comment]
> You could experiment by changing the expression slightly:
> 
> ```emacs-lisp
> (with-current-buffer
>     (url-retrieve-synchronously "https://baidu.com" nil 'inhibit-cookies)
>   (buffer-string))
> ```
> 
> I removed the "silent" option and the buffer string should be printed after the url is retrieved. Perhaps the request is timing out or there is another networking issue?

@progfolio  This still hangs. It is connecting to baidu.com:443 and this goes forever. I suspect this is due to the lack of proxy settings. Since we need to use proxy to connect to internet. FYI, `curl https://baidu.com` also fails on the command line.

**Comment by progfolio** [comment]
I see. I'm going to close this issue as I don't think there's more we can do here on straight's end. If you come across any more info that you think needs to be addressed, comment here and we can reopen the issue. Thanks.

**Comment by raxod502** [comment]
Hmm, it doesn't seem unreasonable to me to say we could add support for a user option that could be set to a proxy that `straight.el` would use for initiating network connections in the bootstrap snippet (if set). Thoughts @progfolio? Seems like it would be a straightforward and backwards-compatible way to address this use case, which doesn't have a great workaround otherwise.
