### ISSUE TITLE
Auctex installs on Linux, but not on Windows

### ISSUE THREAD

**Issue by jthaman** [raxod502/straight.el#843]
Using the same configuration on both Linux and Windows, and setting `(setq straight-recipes-gnu-elpa-use-mirror t)`, the configuration 

```
(straight-use-package 'auctex)
```

has no problems on my Linux computer: the package builds without error. On my windows machine, the same configuration results in a failed build and produces this error

```
autoload-generate-file-autoloads: tex-jp.el:0:0: error: error: (Local variables entry is missing the suffix)
```

I've tried a few different straight incantations, but the same error keeps popping up on Windows.

**Comment by progfolio** [comment]
Could you paste the contents of the \*straight-process-buffer* for the failed build?

**Comment by jthaman** [comment]
Hmm, that's not in my buffer list.

**Comment by progfolio** [comment]
possibly related:
https://github.com/hlissner/doom-emacs/issues/2637

**Comment by jthaman** [comment]
Yes, very likely, I noticed that the offending file, tex-jp.el, is using an odd coding system.

**Comment by jthaman** [comment]
If I manually change the coding in tex-jp.el to utf-8, Auctex installs without error on Windows using straight.

**Comment by progfolio** [comment]
Thanks for the info.
I don't think there's anything we can do on straight's side to fix this.
You may be able to automate a workaround via the `:pre-build` recipe keyword, but I would recommend asking/reporting this upstream.
