### ISSUE TITLE
If the package installation fails, first try `straight-pull-recipe-repositories`, and then automatically retry the installation.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#846]
Today, when  I started Emacs, I encountered the following error:

![image](https://user-images.githubusercontent.com/11155854/134348460-915c50db-49ba-48ce-a7a1-df8a66512ba3.png)

After I issue the command `M-x straight-pull-recipe-repositories RET`, the package can be installed successfully. So, I want to have the following logic: if the package installation fails, first try `straight-pull-recipe-repositories`, and then automatically retry the installation. Does straight have implemented the corresponding function/command/macro?

Regards,
HZ

**Comment by progfolio** [comment]
There are other problems that could cause a recipe lookup to fail (network connectivity, the package doesn't exist in any recipe-repository, etc). If we were to design some sort of opt in behavior, then we need to consider all those cases and what the appropriate behavior is without misleading the user.

**Comment by hongyi-zhao** [comment]
Got it, but  how to use a custom function to achieve this aim, if I want to have this feature in my `~/.emacs.d/init.el`?

**Comment by progfolio** [comment]
You could write a command which wraps `straight-use-package` in a condition-case, catches the error and does whatever you want to do instead. That's more of an elisp question than a straight.el question, though.
