### ISSUE TITLE
`Undo-tree` package in `emacs-straight` repo is lagged after the latest version found on github.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#850]
I noticed that the [undo-tree](https://github.com/emacs-straight/undo-tree) package in `emacs-straight` repo is lagged after [the latest version](https://github.com/tarsiiformes/undo-tree) found on GitHub. Why not use this repo as its upstream? 

Regards,
HZ

**Comment by progfolio** [comment]
The mirrors are automated. We do not hand curate their recipes. You can specify a recipe which points to the version of undo-tree you'd like to use.
