### ISSUE TITLE
straight-version fails on Windows?

### ISSUE THREAD

**Issue by progfolio** [raxod502/straight.el#861]
```
$ cd "c:/Users/user/AppData/Local/Temp/straight.el-test-iZb2iS/straight/build/straight/"
$ "git" "show" "-s" ^"--format=^%d ^%h ^%cs^"

fatal: not a git repository (or any of the parent directories): .git

[Return code: 128]
```

Explains why we're not getting useful output from `straight-version`. I'm guessing this has to do with the lack of symlinks on Windows.

_Originally posted by @progfolio in https://github.com/raxod502/straight.el/issues/860#issuecomment-940202903_

**Comment by raxod502** [comment]
You can probably reproduce this without running Windows, by setting `straight-use-symlinks` to non-nil at startup and triggering a rebuild of the relevant package(s). That will enable the usage of the fake symlink emulation which may e.g. be fooling an invocation of `file-truename`.

**Comment by raxod502** [comment]
Oh, yeah, just looking at this code https://github.com/raxod502/straight.el/blob/73cff920c8eb63d180dafdcbe68414b2f70e60e1/straight.el#L6731 that must be what's happening. You can use `straight-chase-emulated-symlink` to resolve those.

**Comment by progfolio** [comment]
> You can use straight-chase-emulated-symlink to resolve those.

Thanks for the pointer.
