### ISSUE TITLE
Dependencies are not installed for clj-refactor

### ISSUE THREAD

**Issue by andreyorst** [raxod502/straight.el#868]
Here's a minimal `init.el`:

```emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
	(url-retrieve-synchronously
	 "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	 'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq package-enable-at-startup nil)

(straight-use-package 'clj-refactor)

(require 'clj-refactor)
```

When running `emacs -Q -l init.el` I get the following messages:

```
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...done
Cloning clj-refactor.el...done
Building clj-refactor...done
eval-buffer: Cannot open load file: No such file or directory, yasnippet
```

This pulls `straight.el` checked out to this commit af5437f2afd00936c883124d6d3098721c2d306c, then mirrors, and finally just clones `clj-refactor` without dependencies. All dependencies are specified in `clj-refactor.el` package:

``` emacs-lisp
;; Package-Requires: ((emacs "26.1") (seq "2.19") (yasnippet "0.6.1") (paredit "24") (multiple-cursors "1.2.2") (clojure-mode "5.9") (cider "1.0") (parseedn "1.0.46) (inflections "2.3") (hydra "0.13.2"))
```

I haven't found this package in https://github.com/emacs-straight, or on NonGNU Elpa, so I assume the recipe comes from Melpa? And AFAIK MELPA lists dependencies correctly: https://melpa.org/#/clj-refactor.

**Comment by progfolio** [comment]
Looks like the package metadata is corrupt.
I've submitted a pull upstream:

https://github.com/clojure-emacs/clj-refactor.el/compare/master...progfolio:patch-1

FYI, the package throws 552 other issues via `package-lint`, so it may be worth it talking to the package authors about those if you plan on relying on this package.
