### ISSUE TITLE
QE-modes installatio with straight.el.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#871]
The [QE-modes](https://gitlab.com/QEF/q-e/-/tree/develop/GUI/QE-modes) package is an open-source collection of Emacs major-modes for making the editing of Quantum ESPRESSO input files somewhat easier and more comfortable with Emacs editor.

I would like to know how to use `straight.el`  to install and manage it.

Regards,
HZ

**Comment by hongyi-zhao** [comment]
> ```emacs-lisp
> (straight-use-package
>  '(qe-modes
>    :host gitlab
>    :repo "QEF/q-e"
>    :files ("GUI/QE-modes/qe-modes/*.el")
>    :includes
>    (cp-mode ld1-mode neb-mode ph-mode pp-mode pw-mode pwtk-mode qe-funcs qe-mode qe-modes)))
> ```

I tried the following in my init file:

```emacs-lisp
(use-package qe-modes
  :straight (:host gitlab
		   :repo "QEF/q-e"
		   :files ("GUI/QE-modes/qe-modes/*.el")
		   :includes
		   (cp-mode ld1-mode neb-mode ph-mode pp-mode pw-mode pwtk-mode qe-funcs qe-mode qe-modes)))
```
The above recipe will compile the el files automatically, but the whole repository, which is a huge project, must be cloned first. I wonder if I can just clone the files `straight` needs?

**Comment by progfolio** [comment]
> The above recipe will compile the el files automatically, but the whole repository, which is a huge project, must be cloned first. I wonder if I can just clone the files straight needs?

I cloned the repo and it looks like it's just under 1GB.
A shallow clone was roughly 1/10th of that size.
Unless you need the full repository history and tags, you can set the recipe `:depth` keyword for this repository.

See: https://github.com/raxod502/straight.el/tree/develop#git-backend

**Comment by hongyi-zhao** [comment]
I tried with the following recipe:

```emacs-lisp
(use-package qe-modes
  :straight (:host gitlab
		   :repo "QEF/q-e"
		   :files ("GUI/QE-modes/qe-modes/*.el")
		   :depth 1
		   :includes
		   (cp-mode ld1-mode neb-mode ph-mode pp-mode pw-mode pwtk-mode qe-funcs qe-mode qe-modes)))
```
But the size still exceeds 1GB:
```
$ git log 
commit e94356770b00ef39ca52436b08c144d7cbae30d5 (grafted, HEAD -> develop, origin/develop, origin/HEAD)
Author: giannozz <paolo.giannozzi@uniud.it>
Date:   Sun Dec 19 07:52:36 2021 +0000

    Merge branch 'fix_ipi' into 'develop'
    
    Fix the i-PI communication protocol in run_driver.f90
    
    See merge request QEF/q-e!1677

$ du -d1 -h ~/.emacs.d/straight/repos/q-e/ | tail -1
1.4G	/home/werner/.emacs.d/straight/repos/q-e/
```

**Comment by progfolio** [comment]
Apologies. I must've misread my test output. Unfortunately, we don't currently support sparse checkouts, as there is limited forge/git support for it at the moment. 

See: https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository

Not much we can do about it if the elisp and the main project are hosted in the same repository.

**Comment by hongyi-zhao** [comment]
> Unfortunately, we don't currently support sparse checkouts, as there is limited forge/git support for it at the moment.
> 
> See: https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository

I have heard of this feature of git and, IIRC, have also used it before.

> Not much we can do about it if the elisp and the main project are hosted in the same repository.

If I understand correctly, currently, the [Makefile](https://gitlab.com/QEF/q-e/-/blob/develop/GUI/QE-modes/Makefile) of this package relies on the main project to build this package.

**Comment by hongyi-zhao** [comment]
Is it possible or there a plan for straight to support such things like git sparse checkout?

**Comment by progfolio** [comment]
> Is it possible or there a plan for straight to support such things like git sparse checkout?

> Unfortunately, we don't currently support sparse checkouts, as there is limited forge/git support for it at the moment.

It's a relatively new feature of git itself and from what I understand has limited support on github. So not any time soon.

**Comment by hongyi-zhao** [comment]
Another question following-up your above point of view: Is it possible to use the powerful features of elisp, such as the advice function, to implement git sparse checkout in `straight-use-package`?

**Comment by progfolio** [comment]
Try it out and let me know.

**Comment by hongyi-zhao** [comment]
But I've no idea what/where/how should I advise `straight-use-package`, shame on me for my low understanding on straight and elisp.
