### ISSUE TITLE
Emacs hangs on Windows due to straight-ಠ_ಠ

### ISSUE THREAD

**Issue by dinkonin** [raxod502/straight.el#877]
So I struggle with a funny bug on Emacs 27.2 in Windows 10. 
When I type "straight" in the minibuffer and trigger completion emacs hangs for a couple of seconds. After an embarrassing amount of time debugging (tested vertico , selectrum , orderless) I loaded up emacs -Q with only straight loaded and was able to narrow the hang to the funny named straight-ಠ_ಠ function.

I was able to fix the problem this in my init.el with:
```elisp
(fmakunbound 'straight-ಠ_ಠ-mode)
(makunbound 'straight-ಠ_ಠ)
```
BUT now emacs hangs for 5 when I open my init.el for the first time. Maybe this alias should be removed or at least not be defined in Windows ?

**Comment by dinkonin** [comment]
After further testing I can confirm that the issue still occurs on Emacs 29 (build on windows with MSYS2).

Additionally to unbinding the variable and the function I've fixed my init.el issue by adding:
```elisp
;;Local Variables:
;;eval: (set-buffer-multibyte nil)
;;End:
``` 
in the end of my init.el file.

**Comment by progfolio** [comment]
I'm unable to reproduce this, but I'm on Linux.

>  I loaded up emacs -Q with only straight loaded and was able to narrow the hang to the funny named straight-ಠ_ಠ function

If you eliminate straight.el from the picture and define a command with the same unicode character (https://www.fileformat.info/info/unicode/char/0ca5/index.htm) or other unicode characters, does the issue persist?

This seems like a configuration bug or an upstream bug with Emacs itself to me. 

Using unicode characters in symbol names seems like fair game if I'm reading this correctly:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Symbol-Type.html

> A symbol name can contain any characters whatever.

Try reproducing the problem without straight.el loaded and let me know if the issue persists.

**Comment by dinkonin** [comment]
> I'm unable to reproduce this, but I'm on Linux.

Indeed this issue occurs only on windows , I've tested on arch and fedora. 

I've eliminated straight and defined a function like this:
```elisp
(defun testಠ-ಠ ()
(interactive)
nil)
```
and the yes, the issue persists. 

>This seems like a configuration bug or an upstream bug with Emacs itself to me.

Highly doubt it's a config issue since I'm testing with 3 different versions of emacs (26, 27.2 and 29 build from master) all started with `emacs -Q` on two Windows versions (home and enterprise)

>That's not a solution. It addresses the symptom for one package, but you would have the same issue with any other program which defined a symbol in such a way. Better to figure out and address the root cause.

Tested with vscode , Visual studio , atom  no unicode issues whatsoever.

AFAIK this seems as an upstream issue, but I still humbly propose removing this alias, as it is obviously not essential and even if Unicode functions are OK in elisp as explained by your link when I look at the 100+ packages in my init.el only straight is using one.

**Comment by progfolio** [comment]
> Tested with vscode , Visual studio , atom no unicode issues whatsoever.

I should have been clearer. I meant any other elisp program defining an elisp symbol with unicode characters in it.

> Highly doubt it's a config issue...AFAIK this seems as an upstream issue,

Please report it upstream on the Emacs bug mailing list.

> I still humbly propose removing this alias, as it is obviously not essential and even if Unicode functions are OK in elisp as explained by your link when I look at the 100+ packages in my init.el only straight is using one.

I agree the alias could stand to be removed, but again, that doesn't fix the root of the problem.
Once you've reported it upstream, I will follow that thread and see how it shakes out.
If it is indeed the case that we should not be using any unicode in our symobls, I will remove the alias.

**Comment by dinkonin** [comment]
Thanks for the quick response.
>Please report it upstream on the Emacs bug mailing list.

Unfortunately due to previous unpleasant experience with bugs-gnu-emacs I'm not going to report this there. You can close this for now or leave it open in case anyone struggles with the same issue and is willing to report upstream.

Sorry for wasting your time.

**Comment by progfolio** [comment]
I have reported it on your behalf.

https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-11/msg00203.html

Thanks.

**Comment by Eli-Zaretskii** [comment]
I cannot reproduce this on my Windows machine. However, you didn't say what does "trigger completion" mean, so maybe I didn't use the right recipe.  A full detailed recipe starting from `emacs -Q` will help.

What font do you have that displays those characters?  If you don't have the Symbola font installed, can you try installing it and re-testing?

If none of that helps, profile (with `M-x profiler-start` and `M-x profiler-report`) the command that hangs in this way and post the fully expanded profile.

**Comment by dinkonin** [comment]
Hello this is how to reproduce the issue:
1.Create a file test.el containing this:
```elisp
(defun testಠ-ಠ ()
(interactive)
nil)
```
2. Load the file like this `emacs -Q -l test.el`
3. Press M-x and type test then press TAB to trigger mini-buffer completion
4. emacs freezes for 5 secs...

Tried installing symbola from here https://github.com/gearit/ttf-symbola but that made no difference.
On my Windows 10 Home edition the unicode symbols do not appear and describe-char display: no font available
on my Windows 10 Enterprise  at work the symbols apper and the Nirmala is used, bud the hangs occurs on both.
I also tried loading It with `(setq inhibit-compacting-font-caches t)` , that also did not make an observable difference.

Here is the profiler-report
```
- command-execute                                                1613  99%
 - call-interactively                                            1613  99%
  - byte-code                                                    1605  99%
   - read-extended-command                                       1605  99%
    - completing-read                                            1605  99%
     - completing-read-default                                   1605  99%
      - read-from-minibuffer                                     1602  99%
       - command-execute                                         1598  99%
        - call-interactively                                     1598  99%
         - funcall-interactively                                 1598  99%
          - minibuffer-complete                                  1598  99%
           - completion-in-region                                1598  99%
            - completion--in-region                              1598  99%
             - #<compiled 0x5d30d6d6d9>                          1598  99%
              - apply                                            1598  99%
               - #<compiled 0x5d2fe07dc7>                        1598  99%
                - completion--in-region-1                        1598  99%
                 - completion--do-completion                     1598  99%
                  - minibuffer-completion-help                   1598  99%
                     fit-window-to-buffer                        1598  99%
       + redisplay_internal (C function)                            1   0%
  + funcall-interactively                                           8   0%
+ ...                                                               1   0%

```

**Comment by dinkonin** [comment]
Just figured something out !
```elisp
(set-fontset-font "fontset-default" 'unicode-bmp
                  "Nirmala UI")
```
This fixes the issue on both windows machines. But I still think that the user should not have to set it in their config.

**Comment by Eli-Zaretskii** [comment]
> But I still think that the user should not have to set it in their config.

If you have no fonts for the Kannada script, what you see is expected.  It is strange, though, that Emacs doesn't find a suitable font on your system, because it does find it on mine.

So bottom line, I see no problem with Emacs here.

**Comment by dinkonin** [comment]
I don't really agree with your assessment of this situation. First obliviously I have fonts supporting this script because as I mentioned above overriding "fontset-default" with the correct font fixes it.
As I also mentioned above I've tested on two different versions of windows on two separate machines with 3 different versions of emacs. I should add also Windows Server 2016 to this list as I tested it a few moments ago and experience the same behavior. 

Let me know if can I provide you additional information, I can even prepare a clean install of windows 10 in a VM and clean install of emacs and give you remote access to it.

**Comment by progfolio** [comment]
You mentioned that you're using MSYS2. Might this have something to do with it?
Possibly related?: https://github.com/msys2/MINGW-packages/issues/5762

**Comment by dinkonin** [comment]
>You mentioned that you're using MSYS2. Might this have something to do with it?

I don't think so, I've tested with emacs downloaded from the official ftp. Also tested with the one in the scoop package manager.

**Comment by Eli-Zaretskii** [comment]
> You mentioned that you're using MSYS2. Might this have something to do with it? Possibly related?: msys2/MINGW-packages#5762

No, Emacs on MS-Windows doesn't use Fontconfig to find fonts, it uses Win32 APIs.

**Comment by Eli-Zaretskii** [comment]
> I don't really agree with your assessment of this situation. First obliviously I have fonts supporting this script because as I mentioned above overriding "fontset-default" with the correct font fixes it. As I also mentioned above I've tested on two different versions of windows on two separate machines with 3 different versions of emacs. I should add also Windows Server 2016 to this list as I tested it a few moments ago and experience the same behavior.

I don't know why Emacs doesn't find that font on your system.  Does the font announce its support for Kannada via the Unicode Subrange Bits (USB)?  That's how Emacs identifies fonts which support the characters of a certain script.

In any case, I think the conclusion is that the problem is with Emacs not finding the font for those characters, not with the straight.el package or completion.

**Comment by Eli-Zaretskii** [comment]
FWIW: on my system, Emacs picks up the Tunga font for these characters.  According to this:

         https://github.com/MicrosoftDocs/typography-issues/issues/350

Tunga font was "moved to feature-on-demand packages", so perhaps you need to install it manually.  Worth trying, I think.

**Comment by dinkonin** [comment]
I think we-re going on the wrong direction with this, as I said before on two of my systems emacs find the font supporting these characters, but hanging the issue still persists. I've run ProcMon on one of them and repeated the step, here are the results:
[emacs-profile.zip](https://github.com/raxod502/straight.el/files/7488640/emacs-profile.zip)

As you can see there emacs spends 90+% of the time opening every single NLS for every code page supported by windows. This does not occur with any other program I've opened the same file in.

I completely agree that the issue is not with straight, my humble proposal to them was to remove/rename the offending function and alias because they serve no purpose and would be an easy fix to a deeper problem be it in emacs or windows.

In any case the my fix for the issue with straight works:
`(set-fontset-font "fontset-default" '#xca0 'nil)`, this brings the time to display the offending function from 2-5 secs to instantaneous on all machines.

**Comment by Eli-Zaretskii** [comment]
I cannot access that zip file, I guess Github doesn't like my browser (what else is new?).

What do you mean by "opens every single NLS"?

And I'm confused now: earlier you said forcing Emacs to use a specific font solves the issue, now you say it doesn't?  But saying that this character has no font does solve the issue?  How is this not a font-related problem?

**Comment by dinkonin** [comment]
Forcing emacs to use a specific font indeed solves the issue, forcing emacs to ignore the character also solves the issue. I'm sorry that English is not my first language and maybe I failed to relay some information.
It may be a font issue but it's an issue that occurs an default windows installation with the official emacs windows package.  The font I mantionoed above is provided by the os not additionally installed.

>What do you mean by "opens every single NLS"?

As you can see if you succeed in opening  .csv(link below) emacs spends most of the time (while it hangs) opening every single c_****.nls in windows\system32, which I guess(I'm not a programmer) is OK because they provide some sort regional and character-set conversion information, but takes too much of time in my opinion.

Does this work for you https://gofile.io/d/VOwmj5

**Comment by dinkonin** [comment]
Just saw your conversation in lists.gnu.org
>I think this bug can be closed now, since it turns out the "hang" is
due to Emacs looking for a suitable font for some special characters
(and not finding it, for some reason).

Just to be clear, emacs finds the font of most my machines, fails on to find it some but ALWAYS hangs.

I'm attaching a video of the delay (notice it after I type test) , lets hope your browser likes it.
FYI this is a machine with AMD Ryzen 7 5800 / 32 GB ram and an nvme drive.

https://user-images.githubusercontent.com/12976386/140580148-a116aeaa-1e3f-4b55-9627-53a0febf38fb.mp4

**Comment by dinkonin** [comment]
This is the same machine with the font forced thru set-fontset-fo

https://user-images.githubusercontent.com/12976386/140581952-83b56d52-9f2a-48ea-b537-09834c570f3b.mp4

nt

**Comment by Eli-Zaretskii** [comment]
> As you can see if you succeed in opening .csv(link below) emacs spends most of the time (while it hangs) opening every single c_****.nls in windows\system32

Ah, that.  That is normal, and AFAIK has no relation to the issue.

**Comment by Eli-Zaretskii** [comment]
> Just to be clear, emacs finds the font of most my machines, fails to find it on some but ALWAYS hangs.

I'm again confused.  In a previous comment you said:

> Forcing emacs to use a specific font indeed solves the issue, forcing emacs to ignore the character also solves the issue.

Doesn't "solves the issue" mean that there's no hang in those cases, i.e. when you force Emacs to use a specific font or tell it there's no font for that character?

Or do you mean Emacs hangs on those systems where it does find the font without your forcing it to use a particular font?  That could be because you have many fonts installed, and the search for a font takes a lot of time.  What does the following yield if you evaluate it in `emacs -Q`?

          (length (delete-dups
                   (x-list-fonts "-*-*-medium-r-normal-*-*-*-*-*-*-iso10646-1"
                                 'default)))

**Comment by dinkonin** [comment]
It always hangs if set-fontset-font is not used.

This is the output that I get when I evaluate your command `85 (#o125, #x55, ?U)`

I have not installed any additional fonts other than those installed by default on windows.

**Comment by dinkonin** [comment]
Actually no I had Libreoffice which I uninstalled now my fonts are 81, the hang still occurs. I Even tried uninstalling some of the microsoft fonts thru Font Settings but is get "FONT cannot be deleted because it is a protected system font."

As I MS side note its funny that I can delete explorer.exe or system32 but cannot delete a 50mb Myanmarian/Chinese font that I'm sure I'll never use..

**Comment by dinkonin** [comment]
So I did something stupid but apparently effective:

Booted a linux live cd and deleted all the Microsoft fonts for japanese/chineese/mongolian/etc scripts also deleted them from windows registry one by one and then rebuilt the windows fontcache.

Emacs reports 43 fonts and the hanging issue is gone. Also maybe I'm wrong but it starts a bit faster.

**Comment by dinkonin** [comment]
@Eli-Zaretskii This is an interesting discussion on what I suspect is the issue https://stackoverflow.com/questions/11253827/too-many-fonts-when-enumerating-with-enumfontfamiliesex-function 

I find the answer from James Johnston especially illuminating. 

Stumbled upon it when I saw that emacs uses EnumFontFamiliesEx on one on of my debug attempts.

**Comment by Eli-Zaretskii** [comment]
Thanks for the pointer to that discussion.

> I find the answer from James Johnston especially illuminating.

You mean, where he explains how to detect hidden fonts?  We cannot use that, because Emacs is multilingual: we don't limit users to the fonts that support only their locale.  Emacs users expect Emacs to show any character, provided that the system has a font for it.

As for the advice to use Unicode subranges: we already do.

**Comment by dinkonin** [comment]
Yes I figured as much. I'm content in knowing that my issue is a Windows one and that there are multiple ways to fix/mitigate it. It's amazing how much new stuff I learned from a unicode smiley face problem.

Thanks for your time and efforts.

**Comment by meziberry** [comment]
After the newest commit, the hangs problem has disappeared.  
I use emacs on Win11 + msys2.   This problem has annoyed me for a long time.   Thank you.

**Comment by meziberry** [comment]
Maybe the symbols `straight-ಠ_ಠ-mode` also need to be removed.  it still hangs emacs when completing the str****  input on the minibuffer.

**Comment by progfolio** [comment]
> Maybe the symbols straight-ಠ_ಠ-mode also need to be removed. it still hangs emacs when completing the str**** input on the minibuffer.

Removed on "develop".
