### ISSUE TITLE
Install fails on Raspbian Buster

### ISSUE THREAD

**Issue by robertpostill** [raxod502/straight.el#884]
HI, 

I have an emacs (self reports as 26.1) from Raspbian Buster and am having trouble bootstrapping straight.el.  

In my init file I have the usual setup:
```
;; setup straight.el
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
```
When the emacs version is started I get:
```
End of file during parsing: /home/rpostill/.emacs.d/init.el
```
If run C-x C-e at the end of the let I get:
```
elisp--preceding-sexp: End of file during parsing
``` 
I downloaded the file from the raw URL and placed it in ~/.emacs.d/straight/repos/straight.el/bootsrap.el which got me the bootstrapping straight.el message.  But then an error about :beta not being a recipe version:
```
error: Unknown recipe version: :beta
```
In reading the install.el/bootstrap.el file line 157 makes me nervous that I don't know enough to understand the issue.

So I was hoping to get some advice on how to debug the issue?

**Comment by progfolio** [comment]
> End of file during parsing: /home/rpostill/.emacs.d/init.el

This indicates that you have a syntax error in your init file.
More specifically, a missing paren. The parser hit the end of the file before seeing the end of the expression it was trying to parse.
If you open the file in Emacs and `M-x check-parens` it should move point to the start of last expression it was trying to read when it encountered the error.
Fixing this should be your first order of business and may allow straight to bootstrap.

> error: Unknown recipe version: :beta

This error indicates that the version of straight.el used during bootstrap was not retrieved successfully.
If the issue persists after fixing the above error, I would double check your network settings.
Are  you able to access `https://raw.githubusercontent.com/raxod502/straight.el/install/beta/straight.el` :

- through a browser on the machine?
- via curl or wget on the machine?
- by manually evaluating the following in a \*scratch* buffer:

```emacs-lisp
(display-buffer
 (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straight.el/install/beta/straight.el"))
```
Does that help?

**Comment by robertpostill** [comment]
Thanks for the reply @progfolio.

So I've commented out everything in my init.el except for:
```
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
```
Running `M-x check-parens` does not move the mark or provide any visible feedback.  So I think that's OK?

I can retrieve the file using a browser or curl without issue.  However, the `display-buffer` form returns an empty buffer.  Which seems bad.  So at this point I'm going to close the bug on the assumption it's an emacs issue instead.

**Comment by progfolio** [comment]
> Running M-x check-parens does not move the mark or provide any visible feedback. So I think that's OK?

The syntax of that code looks fine to me.

>  However, the display-buffer form returns an empty buffer. Which seems bad. So at this point I'm going to close the bug on the assumption it's an emacs issue instead.

Yes, that shouldn't be the case. I would look into seeing if something in your environment is preventing Emacs from being able to retrieve that URL properly. Good luck with it and do share if you find a solution.

**Comment by doolio** [comment]
I observe the same issue with Emacs 25.3 in a corporate environment (sadly can't upgrade to a newer version).

> Are you able to access https://raw.githubusercontent.com/raxod502/straight.el/install/beta/straight.el :
> through a browser on the machine?

Yes.

> via curl or wget on the machine?

Yes.

> by manually evaluating the following in a *scratch* buffer:

No, I get the message:

```
Contacting host: raw.githubusercontent.com:443
#<window 10 on  *http raw.githubusercontent.com:443*-195457>
```
