### ISSUE TITLE
straight-cache-autoloads brakes non-english docstrings

### ISSUE THREAD

**Issue by dinkonin** [raxod502/straight.el#888]
I have a package which declares a function with a non-english docstring
like this 
```
;;;###autoload
(defun my-test-fun ()
  "Тест кирилица")
```
When `straight-cache-autoloads` is enabled the string generated in `build-cache.el` looks like this
`����������������`
which prevents de docstring of being displayed properly. When `straight-cache-autoloads` is set to `nil` the problem does not occur.

Tested in Windows emacs 27 , and Linux Emacs 28.

**Comment by progfolio** [comment]
Are you able to reproduce the problem from `straight-bug-report`?

**Comment by dinkonin** [comment]
I'm sorry but I'm not exactly sure how to do that with `straight-bug-report`.  The text does display correctly in the source and  everywhere else. It even displays correctly when the package is loaded (either when I manually require it or execute the problematic function once).

**Comment by dinkonin** [comment]
So I additionally tested like this:  
loaded emacs with  `emacs -Q -l $HOME/.config/emacs/straight/repos/straight.el/bootstrap.el` 
then evaluated `(straight-use-package '(my-package :local-repo "~/.config/emacs/lisp/")`
and the resulting `build-cache.el` still contained the broken text (and it made straight rebuild all my packages on the next normal emacs launch).

**Comment by progfolio** [comment]
Yes, you'll want to test in a clean environment. That's why I suggest `straight-bug-report` (included with straight.el) or yodel (which is a cleaner version of the same idea I extracted from straight.el into its own library).

Does the following report accurately  describe the encoding issue you're seeing?:

[Yodel](https://github.com/progfolio/yodel) Report (2021-11-25 15:09:44):

```emacs-lisp
(yodel
  :formatter yodel-format-as-github-markdown
  :user-dir "autoload-test"
  :packages*
  (autoload-test
   :host github
   :repo "progfolio/autoload-test"
   :files
   ("autoload-test.el"))
  :post*
  (straight-rebuild-package "autoload-test")
  (message "%S"
           (describe-function #'autoload-test-english))
  (message "%S"
           (describe-function #'autoload-test-cyrillic)))
```

<details><summary>STDOUT:</summary>

```emacs-lisp
Loading /tmp/autoload-test/straight-bootstrap-snippet.el (source)...
Building autoload-test...
Building autoload-test...done

Type C-x 1 to delete the help window, C-M-v to scroll help.
#("autoload-test-english is an autoloaded Lisp function in
`autoload-test.el'.

[Arg list not available until function definition is loaded.]

English Test.

" 57 73 (button (t) category help-function-def-button help-args (autoload-test-english "/tmp/autoload-test/straight/build/autoload-test/autoload-test.el")))

#("autoload-test-cyrillic is an autoloaded Lisp function in
`autoload-test.el'.

[Arg list not available until function definition is loaded.]

\320\242\320\265\321\201\321\202 \320\272\320\270\321\200\320\270\320\273\320\270\321\206\320\260

" 58 74 (button (t) category help-function-def-button help-args (autoload-test-cyrillic "/tmp/autoload-test/straight/build/autoload-test/autoload-test.el")))
```

</details>
<details><summary>Environment</summary>

- **emacs version**: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-11-22
- **system type**: gnu/linux

<details open><summary>Packages</summary>

| Name                                                        | Branch | Commit                                                                                     | Date       | Source |
|-------------------------------------------------------------|--------|--------------------------------------------------------------------------------------------|------------|--------|
| [autoload-test](https://github.com/progfolio/autoload-test) | master | https://github.com/progfolio/autoload-test/commit/5db0c5129fc19ab2f613f7462dff5827243c0d7e | 2021-11-25 | nil    |

</details>

</details>

**Comment by dinkonin** [comment]
Yes `\320\242\320\265\321\201\321\202....` is exactly what I'm seeing instead of the cyrillic text.

**Comment by progfolio** [comment]
Can you evaluate the following in your \*scratch* buffer?
It will install straight.el and the test package in a clean, temporary, environment.
Once it is done running a buffer will pop up and you can copy the results here.


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :preserve t
  :user-dir "autoload-encoding.straight"
  :pre-bootstrap 
  (setq straight-repository-branch "develop")
  :post-bootstrap 
  (straight-use-package
   '(autoload-test :host github :repo "progfolio/autoload-test" :files
                   ("autoload-test.el")))
  (message "%S"
           (documentation #'autoload-test-english))
  (message "%S"
           (documentation #'autoload-test-cyrillic))
  (with-current-buffer
      (find-file-noselect
       (straight--build-file "autoload-test" "autoload-test-autoloads.el"))
    (message "%S:"
             (buffer-file-name))
    (message "%s"
             (buffer-string))))
```
</details>

- Test run at: `2021-11-25 15:39:50`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 92d4153 2021-11-23`
- emacs-version: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-11-22`

<details><summary>Output</summary>

```emacs-lisp
Test run with version: prerelease (HEAD -> develop, origin/develop) 92d4153 2021-11-23
"English Test."
"\320\242\320\265\321\201\321\202 \320\272\320\270\321\200\320\270\320\273\320\270\321\206\320\260"
"/tmp/autoload-encoding.straight/straight/build/autoload-test/autoload-test-autoloads.el":
;;; autoload-test-autoloads.el --- automatically extracted autoloads  -*- lexical-binding: t -*-
;;
;;; Code:


;;;### (autoloads nil "autoload-test" "autoload-test.el" (0 0 0 0))
;;; Generated autoloads from autoload-test.el

(autoload 'autoload-test-english "autoload-test" "\
English Test." nil nil)

(autoload 'autoload-test-cyrillic "autoload-test" "\
Тест кирилица" nil nil)

;;;***

(provide 'autoload-test-autoloads)
;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8
;; End:
;;; autoload-test-autoloads.el ends here

Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master a81f7dcb 2021-11-24
"gnu-elpa-mirror"         n/a                  master fea2b2e 2021-11-25
"el-get"                  melpa                master 960f3fb9 2021-10-31
"emacsmirror-mirror"      n/a                  master 82752f0 2021-11-23
"straight"                n/a                  develop 92d4153 2021-11-23
"autoload-test"           n/a                  master 5db0c51 2021-11-25


```
</details>

**Comment by dinkonin** [comment]
I'just get `error in process sentinel: Symbol’s value as variable is void: interactive [2 times]` Again tested in linux and windows.

**Comment by progfolio** [comment]
Is lexical binding enabled in the enviornment you evaled from?

**Comment by dinkonin** [comment]
I've put `(setq lexical-binding t)` before `(straight-bug-report...` same result

**Comment by dinkonin** [comment]
oops it worked with `;;; -*- lexical-binding: t; -*-`


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :preserve t
  :user-dir "autoload-encoding.straight"
  :pre-bootstrap 
  (setq straight-repository-branch "develop")
  :post-bootstrap 
  (straight-use-package
   '(autoload-test :host github :repo "progfolio/autoload-test" :files
		   ("autoload-test.el")))
  (message "%S"
	   (documentation #'autoload-test-english))
  (message "%S"
	   (documentation #'autoload-test-cyrillic))
  (with-current-buffer
      (find-file-noselect
       (straight--build-file "autoload-test" "autoload-test-autoloads.el"))
    (message "%S:"
	     (buffer-file-name))
    (message "%s"
	     (buffer-string))))
```
</details>

- Test run at: `2021-11-25 21:56:30`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 92d4153 2021-11-23`
- emacs-version: `GNU Emacs 28.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
 of 2021-11-23`

<details><summary>Output</summary>

```emacs-lisp
Test run with version: prerelease (HEAD -> develop, origin/develop) 92d4153 2021-11-23
"English Test."
"\320\242\320\265\321\201\321\202 \320\272\320\270\321\200\320\270\320\273\320\270\321\206\320\260"
"/tmp/autoload-encoding.straight/straight/build/autoload-test/autoload-test-autoloads.el":
;;; autoload-test-autoloads.el --- automatically extracted autoloads  -*- lexical-binding: t -*-
;;
;;; Code:


;;;### (autoloads nil "autoload-test" "autoload-test.el" (0 0 0 0))
;;; Generated autoloads from autoload-test.el

(autoload 'autoload-test-english "autoload-test" "\
English Test." nil nil)

(autoload 'autoload-test-cyrillic "autoload-test" "\
Тест кирилица" nil nil)

;;;***

(provide 'autoload-test-autoloads)
;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8
;; End:
;;; autoload-test-autoloads.el ends here

Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master a81f7dcb 2021-11-24
"gnu-elpa-mirror"         n/a                  master fea2b2e 2021-11-25
"el-get"                  melpa                master 960f3fb9 2021-10-31
"emacsmirror-mirror"      n/a                  master 82752f0 2021-11-23
"straight"                n/a                  develop 92d4153 2021-11-23
"autoload-test"           n/a                  master 5db0c51 2021-11-25


```
</details>

**Comment by progfolio** [comment]
> oops it worked with ;;; -*- lexical-binding: t; -*-

Yes, the variable needs to be set prior to the file being loaded.
It's the default now in the scratch buffer, that was only added recently.

It looks like your test provided the same results, so we have the same encoding issue.
I'm not sure if this is a straight.el problem or an Emacs problem yet.
The next step is to see if the problem can be reproduced without straight.el.
I will look into that soon (headed out for family gathering, so probably not today).
If you want to investigate this on your own, I would try to generate the autoloads for that file without straight.el and see if the issue persists.

**Comment by dinkonin** [comment]
Thank you very much and have fun with the family. 
I can confirm  that the issue does not happen with vanilla package.el and the package loaded like this: 
```
(setq package-quickstart t)
.....
(use-package autoload-test
  :load-path "~/test")
```
After a `package-refresh-contents` the resulting `package-quickstart.el` contains the proper string.

**Comment by progfolio** [comment]
Appreciate your patience on this one. I had a chance to look into it. #900 has been pushed to the "develop" branch and should fix the problem. Testing is appreciated. Thanks.

**Comment by dinkonin** [comment]
I confirm that the problem is indeed fixed. Thank you.
