### ISSUE TITLE
How to overwrite default recipe

### ISSUE THREAD

**Issue by stefanhusmann** [raxod502/straight.el#889]
I was not able to make straight.el look for the souces for emacs-jabber under  https://tildegit.org/wgreenhouse/emacs-jabber.git instead of the github repo.

```
Warning (straight): Two different recipes given for "jabber" (:repo cannot be both "https://tildegit.org/wgreenhouse/emacs-jabber.git" and "legoscia/emacs-jabber")
```
I tired this in my init file
``` elisp
(straight-use-package
 '(jabber :type git :host nil :repo "https://tildegit.org/wgreenhouse/emacs-jabber.git" local: ~/sources/emacs-jabber))
```
Help would be appreciated!

**Comment by progfolio** [comment]
Try `M-x straight-normalize-package jabber` and then restarting Emacs.

**Comment by stefanhusmann** [comment]
Thanks. I did so, and then I got an interactive dialog, where I could choose how to proceed. I typed "r" and now the repo configureation has a newly created [origin1] entry. With this it seems to work.
