### ISSUE TITLE
Is there a way to get something like a update history of each repository?

### ISSUE THREAD

**Issue by nowislewis** [raxod502/straight.el#890]
Hello, I want to know if there is a way to see the git commit history of each repository during "straight-pull-all", as shown by doom emacs using "doom upgrade". Then we can quickly understand what is updated in each package.

Thanks for this great and beautifule work!

**Comment by progfolio** [comment]
There is no direct command  that shows everything at the moment. However you could run `straight-fetch-all` and then use a combination of `find-library` and `magit-status`.

**Comment by nowislewis** [comment]
I'm very sorry for the late reply, things got stuck recently. The following is the updated content you can see with "doom upgrade" in cli:
![image](https://user-images.githubusercontent.com/41566630/145344418-d3d79a48-8459-4085-87ec-f2a7db7dcdfe.png)
I will try to explain this example：
1. I have a total of 212 packages. The updated packages shown in the figure are 35, 73, 74, etc. 
2. When updating, the commits compared to local will  be printed out. So you can see 12 commits or 1 commit because different packages update different content.

The real meaning of these contents is to let users understand what is updated or what bugs are fixed in these packages, and to avoid various problems caused by black box upgrades. If users find that the configuration crashes, they can use the advantages of straight to reverse commit in time

**Comment by nowislewis** [comment]
This is a very useful feature. I don't need to go to the package repo to check the updates one by one. After each update, I can easily list the new features of the all packages without checking their repos or websites. Doom has done a lot of productive work, but I think it mainly takes native advantage of straight.

**Comment by progfolio** [comment]
This isn't quite ready for integration into straight, but I sketched out a rough command which can be used to generate a report of all fetched commits:

```emacs-lisp
(defun straight-fetch-report (&rest _)
  "Show fetched commit summary."
  (interactive)
  (with-current-buffer (get-buffer-create "*straight-fetch-report*")
    (read-only-mode -1)
    (erase-buffer)
    (let ((updates nil))
      (straight--map-repos
       (lambda (recipe)
         (straight--with-plist recipe (package local-repo)
           (let* ((default-directory (straight--repos-dir local-repo))
                  (commits (straight--process-output "git" "log" "..@{u}" "--oneline")))
             (unless (string-empty-p commits)
               (push (cons package (split-string commits "\n")) updates))))))
      (mapc (lambda (update)
              (let* ((commits (cdr update)))
                (insert
                 (propertize
                  (format "%s [%s commit%s]\n"
                          (car update)
                          (number-to-string (length commits))
                          (if (cdr commits) "s" ""))
                  'face 'font-lock-constant-face)
                 (format "  %s\n" (string-join (cdr update) "\n  ")))))
            (cl-sort updates #'string< :key #'car))
      (special-mode)
      (pop-to-buffer (current-buffer)))))
```

Which outputs the following:

```
doom-modeline [1 commit]
  371ad23 Replaced iex with elixir, where iex doesn't quit gracefully leading to multiple stale beam processes (#493)
doom-themes [7 commits]
  9966728 docs: fix complimentary -> complementary
  9d95fae theme: add doom-earl-grey
  f2ccdf2 theme: add doom-tokyo-night
  78372b9 tweak(gruvbox): various fixes and enhancements
  88b7c8e refactor: move extensions to subfolder
  e310373 dev: add codeowners
  084241e dev: exempt new-theme issues/PRs from stalebot
emacsmirror-mirror [1 commit]
  482c86b Update Emacsmirror mirror
magit-section [1 commit]
  65c4485e magit-current-blame-chunk: Don't try to operate in Dired buffers
melpa [5 commits]
  72422ead Update recipe for doom-themes (#7822)
  e75a21c9 Add recipe for eglot-java (#7814)
  11c919a3 Merge commit '0e041d3bacbfbcf2645e491dde169b72742420c9'
  0e041d3b Squashed 'package-build/' changes from 01246e73..da9fcbb6
  f07a741d Remove `version-regexp` from tree-sitter related recipes.
mu4e [2 commits]
  9d4326e3 Merge pull request #2180 from wavexx/ignore_old_elc
  86f88299 Ignore existing compiled files when byte-compiling
projectile [2 commits]
  cd8bcbc Merge pull request #1735 from eggert/timestamp
  43decc5 Port projectile-time-seconds to future Emacs
which-key [1 commit]
  5f19ec6 Update to the newer advice API
```

This can be used after a `straight-fetch-all` to evaluate what has changed before merging the changes. You could also advice `straight-fetch-all` to do this automatically:

```emacs-lisp
(advice-add #'straight-fetch-all :after #'straight-fetch-report)
```

Which would cause the buffer to be displayed after a `straight-pull-all` as well.
There are still some design details to be ironed out before I can include such a command, but feel free to give a try.

**Comment by nowislewis** [comment]
Amazing, that's exactly what I need, you did a great job!

This feature will definitely help many users

**Comment by progfolio** [comment]
Thank you for testing. I'll clean this up in the future and we should be able to add a user-option to automatically include the report when fetching.
