### ISSUE TITLE
Failed to enable the `wgrep` support of `urgrep` through the straight's use-package integration.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#892]
I try to install `urgrep` with straight and using its [`wgrep` support](https://github.com/jimporter/urgrep#using-with-wgrep) as follows, but all failed:
1.
```emacs-lisp
(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep")
  :config
  (load "urgrep-wgrep.el" nil t t)
  )
```
and
```emacs-lisp
(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep")
  :config
  (require 'urgrep-wgrep)
  )
```
The above two configurations will trigger the following Warnings:

`Error (use-package): urgrep/:config: Cannot open load file: No such file or directory, wgrep Disable showing Disable logging`

2.
```emacs-lisp
(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep") 
  :config (use-package urgrep-wgrep))
```
The above configuration will trigger the following Warnings:
`
Error (use-package): urgrep/:config: Could not find package urgrep-wgrep. Updating recipe repositories: (org-elpa melpa gnu-elpa-mirror el-get emacsmirror-mirror) with ‘straight-pull-recipe-repositories’ may fix this Disable showing Disable logging`

See [here](https://github.com/jimporter/urgrep/issues/3#issuecomment-948234619) for the related discussion. Any hints for this problem? 

Regards,
HZ

**Comment by progfolio** [comment]
See the `:includes` keyword in the documentation:

https://github.com/raxod502/straight.el/tree/develop#the-recipe-format

**Comment by hongyi-zhao** [comment]
```emacs-lisp
(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep"
		   :includes urgrep-wgrep
		   )

  :config
  (use-package urgrep-wgrep)
  )
```

Will trigger the following:

`Error (use-package): urgrep-wgrep/:catch: Cannot open load file: No such file or directory, wgrep Disable showing Disable logging`


```emacs-lisp
(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep"
		   :includes urgrep-wgrep
		   )

  :config
  (require 'urgrep-wgrep)
  )
```
Will trigger the following:

`Error (use-package): urgrep/:config: Cannot open load file: No such file or directory, wgrep Disable showing Disable logging`

**Comment by progfolio** [comment]
`No such file or directory, wgrep` indicates that there is a `(require 'wgrep)` somewhere in the author's package. My hunch is they do not declare `wgrep` as an explicit requirement (because the main package doesn't depend on it). Straight cannot detect the dependency in this case, so you would have to install it yourself before requiring that library.

**Comment by hongyi-zhao** [comment]
Your hunch is correct!

The problem can be solved with either of the following configurations:


```emacs-lisp
(use-package wgrep)

(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep"
		   :includes urgrep-wgrep
		   )

  :config
  (use-package urgrep-wgrep)
  )
```
Or
```emacs-lisp
(use-package wgrep)
(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep"
		   :includes urgrep-wgrep
		   )

  :config
  (require 'urgrep-wgrep)
  )
```
