### ISSUE TITLE
Do multiple back quotes really needed in the example given in the documentation?

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#894]
The following example is given [in the documentation](https://github.com/raxod502/straight.el#the-recipe-format):

```emacs-lisp
(straight-use-package
 `( example :type git :host github :repo "user/example.el"
    :pre-build ,(pcase system-type
                  (`windows-nt '(message "This might take a while"))
                  (_ '(("./configure") ("make") ("make" "install"))))))
```
But I really can't understand why we need the second back quote, i.e., used in the following struct:

```
 (`windows-nt '(message "This might take a while"))
```
According to the following description in the [Emacs official document](https://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html):

```
Backquote constructs allow you to quote a list, but selectively evaluate elements of that list. 
```
As you can see, in the example above, the `windows-nt` isn't a list at all. So, how should we still apply the back quote operation on it?

**Comment by progfolio** [comment]
See the documentation of `pcase`. This is more of a general elisp question, so please ask about it on the appropriate channels.

**Comment by hongyi-zhao** [comment]
Thank you. It seems related to the "Backquote-style pcase patterns: `QPAT", and something discussued [here](https://emacs.stackexchange.com/questions/63416/specify-optional-matches-with-pcase).
