### ISSUE TITLE
Advise with init.el reloading needed

### ISSUE THREAD

**Issue by d9d6ka** [raxod502/straight.el#895]
Hi! I want to ask whether I'm doing something wrong.

After I modify my `init.el` I try to reload it with

``` emacs-lisp
(load-file user-init-file)
```

But every time I receive the following error and the load of `init.el` breaks

```
Cannot open load file: No such file or directory, c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/repos/straight.el/bootstrap.el
```

`straight.el` is installed with the bootstrapping snippet from the readme, The snippet installs it to `c:/Users/vadim/AppData/Roaming/.emacs.d/...`

**Comment by progfolio** [comment]
Does the bootstrap.el file exist at this path?:

> c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/repos/straight.el/bootstrap.el

**Comment by d9d6ka** [comment]
> ~Does the bootstrap.el file exist at this path?:~
> 
> > ~c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/repos/straight.el/bootstrap.el~

~No? it exists at `c:/Users/vadim/AppData/Roaming/.emacs.d/straight/repos/straight.el/bootstrap.el`~

Crap everything above! I've shoot myself in the foot, I had a setting in me `init.el` changing `user-emacs-directory` to cache dir (to keep .emacs.d clean).

Sorry for wasting your time... :(
