### ISSUE TITLE
Add a `!` choice meaning `confirm all` or something like that to `straight-remove-unused-repos`.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#898]
I noticed that the [`straight-remove-unused-repos`](https://github.com/raxod502/straight.el/blob/af5437f2afd00936c883124d6d3098721c2d306c/straight.el#L5431) function takes a `force` argument, which allows me to provide any prefix arg so that it will delete all repos without prompting. One way is to use `current-prefix-arg`, [as shown below](https://lists.gnu.org/archive/html/help-gnu-emacs/2021-12/msg00118.html):

```emacs-lisp
(let ((current-prefix-arg '(4)))
  (call-interactively #'straight-remove-unused-repos))
```
But this is a little inconvenient. It seems that one solution is to add a `!` choice, meaning `confirm all` or something like that.

Regards,
HZ

**Comment by progfolio** [comment]
Please see: https://www.gnu.org/software/emacs/manual/html_node/emacs/Arguments.html

You can pass the universal argument to the command and `force` will be non-nil.

**Comment by hongyi-zhao** [comment]
> ```emacs-lisp
> (straight-remove-unused-repos 'force)
> ```

Thanks, and it seems that any non-nil argument will do the trick, say, the following ones: `t`, `'bla`, and so on.
