### ISSUE TITLE
repo vs local-repo

### ISSUE THREAD

**Issue by gour** [raxod502/straight.el#925]
Hello,

Moving from `use-package` setup to `straight.el` and tried to convert some declarations using local files, e.g.:

```
(use-package some-local-package
  :load-path "lisp/")
```

into adequate ones suitable for `straight.el` like (as seen [here](https://github.com/raxod502/straight.el/issues/441#issuecomment-560141867)):

```
(straight-use-package
  '(some-local-package :local-repo "some-local-package/some-local-package.el"
  ))
```

but that didn't work, although it does work with `repo` instead of `local-repo`, but I'm a bit confused.

Any explanation?

**Comment by progfolio** [comment]
> :local-repo "some-local-package/some-local-package.el"

If the repository is located on disk at "some-local-package" you want to point to that, not the elisp file within that repository. e.g.

```emacs-lisp
(straight-use-pcakge '(local :local-repo "/path/to/local"))
```
Does that help?

**Comment by gour** [comment]
> ```
>   :config
>   (setq calendar-holidays (append calendar-holidays holiday-croatian-holidays))
> ```

I've changed it into:

```
:config
(setq calendar-holidays holiday-croatian-holidays)
```
(the file was adapted from [this](https://github.com/abo-abo/netherlands-holidays) one and now everything is fine, although I'm not clear what is the issue here - probably some difference in loading of packages... :confused: 

However, thanks to you help, it's more clear now. :smile:
