### ISSUE TITLE
Why not use `straight-x-fetch-all` in `straight-x-pull-all`?

### ISSUE THREAD

**Issue by mkvoya** [raxod502/straight.el#930]
I really enjoy the parallelism brought by `straight-x-fetch-all`. But the parallelism does not exist in `straight-x-pull-all`.

Current implementation of `straight-x-pull-all` calls `straight-pull-all` and then `straight-x-thaw-pinned-versions`.

https://github.com/raxod502/straight.el/blob/af5437f2afd00936c883124d6d3098721c2d306c/straight-x.el#L197-L203

`straight-pull-all` consists of `straight-fetch-all` and `straight-merge-all`. 

https://github.com/raxod502/straight.el/blob/af5437f2afd00936c883124d6d3098721c2d306c/straight.el#L6161-L6176

I am wondering is it possible to let `straight-x-pull-all` directly call `straight-x-fetch-all` and `straight-merge-all` so that the fetch part in `straight-x-pull-all` can enjoy the parallelism?

Thanks. :)

**Comment by progfolio** [comment]
Pulling may require user intervention to resolve the state of user's repositories.
That would need to be redesigned to accommodate concurrency.

**Comment by mkvoya** [comment]
Is user intervention required in the fetch part?
If not, I think it's okay to replace only the fetch part to the parallel version and leave the merge part unchanged.

**Comment by progfolio** [comment]
It's possible, but it's not as trivial as just calling `straight-x-fetch-all` prior to merging. The fetches happen asynchronously, so one would have to implement either a way to know when they had all finished, or a UI which allowed the rest of the process to take place asynchronously.
