### ISSUE TITLE
`straight-enable-package-integration` vs `(setq package-enable-at-startup nil)`

### ISSUE THREAD

**Issue by lambdadog** [raxod502/straight.el#932]
My understanding of using straight.el and disabling package.el is in a bootstrapped install there was no need to set `package-enable-at-startup` to `nil`, since [`straight-package-neutering-mode` does this](https://github.com/raxod502/straight.el/blob/af5437f2afd00936c883124d6d3098721c2d306c/straight.el#L6358) and [is enabled when `straight-enable-package-integration` is `t`](https://github.com/raxod502/straight.el/blob/af5437f2afd00936c883124d6d3098721c2d306c/bootstrap.el#L128) (which is [the default](https://github.com/raxod502/straight.el/blob/af5437f2afd00936c883124d6d3098721c2d306c/straight.el#L6328))

However, I'm noticing now that [the README suggest adding it to your early-init file](https://github.com/raxod502/straight.el/blob/af5437f2afd00936c883124d6d3098721c2d306c/README.md?plain=1#L236).

Surely only one of `straight-package-neutering-mode` or `(setq package-enable-at-startup nil)` should be necessary, no?

If users are intended to add `(setq package-enable-at-startup nil)` to their early init file, then `straight-package-neutering-mode` probably ought to be removed.

Otherwise, if `straight-package-neutering-mode` is handling disabling package.el, instructions should probably have you bootstrapping and configuring straight.el in early-init so it can handle it properly.

**Comment by lambdadog** [comment]
To clarify, I'm aware of why this recommendation was added to the README -- straight.el disables package.el *once it loads*, but currently straight.el recommends bootstrapping in the init step rather than the early-init step of initialization, whereas `package-activate-all` is called *after early-init but before init*.

It just seems like there should be a shift to bootstrapping in the early-init step instead so this hack isn't necessary.

There's the argument that you shouldn't run anything lengthy in the early-init step, but straight.el setup honestly isn't particularly lengthy (other than perhaps the http fetch in the uncached case) and it's liable to be needed for the rest of your init file anyway. Theoretically you could hook the rest to `before-init-hook` but since you're disabling package.el anyway, the only difference would be that you'd be waiting until `window-system-initialization` is called which isn't a big enough difference to worry about.

**Comment by progfolio** [comment]
We still support Emacs versions lower than 27 (minimum requirement of 25 at the moment). The early init file does not exist in those versions.

**Comment by lambdadog** [comment]
@progfolio Oh, absolutely, but if you're fine gating something on "if you're on emacs>=27 add `(setq package-enable-at-startup nil)` to your early-init" in the README, you can instead say "If you're using emacs earlier than 27, put this code (the bootstrap code) in your init file, otherwise put it in your early-init."

**Comment by progfolio** [comment]
> There's the argument that you shouldn't run anything lengthy in the early-init step, but straight.el setup honestly isn't particularly lengthy (other than perhaps the http fetch in the uncached case) and it's liable to be needed for the rest of your init file anyway.

This is part of the reason why I would not generally recommend bootstrapping straight.el during early-init.
So long as we have to support versions of Emacs prior to the early-init file being introduced, `straight-package-neutering-mode` should stay in place. I see no benefit in further complicating the bootstrapping instructions. Closing this for now, but we can re-evaluate once we drop support for older Emacs versions.
