### ISSUE TITLE
Using :after does not work

### ISSUE THREAD

**Issue by mekeor** [raxod502/straight.el#935]
I want to load [ement.el](https://github.com/alphapapa/ement.el) (which depends on [plz.el](https://github.com/alphapapa/plz.el)) with use-package and straight.el. I figured that I have to manually load plz.el, too. It works when I first invoke `(use-package plz)` and afterwards `(use-package ement)`:

Just start `emacs -Q` and evaluate this file:

```elisp
(setq package-enable-at-startup nil)
(setq straight-use-package-by-default t)

(load "~/.emacs.d/straight/repos/straight.el/bootstrap.el")

(add-to-list 'load-path "~/.emacs.d/straight/build/use-package")
(add-to-list 'load-path "~/.emacs.d/straight/build/bind-key")

(require 'use-package)

(setq use-package-always-defer nil)
(setq use-package-always-demand t)

(use-package plz
  :straight (plz :host github :repo "alphapapa/plz.el"))

(use-package ement
  :straight (ement :host github :repo "alphapapa/ement.el"))
```

But I like to keep my use-package invocations sorted. I.e. I want `(use-package ement)` to appear in the code before `(use-package plz)`. But whether or not I add `:after plz`, I get this error:

```elisp
;; ...

(use-package ement
  :after plz
  :straight (ement :host github :repo "alphapapa/ement.el"))

(use-package plz
  :straight (plz :host github :repo "alphapapa/plz.el"))
```

> straight--convert-recipe: Could not find package plz. Updating recipe repositories: (org-elpa melpa gnu-elpa-mirror el-get emacsmirror-mirror) with ‘straight-pull-recipe-repositories’ may fix this

How to get this working?

**Comment by progfolio** [comment]
```emacs-lisp
(use-package ement
  :after plz
  :straight (ement :host github :repo "alphapapa/ement.el"))
```

Expands to:

```emacs-lisp
(progn
  (straight-use-package
   '(ement :host github :repo "alphapapa/ement.el"))
  (eval-after-load 'plz
    '(require 'ement nil nil)))
```

The installation of the package happens prior to the rest of the use-package forms.
In order to get this working you could, as you mentioned, order the use-package declarations so that plz's declaration comes first. Alternatively, you could make an explicit call to `straight-use-package prior to the use-package declaration for ement. e.g.

```emacs-lisp
(straight-use-package '(plz :host github :repo "alphapapa/plz.el"))
(use-package ement
  ;etc
  )
(use-package plz
  :straight nil
  ;;etc
  )
```
Personally, I would opt for the first solution because it keeps the installation with the rest of plz's configuration.

Does that help?

**Comment by mekeor** [comment]
Thank you.

1. Why does installing ement.el already throw an error that it's missing plz.el (although it's apparently not "required" yet)?

2. Why does this

```elisp
(use-package ement
  :after plz
  :straight (ement :host github :repo "alphapapa/ement.el"))
```

not expand to something like

```elisp
(progn
  (eval-after-install 'plz
    (straight-use-package
     '(ement :host github :repo "alphapapa/ement.el")))
  (eval-after-load 'plz
    '(require 'ement nil nil)))
```

?

**Comment by progfolio** [comment]
> Why does installing ement.el already throw an error that it's missing plz.el (although it's apparently not "required" yet)?

The dependencies are required to build the package prior to it being loaded.
The error you posted happens during recipe conversion:

> straight--convert-recipe: Could not find package plz. Updating recipe repositories: (org-elpa melpa gnu-elpa-mirror el-get emacsmirror-mirror) with ‘straight-pull-recipe-repositories’ may fix this

Straight is looking for the recipes for ement's dependencies.
It does not find plz becuase there is no registered recipe in any of the recipe repositories.
Providing that recipe as described in the previous comment will bypass that error.

> 2. Why does [package installation take place before use-package's package configuration forms]?

This is the consistent with use-package's `:ensure` keyword behavior. e.g.

```emacs-lisp
(use-package test
  :after before
  :ensure t)
```

Expands to:

```emacs-lisp
(progn
  (use-package-ensure-elpa 'test
                           '(t)
                           'nil)
  (eval-after-load 'before
    '(require 'test nil nil)))
```

See also this related issue:

https://github.com/raxod502/straight.el/issues/235

**Comment by progfolio** [comment]
If you have any more questions, feel free to comment and we can reopen this issue.
