### ISSUE TITLE
Can't install org in fresh emacs 

### ISSUE THREAD

**Issue by salvari** [raxod502/straight.el#942]
I'm using a new set of emacs config files with almost no configuration. I'm asking for org install with 

`(straight-use-package 'org)`

But I've got the error:

`error: :pre-build command error in "org" recipe (error "Failed to parse ORGVERSION")`

It seems that there is a new release for org (9.5.3) from 28 hours ago. Could it have something to do with this error?

**Comment by progfolio** [comment]
What is the output of the command `straight-version`?

**Comment by progfolio** [comment]
Everything seems to be working according to the following test case:

[Yodel](https://github.com/progfolio/yodel) Report (2022-04-20 10:55:49):

```emacs-lisp
(yodel
  :packages*
  org
  :post*
  (org-version nil 'full 'message))
```

<details><summary>STDOUT:</summary>

```emacs-lisp
Loading /tmp/yodel-ulsEM2/straight-bootstrap-snippet.el (source)...
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done
Cloning org...
Cloning org...done
Building org...
Building org...done

Org mode version 9.5.3 (9.5.3-g81289b @ /tmp/yodel-ulsEM2/straight/build/org/)
```

</details>
<details><summary>Environment</summary>

- **emacs version**: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6)
 of 2022-04-12
- **system type**: gnu/linux

<details open><summary>Packages</summary>

| Name                                                        | Branch | Commit                                                                                                                 | Date       | Source   |
|-------------------------------------------------------------|--------|------------------------------------------------------------------------------------------------------------------------|------------|----------|
| [org](https://git.savannah.gnu.org/cgit/emacs/org-mode.git) | main   | [81289bddee](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=81289bddee665ee2708c9eaefbaa57796fc08ad2) | 2022-04-20 | org-elpa |

</details>

</details>

Can you try evaluating the following in your scratch buffer?:

```emacs-lisp
(straight-bug-report
  :post-bootstrap
  (straight-use-package 'org)
  (org-version nil 'full 'message))
```
It will install straight.el and org in a clean environment. When it's done a result buffer should pop up. You can copy the contents of that buffer here.

**Comment by salvari** [comment]
straight-version
prerelease (HEAD -> master, origin/master, origin/HEAD) af5437f 2021-09-27

straight-bug-report result:

<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (straight-use-package 'org)
  (org-version nil 'full 'message))
```
</details>

- Test run at: `2022-04-20 18:53:40`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> master, origin/master, origin/HEAD) af5437f 2021-09-27`
- emacs-version: `GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2020-09-19`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 4517e11 2022-04-13
Cloning org...
Cloning org...done
Building org...
Building org...done

Org mode version 9.5.3 (9.5.3-g81289b @ /tmp/straight.el-test-9YXs1e/straight/build/org/)
Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 12505571 2022-04-17
"gnu-elpa-mirror"         n/a                  master e9835ab 2022-04-16
"el-get"                  melpa                master 93533097 2021-12-24
"emacsmirror-mirror"      n/a                  master b70b3e1 2022-04-20
"straight"                n/a                  develop 4517e11 2022-04-13
"org"                     org-elpa             main 81289bdde 2022-04-20


```
</details>


After running the test the org-version command gives me Org mode version 9.3 (It's the latest)

But still same error at startup

**Comment by salvari** [comment]
I tested the config files in a fresh and clean `.emacs.d` directory. Everything works fine now. 
Sorry to have bothered you. I suppose I made a mistake in the first attempt  :-(
