### ISSUE TITLE
guix in harmony with straight.el: how to use some of its packages?

### ISSUE THREAD

**Issue by WorldsEndless** [raxod502/straight.el#943]
Somewhat like #837 I have jumped in to the deep end with GUIX standalone. Unlike that thread, however, I am not yet ready to fold up my fairly massive straight setup to try guix packages (except when those packages are for involvement with non-emacs processes). The biggest reason for this is because I use straight not only for adding packages, but for a custom-file replacement for all my customization of packages. I like to have everything customized only in my (tangled) straight use-package statements. In addition to my question, I'm game for any advice on this front.

So, my question: how can I tell straight to use the installed GUIX version of something on certain packages, rather than the a /straight/repo one? Will :built-in work for this, even though they aren't technically built in?

**Comment by progfolio** [comment]
If there is a repository on disk somewhere you can point straight to it via that `:local-repo` keyword.
I'm not all that familiar with how Guix packaging works, though.

**Comment by WorldsEndless** [comment]
I'm trying that out now. It seems to be working pretty well, linking it to the place where the guix files are at, and using that repo. The only concern I have is that the Guix location is named according to the version of the library, so updating it will change or break things. But that would be a subject for another issue, when the time comes.

**Comment by progfolio** [comment]
Glad it's working out.

> The only concern I have is that the Guix location is named according to the version of the library, so updating it will change or break things

You should be able to backquote your recipe and dynamically compute the location of the :local-repo. e.g.

```emacs-lisp
(straight-use-package `(my-package :local-repo ,(elisp-which-gets-guix-location))
```
This should trigger a rebuild of the package if the value changes as well.
